objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partial</fullName>
                    <default>true</default>
                    <label>Partial</label>
                </value>
                <value>
                    <fullName>Free Trial</fullName>
                </value>
                <value>
                    <fullName>Active Paid</fullName>
                </value>
                <value>
                    <fullName>Active Grace</fullName>
                </value>
                <value>
                    <fullName>Frozen</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Expired Marketing</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Apple</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>All_Email_Preferences__c</fullName>
        <defaultValue>true</defaultValue>
        <label>All Email Preferences</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsReadyToSyncInZuora__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to identify record needs to be sync in Zuora</description>
        <label>IsReadyToSyncInZuora</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Double_OptIn__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to identify user is double opt-in for marketing emails.</description>
        <label>Is Double OptIn</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notification_Country_Code__c</fullName>
        <label>Notification Country Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/DAZNConfiguration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is a configurable custom setting for Forgot Password link</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>Field to store configuration value for specific key</description>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>DAZN Configuration</label>
</CustomObject>

objects/Partner_Account_Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Partner Account Configuration for all users which are partner users like users coming via Docomo or Amazon Pay etc.</description>
    <fields>
        <fullName>Cancel_Subscription_URL_Large__c</fullName>
        <description>URL for cancel subscription button for Large breakpoint, to be used when the Account status = Active Paid</description>
        <label>Cancel Subscription URL Large</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Cancel_Subscription_URL_Medium__c</fullName>
        <description>URL for cancel subscription button for Medium breakpoint, to be used when the Account status = Active Paid</description>
        <label>Cancel Subscription URL Medium</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Cancel_Subscription_URL_Small__c</fullName>
        <description>URL for cancel subscription button for Small breakpoint, to be used when the Account status = Active Paid</description>
        <label>Cancel Subscription URL Small</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Page_Name__c</fullName>
        <description>To indicate which VF page needs to be displayed for a partner type as specified in the field Partner Type</description>
        <label>Page Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Type__c</fullName>
        <description>The name of the Partner Type for which this my account page is for. This will be the same value as populated on the User type field on the Account.</description>
        <label>Partner Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Payment_History_URL__c</fullName>
        <description>The link for Payment history for DfD</description>
        <label>Payment History URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Subscription_Type_Heading_Text__c</fullName>
        <description>The static text to be shown for Subscription Type Heading</description>
        <label>Subscription Type Heading Text</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_Type_Sub_Heading_Text__c</fullName>
        <description>The static text to be shown for Subscription Type sub Heading</description>
        <label>Subscription Type Sub Heading Text</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Partner Account Configuration</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>All_Email_Preferences__c</fullName>
        <defaultValue>true</defaultValue>
        <label>All Email Preferences</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/AnonymizerAccountTest.cls
@isTest
private class AnonymizerAccountTest {
	
	private static final String EMAIL_PATTERN = '@testEmailPattern.com';
	private static final String STR_ENV_NAME = 'testVal';
	
	@testSetup static void generateTestData() {
		CreateTestDataforUnitTest.triggerSettings();

		Partner_Account_Configuration__c pac = new Partner_Account_Configuration__c(
        	Name = 'Docomo',
        	Partner_Type__c = 'Docomo',
        	Page_Name__c = 'PartnerAccount.page',
        	Subscription_Type_Heading_Text__c = 'Docomo',
        	Subscription_Type_Sub_Heading_Text__c = 'Your subscription is managed through your d Account and is payable monthly via your contract with Docomo.',
        	Payment_History_URL__c = 'https://www.google.com',
        	Cancel_Subscription_URL_Small__c = 'https://www.google.com',
        	Cancel_Subscription_URL_Medium__c = 'https://www.google.com',
        	Cancel_Subscription_URL_Large__c = 'https://www.google.com'
        );
        insert pac;

		DAZNConfiguration__c daznConfig = new DAZNConfiguration__c(
        	Name = 'EnviornmentName',
        	Value__c = STR_ENV_NAME
        );
        insert daznConfig;

        Profile profileForTestUser = [Select Id, Name From Profile Where Name = 'Customer Community User' LIMIT 1];

        List<Account> accountsForTestUsers = new List<Account>();
        accountsForTestUsers.add(
        	new Account(
        		FirstName = 'firstName1',
                LastName = 'lastName1',
                PersonEmail = 'email1' + EMAIL_PATTERN,
                Notification_Country_Code__c = 'DE',
                All_Email_Preferences__c = true,
                Account_Status__c = 'Active Paid',
                Is_Double_OptIn__c = true,
                IsReadyToSyncInZuora__c = true
        	)
        );
        insert accountsForTestUsers;

        String personContactId = [Select Id, PersonContactId From Account].PersonContactId;

        List<User> usersForTest = new List<User>();
        usersForTest.add(
        	new User(
        		FirstName = 'anonymous[' + STR_ENV_NAME + ']' + '1',
        		LastName = 'anonymous[' + STR_ENV_NAME + ']' + '1',
        		Email = 'anonymous' + STR_ENV_NAME + '1' + '@livesport.com',
        		UserName = 'anonymous[' + STR_ENV_NAME + ']' + '1' + '@livesport.com',
        		Alias = 'LiveSp1',
        		TimeZoneSidKey = 'Europe/London',
        		LocaleSidKey = 'de_DE',
        		EmailEncodingKey = 'ISO-8859-1',
        		ProfileId = profileForTestUser.Id,
        		LanguageLocaleKey = 'en_GB',
        		ContactId = personContactId
        	)
        );
        insert usersForTest;
    }
	
	@isTest static void testBatch() {
		String testUserEmail = 'email1' + EMAIL_PATTERN;
		Account testAccountBefore = [Select Id, All_Email_Preferences__c, PersonEmail, Account_Status__c, FirstName, LastName From Account Where PersonEmail = :testUserEmail LIMIT 1];

		AnonymizerAccount anonymizerAccount = new AnonymizerAccount(EMAIL_PATTERN);

		Test.startTest();
		Database.executeBatch(anonymizerAccount, 1000);
		Test.stopTest();

		Account testAccountAfter = [Select Id, All_Email_Preferences__c, PersonEmail, Account_Status__c, FirstName, LastName From Account Where Id = :testAccountBefore.Id LIMIT 1];
		User testUser = [Select Id, FirstName, LastName, Email From User Where AccountId = :testAccountBefore.Id];

		System.assertEquals(false, testAccountAfter.All_Email_Preferences__c);
        System.assertEquals(testUser.Email, testAccountAfter.PersonEmail);
        System.assertEquals('Expired', testAccountAfter.Account_Status__c);
        System.assertEquals(testUser.FirstName, testAccountAfter.FirstName);
        System.assertEquals(testUser.LastName, testAccountAfter.LastName);
	}
	
}