objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partial</fullName>
                    <default>true</default>
                    <label>Partial</label>
                </value>
                <value>
                    <fullName>Free Trial</fullName>
                </value>
                <value>
                    <fullName>Active Paid</fullName>
                </value>
                <value>
                    <fullName>Active Grace</fullName>
                </value>
                <value>
                    <fullName>Frozen</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Expired Marketing</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Apple</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submitted_for_cancellation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Submitted for cancellation</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/DAZNConfiguration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is a configurable custom setting for Forgot Password link</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>Field to store configuration value for specific key</description>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>DAZN Configuration</label>
</CustomObject>

objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>R00N40000001kyLcEAI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__PaymentMethod__c.object
<CustomObject>
    <description>PaymentMethod contains information on how the contact pays for the account. In order to activate an account, you need to create a payment method.</description>
    <fields>
        <fullName>Zuora__BillingAccount__c</fullName>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Payment Methods</relationshipLabel>
        <relationshipName>Payment_Methods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora__CreditCardExpirationMonth__c</fullName>
        <label>Credit Card Expiration Month</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zuora__CreditCardExpirationYear__c</fullName>
        <description>The expiration year of the credit or debit card.</description>
        <inlineHelpText>The expiration year of the credit or debit card.</inlineHelpText>
        <label>Credit Card Expiration Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACH</fullName>
                </value>
                <value>
                    <fullName>BankTransfer</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>CreditCard</fullName>
                </value>
                <value>
                    <fullName>CreditCardReferenceTransaction</fullName>
                </value>
                <value>
                    <fullName>DebitCard</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PayPal</fullName>
                </value>
                <value>
                    <fullName>WireTransfer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment Method</label>
    <nameField>
        <label>Payment Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__CustomerAccount__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This field holds the Zuora object ID, and is used as external ID for data synchronization between Salesforce and Zuora.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__NextChargeDate__c</fullName>
        <label>Next Charge Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MembershipReactivationControllerTest.cls
/*
 Description: MembershipReactivationControllerTest is using by Reactivate Subscription Test class.
 PD-7810- Test class is changed as per PD notes. 
*/
@isTest
public class MembershipReactivationControllerTest {
    @testSetup 
    public static void getCommunityUsersTestData(){
        CreateTestDataforUnitTest.triggerSettings();
        CreateZuoraDataforUnitTest.createZuoraDeatils();
        CreateZuoraDataforUnitTest.createInvoice();
        CreateTestDataforUnitTest.createTestcustomsetting();
        CreateTestDataforUnitTest.CreateGuestUser();
    }    
    static testmethod void testReactivateMembershipForFreeTrial()
    {
        List<Account> accList = [Select Id, Name, PersonEmail,PersonContactId from Account where Account_Status__c = 'Active Paid'];
        List<Id> contactIdList = new List<Id>();
        for(Account acc : accList){
            contactIdList.add(acc.PersonContactId);
        }
        List<User> oUser = [Select Id, Name, UserName,Alias,Country,LanguageLocaleKey from User where ContactId In : contactIdList];
        List<Zuora__CustomerAccount__c> getlstZaccount=[Select Id, Zuora__Status__c,Zuora__Account__c   from Zuora__CustomerAccount__c where Zuora__Account__c In : accList ];
        List<Zuora__Subscription__c> getlstSubscription=[Select Id, Zuora__Status__c,Zuora__CustomerAccount__c  from Zuora__Subscription__c where Zuora__CustomerAccount__c In :getlstZaccount];
        List<Zuora__PaymentMethod__c> getlstPayment=[Select Id, Zuora__Type__c, Zuora__CreditCardExpirationMonth__c, Zuora__BillingAccount__c  from Zuora__PaymentMethod__c where Zuora__BillingAccount__c In :getlstZaccount];
        getlstSubscription[0].Zuora__Status__c='Cancelled';
        update getlstSubscription;
       System.assertNotEquals(null,oUser[0]);
        System.runAs(oUser[0])
        { 
            Test.startTest();
            MembershipReactivationController oMembershipReactivationController = new MembershipReactivationController();      
            oMembershipReactivationController.ReactivateMembership();
            String navigatreslut = oMembershipReactivationController.redirectToMyAccount().getUrl();
            System.assertEquals('/MyAccount',navigatreslut);
            String navigatHandler = oMembershipReactivationController.navigationHandler().getUrl();
            Test.stopTest();
        }
    }
    
    static testmethod void testReactivateMembershipForFreeTrial11()
    {
        List<Account> accList = [Select Id, Name, PersonEmail,PersonContactId from Account where Account_Status__c = 'Active Paid'];
        List<Id> contactIdList = new List<Id>();
        for(Account acc : accList){
            contactIdList.add(acc.PersonContactId);
        }
        List<User> oUser = [Select Id, Name, UserName,Alias,Country,LanguageLocaleKey from User where ContactId In : contactIdList];
        List<Zuora__CustomerAccount__c> getlstZaccount=[Select Id, Zuora__Status__c,Zuora__Account__c   from Zuora__CustomerAccount__c where Zuora__Account__c In : accList ];
        List<Zuora__Subscription__c> getlstSubscription=[Select Id, Zuora__Status__c,Zuora__CustomerAccount__c  from Zuora__Subscription__c where Zuora__CustomerAccount__c In :getlstZaccount];
        List<Zuora__PaymentMethod__c> getlstPayment=[Select Id, Zuora__Type__c, Zuora__CreditCardExpirationMonth__c, Zuora__BillingAccount__c  from Zuora__PaymentMethod__c where Zuora__BillingAccount__c In :getlstZaccount];
        getlstSubscription[0].Zuora__Status__c='Cancelled';
        update getlstSubscription;
        getlstPayment[0].Zuora__CreditCardExpirationMonth__c = '12';
        update getlstPayment;
       System.assertNotEquals(null,oUser[0]);
        System.runAs(oUser[0])
        { 
            Test.startTest();
            MembershipReactivationController oMembershipReactivationController = new MembershipReactivationController();      
            oMembershipReactivationController.ReactivateMembership();
            String navigatreslut = oMembershipReactivationController.redirectToMyAccount().getUrl();
            System.assertEquals('/MyAccount',navigatreslut);
            String navigatHandler = oMembershipReactivationController.navigationHandler().getUrl();
            Test.stopTest();
        }
    }
    
    static testmethod void testReactivateMembershipForActivePaid()
    {
        List<Account> accList = [Select Id, Name, PersonEmail,PersonContactId from Account where Account_Status__c = 'Free Trial'];
        List<Id> contactIdList = new List<Id>();
        for(Account acc : accList){
            contactIdList.add(acc.PersonContactId);
        }
        List<User> oUser = [Select Id, Name, UserName,Alias,Country,LanguageLocaleKey from User where ContactId In : contactIdList];
        List<Zuora__CustomerAccount__c> getlstZaccount=[Select Id, Zuora__Status__c,Zuora__Account__c   from Zuora__CustomerAccount__c where Zuora__Account__c In : accList ];
        List<Zuora__Subscription__c> getlstSubscription=[Select Id, Zuora__Status__c,Zuora__CustomerAccount__c  from Zuora__Subscription__c where Zuora__CustomerAccount__c In :getlstZaccount];
        List<Zuora__PaymentMethod__c> getlstPayment=[Select Id, Zuora__Type__c, Zuora__CreditCardExpirationMonth__c, Zuora__BillingAccount__c  from Zuora__PaymentMethod__c where Zuora__BillingAccount__c In :getlstZaccount];
        getlstSubscription[0].Zuora__Status__c='Cancelled';
       //getlstSubscription[0].Zuora__External_Id__c = '1';
       update getlstSubscription;
        getlstPayment[0].Zuora__CreditCardExpirationMonth__c = '';
        getlstPayment[0].Zuora__CreditCardExpirationYear__c = '';
      update getlstPayment;
        System.assertNotEquals(null,accList[0]);
        System.runAs(oUser[0])
        { 
            Test.startTest(); 
            MembershipReactivationController oMembershipReactivationController = new MembershipReactivationController();      
            //oMembershipReactivationController.sCountry = 'CA';
            oMembershipReactivationController.ReactivateMembership();
            String navigatreslut = oMembershipReactivationController.navigateToErrorPage().getUrl();
            System.assertEquals('/MyAccount?ResubscribesError=true',navigatreslut.substringBefore('Errormsg'));
            
            oMembershipReactivationController.navigateError = false;
            oMembershipReactivationController.navigateToErrorPage();

            Test.stopTest();
        }
      //Below lines to cover , Without use accessing Reactivation page.
       MembershipReactivationController oMembershipReactivationControllerWithoutUser = new MembershipReactivationController();      
       oMembershipReactivationControllerWithoutUser.getUserSubscription();
    }
    static testmethod void testReactivateMembershipForActivePaid4()
    {
        List<Account> accList = [Select Id, Name, PersonEmail,PersonContactId from Account where Account_Status__c = 'Free Trial'];
        List<Id> contactIdList = new List<Id>();
        for(Account acc : accList){
            contactIdList.add(acc.PersonContactId);
        }
        //List<User> oUser = [Select Id, Name, UserName,Alias,Country,LanguageLocaleKey from User where ContactId In : contactIdList];
        List<Zuora__CustomerAccount__c> getlstZaccount=[Select Id, Zuora__Status__c,Zuora__Account__c   from Zuora__CustomerAccount__c where Zuora__Account__c In : accList ];
        List<Zuora__Subscription__c> getlstSubscription=[Select Id, Zuora__Status__c,Zuora__CustomerAccount__c  from Zuora__Subscription__c where Zuora__CustomerAccount__c In :getlstZaccount];
        List<Zuora__PaymentMethod__c> getlstPayment=[Select Id, Zuora__Type__c, Zuora__CreditCardExpirationMonth__c, Zuora__BillingAccount__c  from Zuora__PaymentMethod__c where Zuora__BillingAccount__c In :getlstZaccount];
        getlstSubscription[0].Zuora__Status__c='Cancelled';
      // getlstSubscription[0].Zuora__External_Id__c = '';
       update getlstSubscription;
        getlstPayment[0].Zuora__CreditCardExpirationMonth__c = '';
        getlstPayment[0].Zuora__CreditCardExpirationYear__c = '';
      update getlstPayment;
        System.assertNotEquals(null,accList[0]);
        //System.runAs(oUser[0])
        //{ 
            Test.startTest(); 
            MembershipReactivationController oMembershipReactivationController = new MembershipReactivationController();      
            oMembershipReactivationController.ReactivateMembership();
            //oMembershipReactivationController.sCountry = 'CA';
            String navigatreslut = oMembershipReactivationController.navigateToErrorPage().getUrl();
            System.assertEquals('/MyAccount?ResubscribesError=true',navigatreslut.substringBefore('Errormsg'));
            oMembershipReactivationController.navigateError = false;
            oMembershipReactivationController.navigateToErrorPage();

            Test.stopTest();
        //}
      //Below lines to cover , Without use accessing Reactivation page.
       MembershipReactivationController oMembershipReactivationControllerWithoutUser = new MembershipReactivationController();      
       oMembershipReactivationControllerWithoutUser.getUserSubscription();
    }

    static testmethod void testNavigateToErrorPage() {
        List<Account> accList = [Select Id, Name, PersonEmail,PersonContactId from Account where Account_Status__c = 'Free Trial'];
        
        List<Zuora__CustomerAccount__c> getlstZaccount = [Select Id, Zuora__Status__c,Zuora__Account__c   from Zuora__CustomerAccount__c where Zuora__Account__c = :accList[0].Id];
        List<Zuora__Subscription__c> getlstSubscription = [Select Id, Zuora__Status__c,Zuora__CustomerAccount__c  from Zuora__Subscription__c where Zuora__CustomerAccount__c In :getlstZaccount];
        List<Zuora__PaymentMethod__c> getlstPayment = [Select Id, Zuora__Type__c, Zuora__CreditCardExpirationMonth__c, Zuora__BillingAccount__c  from Zuora__PaymentMethod__c where Zuora__BillingAccount__c In :getlstZaccount];
        getlstSubscription[0].Zuora__Status__c = 'Active';
        getlstSubscription[0].Zuora__NextChargeDate__c = Date.today() + 1;
        update getlstSubscription;

        System.runAs([Select Id From User Where AccountId = :accList[0].Id][0]) { 
            Test.startTest(); 
            MembershipReactivationController oMembershipReactivationController = new MembershipReactivationController();
            oMembershipReactivationController.navigateError = false;
            PageReference navigatreslut = oMembershipReactivationController.navigateToErrorPage();
            System.assertEquals(null, navigatreslut);
            Test.stopTest();
        }
    }   
   
    static testMethod void TestgetUserSubscription() {
  
        Account oAccount = SetUpTestData.createPersonAccount('TestFirstName', 'TestLastName','pm3testemail@email.com','Free Trial');
       
        
         User cUser = SetUpTestData.createCommunityUser('de', 'DE', oAccount.Id, 'pauseuser@email.com', 'pauseuseree@email.com', 'tstals','Europe/London','ISO-8859-1','de','de','PauseUserFName','PauseUserLName',true);
        
        Zuora__CustomerAccount__c bAccount = SetUpTestData.createBillingAccount(oAccount.Id,'test billing account', 'Cancelled', 'A00000073', 'testbill Name', 'United Kingdom', 'test bill name', 'Credit Card', 'batch2', 'USD','1st of the month');
        
        Zuora__Subscription__c zSubsp = SetUpTestData.createZuoraSubscription(oAccount.Id ,bAccount.Id, 'Test Zuora', 'Cancelled', System.today(), system.today()+30);
       
        String scCountry = 'CA';
        PageReference pageRef = Page.resubscribe;
        pageRef.getParameters().put('Country', scCountry);
        Test.setCurrentPage(pageRef);
        
                   
            Test.StartTest();
 
            System.RunAs(cUser){
         
             MembershipReactivationController oMembershipReactivationController = new MembershipReactivationController();      
            oMembershipReactivationController.ReactivateMembership();
            oMembershipReactivationController.getUserSubscription();
            
            Test.StopTest();
        }
           
    }
   
    static testMethod void TestgetUserSubscription_1() {
  
        Account oAccount = SetUpTestData.createPersonAccount('TestFirstName', 'TestLastName','pm3testemail@email.com','Active Paid');
       
        
         User cUser = SetUpTestData.createCommunityUser('de', 'DE', oAccount.Id, 'pauseuser@email.com', 'pauseuseree@email.com', 'tstals','Europe/London','ISO-8859-1','de','de','PauseUserFName','PauseUserLName',true);
        
        Zuora__CustomerAccount__c bAccount = SetUpTestData.createBillingAccount(oAccount.Id,'test billing account', 'Cancelled', 'A00000073', 'testbill Name', 'United Kingdom', 'test bill name', 'Credit Card', 'batch2', 'USD','1st of the month');
        
        Zuora__Subscription__c zSubsp = SetUpTestData.createZuoraSubscription(oAccount.Id ,bAccount.Id, 'Test Zuora', 'Cancelled', System.today(), system.today()+30);
       
        String scCountry = 'CA';
        PageReference pageRef = Page.resubscribe;
        pageRef.getParameters().put('Country', scCountry);
        Test.setCurrentPage(pageRef);
        
                   
            Test.StartTest();
 
            System.RunAs(cUser){
         
             MembershipReactivationController oMembershipReactivationController = new MembershipReactivationController();      
            oMembershipReactivationController.ReactivateMembership();
            oMembershipReactivationController.getUserSubscription();
            
            Test.StopTest();
        }
           
    }
   
   
    static testMethod void TestgetUserSubscription_2() {
  
        Account oAccount = SetUpTestData.createPersonAccount('TestFirstName', 'TestLastName','pm3testemail@email.com','Active Paid');
       
        
         User cUser = SetUpTestData.createCommunityUser('de', 'DE', oAccount.Id, 'pauseuser@email.com', 'pauseuseree@email.com', 'tstals','Europe/London','ISO-8859-1','de','de','PauseUserFName','PauseUserLName',true);
       
                   
            Test.StartTest();
 
            System.RunAs(cUser){
         
             MembershipReactivationController oMembershipReactivationController = new MembershipReactivationController();      
            oMembershipReactivationController.ReactivateMembership();
            oMembershipReactivationController.getUserSubscription();
            
            Test.StopTest();
        }
           
    }
   
    static testMethod void tesStartUndoCancellationZuoraWorkflow() {
        //Create personal account
        Account oAccount = SetUpTestData.createPersonAccount('TestFirstName', 'TestLastName','testCustomer123@email.com','Active Paid');
        oAccount.Submitted_for_cancellation__c = true;
        update oAccount;
        //Create Billing Account
        Zuora__CustomerAccount__c bAccount = SetUpTestData.createBillingAccount(oAccount.Id,'test billing account', 'Active', 'A00000073', 'testbill Name', 'United Kingdom', 'test bill name', 'Credit Card', 'batch2', 'USD','1st of the month'); 
        Zuora__Subscription__c subscription = SetUpTestData.createZuoraSubscription(oAccount.Id, bAccount.Id, 'Zuora__Subscription__c', '', date.today(), date.today().addDays(7));
        List<Zuora__Subscription__c> subscriptions = [SELECT Id, Name FROM Zuora__Subscription__c WHERE Id =: subscription.Id];
        
        List<DAZNConfiguration__c> config = new List<DAZNConfiguration__c>();
        config.add(new DAZNConfiguration__c(
            Name = 'ZuoraReactivationUrl',
            Value__c = 'https://workflow.apps.zuora.com/api/v1/workflows/552/run'
        ));
        config.add(new DAZNConfiguration__c(
            Name = 'ZuoraPauseUsername',
            Value__c = 't1'
        ));
        config.add(new DAZNConfiguration__c(
            Name = 'ZuoraPausePassword',
            Value__c = 't2'
        ));
        insert config;

        Test.StartTest();
            MembershipReactivationController objwhyCntrl = new MembershipReactivationController();
            objwhyCntrl.startUndoCancellationZuoraWorkflow(subscriptions[0].Name, oAccount.Id);
            Test.setMock(HttpCalloutMock.class, new MockStandardUndoCancelResponse());
            MembershipReactivationController objwhyCntrl2 = new MembershipReactivationController();
            objwhyCntrl2.startUndoCancellationZuoraWorkflow(subscriptions[0].Name, oAccount.Id);
        Test.stopTest();
    }
    
    public class MockStandardUndoCancelResponse implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody(
                '{ '+
                '    "id": 57, '+
                '    "name": "WF-9-00000011", '+
                '    "originalWorkflowId": 9, '+
                '    "type": "Workflow::Instance", '+
                '    "tasks": { '+
                '        "total": 1, '+
                '        "queued": 1, '+
                '        "processing": 0, '+
                '        "pending": 0, '+
                '        "stopped": 0, '+
                '        "success": 0, '+
                '        "error": 0 '+
                '    }, '+
                '    "runTime": null, '+
                '    "cpuTime": "00:00:00", '+
                '    "createdAt": "2017-03-24 09:56:17 UTC", '+
                '    "updatedAt": "2017-03-24 09:56:17 UTC" '+
                '}'
            );
            res.setStatusCode(200);
            return res;
        }
    }
   
   
}