objects/Account.object
<CustomObject>
    <fields>
        <fullName>Free_Trial_Start_Date__c</fullName>
        <label>Free Trial Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/DAZN_Country_Currency_ISO_Code__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>CurrencySymbol__c</fullName>
        <label>CurrencySymbol</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>DAZN Country Currency ISO Code</label>
</CustomObject>

objects/DAZNConfiguration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is a configurable custom setting for Forgot Password link</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>Field to store configuration value for specific key</description>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>DAZN Configuration</label>
</CustomObject>

objects/Payment_history_configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Country_code__c</fullName>
        <label>Country code</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show_free_trial__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Show free trial</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subscription_type__c</fullName>
        <label>Subscription type</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Payment history configuration</label>
</CustomObject>

objects/PaymentHistoryDownloadConfiguration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Country_code__c</fullName>
        <label>Country code</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Download_Invoice__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Download Invoice</label>
        <type>Checkbox</type>
    </fields>
    <label>Payment history download configuration</label>
</CustomObject>

objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__Payment__c.object
<CustomObject>
    <description>Zuora Payment object.  A payment is the money that customers send to pay for charges related to their subscriptions. 
The Payment object holds all of the information about an individual payment, including the payment amount and to which invoices the payment is applied.</description>
    <fields>
        <fullName>Zuora__EXT_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>External Id For Payment object,   Represents a Zuora Payment object Id</description>
        <externalId>true</externalId>
        <label>Unique External Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__Effective_Date__c</fullName>
        <description>The date when the payment takes effect.</description>
        <inlineHelpText>The date when the payment takes effect.</inlineHelpText>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__PaymentMethod__c</fullName>
        <description>The display name of the payment method used for the payment.</description>
        <inlineHelpText>The display name of the payment method used for the payment.</inlineHelpText>
        <label>Payment Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <description>The status of the payment in the Zuora system. The value depends on the type of payment.</description>
        <inlineHelpText>The status of the payment in the Zuora system. The value depends on the type of payment.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Posted</fullName>
                </value>
                <value>
                    <fullName>Voided</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__PaymentInvoice__c.object
<CustomObject>
    <description>Zuora Invoice Payment object.  An Invoice Payment is a mechanism to tie a payment to an invoice and indicate how much of the payment to apply to the invoice.  PaymentInvoice has Master-Detail relationship to Payment object and Lookup relationship to Invoice.</description>
    <fields>
        <fullName>Zuora__EXT_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>External Id For Invoice Payment object,   Represents a Zuora Invoice Payment object Id</description>
        <externalId>true</externalId>
        <label>Unique External Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__Payment__c</fullName>
        <description>The payment associated with this Invoice Payment object.</description>
        <inlineHelpText>The payment associated with this Invoice Payment object.</inlineHelpText>
        <label>Payment</label>
        <referenceTo>Zuora__Payment__c</referenceTo>
        <relationshipLabel>Invoice Payments</relationshipLabel>
        <relationshipName>PaymentInvoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice Payment</label>
    <nameField>
        <displayFormat>IP{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__Refund__c.object
<CustomObject>
    <description>The Refund object is used to create and query refunds. 

Note that refunds imply that money has been returned to customers. You should use adjustments (credit memos) if you are issuing credit to customers, but are not returning funds to a customer.</description>
    <fields>
        <fullName>Zuora__PaymentMethod__c</fullName>
        <description>A valid PaymentMethod ID indicating the method being used to make the payment.</description>
        <inlineHelpText>A valid PaymentMethod ID indicating the method being used to make the payment.</inlineHelpText>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACH,</fullName>
                </value>
                <value>
                    <fullName>PayPal,</fullName>
                </value>
                <value>
                    <fullName>CreditCard,</fullName>
                </value>
                <value>
                    <fullName>DebitCard,</fullName>
                </value>
                <value>
                    <fullName>CreditCardReferenceTransaction,</fullName>
                </value>
                <value>
                    <fullName>BankTransfer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zuora__Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference of a previous payment to which a refund is applied.</description>
        <inlineHelpText>The reference of a previous payment to which a refund is applied.</inlineHelpText>
        <label>Payment</label>
        <referenceTo>Zuora__Payment__c</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <description>The status of the refund. These statuses are determined by the system.</description>
        <inlineHelpText>The status of the refund. These statuses are determined by the system.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Voided</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Refund</label>
    <nameField>
        <label>Refund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__RefundInvoicePayment__c.object
<CustomObject>
    <description>Refund Invoice Payment Object represents the relation table between Refund and Invoice Payment object. This object would have Master Details relation between Refund and RefundInvoicePayment and reference relation between InvoicePayment and RefundInvoicePayment</description>
    <fields>
        <fullName>Zuora__EXT_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>External Id For Refund Invoice Payment Object,   Represents a Zuora Refund Invoice Payment Object Id</description>
        <externalId>true</externalId>
        <label>Unique External Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Refund Invoice Payment</label>
    <nameField>
        <displayFormat>RIP{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refund Invoice Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__CustomerAccount__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__SubscriptionStartDate__c</fullName>
        <description>The date when the subscription term starts. This is equal to the term start date if the subscription is on its initial term. Otherwise, it is the original term start date if the subscription has renewed.</description>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Zuora__ZInvoice__c.object
<CustomObject>
    <description>Zuora Invoice object. Invoices are bills that you send to customers.</description>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <description>The status of the invoice in the system. This status is not the status of the payment of the invoice, just the status of the invoice itself.</description>
        <inlineHelpText>The status of the invoice in the system. This status is not the status of the payment of the invoice, just the status of the invoice itself.</inlineHelpText>
        <label>Status</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__TaxAmount__c</fullName>
        <description>The total amount of the taxes applied to the invoice.</description>
        <inlineHelpText>The total amount of the taxes applied to the invoice.</inlineHelpText>
        <label>Tax Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Zuora__TaxExemptAmount__c</fullName>
        <description>The total amount of the invoice that is exempt from taxation.</description>
        <inlineHelpText>The total amount of the invoice that is exempt from taxation.</inlineHelpText>
        <label>Tax Exempt Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Zuora__TotalAmount__c</fullName>
        <description>The amount of the invoice.</description>
        <inlineHelpText>The amount of the invoice.</inlineHelpText>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PaymentHistoryControllerSeeAllDataTest.cls
@isTest 
private class PaymentHistoryControllerSeeAllDataTest {
    @testSetup
    public static void setup() {
        List<DAZNConfiguration__c> config = new List<DAZNConfiguration__c>();
        config.add(new DAZNConfiguration__c(
            Name = 'ZuoraEndPointInvoiceURL',
            Value__c = 'https://apisandbox-api.zuora.com/rest/v1/transactions/invoices/accounts/'
        ));
        config.add(new DAZNConfiguration__c(
            Name = 'ZuoraAPIUserId',
            Value__c = 'Librada.CespedosaSantiago@cognizant.com'
        ));
        config.add(new DAZNConfiguration__c(
            Name = 'ZuoraAPIUserPassword',
            Value__c = 'Amarillo12%'
        ));
        config.add(new DAZNConfiguration__c(
            Name = 'PaymentHistoryDownloadError',
            Value__c = 'paymenthistory?dowloaderror='
        ));
        config.add(new DAZNConfiguration__c(
            Name = 'InvoicePDFLink',
            Value__c = '/InvoicePDFPage?endpointForDownload='
        ));
        config.add(new DAZNConfiguration__c(
            Name = 'InvoicePDFGettingTimeout',
            Value__c = '3000'
        ));
        insert config;
        
        List<PaymentHistoryDownloadConfiguration__c> configDowload = new List<PaymentHistoryDownloadConfiguration__c>();
        configDowload.add(new PaymentHistoryDownloadConfiguration__c(
            Name = 'DE',
            Country_code__c = 'DE',
            Download_Invoice__c = true
        ));
        configDowload.add(new PaymentHistoryDownloadConfiguration__c(
            Name = 'US',
            Country_code__c = 'US',
            Download_Invoice__c = true
        ));
        configDowload.add(new PaymentHistoryDownloadConfiguration__c(
            Name = 'JP',
            Country_code__c = 'JP',
            Download_Invoice__c = true
        ));
        insert configDowload;
        DAZN_Country_Currency_ISO_Code__c isoUSD = new DAZN_Country_Currency_ISO_Code__c();
        isoUSD.name = 'USD';
        isoUSD.CurrencySymbol__c = '$';
        insert isoUSD;
        SetupTestData.createDAZNConfigurations();

        List<Payment_history_configuration__c> ls = new List<Payment_history_configuration__c>();
        ls.add(new Payment_history_configuration__c(
            Name = 'DE',
            Country_code__c = 'DE',
            Show_free_trial__c = true,
            Subscription_type__c = 'EVERGREEN'
        ));
        ls.add(new Payment_history_configuration__c(
            Name = 'JP',
            Country_code__c = 'JP',
            Show_free_trial__c = true,
            Subscription_type__c = 'EVERGREEN'
        ));
        ls.add(new Payment_history_configuration__c(
            Name = 'CA',
            Country_code__c = 'CA',
            Show_free_trial__c = false,
            Subscription_type__c = 'EVERGREEN'
        ));
        ls.add(new Payment_history_configuration__c(
            Name = 'CH',
            Country_code__c = 'CH',
            Show_free_trial__c = true,
            Subscription_type__c = 'EVERGREEN'
        ));
        ls.add(new Payment_history_configuration__c(
            Name = 'US',
            Country_code__c = 'US',
            Show_free_trial__c = true,
            Subscription_type__c = 'EVERGREEN'
        ));

        insert ls;
    }
    
    static testMethod void unitPaymentMethodCreditCard(){
     
        SetUpTestData.triggerSettings();
        SetUpTestData.emailCustsett();  
        Account oAccount = SetUpTestData.createPersonAccount('TestFirstName', 'TestLastName','uniqueEmail1@test.com','Free Trial');
        oAccount.Free_Trial_Start_Date__c = Date.today();
        update oAccount;
        User oUser = SetUpTestData.createCommunityUser(oAccount.Id, 'testemail@email.com', 'testusername@email.com', 'tstals','Europe/London','ISO-8859-1','fr_CA','fr_CA','TestFName','TestLName',true); 
        Zuora__CustomerAccount__c bAccount = SetUpTestData.createBillingAccount(oAccount.Id,'test billing account', 'Active', 'A00000073', 'testbill Name', 'United Kingdom', 'test bill name', 'PayPal', 'batch2', 'USD','1st of the month');
        system.assertNotEquals(null,bAccount.Id);
        Zuora__Subscription__c zSubsr = SetupTestData.createZuoraSubscription(oAccount.Id, bAccount.Id, 'test billing account subs', 'Active', Date.Today(), Date.today().addMonths(2) );
        Zuora__ZInvoice__c  zInv = SetUpTestData.createZuoraInvoice(oAccount.Id, bAccount.Id, 5000.00 );
        zInv.Zuora__TaxExemptAmount__c = 100.00 ;
        zInv.Zuora__TaxAmount__c = 200.00 ;
        zInv.Zuora__TotalAmount__c = 5100.00;
        update zInv;
        
        Zuora__Payment__c zPay = SetUpTestData.createZuoraPayment(oAccount.Id,bAccount.Id,zInv.Id, 5000.00);
        zPay.Zuora__Status__c = 'Processed';
        zPay.Zuora__Effective_Date__c = Date.today();
        zPay.Zuora__EXT_ID__c = 'testpaymentID';
        zPay.Zuora__PaymentMethod__c = 'Credit Card Visa ************1111';
        update zPay;

        zSubsr.Zuora__SubscriptionStartDate__c = Date.today();
        zSubsr.Zuora__TermSettingType__c = 'EVERGREEN';
        update zSubsr;
        
        Zuora__PaymentMethod__c zPaymentMethod = SetUpTestData.createZuoraPaymentMethod(bAccount.Id,'Active', 'CreditCard', '************7735', 'Visa', 'TestFirstName TestLastName', '04', '2018', '123456', 'Processed');
        
        Zuora__PaymentInvoice__c zPaymentInvoice = SetupTestData.createZuoraPaymentInvoice(zPay.Id, zInv.Id);
        zPaymentInvoice.Zuora__RefundAmount__c = 1000;
        update zPaymentInvoice; 
        
        Zuora__Refund__c oZuoraRefund = new Zuora__Refund__c();
        oZuoraRefund.Zuora__Account__c = oAccount.Id;
        oZuoraRefund.Zuora__BillingAccount__c = bAccount.Id;
        oZuoraRefund.Zuora__Payment__c = zPay.Id;
        oZuoraRefund.Zuora__Amount__c = 1000.00;    
        oZuoraRefund.Zuora__RefundDate__c = Date.today().addDays(-5);
        insert oZuoraRefund;
        system.assertNotEquals(null, oZuoraRefund);
        Zuora__RefundInvoicePayment__c oZuoraRefundInvoicePayment = new Zuora__RefundInvoicePayment__c();
        oZuoraRefundInvoicePayment.Zuora__Refund__c = oZuoraRefund.Id;
        oZuoraRefundInvoicePayment.Zuora__InvoicePayment__c =  zPaymentInvoice.Id;
        oZuoraRefundInvoicePayment.Zuora__RefundAmount__c = 1000.00;    
        insert oZuoraRefundInvoicePayment;    
        system.assertNotEquals(null, oZuoraRefundInvoicePayment);
        Test.StartTest();
        System.RunAs(oUser){
             ApexPages.currentPage().getParameters().put('lang', 'fr_CA');
            ApexPages.currentPage().getParameters().put('Country', 'CA');

            PaymentHistoryController objCntrl = new PaymentHistoryController();
            objCntrl.isSeeAllDataTest = true;
                       
            objCntrl.getUserSubscription(); 
            objCntrl.getCustomerPaymentHistory();
        }
    } 
    static testMethod void unitPaymentMethodPayPal(){
     
        SetUpTestData.triggerSettings();
        SetUpTestData.emailCustsett();  
        Account oAccount = SetUpTestData.createPersonAccount('TestFirstName', 'TestLastName','uniqueEmail13@test.com','Free Trial');
        oAccount.Free_Trial_Start_Date__c = Date.today();
        update oAccount;
        User oUser = SetUpTestData.createCommunityUser(oAccount.Id, 'testemail@email.com', 'testusername@email.com', 'tstals','Europe/London','ISO-8859-1','fr_CA','fr_CA','TestFName','TestLName',true); 
        Zuora__CustomerAccount__c bAccount = SetUpTestData.createBillingAccount(oAccount.Id,'test billing account', 'Active', 'A00000073', 'testbill Name', 'United Kingdom', 'test bill name', 'PayPal', 'batch2', 'USD','1st of the month');
        system.assertNotEquals(null,bAccount.Id);
        Zuora__Subscription__c zSubsr = SetupTestData.createZuoraSubscription(oAccount.Id, bAccount.Id, 'test billing account subs', 'Active', Date.Today(), Date.today().addMonths(2) );
        Zuora__ZInvoice__c  zInv = SetUpTestData.createZuoraInvoice(oAccount.Id, bAccount.Id, 5000.00 );
        zInv.Zuora__TaxExemptAmount__c = 100.00 ;
        zInv.Zuora__TaxAmount__c = 200.00 ;
        zInv.Zuora__TotalAmount__c = 5100.00;
        update zInv;
        
        Zuora__Payment__c zPay = SetUpTestData.createZuoraPayment(oAccount.Id,bAccount.Id,zInv.Id, 5000.00);
        zPay.Zuora__Status__c = 'Processed';
        zPay.Zuora__Effective_Date__c = Date.today();
        zPay.Zuora__EXT_ID__c = 'testpaymentID';
        zPay.Zuora__PaymentMethod__c = 'Credit Card Visa ************1111';
        update zPay;

        zSubsr.Zuora__SubscriptionStartDate__c = Date.today();
        zSubsr.Zuora__TermSettingType__c = 'EVERGREEN';
        update zSubsr;
        
        Zuora__PaymentMethod__c zPaymentMethod = SetUpTestData.createZuoraPaymentMethod(bAccount.Id,'Active', 'PayPal', '************7735', 'Visa', 'TestFirstName TestLastName', '04', '2018', '123456', 'Processed');
        
        Zuora__PaymentInvoice__c zPaymentInvoice = SetupTestData.createZuoraPaymentInvoice(zPay.Id, zInv.Id);
        zPaymentInvoice.Zuora__RefundAmount__c = 1000;
        update zPaymentInvoice; 
        
        Zuora__Refund__c oZuoraRefund = new Zuora__Refund__c();
        oZuoraRefund.Zuora__Account__c = oAccount.Id;
        oZuoraRefund.Zuora__BillingAccount__c = bAccount.Id;
        oZuoraRefund.Zuora__Payment__c = zPay.Id;
        oZuoraRefund.Zuora__Amount__c = 1000.00;    
        oZuoraRefund.Zuora__RefundDate__c = Date.today().addDays(-5);
        insert oZuoraRefund;
        system.assertNotEquals(null, oZuoraRefund);
        Zuora__RefundInvoicePayment__c oZuoraRefundInvoicePayment = new Zuora__RefundInvoicePayment__c();
        oZuoraRefundInvoicePayment.Zuora__Refund__c = oZuoraRefund.Id;
        oZuoraRefundInvoicePayment.Zuora__InvoicePayment__c =  zPaymentInvoice.Id;
        oZuoraRefundInvoicePayment.Zuora__RefundAmount__c = 1000.00;    
        insert oZuoraRefundInvoicePayment;    
        system.assertNotEquals(null, oZuoraRefundInvoicePayment);
        Test.StartTest();
        System.RunAs(oUser){
             ApexPages.currentPage().getParameters().put('lang', 'fr_CA');
            ApexPages.currentPage().getParameters().put('Country', 'CA');

            PaymentHistoryController objCntrl = new PaymentHistoryController();
            objCntrl.isSeeAllDataTest = true;
                       
            objCntrl.getUserSubscription(); 
            objCntrl.getCustomerPaymentHistory();
        }
    } 
    static testMethod void unitPaymentMethodBankTransfer(){
     
        SetUpTestData.triggerSettings();
        SetUpTestData.emailCustsett();  
        Account oAccount = SetUpTestData.createPersonAccount('TestFirstName', 'TestLastName','uniqueEmail2@test.com','Free Trial');
        oAccount.Free_Trial_Start_Date__c = Date.today();
        update oAccount;
        User oUser = SetUpTestData.createCommunityUser(oAccount.Id, 'testemail@email.com', 'testusername@email.com', 'tstals','Europe/London','ISO-8859-1','fr_CA','fr_CA','TestFName','TestLName',true); 
        Zuora__CustomerAccount__c bAccount = SetUpTestData.createBillingAccount(oAccount.Id,'test billing account', 'Active', 'A00000073', 'testbill Name', 'United Kingdom', 'test bill name', 'PayPal', 'batch2', 'USD','1st of the month');
        system.assertNotEquals(null,bAccount.Id);
        Zuora__Subscription__c zSubsr = SetupTestData.createZuoraSubscription(oAccount.Id, bAccount.Id, 'test billing account subs', 'Active', Date.Today(), Date.today().addMonths(2) );
        Zuora__ZInvoice__c  zInv = SetUpTestData.createZuoraInvoice(oAccount.Id, bAccount.Id, 5000.00 );
        zInv.Zuora__TaxExemptAmount__c = 100.00 ;
        zInv.Zuora__TaxAmount__c = 200.00 ;
        zInv.Zuora__TotalAmount__c = 5100.00;
        zInv.Zuora__External_Id__c = 'testinvoiceID';
        update zInv;
        
        Zuora__Payment__c zPay = SetUpTestData.createZuoraPayment(oAccount.Id,bAccount.Id,zInv.Id, 5000.00);
        zPay.Zuora__Status__c = 'Processed';
        zPay.Zuora__Effective_Date__c = Date.today();
        zPay.Zuora__EXT_ID__c = 'testpaymentID';
        zPay.Zuora__PaymentMethod__c = 'Credit Card Visa ************1111';
        update zPay;

        zSubsr.Zuora__SubscriptionStartDate__c = Date.today();
        zSubsr.Zuora__TermSettingType__c = 'EVERGREEN';
        update zSubsr;
        
        Zuora__PaymentMethod__c zPaymentMethod = SetUpTestData.createZuoraPaymentMethod(bAccount.Id,'Active', 'BankTransfer', '************7735', 'Visa', 'TestFirstName TestLastName', '04', '2018', '123456', 'Processed');
        
        Zuora__PaymentInvoice__c zPaymentInvoice = SetupTestData.createZuoraPaymentInvoice(zPay.Id, zInv.Id);
        zPaymentInvoice.Zuora__RefundAmount__c = 1000;
        update zPaymentInvoice; 
        
        Zuora__Refund__c oZuoraRefund = new Zuora__Refund__c();
        oZuoraRefund.Zuora__Account__c = oAccount.Id;
        oZuoraRefund.Zuora__BillingAccount__c = bAccount.Id;
        oZuoraRefund.Zuora__Payment__c = zPay.Id;
        oZuoraRefund.Zuora__Amount__c = 1000.00;    
        oZuoraRefund.Zuora__RefundDate__c = Date.today().addDays(-5);
        insert oZuoraRefund;
        system.assertNotEquals(null, oZuoraRefund);
        Zuora__RefundInvoicePayment__c oZuoraRefundInvoicePayment = new Zuora__RefundInvoicePayment__c();
        oZuoraRefundInvoicePayment.Zuora__Refund__c = oZuoraRefund.Id;
        oZuoraRefundInvoicePayment.Zuora__InvoicePayment__c =  zPaymentInvoice.Id;
        oZuoraRefundInvoicePayment.Zuora__RefundAmount__c = 1000.00;    
        insert oZuoraRefundInvoicePayment;    
        system.assertNotEquals(null, oZuoraRefundInvoicePayment);
        Test.StartTest();
        System.RunAs(oUser){
             ApexPages.currentPage().getParameters().put('lang', 'fr_CA');
            ApexPages.currentPage().getParameters().put('Country', 'CA');

            PaymentHistoryController objCntrl = new PaymentHistoryController();
            objCntrl.isSeeAllDataTest = true;
                       
            objCntrl.getUserSubscription(); 
            objCntrl.getCustomerPaymentHistory();
        }
    }
    
}