objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partial</fullName>
                    <default>true</default>
                    <label>Partial</label>
                </value>
                <value>
                    <fullName>Free Trial</fullName>
                </value>
                <value>
                    <fullName>Active Paid</fullName>
                </value>
                <value>
                    <fullName>Active Grace</fullName>
                </value>
                <value>
                    <fullName>Frozen</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Expired Marketing</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Apple</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/MISL_Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used to store the settings related to MISL Integarion.</description>
    <fields>
        <fullName>Enabled_Country_Codes__c</fullName>
        <label>Enabled Country Codes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Timeout__c</fullName>
        <defaultValue>3000</defaultValue>
        <label>Timeout</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MISL Configuration</label>
</CustomObject>

objects/User_Devices__c.object
<CustomObject>
    <description>This object is used to store user devices used to sign-in in application.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>User Account and Device Relationship field</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>User Devices</relationshipLabel>
        <relationshipName>User_Devices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Of_Registration__c</fullName>
        <description>Device Registration Date</description>
        <label>Date Of Registration</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Device_Name__c</fullName>
        <description>This field is used to store registered device name.</description>
        <label>Device Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Device Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>InActive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Device Type</description>
        <label>Device Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Console</fullName>
                </value>
                <value>
                    <fullName>Desktop</fullName>
                </value>
                <value>
                    <fullName>Laptop</fullName>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                </value>
                <value>
                    <fullName>Tablet</fullName>
                </value>
                <value>
                    <fullName>TV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Devices</label>
    <nameField>
        <displayFormat>DN-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Devices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CSSignoutfromalldevicesTest.cls
@isTest
public class CSSignoutfromalldevicesTest {

    @testSetup
    public static void getCommUsersTestData() {
        CreateTestDataforUnitTest.triggerSettings();
        CreateZuoraDataforUnitTest.createZuoraDeatils();
        CreateTestDataforUnitTest.createTestcustomsetting();
        
        List<MISL_Configuration__c> config = new List<MISL_Configuration__c>();
        config.add(new MISL_Configuration__c(
            Name = 'MISL_DeRegisterDevices',
            Value__c = 'DeRegisterDevices',
            Enabled_Country_Codes__c = 'DE',
            Timeout__c = 3000
        ));
        config.add(new MISL_Configuration__c(
            Name = 'MISL_Username',
            Value__c = 't1'
        ));
        config.add(new MISL_Configuration__c(
            Name = 'MISL_Password',
            Value__c = EncodingUtil.base64Encode(Blob.valueOf('t2'))
        ));
        insert config;
    }  
    static testMethod void testCSShowallleDeviceSuccess() {
        List<Account> accList = [SELECT Id, Name, PersonEmail, PersonContactId FROM Account WHERE Account_Status__c = 'Active Paid'];
	    List<Profile> profile = [SELECT Id, Name FROM profile WHERE Name = 'Customer Service Team Member' LIMIT 1];
        System.assert(profile.size() > 0);
        List<User> oUser = [
            SELECT Id, Name, UserName, Alias, Country, profileId, LanguageLocaleKey
            FROM User
            WHERE profileId=:profile[0].Id
            AND IsActive = true LIMIT 1
        ];
        System.assertNotEquals(null, oUser);
        List<User_Devices__c> userDiv = [
            SELECT Id, Device_Name__c, Account__c, Date_Of_Registration__c, Type__c, Status__c
            FROM User_Devices__c
            WHERE Account__c =: accList[0].id
        ];
        Integer countOfDiv = userDiv.size();
        System.RunAs(oUser[0]) {
            Test.startTest();
            
            Test.setMock(HttpCalloutMock.class, new MockDeRegisterDevicesResponse());
            String isSuccess = CSSignoutfromalldevices.CSForceSignout(accList[0].Id);
            System.assertEquals('Success', isSuccess);
            
            Test.stopTest();
        }
    }
    
    static testMethod void testCSShowallleDeviceMISLDisabled() {
        List<Account> accList = [SELECT Id, Name, PersonEmail, PersonContactId FROM Account WHERE Account_Status__c = 'Active Paid'];
        List<Profile> profile = [SELECT Id, Name FROM profile WHERE Name = 'Customer Service Team Member' LIMIT 1];
        System.assert(profile.size() > 0);
        List<User> oUser = [
            SELECT Id, Name, UserName, Alias, Country, profileId, LanguageLocaleKey
            FROM User
            WHERE profileId=:profile[0].Id
            AND IsActive = true LIMIT 1
        ];
        System.assertNotEquals(null, oUser);
        List<User_Devices__c> userDiv = [
            SELECT Id, Device_Name__c, Account__c, Date_Of_Registration__c, Type__c, Status__c
            FROM User_Devices__c
            WHERE Account__c =: accList[0].Id
        ];
        User_Devices__c singleDev = SetUpTestData.createUserDevice(accList[0].Id, 'Test User Device', System.today(), 'Desktop' , 'Active');
        delete MISL_Configuration__c.getValues('MISL_DeRegisterDevices');
        System.RunAs(oUser[0]) {
            Test.startTest();
            String isSuccess = CSSignoutfromalldevices.CSForceSignout(accList[0].Id);
            System.assertEquals('Success', isSuccess);
            Test.stopTest();
        }
        System.assertEquals(0, [SELECT Id FROM User_Devices__c WHERE Account__c =: accList[0].Id].size());
    }
    
    static testMethod void testCSShowallleDeviceFailure() {
        List<Account> accList = [SELECT Id, Name, PersonEmail, PersonContactId FROM Account WHERE Account_Status__c = 'Active Paid'];
	    List<Profile> profile = [SELECT Id, Name FROM profile WHERE Name = 'Customer Service Team Member' LIMIT 1];
        System.assert(profile.size() > 0);
        List<User> oUser = [
            SELECT Id, Name, UserName, Alias, Country, profileId, LanguageLocaleKey
            FROM User
            WHERE profileId=:profile[0].Id
            AND IsActive = true LIMIT 1
        ];
        System.assertNotEquals(null, oUser);
        List<User_Devices__c> userDiv = [
            SELECT Id, Device_Name__c, Account__c, Date_Of_Registration__c, Type__c, Status__c
            FROM User_Devices__c
            WHERE Account__c =: accList[0].id
        ];
        Integer countOfDiv = userDiv.size();
        System.RunAs(oUser[0]) {
            Test.startTest();
            
            String isSuccess = CSSignoutfromalldevices.CSForceSignout(accList[0].Id);
            System.assertNotEquals('Success', isSuccess);
            
            Test.stopTest();
        }
    }
    
    public class MockDeRegisterDevicesResponse implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setStatusCode(204);
            return res;
        }
    }

}