objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partial</fullName>
                    <default>true</default>
                    <label>Partial</label>
                </value>
                <value>
                    <fullName>Free Trial</fullName>
                </value>
                <value>
                    <fullName>Active Paid</fullName>
                </value>
                <value>
                    <fullName>Active Grace</fullName>
                </value>
                <value>
                    <fullName>Frozen</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Expired Marketing</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Apple</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cancelled_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelled Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notification_Country_Code__c</fullName>
        <label>Notification Country Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification_Language_Code__c</fullName>
        <label>Notification Language Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PauseScheduled__c</fullName>
        <formula>IF( 
ISNULL( Pause_From__c ), 
false, 
IF( 
Pause_From__c &gt; TODAY(), 
true, 
false 
) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PauseScheduled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pause_From__c</fullName>
        <label>Pause From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Pause_Until__c</fullName>
        <label>Pause Until</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Previous_BCD__c</fullName>
        <label>Previous BCD</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Submitted_for_cancellation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Submitted for cancellation</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Notification_Language_Code__c</fullName>
        <label>Notification Language Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/User_Devices__c.object
<CustomObject>
    <description>This object is used to store user devices used to sign-in in application.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>User Account and Device Relationship field</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>User Devices</relationshipLabel>
        <relationshipName>User_Devices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Device Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>InActive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Devices</label>
    <nameField>
        <displayFormat>DN-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Devices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__Payment__c.object
<CustomObject>
    <description>Zuora Payment object.  A payment is the money that customers send to pay for charges related to their subscriptions. 
The Payment object holds all of the information about an individual payment, including the payment amount and to which invoices the payment is applied.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The CRM Account that this payment is related to.</description>
        <inlineHelpText>The CRM Account that this payment is related to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__CreatedDate__c</fullName>
        <description>The date when the payment was created in Zuora system.</description>
        <inlineHelpText>The date when the payment was created in Zuora system.</inlineHelpText>
        <label>Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Zuora__EXT_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>External Id For Payment object,   Represents a Zuora Payment object Id</description>
        <externalId>true</externalId>
        <label>Unique External Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <description>The payment ID in Zuora system.</description>
        <externalId>true</externalId>
        <label>External ID(Deprecated)</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__SettledOn__c</fullName>
        <description>The date when the payment was settled in the payment processor.</description>
        <inlineHelpText>The date when the payment was settled in the payment processor.</inlineHelpText>
        <label>Settled On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <description>The status of the payment in the Zuora system. The value depends on the type of payment.</description>
        <inlineHelpText>The status of the payment in the Zuora system. The value depends on the type of payment.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Posted</fullName>
                </value>
                <value>
                    <fullName>Voided</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__Refund__c.object
<CustomObject>
    <description>The Refund object is used to create and query refunds. 

Note that refunds imply that money has been returned to customers. You should use adjustments (credit memos) if you are issuing credit to customers, but are not returning funds to a customer.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The CRM Account that this payment is related to.</description>
        <inlineHelpText>The CRM Account that this payment is related to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__CreatedDate__c</fullName>
        <description>The Zuora system automatically generates this value, which records when the object was created.</description>
        <inlineHelpText>The Zuora system automatically generates this value, which records when the object was created.</inlineHelpText>
        <label>Created On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External_Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference of a previous payment to which a refund is applied.</description>
        <inlineHelpText>The reference of a previous payment to which a refund is applied.</inlineHelpText>
        <label>Payment</label>
        <referenceTo>Zuora__Payment__c</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <description>The status of the refund. These statuses are determined by the system.</description>
        <inlineHelpText>The status of the refund. These statuses are determined by the system.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Voided</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Refund</label>
    <nameField>
        <label>Refund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This field holds the Zuora object ID, and is used as external ID for data synchronization between Salesforce and Zuora.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__NextChargeDate__c</fullName>
        <label>Next Charge Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__NextRenewalDate__c</fullName>
        <label>Next Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__SubscriptionEndDate__c</fullName>
        <description>This is when the subscription ends. This is always equal to term end date, unless the subscription has been cancelled. If the subscription has been cancelled, this is set to the cancellation date.</description>
        <label>Subscription End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__SubscriptionStartDate__c</fullName>
        <description>The date when the subscription term starts. This is equal to the term start date if the subscription is on its initial term. Otherwise, it is the original term start date if the subscription has renewed.</description>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CancelSubscriptionExtension.cls
/**
* @author Cognizant Technology Solutuions
* @date 10/12/2015
* @description Cancel Subscription Extension class for service agent cancel subscription operation
*/

public without sharing class CancelSubscriptionExtension{
    public string reasonForCncl{get;set;}
    public Boolean showSubmitButton {get; set;}
    public Boolean showErrMsg{get;set;}
    public string cancellationType {get; set;}
    @TestVisible
    public List<Account> lstAccount {get;set;}
    private string sAccountID {get;set;}
    //public Boolean activeSubscriptions{get;set;}
    public string sAccountStatus{get;set;}
    public Boolean isFreeTrialAccount{get;set;}
    public string sPersonContactId {get;set;}
    public string sEmail {get;set;}
    public string sUserLanguage {get;set;}
    public string sUserCountryCode{get;set;}
    
    public Boolean isPauseScheduled {get;set;}
    String serviceStartDate/* = null*/;
    public List<Zuora__Payment__c> chosePayment;
    /*
Description: Constructor, used to enable / disable Cancel & Refund buttons based on subscription status.
*/
    public CancelSubscriptionExtension(ApexPages.StandardController controller) {
        // To get account id from controller PD-7932.
        sAccountID = controller.getId();
        showSubmitButton = true;
        isFreeTrialAccount = false;
        showErrMsg = false;
        serviceStartDate = null;

        /* Retrive subscriptions information for customer.*/
        if(sAccountID!=null){
            lstAccount =  [SELECT ID, Account_Status__c, PersonContactId, PersonEmail, Notification_Language_Code__c, Notification_Country_Code__c, Pause_From__c, PauseScheduled__c, Pause_Until__c, Previous_BCD__c,
                           (SELECT Name, Zuora__Status__c, Zuora__NextRenewalDate__c,Zuora__External_Id__c,Zuora__NextChargeDate__c, Zuora__SubscriptionEndDate__c 
                            FROM Zuora__Subscriptions__r 
                            Where Zuora__Status__c='Active'
                            Order By Zuora__SubscriptionStartDate__c 
                            DESC NULLS LAST)                                                    
                           FROM Account 
                           WHERE ID=:sAccountID 
                           LIMIT 1];
        }
        
        if(lstAccount !=null && !lstAccount.isEmpty()){
            sAccountStatus = lstAccount[0].Account_Status__c;
            sPersonContactId = lstAccount[0].PersonContactId;
            isPauseScheduled = lstAccount[0].PauseScheduled__c;
            sEmail = lstAccount[0].PersonEmail;
            sUserLanguage = lstAccount[0].Notification_Language_Code__c;
            sUserCountryCode = lstAccount[0].Notification_Country_Code__c;
            if(sAccountStatus == 'Partial' || sAccountStatus== 'Frozen' ||sAccountStatus == 'Expired'||sAccountStatus == 'Expired Marketing'){
                apexpages.addmessage(new apexpages.message(ApexPages.severity.INFO, System.Label.LS_CancelSubscription_ErrMsg_NoCancellation));
                showErrMsg = true;
                return;
            }
            if(sAccountStatus == 'Free Trial'){
                isFreeTrialAccount = true ;
            }
            if(lstAccount[0].Zuora__Subscriptions__r == null || lstAccount[0].Zuora__Subscriptions__r.isEmpty() )
            {
                apexpages.addmessage(new apexpages.message(ApexPages.severity.INFO, System.Label.LS_CancelSubscription_ErrMsg_NoActiveSubscription));
                showErrMsg = true;return;
            }
            
        }else{
            apexpages.addmessage(new apexpages.message(ApexPages.severity.ERROR, System.Label.LS_CancelSubscription_Page_Message_No_Account_Found ));
            showSubmitButton = false;return;
        }                       
    }


    /*
    Description: Method to cancel the subscription and create a Refund based on cancellation type
    */
    public PageReference CancelSubscription() { 
        if (String.isNotBlank(reasonForCncl)) {
            reasonForCncl = reasonForCncl.replace('&amp;', '&');
        } else {
            reasonForCncl = 'Others';
        }
        Boolean bGenerateInvoice = false;
        showErrMsg = false;
        try {
            /* Check option is selected for cancellation.*/
            if (String.isNotBlank(cancellationType)) {
                /*Check if Cancellation Reason is specified*/
                if (String.isNotBlank(reasonForCncl)) {
                    Zuora__Subscription__c oSubscription = lstAccount[0].Zuora__Subscriptions__r[0];
                    /*Check Account has atleast one subscription and the subscription is active*/
                    if (lstAccount[0].Zuora__Subscriptions__r.size() > 0 && oSubscription.Zuora__Status__c == 'Active') {
                        if(cancellationType != 'Immediate') {
                            /*Start part of PD-11896. Standard cancelation Pause in Future*/
                            // std cancel for future pause
                            if (sAccountStatus == 'Paused') {
                                /*Standard cancelation Pause started*/
                                apexpages.addmessage(new apexpages.message(ApexPages.severity.ERROR, System.Label.LS_MyAccount_StCancelationNotPossible));
                                showErrMsg = true;
                                return null;
                            } else if (sAccountStatus == 'Active Grace') {
                                apexpages.addmessage(new apexpages.message(ApexPages.severity.ERROR, System.Label.LS_MyAccount_StCancelationForActiveGraceNotPossible));
                                showErrMsg = true;
                                return null;
                            } else {
                                //added as part of PD-13271
                                Date ratePlanChargeChargedThroughDate = ZuoraTransactionHelper.getRatePlanChargeChargedThroughDateByAccountId(sAccountID);
                                if (ratePlanChargeChargedThroughDate != null) {
                                    serviceStartDate = CommunityHelper.ConvertDateToString(ratePlanChargeChargedThroughDate,'ZouraFormat','NA');
                                } else {
                                    apexpages.addmessage(new apexpages.message(ApexPages.severity.ERROR, System.Label.LS_CancelSubscription_ErrMsg_NoRatePlanCharge));
                                    showErrMsg = true;return null;
                                }
                                
                                if (isPauseScheduled) {
                                    return startFlowStandartFuture();
                                } else {
                                    return startStandardCancelZuoraWorkflow(oSubscription.Name, serviceStartDate);
                                }
                            }
                        } else {
                             String paymentId = '';
                             serviceStartDate = CommunityHelper.ConvertDateToString(Date.today(), 'ZouraFormat', 'NA');
                             bGenerateInvoice = true;
                            //PD-11761
                            List<Zuora__Payment__c> paymentRecObj = new List<Zuora__Payment__c>();
                            if (lstAccount.size() > 0) {
                                paymentRecObj = [
                                    SELECT Id, Name, Zuora__EXT_ID__c, Zuora__SettledOn__c, Zuora__CreatedDate__c, Zuora__Account__c
                                    FROM Zuora__Payment__c
                                    WHERE Zuora__Account__c = :lstAccount[0].Id ORDER BY Zuora__CreatedDate__c DESC
                                ];
                            }
                            if (paymentRecObj.size() > 0) {
                                if (paymentRecObj[0].Zuora__SettledOn__c != null) {
                                    paymentId = paymentRecObj[0].Zuora__EXT_ID__c;

                                    /*Start part of PD-11761*/
                                    if (!String.isBlank(paymentId)) {
                                        List<Zuora__Refund__c> refunds = [SELECT Zuora__Payment__c FROM Zuora__Refund__c WHERE Zuora__Payment__c = :paymentRecObj[0].Id];
                                        if (!refunds.isEmpty()) {
                                            paymentId = null;
                                        }
                                    }
                                    /*End part of PD-11761*/

                                } else{
                                    apexpages.addmessage(new apexpages.message(ApexPages.severity.ERROR, System.Label.LS_CancelSubscription_Page_Message_No_Settled_On));
                                    showErrMsg = true;
                                    return null;
                                }
                            }
                            
                            if (isPauseScheduled) {
                                return startFlowImmediateFuture();
                            } else {
                                System.debug('##### paymentId = ' + paymentId);
                                return startImmediateCancelZuoraWorkflow(oSubscription.Name, serviceStartDate, paymentId);
                            }

                        }

                    } else {
                        apexpages.addmessage(new apexpages.message(ApexPages.severity.ERROR, System.Label.LS_CancelSubscription_ErrMsg_NoActiveSubscription ));
                        showErrMsg = true;
                        return null;
                    }
                } else {
                    showSubmitButton = false;
                }
            } else {
                showSubmitButton = false;
            }
        } catch (Exception ex) {
            ExceptionLoggerHelper.createExceptionLog(UserInfo.getUserId(), 'CancelSubscriptionExtension ', 'cancelSubscription', ex.getMessage(), ex.getTypeName(), ex.getStackTraceString()); 
        }
        if (showErrMsg) {
            return null;
        } else {
            return new PageReference('/' + sAccountId);
        }
    }
    
   

    public static void updateAccountStatusPause(Id sId, string sStatus){
        if(sId != null){
            Account objAccount=[Select ID, Account_Status__c, Submitted_for_cancellation__c, Cancelled_Account__c, Pause_From__c, PauseScheduled__c, Pause_Until__c, Previous_BCD__c From Account where ID =:sId Limit 1];
            if (sStatus != null) {
                objAccount.Account_Status__c = sStatus;
            }
            objAccount.Submitted_for_cancellation__c = true;
            objAccount.Pause_Until__c = null;
            objAccount.Pause_From__c = null;
            objAccount.Cancelled_Account__c = true;
            update objAccount;
        }
    }

    public PageReference startFlowStandartFuture() {
        Map<String, String> outputResult = PauseCalloutHelper.initPauseCalloutScheduledFuture(lstAccount[0], true);
        Boolean isResultSuccess = Boolean.valueOf(outputResult.get('success'));
        if (!isResultSuccess) {
            apexpages.addmessage(new apexpages.message(ApexPages.severity.ERROR, System.Label.LS_MyAccount_FailSubscriptionPause));
            showErrMsg = true;
            return null;
        } else {
            updateAccountStatusPause(lstAccount[0].Id, null);
            createTaskForCancelation();
            apexpages.addmessage(new apexpages.message(ApexPages.severity.CONFIRM, System.Label.LS_CancelSubscription_Page_Message_Standard_Cancelled_Success));
            showErrMsg = true;
            return null;
        }
    }

    public PageReference startFlowImmediateFuture() {
        Map<String, String> outputResult = PauseCalloutHelper.initPauseCalloutScheduledFuture(lstAccount[0], false);
        Boolean isResultSuccess = Boolean.valueOf(outputResult.get('success'));
        if (isResultSuccess) {
            updateAccountStatusPause(lstAccount[0].Id, 'Frozen');
            createTaskForCancelation();
            //CommunityHelper.updateSignoutKey(lstAccount[0].Id); //Commented Redundant code as part of PD-11487
            apexpages.addmessage(new apexpages.message(ApexPages.severity.CONFIRM, System.Label.LS_MyAccount_SuccessSubscriptionPause));
            showErrMsg = true;
            return null;
        } else {
            apexpages.addmessage(new apexpages.message(ApexPages.severity.ERROR, System.Label.LS_MyAccount_FailSubscriptionPause));
            showErrMsg = true;
            return null;
        }
    }
    
    public PageReference startImmediateCancelZuoraWorkflow(String subscriptionName, String cancelDate, String paymentId) {
        Map<String, String> outputResult = PauseCalloutHelper.runImmediateCancelZuoraWorkflow(subscriptionName, cancelDate, paymentId);
        Boolean isResultSuccess = Boolean.valueOf(outputResult.get('success'));
        if (isResultSuccess) {
            updateAccountFieldsAndStatusToFrozen(true);
            createTaskForCancelation();
            return null;
        } else {
            apexpages.addmessage(new apexpages.message(ApexPages.severity.ERROR, outputResult.get('message')));
            showErrMsg = true;
            return null;
        }
    }
    
    public PageReference startStandardCancelZuoraWorkflow(String subscriptionName, String cancelDate) {
        Map<String, String> outputResult = PauseCalloutHelper.runStandardCancelZuoraWorkflow(subscriptionName, cancelDate);
        Boolean isResultSuccess = Boolean.valueOf(outputResult.get('success'));
        if (isResultSuccess) {
            List<Account> acc = [
                SELECT Id, Submitted_for_cancellation__c, Cancelled_Account__c
                FROM Account 
                WHERE Id =:sAccountID LIMIT 1
            ];
            if (acc != null && !acc.isEmpty()) {
                acc[0].Submitted_for_cancellation__c = true;
                acc[0].Cancelled_Account__c = true;
                update acc[0];
            }
            createTaskForCancelation();
            return new PageReference('/' + sAccountId);
        } else {
            apexpages.addmessage(new apexpages.message(ApexPages.severity.ERROR, System.Label.LS_MyAccount_FailSubscriptionPause));
            showErrMsg = true;
            return null;
        }
    }

    public void createTaskForCancelation() {
        insert new Task(
            ActivityDate = system.today(),
            Description = reasonForCncl,
            Status = 'Completed',
            Subject = Label.LS_Why_Subscription_Cancellation,
            OwnerId = userinfo.getUserId(),
            WhatId = sAccountID
        );
    }

    /*Update Account Status on successful cancellation to "Frozen" */
    public void updateAccountFieldsAndStatusToFrozen(Boolean isShowMessage) {
        CommunityHelper.updateAccountStatus(sAccountID, 'Frozen');
                                                    
        apexpages.addmessage(new apexpages.message(ApexPages.severity.CONFIRM, System.Label.LS_CancelSubscription_Page_Message_Immediate_Cancelled_Success));
        showErrMsg = isShowMessage;
        // delete the user registered devices
        List<User_Devices__c> lstAllUserDevices = [
            SELECT Status__c
            FROM User_Devices__c 
            WHERE Account__c =:sAccountID and Status__c='Active' 
            LIMIT 100
        ];
        if (lstAllUserDevices!=null && !lstAllUserDevices.isEmpty()) {
            delete lstAllUserDevices;
        }
    }

    public static void updateAccountStatusAfterCancelSubscription(String accId, String effectiveDate) {
        Account accountToUpdate = [SELECT Id, Account_Status__c, Cancelled_Account__c FROM Account WHERE Id = :accId];
        Date dEffectiveDate = Date.valueOf(effectiveDate);
        if (dEffectiveDate <= Date.today()) {
            accountToUpdate.Account_Status__c = 'Frozen';
            accountToUpdate.Cancelled_Account__c = true;
        }
        update accountToUpdate;
    }
    
}