objects/Account.object
<CustomObject>
    <fields>
        <fullName>IP_address__c</fullName>
        <description>storing IP address</description>
        <label>IP address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification_Country_Code__c</fullName>
        <label>Notification Country Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/DeviceSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This Custom setting is used to limit the number of Active User devices for each Country</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MaxDevices__c</fullName>
        <label>MaxDevices</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DeviceSettings</label>
</CustomObject>

objects/User_Devices__c.object
<CustomObject>
    <description>This object is used to store user devices used to sign-in in application.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>User Account and Device Relationship field</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>User Devices</relationshipLabel>
        <relationshipName>User_Devices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Of_Registration__c</fullName>
        <description>Device Registration Date</description>
        <label>Date Of Registration</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Device_Id__c</fullName>
        <label>Device Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Device_Name__c</fullName>
        <description>This field is used to store registered device name.</description>
        <label>Device Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Device_Registration_Date__c</fullName>
        <description>Device Registration Date</description>
        <label>Device Registration Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Device_manufacturer__c</fullName>
        <label>Device manufacturer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Device_version__c</fullName>
        <label>Device version</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IP_address__c</fullName>
        <description>Storing IP address</description>
        <label>IP address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operating_System_Name__c</fullName>
        <label>Operating System Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operating_System_Version__c</fullName>
        <label>Operating System Version</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Device Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>InActive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Device Type</description>
        <label>Device Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Console</fullName>
                </value>
                <value>
                    <fullName>Desktop</fullName>
                </value>
                <value>
                    <fullName>Laptop</fullName>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                </value>
                <value>
                    <fullName>Tablet</fullName>
                </value>
                <value>
                    <fullName>TV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Agent__c</fullName>
        <label>User Agent</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>User Devices</label>
    <nameField>
        <displayFormat>DN-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Devices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BatchUserDevicesDeleteonAccountTest.cls
@IsTest
public class BatchUserDevicesDeleteonAccountTest {
    static testMethod void test() {
        SetUpTestData.triggerSettings();
        //Database.BatchableContext BC=new Database.BatchableContext();
        DeviceSettings__c setting = new DeviceSettings__c();
        setting.Name = 'Japan';
        setting.Country__c = 'JP';
        setting.MaxDevices__c = 4;
        insert setting;
        System.assertEquals('Japan', setting.Name);
        list<User_Devices__c> listuserdevices = new list<User_Devices__c>();
        //Insert account
        Account oAccount = SetUpTestData.createPersonAccount('TestFirstName', 'TestLastName','pm1testemail@email.com','Free Trial');        
        //SetUpTestData.createCommunityUser(oAccount.Id, 'pm1testemail@email.com', 'pm1testemail@email.com', 'tstals1','Europe/London','ISO-8859-1','en_US','en_US','TestFName','TestLName',true);
        /*Account oAccount=new Account();
oAccount.Name='NameDemo';
oAccount.Notification_Country_Code__c='JP';
insert oAccount;*/
        oAccount.Notification_Country_Code__c = 'JP';
        update oAccount;
        
        //inserting devices related to account
        User_Devices__c device1=new User_Devices__c();
        device1.Account__c=oAccount.Id;
        device1.Date_Of_Registration__c=System.today();
        device1.Device_Id__c='DESK001';
        device1.Device_manufacturer__c='';
        device1.Device_Name__c='Desktop1';
        device1.Device_Registration_Date__c=System.today();
        device1.Type__c='Desktop';
        device1.Device_version__c='';
        device1.IP_address__c ='1638399';
        device1.Operating_System_Name__c='';
        device1.Operating_System_Version__c='';
        device1.Status__c='Active';
        device1.User_Agent__c='';
        listuserdevices.add(device1);
        
        User_Devices__c device2=new User_Devices__c();
        device2.Account__c=oAccount.Id;
        device2.Date_Of_Registration__c=System.today();
        device2.Device_Id__c='DESK001';
        device2.Device_manufacturer__c='';
        device2.Device_Name__c='Desktop1';
        device2.Device_Registration_Date__c=System.today();
        device2.Type__c='Desktop';
        device2.Device_version__c='';
        device2.IP_address__c ='1638399';
        device2.Operating_System_Name__c='';
        device2.Operating_System_Version__c='';
        device2.Status__c='Active';
        device2.User_Agent__c='';
        listuserdevices.add(device2);
        
        User_Devices__c device3=new User_Devices__c();
        device3.Account__c=oAccount.Id;
        device3.Date_Of_Registration__c=System.today();
        device3.Device_Id__c='DESK001';
        device3.Device_manufacturer__c='';
        device3.Device_Name__c='Desktop1';
        device3.Device_Registration_Date__c=System.today();
        device3.Type__c='Desktop';
        device3.Device_version__c='';
        device3.IP_address__c ='1638399';
        device3.Operating_System_Name__c='';
        device3.Operating_System_Version__c='';
        device3.Status__c='Active';
        device3.User_Agent__c='';
        listuserdevices.add(device3);
        
        User_Devices__c device4=new User_Devices__c();
        device4.Account__c=oAccount.Id;
        device4.Date_Of_Registration__c=System.today();
        device4.Device_Id__c='DESK001';
        device4.Device_manufacturer__c='';
        device4.Device_Name__c='Desktop1';
        device4.Device_Registration_Date__c=System.today();
        device4.Type__c='Desktop';
        device4.Device_version__c='';
        device4.IP_address__c ='1638399';
        device4.Operating_System_Name__c='';
        device4.Operating_System_Version__c='';
        device4.Status__c='Active';
        device4.User_Agent__c='';
        listuserdevices.add(device4);
        
        User_Devices__c device5=new User_Devices__c();
        device5.Account__c=oAccount.Id;
        device5.Date_Of_Registration__c=System.today();
        device5.Device_Id__c='DESK001';
        device5.Device_manufacturer__c='';
        device5.Device_Name__c='Desktop1';
        device5.Device_Registration_Date__c=System.today();
        device5.Type__c='Desktop';
        device5.Device_version__c='';
        device5.IP_address__c ='1638399';
        device5.Operating_System_Name__c='';
        device5.Operating_System_Version__c='';
        device5.Status__c='Active';
        device5.User_Agent__c='';
        listuserdevices.add(device5);
        
        list<Account> listOfAccounts=new list<Account>();
        listOfAccounts.add(oAccount);
        if(listuserdevices!= null && listuserdevices.size()>0){
            insert listuserdevices;
        }
        
        
        BatchUserDevicesDeleteonAccount c = new BatchUserDevicesDeleteonAccount();
        Database.executeBatch(c);
        //c.execute(BC, listOfAccounts); 
        
    }
}