objects/Account.object
<CustomObject>
    <fields>
        <fullName>LastInvoiceDate__c</fullName>
        <label>LastInvoiceDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Notification_Country_Code__c</fullName>
        <label>Notification Country Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Type_Last_Digits_and_Expiry_Date__c</fullName>
        <label>Payment Type,Last Digits and Expiry Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retrieve_Email__c</fullName>
        <externalId>true</externalId>
        <label>Retrieve Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/DAZN_Help_Redirect__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>DAZN Help Redirect settings use to redirect the respective page</description>
    <fields>
        <fullName>CountryISOCode__c</fullName>
        <label>CountryISOCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsDefaultCountry__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefaultCountry</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>DAZN Help Redirect</label>
</CustomObject>

objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Retrive_Email__c</fullName>
        <formula>LOWER(Zuora__Account__r.FirstName) &amp;&quot;-&quot;&amp; LOWER(Zuora__Account__r.LastName) &amp; &quot;-&quot; &amp; IF( OR( Zuora__Default_Payment_Method__r.Zuora__BankTransferType__c == &quot;SEPA&quot;,Zuora__Default_Payment_Method__r.Zuora__BankTransferType__c == &quot;IBAN&quot;), RIGHT( Zuora__Default_Payment_Method__r.Zuora__BankTransferAccountNumber__c , 4), RIGHT(Zuora__CreditCard_Number__c, 4))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Retrive Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>R00N40000001kyLcEAI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora__BillToCountry__c</fullName>
        <label>Bill To Address Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__CreditCard_Expiration__c</fullName>
        <formula>IF (   OR( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__Type__c , &quot;CreditCard&quot;) ,   ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__Type__c , &quot;DebitCard&quot;) ),

(IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__CreditCardExpirationMonth__c, &quot;1&quot;) , &quot;01&quot;,  IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__CreditCardExpirationMonth__c, &quot;2&quot;) , &quot;02&quot;, IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__CreditCardExpirationMonth__c, &quot;3&quot;) , &quot;03&quot;, IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__CreditCardExpirationMonth__c, &quot;4&quot;) , &quot;04&quot;, IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__CreditCardExpirationMonth__c, &quot;5&quot;) , &quot;05&quot;, IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__CreditCardExpirationMonth__c, &quot;6&quot;) , &quot;06&quot;, IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__CreditCardExpirationMonth__c, &quot;7&quot;) , &quot;07&quot;, IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__CreditCardExpirationMonth__c, &quot;8&quot;) , &quot;08&quot;, IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__CreditCardExpirationMonth__c, &quot;9&quot;) , &quot;09&quot;, IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__CreditCardExpirationMonth__c, &quot;10&quot;) , &quot;10&quot;, IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__CreditCardExpirationMonth__c, &quot;11&quot;) , &quot;11&quot;, IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__CreditCardExpirationMonth__c, &quot;12&quot;) , &quot;12&quot;, &quot;&quot;))))))))))))

&amp; &quot;/&quot; &amp; Zuora__Default_Payment_Method__r.Zuora__CreditCardExpirationYear__c), &quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Credit Card Expiration</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__CreditCard_Number__c</fullName>
        <formula>Zuora__Default_Payment_Method__r.Zuora__CreditCardMaskNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Credit Card Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__LastInvoiceDate__c</fullName>
        <label>Last Invoiced</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__PaymentMethod_Type__c</fullName>
        <formula>IF (  ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__Type__c, &quot;ACH&quot;), &quot;ACH&quot;,
   IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__Type__c, &quot;BankTransfer&quot;), &quot;Bank Transfer&quot;, 
       IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__Type__c, &quot;Cash&quot;), &quot;Cash&quot;,     
         IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__Type__c, &quot;Check&quot;), &quot;Check&quot;, 
           IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__Type__c, &quot;CreditCard&quot;), &quot;Credit Card&quot;, 
                IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__Type__c, &quot;CreditCardReferenceTransaction&quot;), &quot;Credit Card  Reference Transaction&quot;, 
                    IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__Type__c, &quot;DebitCard&quot;), &quot;Debit Card&quot;, 
                       IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__Type__c, &quot;Other&quot;), &quot;Other&quot;, 
                                IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__Type__c, &quot;PayPal&quot;), &quot;PayPal&quot;, 
                                   IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__Type__c, &quot;WireTransfer&quot;), &quot;Wire Transfer&quot;,  &quot;&quot;
                                     )
                                )
                         )
                     )
                )
         )
    )
  )
))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Method Type</label>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BillingAccountTriggerHandler.cls
/**
* @author Cognizant Technology Solutuions
* @date 1/02/2015
* @description BillingAccountTriggerHandler class for populating the payment related information on Account from Billing Account.
*/
public class BillingAccountTriggerHandler {
    public static void populateBillingAccountInfoOnAccount(list<Zuora__CustomerAccount__c> lstNewBillingAccount, Boolean isInsert){
        Map<ID, Account> oAccount = new Map<ID, Account>();
        Set<Id> setIds = new Set<Id>();
        
        for (Zuora__CustomerAccount__c oBillingAccount : lstNewBillingAccount ) {
            setIds.add(oBillingAccount.Zuora__Account__c);
        }
        
        oAccount = new Map<Id, Account>([
            SELECT Id, Notification_Country_Code__c, Payment_Type_Last_Digits_and_Expiry_Date__c, Retrieve_Email__c, Type, LastInvoiceDate__c
            FROM Account WHERE ID IN :setIds
        ]);
        updateAccountRetrieveEmail(lstNewBillingAccount, oAccount, isInsert); // for PD-10958 - Cog 1.5
        updateAccountCountry(lstNewBillingAccount, oAccount, setIds);
        for (Zuora__CustomerAccount__c oCustAccount: lstNewBillingAccount) {
            if (oCustAccount.Zuora__PaymentMethod_Type__c != null) {
                if (oAccount.containsKey(oCustAccount.Zuora__Account__c)) {
                    if (!string.isBlank(oCustAccount.Zuora__CreditCard_Number__c))
                        oAccount.get(oCustAccount.Zuora__Account__c).Payment_Type_Last_Digits_and_Expiry_Date__c = oCustAccount.Zuora__PaymentMethod_Type__c +' '+oCustAccount.Zuora__CreditCard_Number__c.substring(oCustAccount.Zuora__CreditCard_Number__c.length()-4,oCustAccount.Zuora__CreditCard_Number__c.length())+' '+oCustAccount.Zuora__CreditCard_Expiration__c;
                    else
                        oAccount.get(oCustAccount.Zuora__Account__c).Payment_Type_Last_Digits_and_Expiry_Date__c = oCustAccount.Zuora__PaymentMethod_Type__c ;
                }
            }
            //added as part of PD-13731
            if (oAccount.containsKey(oCustAccount.Zuora__Account__c)) {
                oAccount.get(oCustAccount.Zuora__Account__c).LastInvoiceDate__c = oCustAccount.Zuora__LastInvoiceDate__c;
            }
        }
        
        try {
            if(oAccount.values() != null) {
                update oAccount.values();
            }
        }
        catch(Exception ex) {
            ExceptionLoggerHelper.createExceptionLog(CommunityHelper.getCurrentUser().Id, 'BillingAccountTriggerHandler', 'populateBillingAccountInfoOnAccount', ex.getMessage(), ex.getTypeName(), ex.getStackTraceString());
        }
    }

    // For PD-10958: - Cog 1.5
    // Assumed that the method will be used only when Zuora__CustomerAccount__c record exists because Zuora__CustomerAccount__c.Retrive_Email__c is a formula
    public static void updateAccountRetrieveEmail(List<Zuora__CustomerAccount__c> lstNewBillingAccount, Map<Id, Account> oAccount, Boolean isInsert) {
        List<Account> accountsForUpdate = new List<Account>();
        Account accountForUpdate;
        for (Zuora__CustomerAccount__c item : lstNewBillingAccount) {
            if (oAccount.containsKey(item.Zuora__Account__c)) {
                accountForUpdate = oAccount.get(item.Zuora__Account__c);
                // For PD-12084: - Cog 1.6.2 (Retrieve Email should be populated via BillingAccounttriger for after Insert and only for customers who are not docomo)
                Boolean isUpdateNeeded = /*isInsert &&*/ accountForUpdate.Type != 'Docomo' && accountForUpdate.Retrieve_Email__c != item.Retrive_Email__c;
                if (isUpdateNeeded) {
                    accountForUpdate.Retrieve_Email__c = item.Retrive_Email__c;
                    accountsForUpdate.add(accountForUpdate);
                }
            }
        }
        update accountsForUpdate;
    }

    public static void updateAccountCountry(list<Zuora__CustomerAccount__c> lstNewBillingAccount, Map<Id, Account> oAccount, Set<Id> setIds) {
        Set<String> accountsId = new Set<String>();
        Set<String> billingsId = new Set<String>();
        List<DAZN_Help_Redirect__c> countryCodes = [SELECT Country__c, CountryISOCode__c, IsDefaultCountry__c, Language__c FROM DAZN_Help_Redirect__c LIMIT 10000];
        Map<String,DAZN_Help_Redirect__c> helpRedirectByCountry = new Map<String,DAZN_Help_Redirect__c>();

        for (DAZN_Help_Redirect__c item :countryCodes) {
            helpRedirectByCountry.put(item.Country__c, item);
        }


        if (!helpRedirectByCountry.isEmpty()) {
            for (Zuora__CustomerAccount__c item : lstNewBillingAccount) {
                if (oAccount.containsKey(item.Zuora__Account__c) 
                        && !String.isBlank(oAccount.get(item.Zuora__Account__c).Notification_Country_Code__c) 
                        && helpRedirectByCountry.containsKey(item.Zuora__BillToCountry__c)) {

                    if (helpRedirectByCountry.get(item.Zuora__BillToCountry__c).CountryISOCode__c != oAccount.get(item.Zuora__Account__c).Notification_Country_Code__c) {
                        billingsId.add(item.Id);
                        accountsId.add(oAccount.get(item.Zuora__Account__c).Id);
                    }
                }
            }
        }
        
        if (!accountsId.isEmpty()) {
            updateUser(helpRedirectByCountry, accountsId, billingsId);
        }
    }

    public static void updateUser(Map<String,DAZN_Help_Redirect__c> helpRedirectByCountry, Set<String> accountsId, Set<String> billingsId) {
        List<User> users = [SELECT LocaleSidKey, AccountId, CountryCode, Country FROM User WHERE AccountId IN :accountsId];
        
        List<DAZN_Help_Redirect__c> countryCodes = [SELECT Country__c, CountryISOCode__c, IsDefaultCountry__c, Language__c FROM DAZN_Help_Redirect__c LIMIT 10000];
 
        Map<Id, Account> oAccount;
        Map<Id, Zuora__CustomerAccount__c> billingAccountsByAccountId = new Map<Id, Zuora__CustomerAccount__c>();
        
        oAccount = new Map<Id, Account>([
            SELECT id, Notification_Country_Code__c, Payment_Type_Last_Digits_and_Expiry_Date__c
            FROM Account WHERE Id IN :accountsId
        ]);
        for (Zuora__CustomerAccount__c item : [SELECT id, Zuora__Account__c, Zuora__BillToCountry__c FROM Zuora__CustomerAccount__c WHERE Id IN :billingsId]) {
            billingAccountsByAccountId.put(item.Zuora__Account__c, item);
        }
        if (!users.isEmpty()) {
            for (User item :users) {
                if (oAccount.containsKey(item.AccountId)) {
                    String newCountryForUser = billingAccountsByAccountId.get(item.AccountId).Zuora__BillToCountry__c;
                    String newISOCountryCodeForUser = helpRedirectByCountry.get(newCountryForUser).CountryISOCode__c;
                    String newLocale = createLocaleCode(newISOCountryCodeForUser);

                    if (!String.isBlank(newLocale)) {
                        item.LocaleSidKey = newLocale;
                    } 
                    
                    item.CountryCode = newISOCountryCodeForUser;
                    item.Country = billingAccountsByAccountId.get(item.AccountId).Zuora__BillToCountry__c;
                }
            }
            update users;
        }
    }

    public static String createLocaleCode(String country) {
        Schema.PicklistEntry[] locales = Schema.SObjectType.User.fields.LocaleSidKey.PicklistValues;
        Boolean isContains = false;
        List<String> localeForCountryList = new List<String>();
        for (PicklistEntry locale : locales) {
            String localeForCountry = locale.getValue().substringAfter('_');
            if (localeForCountry.contains(country)) {
                localeForCountryList.add(locale.getValue());
            }
        }
        return localeForCountryList[0];
    }

}