objects/Account.object
<CustomObject>
    <fields>
        <fullName>Notification_Country_Code__c</fullName>
        <label>Notification Country Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/MISL_Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used to store the settings related to MISL Integarion.</description>
    <fields>
        <fullName>Enabled_Country_Codes__c</fullName>
        <label>Enabled Country Codes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Timeout__c</fullName>
        <defaultValue>3000</defaultValue>
        <label>Timeout</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MISL Configuration</label>
</CustomObject>

objects/TriggerSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Trigger Setting to Turn on and Off</description>
    <fields>
        <fullName>Disable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disable</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Setting</label>
</CustomObject>

objects/User_Devices__c.object
<CustomObject>
    <description>This object is used to store user devices used to sign-in in application.</description>
    <label>User Devices</label>
    <nameField>
        <displayFormat>DN-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Devices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UserDeviceRelListControllerTest.cls
/* This test class will cover the code coverage for UserDeviceRelListController */
@isTest
public class UserDeviceRelListControllerTest {

    @isTest 
    static void testGetUserDevicesFromMISL() {
        TriggerSetting__c triggerSet1 = new TriggerSetting__c(name ='BillingAccountTrigger', Disable__c = false);
        insert triggerSet1;
        TriggerSetting__c triggerSet2 = new TriggerSetting__c(name ='UpdateAccountTrigger', Disable__c = false);
        insert triggerSet2;
        TriggerSetting__c triggerSet3 = new TriggerSetting__c(name ='SubscriptionTrigger', Disable__c = false);
        insert triggerSet3;
        TriggerSetting__c triggerSet4 = new TriggerSetting__c(name ='UserDeviceTrigger', Disable__c = false);
        insert triggerSet4;
        
        List<MISL_Configuration__c> config = new List<MISL_Configuration__c>();
        config.add(new MISL_Configuration__c(
            Name = 'MISL_GetUserDevices',
            Value__c = 'UserDevices',
            Enabled_Country_Codes__c = 'DE',
            Timeout__c = 3000
        ));
        config.add(new MISL_Configuration__c(
            Name = 'MISL_Username',
            Value__c = 't1'
        ));
        config.add(new MISL_Configuration__c(
            Name = 'MISL_Password',
            Value__c = EncodingUtil.base64Encode(Blob.valueOf('t2'))
        ));
        insert config;
        
        Account oAccount = SetUpTestData.createPersonAccount('DE', 'EN_GB', 'TestFirstName', 'TestLastName','test@test.com','Free Trial');
        User oUser = SetUpTestData.createCommunityUser(oAccount.Id, 'testemail@email.com', 'testusername@email.com', 'tstals','Europe/London','ISO-8859-1','en_US','en_US','TestFName','TestLName',true);
        oAccount.Notification_Country_Code__c = 'DE';
        update oAccount;

        PageReference userDeviceRelListPage = Page.UserDeviceRelList;
        Test.setCurrentPage(userDeviceRelListPage);
        
        Test.startTest();
            UserDeviceRelListController controller = new UserDeviceRelListController(new ApexPages.StandardController(oAccount));
            System.assertEquals(true, controller.userDevices.isEmpty());
            Test.setMock(HttpCalloutMock.class, new MockUserDevicesResponse());
            UserDeviceRelListController controller2 = new UserDeviceRelListController(new ApexPages.StandardController(oAccount));
            System.assertEquals(true, !controller2.userDevices.isEmpty());
        Test.stopTest();
    }
    
    @isTest 
    static void testGetUserDevicesFromSF() {
        TriggerSetting__c triggerSet1 = new TriggerSetting__c(name ='BillingAccountTrigger', Disable__c = false);
        insert triggerSet1;
        TriggerSetting__c triggerSet2 = new TriggerSetting__c(name ='UpdateAccountTrigger', Disable__c = false);
        insert triggerSet2;
        TriggerSetting__c triggerSet3 = new TriggerSetting__c(name ='SubscriptionTrigger', Disable__c = false);
        insert triggerSet3;
        TriggerSetting__c triggerSet4 = new TriggerSetting__c(name ='UserDeviceTrigger', Disable__c = false);
        insert triggerSet4;
        
        List<MISL_Configuration__c> config = new List<MISL_Configuration__c>();
        config.add(new MISL_Configuration__c(
            Name = 'MISL_Username',
            Value__c = 't1'
        ));
        config.add(new MISL_Configuration__c(
            Name = 'MISL_Password',
            Value__c = EncodingUtil.base64Encode(Blob.valueOf('t2'))
        ));
        insert config;
        
        Account oAccount = SetUpTestData.createPersonAccount('DE', 'EN_GB', 'TestFirstName', 'TestLastName','test@test.com','Free Trial');
        User oUser = SetUpTestData.createCommunityUser(oAccount.Id, 'testemail@email.com', 'testusername@email.com', 'tstals','Europe/London','ISO-8859-1','en_US','en_US','TestFName','TestLName',true);
        oAccount.Notification_Country_Code__c = 'DE';
        update oAccount;
        User_Devices__c singleDev = SetUpTestData.createUserDevice(oAccount.Id, 'Test User Device', System.today(), 'Desktop' , 'Active');

        PageReference userDeviceRelListPage = Page.UserDeviceRelList;
        Test.setCurrentPage(userDeviceRelListPage);
        
        Test.startTest();
            UserDeviceRelListController controller = new UserDeviceRelListController(new ApexPages.StandardController(oAccount));
            System.assertEquals(true, !controller.userDevices.isEmpty());
        Test.stopTest();
    }
    
    public class MockUserDevicesResponse implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody(
                '{' +
                    '"Devices": [' +
                        '{' +
                            '"Id": "deviceId1",' +
                            '"RegistrationDate": "2017-03-10 10:42:43.379Z",' +
                            '"Type": "Tablet"' +
                        '},' +
                        '{' +
                            '"Id": "deviceId2",' +
                            '"RegistrationDate": "2017-03-11 10:44:43.379Z",' +
                            '"Type": "TV"' +
                        '}' +
                    ']' +
                '}'
            );
            res.setStatusCode(200);
            return res;
        }
    }

}