objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partial</fullName>
                    <default>true</default>
                    <label>Partial</label>
                </value>
                <value>
                    <fullName>Free Trial</fullName>
                </value>
                <value>
                    <fullName>Active Paid</fullName>
                </value>
                <value>
                    <fullName>Active Grace</fullName>
                </value>
                <value>
                    <fullName>Frozen</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Expired Marketing</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Apple</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DAZN_Id__c</fullName>
        <externalId>true</externalId>
        <label>DAZN Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Partner_ID__c</fullName>
        <externalId>true</externalId>
        <label>Partner ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Partner_Registration_Status__c</fullName>
        <label>Partner Registration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secondary_Email__c</fullName>
        <label>Secondary Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/DAZNUserFeed__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>User_Feed</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Frozen</fullName>
                </value>
                <value>
                    <fullName>Active Paid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Alias__c</fullName>
        <label>Alias</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BillingCountryCode__c</fullName>
        <label>BillingCountryCode</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CommunityNickname__c</fullName>
        <description>Nickname needed for salesforce</description>
        <label>CommunityNickname</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DAZN_Id__c</fullName>
        <description>Unique Identifier created by Massive to identify the user</description>
        <label>DAZN Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmailEncodingKey__c</fullName>
        <label>EmailEncodingKey</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>UTF-8</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_Preferences__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Marketing preferences as entered by user during sign up, for Docomo users this is always set to TRUE.</description>
        <label>Email Preferences</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>The email of the customer. For partner users like Docomo, this email will be &lt;partner Id&gt;@dazn.com.
For default DAZN subscribers, it will be the email they have used to sign up.</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the user if the user has completed sign up to DAZN                                                                                                                                                                                                                                                                                                                                        , empty otherwise.</description>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LanguageLocaleKey__c</fullName>
        <label>LanguageLocaleKey</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ja</fullName>
                </value>
                <value>
                    <fullName>en_GB</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocaleSidKey__c</fullName>
        <label>LocaleSidKey</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ja_JP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Num_Retries__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Num Retries</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Partner_Id__c</fullName>
        <externalId>true</externalId>
        <label>Partner Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Registration_status__c</fullName>
        <label>Partner Registration status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secondary_Email__c</fullName>
        <description>Email to be used for notifying the customer about information related to their DAZN account. For default DAZN subscribers, this will be the same as Email field. 
For Docomo users, this will be the email they filled in during sign up to DAZN.</description>
        <label>Secondary Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Subscription_Start_Date__c</fullName>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TimeZoneSidKey__c</fullName>
        <label>TimeZoneSidKey</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Asia/Tokyo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Type__c</fullName>
        <label>User Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Docomo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ViewerId__c</fullName>
        <label>ViewerId</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>DAZN User Feed</label>
    <nameField>
        <displayFormat>DFD-{0000}</displayFormat>
        <label>User feed Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DAZN User Feed</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/DocomoConfiguration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Docomo Configuration</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ViewerId__c</fullName>
        <externalId>true</externalId>
        <label>ViewerId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/DFDUserFeedHandlerTest.cls
/**
* @author Cognizant Technology Solutuions
* @date 11/28/2016
* @description Test class to cover DFDUserFeedHandler functionality.
*/
@istest
public class DFDUserFeedHandlerTest {
    @testSetup /*  calling CreateTestDataforUnitTest */  
    public static void getCommunityUsersTestData(){
        CreateTestDataforUnitTest.triggerSettings();
        //CreateZuoraDataforUnitTest.createZuoraDeatils();
        CreateTestDataforUnitTest.createTestcustomsetting();
        CreateTestDataforUnitTest.createTestUserDevices();
    }
    //test method to create account and user 
    public static testmethod void toCreateAccountAndUserwithAllValues(){
        List<Profile> profile=[select Id,Name from profile where Name='External User' limit 1];
        system.assert(profile.size()>0);
        List<User> oUser = [Select Id, Name, UserName,Alias,Country,profileId,LanguageLocaleKey from User where profileId=:profile[0].id and IsActive=True limit 1];
        system.assertNotEquals(null, oUser);
        CreateTestDataforUnitTest.triggerSettings();
        DocomoConfiguration__c custmstng = new DocomoConfiguration__c();
        custmstng.Name = 'Default Password';
        custmstng.Value__c = 'cGFzNzg5dzByZA==';
        insert custmstng;
        System.RunAs(oUser[0]){
            DAZNUserFeed__c userdetails = CreateTestDataforUnitTest.createTestDFDUserFeedRecords();
            insert userdetails;
            system.assertNotEquals(null, userdetails);
        }
        
        
    }
    //test method to create user with registration status is complete 
    static testmethod void toCreateAccountAndUserwithOutAllValues(){
        List<Profile> profile=[select Id,Name from profile where Name='External User' limit 1];
        system.assert(profile.size()>0);
        List<User> oUser = [Select Id, Name, UserName,Alias,Country,profileId,LanguageLocaleKey from User where profileId=:profile[0].id and IsActive=True limit 1];
        system.assertNotEquals(null, oUser);
        DocomoConfiguration__c custmstng = new DocomoConfiguration__c();
        custmstng.Value__c = 'cGFzNzg5dzByZA==';
        custmstng.Name = 'Default Password';
        insert  custmstng;
        System.RunAs(oUser[0]){
            DAZNUserFeed__c userdetails = CreateTestDataforUnitTest.createTestDFDUserFeedRecords();
            userdetails.First_Name__c = '';
            userdetails.Last_Name__c='';
            userdetails.Secondary_Email__c='';
            userdetails.Alias__c = '';
            userdetails.Account_Status__c='';
            insert userdetails;
            system.assertNotEquals(null, userdetails);
        }
        
    }
    //when registration status is incomplete
    static testmethod void totestNumberOfRetries(){
        CreateTestDataforUnitTest.triggerSettings();
        List<Profile> profile=[select Id,Name from profile where Name='External User' limit 1];
        system.assert(profile.size()>0);
        List<User> oUser = [Select Id, Name, UserName,Alias,Country,profileId,LanguageLocaleKey from User where profileId=:profile[0].id and IsActive=True limit 1];
        system.assertNotEquals(null, oUser);
        DocomoConfiguration__c custmstng = new DocomoConfiguration__c();
        custmstng.Name = 'Default Password';
        custmstng.Value__c = 'cGFzNzg5dzByZA==';
        insert custmstng;
        System.RunAs(oUser[0]){
            DAZNUserFeed__c userdetails = CreateTestDataforUnitTest.createTestDFDUserFeedRecords();
            userdetails.BillingCountryCode__c='';
            userdetails.LanguageLocaleKey__c='';
            userdetails.TimeZoneSidKey__c = '';
            userdetails.EmailEncodingKey__c = '';
            userdetails.LocaleSidKey__c = '';
            userdetails.Email__c = '';
            insert userdetails;
            system.assertNotEquals(null, userdetails);
        }
        
    }
    static testmethod void toTestFailedStatus(){
        CreateTestDataforUnitTest.triggerSettings();
        List<Profile> profile=[select Id,Name from profile where Name='External User' limit 1];
        system.assert(profile.size()>0);
        List<User> oUser = [Select Id, Name, UserName,Alias,Country,profileId,LanguageLocaleKey from User where profileId=:profile[0].id and IsActive=True limit 1];
        system.assertNotEquals(null, oUser);
        System.RunAs(oUser[0]){
            DAZNUserFeed__c userdetails = CreateTestDataforUnitTest.createTestDFDUserFeedRecords();
            userdetails.BillingCountryCode__c='';
            userdetails.LanguageLocaleKey__c='';
            userdetails.TimeZoneSidKey__c = '';
            userdetails.Num_Retries__c = 5;
            insert userdetails;
            system.assertNotEquals(null, userdetails);
        }
        
    }
    //when account and user insertion fails
    static testmethod void toTestAccountCreationFailure(){
        CreateTestDataforUnitTest.triggerSettings();
        List<Profile> profile=[select Id,Name from profile where Name='External User' limit 1];
        system.assert(profile.size()>0);
        List<User> oUser = [Select Id, Name, UserName,Alias,Country,profileId,LanguageLocaleKey from User where profileId=:profile[0].id and IsActive=True limit 1];
        system.assertNotEquals(null, oUser);
        List<DAZNUserFeed__c> lstDAZNFeedLst = new List<DAZNUserFeed__c>();
        System.RunAs(oUser[0]){
            DAZNUserFeed__c userdetails = CreateTestDataforUnitTest.createTestDFDUserFeedRecords();
            userdetails.LanguageLocaleKey__c='';
            userdetails.TimeZoneSidKey__c = '';
            userdetails.Num_Retries__c = 4;
            lstDAZNFeedLst.add(userdetails);
            DAZNUserFeed__c userdetails1 = CreateTestDataforUnitTest.createTestDFDUserFeedRecords();
            userdetails1.DAZN_Id__c = '2223e2';
            userdetails1.Partner_Id__c = '332e32';
            userdetails1.ViewerId__c = '232232e23';
            userdetails1.Num_Retries__c = 5;
            userdetails1.Last_Name__c = '';
            lstDAZNFeedLst.add(userdetails1);
            Insert lstDAZNFeedLst ;
            DFDUserFeedHandler.exceptionDaznUserFeeds(userdetails,'Exception' );
       }
        
    }
//method to test when num of retries is greater than 5
 public static testmethod void toTestBulkRecords(){
        CreateTestDataforUnitTest.triggerSettings();
        List<Profile> profile=[select Id,Name from profile where Name='External User' limit 1];
        system.assert(profile.size()>0);
        List<User> oUser = [Select Id, Name, UserName,Alias,Country,profileId,LanguageLocaleKey from User where profileId=:profile[0].id and IsActive=True limit 1];
        system.assertNotEquals(null, oUser);
        List<DAZNUserFeed__c> lstDAZNFeedLst = new List<DAZNUserFeed__c>();
        System.RunAs(oUser[0]){
            lstDAZNFeedLst = CreateTestDataforUnitTest.createTestDFDUserFeedRecordsBulk(50);
            Insert lstDAZNFeedLst;
        }
    }
    static testmethod void toTestFailedUserStatus(){
        //CreateTestDataforUnitTest.triggerSettings();
        List<Profile> profile=[select Id,Name from profile where Name='External User' limit 1];
        system.assert(profile.size()>0);
        List<User> oUser = [Select Id, Name, UserName,Alias,Country,profileId,LanguageLocaleKey from User where profileId=:profile[0].id and IsActive=True limit 1];
        system.assertNotEquals(null, oUser);
        List<DAZNUserFeed__c> lstDAZN = new List<DAZNUserFeed__c>(); 
        System.RunAs(oUser[0]){
            DAZNUserFeed__c userdetails = CreateTestDataforUnitTest.createTestDFDUserFeedRecords();
            DAZNUserFeed__c userdetails1 = CreateTestDataforUnitTest.createTestDFDUserFeedRecords();
            userdetails.BillingCountryCode__c='';
            userdetails.LanguageLocaleKey__c='';
            userdetails.TimeZoneSidKey__c = '';
            userdetails.TimeZoneSidKey__c = '';
           // userdetails.DAZN_Id__c = '';
            userdetails1.BillingCountryCode__c='';
            userdetails1.Num_Retries__c = 5;
           // userdetails1.ViewerId__c = '';
            lstDAZN.add(userdetails);
            lstDAZN.add(userdetails1);
            insert lstDAZN;
            system.assertNotEquals(null, userdetails);
        }
        
    }
    
    
   /*Added as part of PD-11515*/
    /* Method to test Blocked accounts*/
   static testmethod void toTestBlockedAccounts(){
        //CreateTestDataforUnitTest.triggerSettings();
        List<Profile> profile=[select Id,Name from profile where Name='External User' limit 1];
        system.assert(profile.size()>0);
        List<User> oUser = [Select Id, Name, UserName,Alias,Country,profileId,LanguageLocaleKey from User where profileId=:profile[0].id and IsActive=True limit 1];
        system.assertNotEquals(null, oUser);
        List<DAZNUserFeed__c> lstDAZN = new List<DAZNUserFeed__c>(); 
       test.startTest();
            DAZNUserFeed__c userdetails = CreateTestDataforUnitTest.createTestDFDUserFeedRecords();
        insert userdetails;
            
		DAZNUserFeed__c DAZNuser = [select id,AccountId__c from DAZNUserFeed__c where id =: userdetails.id];
        account acc = [select id from account where id =: DAZNuser.AccountId__c];
        acc.Account_Status__c = 'Blocked';
        update acc;
        DAZNUserFeed__c newUserdetails=new  DAZNUserFeed__c();
            newUserdetails.Email__c='test2344@test.com';
            newUserdetails.Email_Preferences__c=true;
            newUserdetails.Secondary_Email__c='test22222@test.com';
            newUserdetails.Account_Status__c='Active Paid';
            newUserdetails.Partner_Id__c='asdghh243';
            newUserdetails.DAZN_Id__c = '2323223';
            newUserdetails.ViewerId__c = '222121223';
        insert newUserdetails;
        test.stopTest();
    } //End of PD-11515
    
    
    /*Method to test frozen account*/
     static testmethod void toTestFrozenAccounts(){
        //CreateTestDataforUnitTest.triggerSettings();
        List<Profile> profile=[select Id,Name from profile where Name='External User' limit 1];
        system.assert(profile.size()>0);
        List<User> oUser = [Select Id, Name, UserName,Alias,Country,profileId,LanguageLocaleKey from User where profileId=:profile[0].id and IsActive=True limit 1];
        system.assertNotEquals(null, oUser);
        List<DAZNUserFeed__c> lstDAZN = new List<DAZNUserFeed__c>(); 
        test.startTest();
        DAZNUserFeed__c userdetails = CreateTestDataforUnitTest.createTestDFDUserFeedRecords();
        insert userdetails;
        DAZNUserFeed__c DAZNuser = [select id,AccountId__c from DAZNUserFeed__c where id =: userdetails.id];
        account acc = [select id from account where id =: DAZNuser.AccountId__c];
        DAZNUserFeed__c newUserdetails=new  DAZNUserFeed__c();
        newUserdetails.Email__c='test2344@test.com';
            newUserdetails.Email_Preferences__c = true;
            newUserdetails.Secondary_Email__c='test22222@test.com';
            newUserdetails.Account_Status__c='Frozen';
            newUserdetails.Partner_Id__c='asdghh243';
            newUserdetails.DAZN_Id__c = '2323223';
            newUserdetails.ViewerId__c = '222121223';
            newUserdetails.First_Name__c = 'TestFirstName';
            newUserdetails.Last_Name__c = 'TestLastName';
            newUserdetails.BillingCountryCode__c = 'JP';
            newUserdetails.LanguageLocaleKey__c = 'ja';
            newUserdetails.Partner_Registration_status__c = 'incomplete';
            newUserdetails.User_Type__c = 'Docomo';
            newUserdetails.Subscription_Start_Date__c = System.today() + 3;
            newUserdetails.CommunityNickname__c =  '1test1Te';
            newUserdetails.TimeZoneSidKey__c = 'Asia/Tokyo';
            newUserdetails.LocaleSidKey__c = 'ja_JP';
            newUserdetails.EmailEncodingKey__c = 'UTF-8';
        insert newUserdetails;
        test.stopTest();
    } 
    
}