objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partial</fullName>
                    <default>true</default>
                    <label>Partial</label>
                </value>
                <value>
                    <fullName>Free Trial</fullName>
                </value>
                <value>
                    <fullName>Active Paid</fullName>
                </value>
                <value>
                    <fullName>Active Grace</fullName>
                </value>
                <value>
                    <fullName>Frozen</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Expired Marketing</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Apple</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>All_Email_Preferences__c</fullName>
        <defaultValue>true</defaultValue>
        <label>All Email Preferences</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsReadyToSyncInZuora__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to identify record needs to be sync in Zuora</description>
        <label>IsReadyToSyncInZuora</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Double_OptIn__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to identify user is double opt-in for marketing emails.</description>
        <label>Is Double OptIn</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notification_Country_Code__c</fullName>
        <label>Notification Country Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification_Language_Code__c</fullName>
        <label>Notification Language Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_ID__c</fullName>
        <externalId>true</externalId>
        <label>Partner ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Secondary_Email__c</fullName>
        <label>Secondary Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/DAZN_Country_Currency_ISO_Code__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>CurrencySymbol__c</fullName>
        <label>CurrencySymbol</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>DAZN Country Currency ISO Code</label>
</CustomObject>

objects/DAZNBetaConfiguration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This Custom setting identifies if the country is in the beta phase</description>
    <fields>
        <fullName>CountryCode__c</fullName>
        <label>CountryCode</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>DAZN Beta Configuration</label>
</CustomObject>

objects/DAZNConfiguration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is a configurable custom setting for Forgot Password link</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>Field to store configuration value for specific key</description>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>DAZN Configuration</label>
</CustomObject>

objects/DAZNLanguageSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Use this custom setting to configure languages on myaccount</description>
    <fields>
        <fullName>LanguageToDisplay__c</fullName>
        <label>LanguageToDisplay</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DAZNLanguageSetting</label>
</CustomObject>

objects/DAZNUserFeed__c.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Frozen</fullName>
                </value>
                <value>
                    <fullName>Active Paid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Alias__c</fullName>
        <label>Alias</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BillingCountryCode__c</fullName>
        <label>BillingCountryCode</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Preferences__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Marketing preferences as entered by user during sign up, for Docomo users this is always set to TRUE.</description>
        <label>Email Preferences</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>The email of the customer. For partner users like Docomo, this email will be &lt;partner Id&gt;@dazn.com.
For default DAZN subscribers, it will be the email they have used to sign up.</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the user if the user has completed sign up to DAZN                                                                                                                                                                                                                                                                                                                                        , empty otherwise.</description>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LanguageLocaleKey__c</fullName>
        <label>LanguageLocaleKey</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ja</fullName>
                </value>
                <value>
                    <fullName>en_GB</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocaleSidKey__c</fullName>
        <label>LocaleSidKey</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ja_JP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Id__c</fullName>
        <externalId>true</externalId>
        <label>Partner Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Email__c</fullName>
        <description>Email to be used for notifying the customer about information related to their DAZN account. For default DAZN subscribers, this will be the same as Email field. 
For Docomo users, this will be the email they filled in during sign up to DAZN.</description>
        <label>Secondary Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>To be retried</fullName>
                </value>
                <value>
                    <fullName>Successful</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TimeZoneSidKey__c</fullName>
        <label>TimeZoneSidKey</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Asia/Tokyo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DAZN User Feed</label>
    <nameField>
        <displayFormat>DFD-{0000}</displayFormat>
        <label>User feed Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DAZN User Feed</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EmailNotification__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Email notification based on these emais.</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>EmailNotification</label>
</CustomObject>

objects/TriggerSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Trigger Setting to Turn on and Off</description>
    <fields>
        <fullName>Disable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disable</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Setting</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>All_Email_Preferences__c</fullName>
        <defaultValue>true</defaultValue>
        <label>All Email Preferences</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notification_Language_Code__c</fullName>
        <label>Notification Language Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/User_Devices__c.object
<CustomObject>
    <description>This object is used to store user devices used to sign-in in application.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>User Account and Device Relationship field</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>User Devices</relationshipLabel>
        <relationshipName>User_Devices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Of_Registration__c</fullName>
        <description>Device Registration Date</description>
        <label>Date Of Registration</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Device_Name__c</fullName>
        <description>This field is used to store registered device name.</description>
        <label>Device Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Device Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>InActive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Device Type</description>
        <label>Device Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Console</fullName>
                </value>
                <value>
                    <fullName>Desktop</fullName>
                </value>
                <value>
                    <fullName>Laptop</fullName>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                </value>
                <value>
                    <fullName>Tablet</fullName>
                </value>
                <value>
                    <fullName>TV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Devices</label>
    <nameField>
        <displayFormat>DN-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Devices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CreateTestDataforUnitTest.cls
@IsTest
public class CreateTestDataforUnitTest {
    /*Description: This method is used for enabling the triggers on the corresponding objects.*/
    @testSetup
    public static void triggerSettings(){
        List<TriggerSetting__c> triggerSet = new List<TriggerSetting__c>();
        List<string> objSettings = new List<string> {'BillingAccountTrigger','UserTrigger','SubscriptionTrigger','UpdateAccountTrigger','UserDeviceTrigger','ZuoraRefundTrigger'};
            for(string objSet : objSettings){
                TriggerSetting__c trigSet = new TriggerSetting__c(name = objSet, Disable__c = false);
                triggerSet.add(trigSet);
            }       
        insert triggerSet;
    }
    /* Description: This method is used to create community user recode.*/
    @testSetup
    public static void createTestAccounts(){
        User oCSUser = SetUpTestData.createCustomerServiceTeamManagementUser(null, 'testcsagent1@email.com', 'testcsagent1@email.com', 'tstals','Europe/London','ISO-8859-1','en_US','en_US','TestFNameCS','TestLNameCS',true);
        System.RunAs(oCSUser){
            String orgId = UserInfo.getOrganizationId();
            List<Account> accList = new List<Account>();
            for (Integer i = 0;i<7;i++){
                String uniqueName = orgId;
                uniqueName += String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
                uniqueName += Integer.valueOf(math.rint(math.random()*1000000));
                Account oAccount = new Account();
                oAccount.FirstName = 'TestFirstName';
                oAccount.LastName = 'TestLastName'+i;
                oAccount.PersonEmail = 'email'+uniqueName+i+ '@testdomain.org';
                oAccount.Notification_Country_Code__c='DE';
                oAccount.All_Email_Preferences__c = true;
                if(i==0){
                    //Create Frozen Account
                    oAccount.Account_Status__c = 'Frozen';
                } else if(i==1){
                    //Create Active Paid Account
                    oAccount.Account_Status__c = 'Active Paid';
                    oAccount.Is_Double_OptIn__c = true;
                    oAccount.IsReadyToSyncInZuora__c=true;
                } else if(i==2){
                    //Create Free Trial Account
                    oAccount.Account_Status__c = 'Free Trial';
                    oAccount.Is_Double_OptIn__c = true;
                    //oAccount.Notification_Language_Code__c= 'de';
                } else if(i==3){
                    //Create Active Grace Account
                    oAccount.Account_Status__c = 'Active Grace';
                } else if(i==4){
                    //Create Expired Account
                    oAccount.Account_Status__c = 'Expired';
                } else if(i==5){
                    //Create Blocked Account
                    oAccount.Account_Status__c = 'Blocked';
                } else if(i==6){
                    //Create Partial Account
                    oAccount.Account_Status__c = 'Partial';
                } 
                accList.add(oAccount);
                
            } //end of for - Account data preparation
            Database.insert(accList,true);
        }
    }
    @testSetup
    public static void createTestAccountsDocomo(){
        String orgId = UserInfo.getOrganizationId();
        List<Account> accList = new List<Account>();
        for (Integer i = 0;i<7;i++){
            String uniqueName = orgId;
            uniqueName += String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
            uniqueName += Integer.valueOf(math.rint(math.random()*1000000));
            Account oAccount = new Account();
            oAccount.FirstName = 'TestFirstName';
            oAccount.LastName = 'TestLastName'+i;
            oAccount.PersonEmail = 'email'+uniqueName+i+ '@testdomain.org';
            oAccount.Notification_Country_Code__c='DE';
            oAccount.Type = 'Docomo';
            oAccount.Partner_ID__c = '1' + String.valueOf(i);
            oAccount.All_Email_Preferences__c = true;
            if(i==0){
                //Create Frozen Account
                oAccount.Account_Status__c = 'Frozen';
            } else if(i==1){
                //Create Active Paid Account
                oAccount.Account_Status__c = 'Active Paid';
                oAccount.Is_Double_OptIn__c = true;
                oAccount.IsReadyToSyncInZuora__c=true;
            } else if(i==2){
                //Create Free Trial Account
                oAccount.Account_Status__c = 'Free Trial';
                oAccount.Is_Double_OptIn__c = true;
                //oAccount.Notification_Language_Code__c= 'de';
            } else if(i==3){
                //Create Active Grace Account
                oAccount.Account_Status__c = 'Active Grace';
            } else if(i==4){
                //Create Expired Account
                oAccount.Account_Status__c = 'Expired';
            } else if(i==5){
                //Create Blocked Account
                oAccount.Account_Status__c = 'Blocked';
            } else if(i==6){
                //Create Partial Account
                oAccount.Account_Status__c = 'Partial';
            } 
            accList.add(oAccount);
            
        } //end of for - Account data preparation
        Database.insert(accList,true);
        
    }
    
    @testSetup
    public static void createTestAccountsDocomoActiveGra(){
        String orgId = UserInfo.getOrganizationId();
        List<Account> accList = new List<Account>();
        for (Integer i = 0;i<7;i++){
            String uniqueName = orgId;
            uniqueName += String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
            uniqueName += Integer.valueOf(math.rint(math.random()*1000000));
            Account oAccount = new Account();
            oAccount.FirstName = 'TestFirstName';
            oAccount.LastName = 'TestLastName'+i;
            oAccount.PersonEmail = 'email'+uniqueName+i+ '@testdomain.org';
            oAccount.Notification_Country_Code__c='DE';
            oAccount.Type = 'Docomo';
            oAccount.Partner_ID__c = '1' + String.valueOf(i);
            oAccount.All_Email_Preferences__c = true;
            
            oAccount.Account_Status__c = 'Active Grace';
            
            accList.add(oAccount);
            
        } //end of for - Account data preparation
        Database.insert(accList,true);
        
    }
    @testSetup
    public static void createTestCommunityUsers(){
        List<Account> getaccList = [Select Id,Name,PersonContactId, Owner.Name, owner.UserRoleId,PersonEmail from Account];
        List<User> userList = new List<User>();
        //Query Profile for community user 
        List<Profile> listOfProfiles = [SELECT Id, Name from Profile where Name = 'Customer Community User' limit 1];
        if (listOfProfiles[0].Id !=null){
            Integer cnt = 11;
            for(Account acc : getaccList){
                User oUser = new User();
                oUser.email= acc.PersonEmail;
                oUser.UserName= acc.PersonEmail;
                oUser.Alias = 'LiveSp'+cnt;
                if(cnt == 11){
                    oUser.TimeZoneSidKey= 'Asia/Tokyo';
                    oUser.LocaleSidKey= 'ja_JP';
                    oUser.LanguageLocaleKey= 'ja';
                    oUser.Country= 'Japan';
                } else if(cnt == 12){
                    oUser.TimeZoneSidKey= 'Europe/Berlin';
                    oUser.LocaleSidKey= 'de_DE';
                    oUser.LanguageLocaleKey= 'de';
                    oUser.Country= 'Germany';
                } else if(cnt == 13){
                    oUser.TimeZoneSidKey= 'Europe/London';
                    oUser.LocaleSidKey= 'de_AT';
                    oUser.LanguageLocaleKey= 'en_GB';
                    oUser.Country= 'Austria';
                } else if(cnt == 14){
                    oUser.TimeZoneSidKey= 'Europe/Berlin';
                    oUser.LocaleSidKey= 'de_CH';
                    oUser.LanguageLocaleKey= 'en_GB';
                    oUser.Country= 'Switzerland';
                }else if(cnt == 15){
                    oUser.TimeZoneSidKey= 'Europe/Berlin';
                    oUser.LocaleSidKey= 'ja_JP';
                    oUser.LanguageLocaleKey= 'en_GB';
                    oUser.Country= 'India';
                }else if(cnt == 16){
                    oUser.TimeZoneSidKey= 'Europe/London';
                    oUser.LocaleSidKey= 'de_DE';
                    oUser.LanguageLocaleKey= 'en_GB';
                    oUser.Country= 'Germany';
                }else if(cnt==17){
                    oUser.TimeZoneSidKey= 'Europe/London';
                    oUser.LocaleSidKey= 'de_DE';
                    oUser.LanguageLocaleKey= 'en_GB';
                    oUser.Country= 'Germany';
                }
                oUser.EmailEncodingKey= 'ISO-8859-1';
                oUser.FirstName = 'TestFName';
                oUser.LastName = 'TestLName'+cnt;
                oUser.isActive= true;
                oUser.ContactId = acc.PersonContactId;
                oUser.profileid = listOfProfiles[0].Id;
                userList.add(oUser) ; 
                cnt = cnt + 1;
            }//end of for loop 
            Database.insert(userList,true);
        } //end of if - profile id null check
    }
    public static void createTestUserDevices(){
        // User Devices
        List<Account> accList = [ Select Id, Name, PersonEmail,PersonContactId from Account where Account_Status__c IN ('Active Paid','Free Trial','Active Grace') ];
        system.debug('accList' +accList);
        List<User_Devices__c> listofUserDevices = new list<User_Devices__c>();
        Integer devCout = 1 ;
        for(Account accls :accList){
            //User Devices 
            if(devCout==1){
                User_Devices__c oUrDevTablet = new User_Devices__c();
                oUrDevTablet.Account__c = accls.id;
                oUrDevTablet.Device_Name__c = 'DN-0000013345';
                oUrDevTablet.Date_Of_Registration__c = System.today();
                oUrDevTablet.Type__c = 'Tablet';
                oUrDevTablet.Status__c = 'Active';
                listofUserDevices.add(oUrDevTablet);
            } else if(DevCout==2){
                User_Devices__c oUrDevTablet = new User_Devices__c();
                oUrDevTablet.Account__c = accls.id;
                oUrDevTablet.Device_Name__c = 'DN-0000013345';
                oUrDevTablet.Date_Of_Registration__c = System.today();
                oUrDevTablet.Type__c = 'Tablet';
                oUrDevTablet.Status__c = 'Active';
                listofUserDevices.add(oUrDevTablet);
            }   else if(DevCout==3){
                User_Devices__c oUrDevMobile = new User_Devices__c();
                oUrDevMobile.Account__c = accls.id;
                oUrDevMobile.Device_Name__c = 'DN-0000013300';
                oUrDevMobile.Date_Of_Registration__c = System.today();
                oUrDevMobile.Type__c = 'Mobile';
                oUrDevMobile.Status__c = 'Active';
                listofUserDevices.add(oUrDevMobile);
            } else if(DevCout==4){
                User_Devices__c oUrDevDesktop = new User_Devices__c();
                oUrDevDesktop.Account__c = accls.id;
                oUrDevDesktop.Device_Name__c = 'DN-0000013300';
                oUrDevDesktop.Date_Of_Registration__c = System.today();
                oUrDevDesktop.Type__c = 'Desktop';
                oUrDevDesktop.Status__c = 'InActive';
                listofUserDevices.add(oUrDevDesktop);
            }
            DevCout = DevCout + 1;
        }//end Devices for loop            
        // inserting custom setting data for User Devices
        
        try{ 
            system.debug('listofUserDevices '+listofUserDevices.size());
            insert listofUserDevices;
        }catch(Exception e){
            system.debug('error ');
            system.debug('error '+e.getMessage());
        }
        
        system.debug(listofUserDevices);
        
    }
    //Use to create custom settings in all Test Class 
    public static void createTestcustomsetting(){
        // To generate unique name for the email settings
        String orgId = UserInfo.getOrganizationId();
        String uniqueName = orgId;
        uniqueName += String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        uniqueName += Integer.valueOf(math.rint(math.random()*1000000));
        //Use custom settings to create and manage custom data at test class
        list<DAZNConfiguration__c> listofDAZNConfig = new list<DAZNConfiguration__c>();
        
        DAZNConfiguration__c dznConfig = new DAZNConfiguration__c();
        dznConfig.Name = 'LoginPageURL';
        dznConfig.Value__c = '/LoginPageURL';
        listofDAZNConfig.add(dznConfig);
        
        DAZNConfiguration__c oDAZNPasswordurl = new DAZNConfiguration__c();
        oDAZNPasswordurl.Name = 'ForgotPasswordLink';
        oDAZNPasswordurl.Value__c = 'http://stag.dazn.com/account/forgot-password';
        listofDAZNConfig.add(oDAZNPasswordurl);
        
        DAZNConfiguration__c oDAZNHomeUrlBeta = new DAZNConfiguration__c();
        oDAZNHomeUrlBeta.Name = 'HomePageURLBeta';
        oDAZNHomeUrlBeta.Value__c = 'http://livesport-web.massiveinteractive.com';
        listofDAZNConfig.add(oDAZNHomeUrlBeta);
        
        DAZNConfiguration__c oDAZNHomeUrl = new DAZNConfiguration__c();
        oDAZNHomeUrl.Name = 'HomePageURL';
        oDAZNHomeUrl.Value__c = 'http://livesport-web.massiveinteractive.com/';
        listofDAZNConfig.add(oDAZNHomeUrl);
        
        DAZNConfiguration__c oDAZNPasswordBeta = new DAZNConfiguration__c();
        oDAZNPasswordBeta.Name = 'ForgotPasswordLinkBeta';
        oDAZNPasswordBeta.Value__c = 'http://stag.dazn.com/account/forgot-password';
        listofDAZNConfig.add(oDAZNPasswordBeta);
        
        DAZNConfiguration__c oDAZNMyAccountURL = new DAZNConfiguration__c();
        oDAZNMyAccountURL.Name = 'MyAccountURL';
        oDAZNMyAccountURL.Value__c = '/MyAccount';
        listofDAZNConfig.add(oDAZNMyAccountURL);
        
        // Added custom settings for PD-7807 Test class Subscription Cancellation
        DAZNConfiguration__c dznConfigFAQURL = new DAZNConfiguration__c();
        dznConfigFAQURL.Name = 'FAQURL';
        dznConfigFAQURL.Value__c = 'policypage?articleType=FAQ';
        listofDAZNConfig.add(dznConfigFAQURL);
        
        DAZNConfiguration__c dznConfigGetInContactURL = new DAZNConfiguration__c();
        dznConfigGetInContactURL.Name = 'GetInContactURL';
        dznConfigGetInContactURL.Value__c = '/ContactUs';
        listofDAZNConfig.add(dznConfigGetInContactURL);
        
        DAZNConfiguration__c dznConfigChangePaymentMethodURL = new DAZNConfiguration__c();
        dznConfigChangePaymentMethodURL.Name = 'CHANGEPAYMENTMETHODURL';
        dznConfigChangePaymentMethodURL.Value__c = 'ChangePaymentMethod';
        listofDAZNConfig.add(dznConfigChangePaymentMethodURL);
        
        DAZNConfiguration__c dznConfigHelpSectionURL = new DAZNConfiguration__c();
        dznConfigHelpSectionURL.Name = 'HelpSectionURL';
        dznConfigHelpSectionURL.Value__c = '/Help';
        listofDAZNConfig.add(dznConfigHelpSectionURL);
        // end PD-7807 

        /*Start PD-14478*/
        DAZNConfiguration__c dznConfigUserNameConf = new DAZNConfiguration__c();
        dznConfigUserNameConf.Name = 'LS_UserName_Configuration';
        dznConfigUserNameConf.Value__c = 'livesport.dev';
        listofDAZNConfig.add(dznConfigUserNameConf);
        /*End PD-14478*/

        listofDAZNConfig.add(new DAZNConfiguration__c(
            Name = 'ZuoraStandardPauseResumeScheduleUrl',
            Value__c = 'https://workflow.apps.zuora.com/api/v1/workflows/9/run'
        ));
        listofDAZNConfig.add(new DAZNConfiguration__c(
            Name = 'ZuoraCancelPauseBeforeStartURL',
            Value__c = 'https://workflow.apps.zuora.com/api/v1/workflows/151/run'
        ));
        listofDAZNConfig.add(new DAZNConfiguration__c(
            Name = 'ZuoraChangeResumeDatesWhileInPauseURL',
            Value__c = 'https://workflow.apps.zuora.com/api/v1/workflows/150/run'
        ));
        listofDAZNConfig.add(new DAZNConfiguration__c(
            Name = 'ZuoraChangeResumeDatesBeforePauseURL',
            Value__c = 'https://workflow.apps.zuora.com/api/v1/workflows/285/run'
        ));
        listofDAZNConfig.add(new DAZNConfiguration__c(
            Name = 'ZuoraPauseUsername',
            Value__c = 'david.francesconi@dazn.com'
        ));
        listofDAZNConfig.add(new DAZNConfiguration__c(
            Name = 'ZuoraPausePassword',
            Value__c = '58c89e0f46f549eded0a140e8d9a842f'
        ));
        listofDAZNConfig.add(new DAZNConfiguration__c(
            Name = 'AmendPauseURL',
            Value__c = 'https://dev.dazn.com/'
        ));
        
        // inserting custom setting data for DAZNConfiguration
        insert listofDAZNConfig;
        
        // custom setting data for DAZNLanguageSetting
        list<DAZNLanguageSetting__c> lisofDAZNConfLan = new list<DAZNLanguageSetting__c>();
        
        DAZNLanguageSetting__c oDAZNLanguageDE = new DAZNLanguageSetting__c();
        oDAZNLanguageDE.Name = 'Germany';
        oDAZNLanguageDE.LanguageToDisplay__c = 'en_GB,DE';
        lisofDAZNConfLan.add(oDAZNLanguageDE);
        
        DAZNLanguageSetting__c oDAZNLanguageJP = new DAZNLanguageSetting__c();
        oDAZNLanguageJP.Name = 'Japan';
        oDAZNLanguageJP.LanguageToDisplay__c = 'en_GB,ja';
        lisofDAZNConfLan.add(oDAZNLanguageJP);
        insert lisofDAZNConfLan;
        
        // End of Use custom settings to create and manage custom data at test class 
        
        
        //Custom Settings for sending email to the admin ()
        EmailNotification__c emailCustomSettings = new EmailNotification__c();
        emailCustomSettings.Name = 'Ad'+orgId;
        emailCustomSettings.Email__c = 'Ad'+uniqueName+'@testdomain.org';
        insert emailCustomSettings;
        //End 
        
        
        //Custom Settings for beta country settings
        DAZNBetaConfiguration__c betaSettings = new DAZNBetaConfiguration__c();
        betaSettings.Name = 'Japan';
        betaSettings.Country__c = 'Japan';
        betaSettings.CountryCode__c ='JP';
        insert betaSettings;
        
        DAZNBetaConfiguration__c betaSettingsIndia = new DAZNBetaConfiguration__c();
        betaSettingsIndia.Name = 'India';
        betaSettingsIndia.Country__c = 'India';
        betaSettingsIndia.CountryCode__c ='IN';
        insert betaSettingsIndia;
        //End
        
        //Custom setting for getting currency symbol 
        DAZN_Country_Currency_ISO_Code__c currencysymbolCAD = new DAZN_Country_Currency_ISO_Code__c();
        currencysymbolCAD.Name = 'CAD'; 
        currencysymbolCAD.CurrencySymbol__c = '$';
        insert currencysymbolCAD;
        
        DAZN_Country_Currency_ISO_Code__c currencysymbolCHF = new DAZN_Country_Currency_ISO_Code__c();
        currencysymbolCHF.Name = 'CHF'; 
        currencysymbolCHF.CurrencySymbol__c = 'CHF';
        insert currencysymbolCHF;
        
        DAZN_Country_Currency_ISO_Code__c currencysymbolCNY = new DAZN_Country_Currency_ISO_Code__c();
        currencysymbolCNY.Name = 'CNY'; 
        currencysymbolCNY.CurrencySymbol__c = '元';
        insert currencysymbolCNY;
        
        DAZN_Country_Currency_ISO_Code__c currencysymbolEUR = new DAZN_Country_Currency_ISO_Code__c();
        currencysymbolEUR.Name = 'EUR'; 
        currencysymbolEUR.CurrencySymbol__c = '€';
        insert currencysymbolEUR;
        
        DAZN_Country_Currency_ISO_Code__c currencysymbolGBP = new DAZN_Country_Currency_ISO_Code__c();
        currencysymbolGBP.Name = 'GBP'; 
        currencysymbolGBP.CurrencySymbol__c = '£';
        insert currencysymbolGBP;
        
        DAZN_Country_Currency_ISO_Code__c currencysymbolJPY = new DAZN_Country_Currency_ISO_Code__c();
        currencysymbolJPY.Name = 'JPY'; 
        currencysymbolJPY.CurrencySymbol__c = '¥';
        insert currencysymbolJPY;
        
        DAZN_Country_Currency_ISO_Code__c currencysymbolUSD = new DAZN_Country_Currency_ISO_Code__c();
        currencysymbolUSD.Name = 'USD'; 
        currencysymbolUSD.CurrencySymbol__c = '$';
        insert currencysymbolUSD;
        
        //End
        
        
    }
    @testSetup
    /*This method is used to create Guest user as per PD-7938*/
    public static  void CreateGuestUser(){
        String orgId = UserInfo.getOrganizationId();
        String uniqueName = orgId;
        uniqueName += String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        uniqueName += Integer.valueOf(math.rint(math.random()*1000000));
        List<Profile> oProfile = [SELECT Id, Name from Profile where Name = 'DAZN Profile' limit 1];
        List<User> lstUser =new List<User>(); 
        User gUser = new User();
        gUser.email= 'TestMember'+uniqueName + '@test' +'.com';
        gUser.UserName=  'TestMember' + uniqueName+'@test'+ '.org';
        gUser.Alias = 'Member';
        gUser.TimeZoneSidKey= 'Asia/Tokyo';
        gUser.EmailEncodingKey= 'ISO-8859-1';
        gUser.LocaleSidKey= 'ja_JP';
        gUser.LanguageLocaleKey= 'en_GB';
        gUser.FirstName = 'TestFName';
        gUser.LastName = 'Member'+uniqueName;
        gUser.isActive= true;
        gUser.profileid = oProfile[0].Id;
        lstUser.add(gUser);
        Database.insert(lstUser,true);   
    }//end of PD-7938
    /* Description: This method is used to create community user recode.*/
    
    public static DAZNUserFeed__c createTestDFDUserFeedRecords(){
        DAZNUserFeed__c userdetails=new  DAZNUserFeed__c();
        userdetails.First_Name__c='firsttest';
        userdetails.Last_Name__c='lasttest';
        userdetails.Email__c='test2344@test.com';
        userdetails.BillingCountryCode__c='JP';
        userdetails.LanguageLocaleKey__c='ja';
        userdetails.Email_Preferences__c=true;
        userdetails.Secondary_Email__c='test222@test.com';
        userdetails.Alias__c = 'tt23';
        userdetails.TimeZoneSidKey__c = 'Asia/Tokyo';
        userdetails.LocaleSidKey__c = 'ja_JP';
        userdetails.Account_Status__c='Active Paid';
        userdetails.Partner_Registration_status__c='complete';
        userdetails.Partner_Id__c='asdghh243';
        userdetails.DAZN_Id__c = '2323223';
        userdetails.Auth_Key__c = system.now();
        userdetails.Account_Type__c = '2';
        userdetails.ViewerId__c = '222121223';
        userdetails.IP_address__c = '255.255.255.255';
        userdetails.User_Type__c = 'Docomo';
        userdetails.Subscription_Start_Date__c = Date.today();
        userdetails.Subscription_End_Date__c = Date.today()+30;
        return userdetails;
    }
    public static List<DAZNUserFeed__c> createTestDFDUserFeedRecordsBulk( integer sizeRecords){
        List<DAZNUserFeed__c> DFDUserFeedRecords = new List<DAZNUserFeed__c>(); 
        for(integer i=0; i<sizeRecords; i++){
            DAZNUserFeed__c userdetails=new  DAZNUserFeed__c();
            //userdetails.Name = 'Test1222'+i;
            userdetails.First_Name__c='firsttest'+i;
            userdetails.Last_Name__c='lasttest'+i;
            userdetails.Email__c='test2344'+i+'@test.com';
            userdetails.BillingCountryCode__c='JP';
            userdetails.LanguageLocaleKey__c='ja';
            userdetails.EmailEncodingKey__c='UTF-8';
            userdetails.Email_Preferences__c=true;
            userdetails.Secondary_Email__c='test222@test.com';
            userdetails.Alias__c = 'ttss'+i;
            userdetails.TimeZoneSidKey__c = 'Asia/Tokyo';
            userdetails.CommunityNickname__c= i+'test'+i+'Te';
            userdetails.LocaleSidKey__c = 'ja_JP';
            userdetails.Account_Status__c='Active Paid';
            userdetails.Partner_Registration_status__c='complete';
            userdetails.Partner_Id__c='asdghh2'+i;
            userdetails.Num_Retries__c = 0;
            userdetails.DAZN_Id__c = '232232323' +i;
            userdetails.Auth_Key__c = system.now();
            userdetails.ViewerId__c = 's1s2s121212w'+i;
            userdetails.IP_address__c = '255.255.255.255';
            userdetails.User_Type__c = 'Docomo';
            userdetails.Subscription_Start_Date__c = Date.today();
        userdetails.Subscription_End_Date__c = Date.today()+30;
            DFDUserFeedRecords.add(userdetails);
        }
        return DFDUserFeedRecords;
    } 
    /*Description: This method is used to create community user with notification language code as de as per PD-9770*/
    @testSetup
    public static void createTestDEAccounts(){
        String orgId = UserInfo.getOrganizationId();
        List<Account> accList = new List<Account>();
        for (Integer i = 0;i<7;i++){
            String uniqueName = orgId;
            uniqueName += String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
            uniqueName += Integer.valueOf(math.rint(math.random()*1000000));
            Account oAccount = new Account();
            oAccount.FirstName = 'TestFirstName';
            oAccount.LastName = 'TestLastName'+i;
            oAccount.PersonEmail = 'email'+uniqueName+i+ '@testdomain.org';
            oAccount.Notification_Country_Code__c='DE';
            oAccount.Notification_Language_Code__c='de';
            oAccount.All_Email_Preferences__c = true;
            if(i==0){
                //Create Frozen Account
                oAccount.Account_Status__c = 'Frozen';
            } else if(i==1){
                //Create Active Paid Account
                oAccount.Account_Status__c = 'Active Paid';
                oAccount.Is_Double_OptIn__c = true;
                oAccount.IsReadyToSyncInZuora__c=true;
            } else if(i==2){
                //Create Free Trial Account
                oAccount.Account_Status__c = 'Free Trial';
                oAccount.Is_Double_OptIn__c = true;
                //oAccount.Notification_Language_Code__c= 'de';
            } else if(i==3){
                //Create Active Grace Account
                oAccount.Account_Status__c = 'Active Grace';
            } else if(i==4){
                //Create Expired Account
                oAccount.Account_Status__c = 'Expired';
            } else if(i==5){
                //Create Blocked Account
                oAccount.Account_Status__c = 'Blocked';
            } else if(i==6){
                //Create Partial Account
                oAccount.Account_Status__c = 'Partial';
            } 
            accList.add(oAccount);
            
        } //end of for - Account data preparation
        Database.insert(accList,true);
        
    }
    @testSetup
    public static void createTestDECommunityUsers(){
        List<Account> getaccList = [Select Id,Name,PersonContactId, Owner.Name, owner.UserRoleId,PersonEmail from Account];
        List<User> userList = new List<User>();
        //Query Profile for community user 
        List<Profile> listOfProfiles = [SELECT Id, Name from Profile where Name = 'Customer Community User' limit 1];
        if (listOfProfiles[0].Id !=null){
            Integer cnt = 11;
            for(Account acc : getaccList){
                User oUser = new User();
                oUser.email= acc.PersonEmail;
                oUser.Notification_Language_Code__c='de';
                oUser.UserName= acc.PersonEmail;
                oUser.Alias = 'LiveSp'+cnt;
                if(cnt == 11){
                    oUser.TimeZoneSidKey= 'Asia/Tokyo';
                    oUser.LocaleSidKey= 'ja_JP';
                    oUser.LanguageLocaleKey= 'ja';
                    oUser.Country= 'Japan';
                } else if(cnt == 12){
                    oUser.TimeZoneSidKey= 'Europe/Berlin';
                    oUser.LocaleSidKey= 'de_DE';
                    oUser.LanguageLocaleKey= 'de';
                    oUser.Country= 'Germany';
                } else if(cnt == 13){
                    oUser.TimeZoneSidKey= 'Europe/London';
                    oUser.LocaleSidKey= 'de_AT';
                    oUser.LanguageLocaleKey= 'en_GB';
                    oUser.Country= 'Austria';
                } else if(cnt == 14){
                    oUser.TimeZoneSidKey= 'Europe/Berlin';
                    oUser.LocaleSidKey= 'de_CH';
                    oUser.LanguageLocaleKey= 'en_GB';
                    oUser.Country= 'Switzerland';
                }else if(cnt == 15){
                    oUser.TimeZoneSidKey= 'Europe/Berlin';
                    oUser.LocaleSidKey= 'ja_JP';
                    oUser.LanguageLocaleKey= 'en_GB';
                    oUser.Country= 'India';
                }else if(cnt == 16){
                    oUser.TimeZoneSidKey= 'Europe/London';
                    oUser.LocaleSidKey= 'de_DE';
                    oUser.LanguageLocaleKey= 'en_GB';
                    oUser.Country= 'Germany';
                }else if(cnt==17){
                    oUser.TimeZoneSidKey= 'Europe/London';
                    oUser.LocaleSidKey= 'de_DE';
                    oUser.LanguageLocaleKey= 'en_GB';
                    oUser.Country= 'Germany';
                }
                oUser.EmailEncodingKey= 'ISO-8859-1';
                oUser.FirstName = 'TestFName';
                oUser.LastName = 'TestLName'+cnt;
                oUser.isActive= true;
                oUser.ContactId = acc.PersonContactId;
                oUser.profileid = listOfProfiles[0].Id;
                userList.add(oUser) ; 
                cnt = cnt + 1;
            }//end of for loop 
            Database.insert(userList,true);
        } //end of if - profile id null check
    }
    /*Description: This method is used to create community user with notification language code as ja as per PD-9770*/
    @testSetup
    public static void createTestJPAccounts(){
        String orgId = UserInfo.getOrganizationId();
        List<Account> accList = new List<Account>();
        for (Integer i = 0;i<7;i++){
            String uniqueName = orgId;
            uniqueName += String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
            uniqueName += Integer.valueOf(math.rint(math.random()*1000000));
            Account oAccount = new Account();
            oAccount.FirstName = 'TestFirstName';
            oAccount.LastName = 'TestLastName'+i;
            oAccount.PersonEmail = 'email'+uniqueName+i+ '@testdomain.org';
            oAccount.Notification_Country_Code__c='DE';
            oAccount.Notification_Language_Code__c='ja';
            oAccount.All_Email_Preferences__c = true;
            if(i==0){
                //Create Frozen Account
                oAccount.Account_Status__c = 'Frozen';
            } else if(i==1){
                //Create Active Paid Account
                oAccount.Account_Status__c = 'Active Paid';
                oAccount.Is_Double_OptIn__c = true;
                oAccount.IsReadyToSyncInZuora__c=true;
            } else if(i==2){
                //Create Free Trial Account
                oAccount.Account_Status__c = 'Free Trial';
                oAccount.Is_Double_OptIn__c = true;
                //oAccount.Notification_Language_Code__c= 'de';
            } else if(i==3){
                //Create Active Grace Account
                oAccount.Account_Status__c = 'Active Grace';
            } else if(i==4){
                //Create Expired Account
                oAccount.Account_Status__c = 'Expired';
            } else if(i==5){
                //Create Blocked Account
                oAccount.Account_Status__c = 'Blocked';
            } else if(i==6){
                //Create Partial Account
                oAccount.Account_Status__c = 'Partial';
            } 
            accList.add(oAccount);
            
        } //end of for - Account data preparation
        Database.insert(accList,true);
        
    }
    @testSetup
    public static void createTestJPCommunityUsers(){
        List<Account> getaccList = [Select Id,Name,PersonContactId, Owner.Name, owner.UserRoleId,PersonEmail from Account];
        List<User> userList = new List<User>();
        //Query Profile for community user 
        List<Profile> listOfProfiles = [SELECT Id, Name from Profile where Name = 'Customer Community User' limit 1];
        if (listOfProfiles[0].Id !=null){
            Integer cnt = 11;
            for(Account acc : getaccList){
                User oUser = new User();
                oUser.email= acc.PersonEmail;
                oUser.UserName= acc.PersonEmail;
                oUser.Alias = 'LiveSp'+cnt;
                if(cnt == 11){
                    oUser.TimeZoneSidKey= 'Asia/Tokyo';
                    oUser.LocaleSidKey= 'ja_JP';
                    oUser.LanguageLocaleKey= 'ja';
                    oUser.Country= 'Japan';
                } else if(cnt == 12){
                    oUser.TimeZoneSidKey= 'Europe/Berlin';
                    oUser.LocaleSidKey= 'de_DE';
                    oUser.LanguageLocaleKey= 'de';
                    oUser.Country= 'Germany';
                } else if(cnt == 13){
                    oUser.TimeZoneSidKey= 'Europe/London';
                    oUser.LocaleSidKey= 'de_AT';
                    oUser.LanguageLocaleKey= 'en_GB';
                    oUser.Country= 'Austria';
                } else if(cnt == 14){
                    oUser.TimeZoneSidKey= 'Europe/Berlin';
                    oUser.LocaleSidKey= 'de_CH';
                    oUser.LanguageLocaleKey= 'en_GB';
                    oUser.Country= 'Switzerland';
                }else if(cnt == 15){
                    oUser.TimeZoneSidKey= 'Europe/Berlin';
                    oUser.LocaleSidKey= 'ja_JP';
                    oUser.LanguageLocaleKey= 'en_GB';
                    oUser.Country= 'India';
                }else if(cnt == 16){
                    oUser.TimeZoneSidKey= 'Europe/London';
                    oUser.LocaleSidKey= 'de_DE';
                    oUser.LanguageLocaleKey= 'en_GB';
                    oUser.Country= 'Germany';
                }else if(cnt==17){
                    oUser.TimeZoneSidKey= 'Europe/London';
                    oUser.LocaleSidKey= 'de_DE';
                    oUser.LanguageLocaleKey= 'en_GB';
                    oUser.Country= 'Germany';
                }
                oUser.EmailEncodingKey= 'ISO-8859-1';
                oUser.FirstName = 'TestFName';
                oUser.LastName = 'TestLName'+cnt;
                oUser.isActive= true;
                oUser.ContactId = acc.PersonContactId;
                oUser.profileid = listOfProfiles[0].Id;
                userList.add(oUser) ; 
                cnt = cnt + 1;
            }//end of for loop 
            Database.insert(userList,true);
        } //end of if - profile id null check
        
    }
    /*Description: This method is used to create community user with notification language code as en as per PD-9770*/
    @testSetup
    public static void createTestENAccounts(){
        String orgId = UserInfo.getOrganizationId();
        List<Account> accList = new List<Account>();
        for (Integer i = 0;i<7;i++){
            String uniqueName = orgId;
            uniqueName += String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
            uniqueName += Integer.valueOf(math.rint(math.random()*1000000));
            Account oAccount = new Account();
            oAccount.FirstName = 'TestFirstName';
            oAccount.LastName = 'TestLastName'+i;
            oAccount.PersonEmail = 'email'+uniqueName+i+ '@testdomain.org';
            oAccount.Notification_Country_Code__c='DE';
            oAccount.Notification_Language_Code__c='en_GB';
            oAccount.All_Email_Preferences__c = true;
            if(i==0){
                //Create Frozen Account
                oAccount.Account_Status__c = 'Frozen';
            } else if(i==1){
                //Create Active Paid Account
                oAccount.Account_Status__c = 'Active Paid';
                oAccount.Is_Double_OptIn__c = true;
                oAccount.IsReadyToSyncInZuora__c=true;
            } else if(i==2){
                //Create Free Trial Account
                oAccount.Account_Status__c = 'Free Trial';
                oAccount.Is_Double_OptIn__c = true;
                //oAccount.Notification_Language_Code__c= 'de';
            } else if(i==3){
                //Create Active Grace Account
                oAccount.Account_Status__c = 'Active Grace';
            } else if(i==4){
                //Create Expired Account
                oAccount.Account_Status__c = 'Expired';
            } else if(i==5){
                //Create Blocked Account
                oAccount.Account_Status__c = 'Blocked';
            } else if(i==6){
                //Create Partial Account
                oAccount.Account_Status__c = 'Partial';
            } 
            accList.add(oAccount);
            
        } //end of for - Account data preparation
        Database.insert(accList,true);
        
    }
    @testSetup
    public static void createTestENCommunityUsers(){
        List<Account> getaccList = [Select Id,Name,PersonContactId, Owner.Name, owner.UserRoleId,PersonEmail from Account];
        List<User> userList = new List<User>();
        //Query Profile for community user 
        List<Profile> listOfProfiles = [SELECT Id, Name from Profile where Name = 'Customer Community User' limit 1];
        if (listOfProfiles[0].Id !=null){
            Integer cnt = 11;
            for(Account acc : getaccList){
                User oUser = new User();
                oUser.email= acc.PersonEmail;
                oUser.UserName= acc.PersonEmail;
                oUser.Alias = 'LiveSp'+cnt;
                if(cnt == 11){
                    oUser.TimeZoneSidKey= 'Asia/Tokyo';
                    oUser.LocaleSidKey= 'ja_JP';
                    oUser.LanguageLocaleKey= 'ja';
                    oUser.Country= 'Japan';
                } else if(cnt == 12){
                    oUser.TimeZoneSidKey= 'Europe/Berlin';
                    oUser.LocaleSidKey= 'de_DE';
                    oUser.LanguageLocaleKey= 'de';
                    oUser.Country= 'Germany';
                } else if(cnt == 13){
                    oUser.TimeZoneSidKey= 'Europe/London';
                    oUser.LocaleSidKey= 'de_AT';
                    oUser.LanguageLocaleKey= 'en_GB';
                    oUser.Country= 'Austria';
                } else if(cnt == 14){
                    oUser.TimeZoneSidKey= 'Europe/Berlin';
                    oUser.LocaleSidKey= 'de_CH';
                    oUser.LanguageLocaleKey= 'en_GB';
                    oUser.Country= 'Switzerland';
                }else if(cnt == 15){
                    oUser.TimeZoneSidKey= 'Europe/Berlin';
                    oUser.LocaleSidKey= 'ja_JP';
                    oUser.LanguageLocaleKey= 'en_GB';
                    oUser.Country= 'India';
                }else if(cnt == 16){
                    oUser.TimeZoneSidKey= 'Europe/London';
                    oUser.LocaleSidKey= 'de_DE';
                    oUser.LanguageLocaleKey= 'en_GB';
                    oUser.Country= 'Germany';
                }else if(cnt==17){
                    oUser.TimeZoneSidKey= 'Europe/London';
                    oUser.LocaleSidKey= 'de_DE';
                    oUser.LanguageLocaleKey= 'en_GB';
                    oUser.Country= 'Germany';
                }
                oUser.EmailEncodingKey= 'ISO-8859-1';
                oUser.FirstName = 'TestFName';
                oUser.LastName = 'TestLName'+cnt;
                oUser.isActive= true;
                oUser.ContactId = acc.PersonContactId;
                oUser.profileid = listOfProfiles[0].Id;
                userList.add(oUser) ; 
                cnt = cnt + 1;
            }//end of for loop 
            Database.insert(userList,true);
        } //end of if - profile id null check
        
    } 
}