objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partial</fullName>
                    <default>true</default>
                    <label>Partial</label>
                </value>
                <value>
                    <fullName>Free Trial</fullName>
                </value>
                <value>
                    <fullName>Active Paid</fullName>
                </value>
                <value>
                    <fullName>Active Grace</fullName>
                </value>
                <value>
                    <fullName>Frozen</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Expired Marketing</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Apple</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/DeviceSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This Custom setting is used to limit the number of Active User devices for each Country</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MaxDevices__c</fullName>
        <label>MaxDevices</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DeviceSettings</label>
</CustomObject>

objects/Inactive_User_Devices__c.object
<CustomObject>
    <description>This object is used to store Inactive user devices that has been deleted.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Inactive User Devices</relationshipLabel>
        <relationshipName>Inactive_User_Devices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Of_Registration__c</fullName>
        <description>Device Registration Date</description>
        <label>Date Of Registration</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Device_Id__c</fullName>
        <label>Device Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Device_Name__c</fullName>
        <label>Device Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Device_Registration_Date__c</fullName>
        <label>Device Registration Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Device_manufacturer__c</fullName>
        <label>Device manufacturer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Device_version__c</fullName>
        <label>Device version</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operating_System_Name__c</fullName>
        <label>Operating System Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operating_System_Version__c</fullName>
        <label>Operating System Version</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Device Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>InActive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Device Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Console</fullName>
                </value>
                <value>
                    <fullName>Desktop</fullName>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                </value>
                <value>
                    <fullName>Tablet</fullName>
                </value>
                <value>
                    <fullName>TV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Agent__c</fullName>
        <label>User Agent</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Inactive User Devices</label>
    <nameField>
        <displayFormat>IDN-{0000000000}</displayFormat>
        <label>Inactive User Devices  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inactive User Devices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User_Devices__c.object
<CustomObject>
    <description>This object is used to store user devices used to sign-in in application.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>User Account and Device Relationship field</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>User Devices</relationshipLabel>
        <relationshipName>User_Devices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Of_Registration__c</fullName>
        <description>Device Registration Date</description>
        <label>Date Of Registration</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Device_Id__c</fullName>
        <label>Device Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Device_Name__c</fullName>
        <description>This field is used to store registered device name.</description>
        <label>Device Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Device_Registration_Date__c</fullName>
        <description>Device Registration Date</description>
        <label>Device Registration Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Device_manufacturer__c</fullName>
        <label>Device manufacturer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Device_version__c</fullName>
        <label>Device version</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operating_System_Name__c</fullName>
        <label>Operating System Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operating_System_Version__c</fullName>
        <label>Operating System Version</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Device Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>InActive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Device Type</description>
        <label>Device Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Console</fullName>
                </value>
                <value>
                    <fullName>Desktop</fullName>
                </value>
                <value>
                    <fullName>Laptop</fullName>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                </value>
                <value>
                    <fullName>Tablet</fullName>
                </value>
                <value>
                    <fullName>TV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Agent__c</fullName>
        <label>User Agent</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>User Devices</label>
    <nameField>
        <displayFormat>DN-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Devices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UserDeviceTriggerTest.cls
@IsTest
public class UserDeviceTriggerTest {
    @testSetup
    public static void createDeviceSettingsData(){              
        DeviceSettings__c setting = new DeviceSettings__c();
        setting.Name = 'Germany';
        setting.Country__c = 'DE';
        setting.MaxDevices__c = 4;        
        insert setting;
        System.assertNotEquals(setting.Id, Null);
        System.assertEquals(setting.Name, 'Germany');
        System.assertEquals(setting.MaxDevices__c, 4);
    }
    
    public static testMethod void UserDeviceTriggerTestMethod1() { 
        CreateTestDataforUnitTest.triggerSettings();
        CreateTestDataforUnitTest.createTestAccounts(); //Create Accounts and User for Unit Test  
        //Retreieve  account Data
        List<Account> oAccountList = new List<Account>();      
        oAccountList = [Select Id, Name from Account where Account_Status__c = 'Active Paid' Limit 1];
        if(oAccountList.size() > 0 && oAccountList[0].id != null ){
            
            List<User_Devices__c> listOfDevices = new List<User_Devices__c>();
            for(Integer i = 0;i < 4;i++){
                //Adding devices related to account
                User_Devices__c device1 = new User_Devices__c(); 
                device1.Account__c = oAccountList[0].Id;
                device1.Date_Of_Registration__c=System.today();
                device1.Device_Id__c='DESK001'+i;
                device1.Device_manufacturer__c='';
                device1.Device_Name__c='Desktop1'+i;
                device1.Device_Registration_Date__c=System.today();
                device1.Type__c='Desktop';
                device1.Device_version__c='';
                device1.Operating_System_Name__c='';
                device1.Operating_System_Version__c='';
                device1.Status__c='Active';
                device1.User_Agent__c='';
                listOfDevices.add(device1);
            }
            Test.startTest();
            if(listOfDevices.size() > 0){
                Insert listOfDevices;
                System.assertNotEquals(listOfDevices[0].Id, Null);
            }
            Test.stopTest();
            //Now Add Additional device
            User_Devices__c device5 = new User_Devices__c();
            device5.Account__c=oAccountList[0].Id;
            device5.Date_Of_Registration__c=System.today();
            device5.Device_Id__c='DESK001';
            device5.Device_manufacturer__c='';
            device5.Device_Name__c='Desktop1';
            device5.Device_Registration_Date__c=System.today();
            device5.Type__c='Desktop';
            device5.Device_version__c='';
            device5.Operating_System_Name__c='';
            device5.Operating_System_Version__c='';
            device5.Status__c='Active';
            device5.User_Agent__c='';
            insert device5;   
            System.assertNotEquals(device5.ID, Null);
        }    
    }
    
    public static testMethod void testDuplicateDeviceIdForUserDevice() { 
        CreateTestDataforUnitTest.triggerSettings();
        CreateTestDataforUnitTest.createTestAccounts(); //Create Accounts and User for Unit Test  
        //Retreieve  account Data
        List<Account> oAccountList = new List<Account>();      
        oAccountList = [Select Id, Name from Account where Account_Status__c = 'Active Paid' Limit 1];
        if(oAccountList.size() > 0 && oAccountList[0].id != null ){
            
            List<User_Devices__c> listOfDevices = new List<User_Devices__c>();
            for(Integer i = 0;i < 4;i++){
                //Adding devices related to account
                User_Devices__c device1 = new User_Devices__c(); 
                device1.Account__c = oAccountList[0].Id;
                device1.Date_Of_Registration__c=System.today();
                device1.Device_Id__c='DESK001'+i;
                device1.Device_manufacturer__c='';
                device1.Device_Name__c='Desktop1'+i;
                device1.Device_Registration_Date__c=System.today();
                device1.Type__c='Desktop';
                device1.Device_version__c='';
                device1.Operating_System_Name__c='';
                device1.Operating_System_Version__c='';
                device1.Status__c='Active';
                device1.User_Agent__c='';
                listOfDevices.add(device1);
            }
             Insert listOfDevices;
            Inactive_User_Devices__c objInactiveUD = new Inactive_User_Devices__c(Account__c = oAccountList[0].Id, Date_Of_Registration__c=System.today(), 
                    Device_Id__c='DESK0011', Device_manufacturer__c='', Device_Name__c='Desktop1', Device_Registration_Date__c=System.today(), 
                    Type__c='Desktop', Device_version__c='', Operating_System_Name__c='', Operating_System_Version__c='', Status__c='Active', User_Agent__c='');
                    Insert objInactiveUD;                                    
            Test.startTest();
            if(listOfDevices.size() > 0){                
               
                System.assertNotEquals(listOfDevices[0].Id, Null);
                objInactiveUD = [Select Id from Inactive_User_Devices__c where Id = :objInactiveUD.Id];
                System.assertNotEquals(objInactiveUD.Id, Null);
            }
            Test.stopTest();
            //Now Add Additional device
            User_Devices__c device5 = new User_Devices__c();
            device5.Account__c=oAccountList[0].Id;
            device5.Date_Of_Registration__c=System.today();
            device5.Device_Id__c='DESK001';
            device5.Device_manufacturer__c='';
            device5.Device_Name__c='Desktop1';
            device5.Device_Registration_Date__c=System.today();
            device5.Type__c='Desktop';
            device5.Device_version__c='';
            device5.Operating_System_Name__c='';
            device5.Operating_System_Version__c='';
            device5.Status__c='Active';
            device5.User_Agent__c='';
            insert device5;   
            
            System.assertNotEquals(device5.ID, Null);
        }    
    }
}