objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partial</fullName>
                    <default>true</default>
                    <label>Partial</label>
                </value>
                <value>
                    <fullName>Free Trial</fullName>
                </value>
                <value>
                    <fullName>Active Paid</fullName>
                </value>
                <value>
                    <fullName>Active Grace</fullName>
                </value>
                <value>
                    <fullName>Frozen</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Expired Marketing</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Apple</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>All_Email_Preferences__c</fullName>
        <defaultValue>true</defaultValue>
        <label>All Email Preferences</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>All_Email_Preferences__c</fullName>
        <defaultValue>true</defaultValue>
        <label>All Email Preferences</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/AnonymizerAccount.cls
global class AnonymizerAccount implements Database.Batchable<sObject> {
	
	private String query;
	private String strEnvName;
	
	global AnonymizerAccount(String emailPattern) {
		this.query = 'Select Id, All_Email_Preferences__c, PersonEmail, Account_Status__c, FirstName, LastName From Account Where PersonEmail LIKE \'%' + String.escapeSingleQuotes(emailPattern) + '\'';
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope) {
   		Map<Id, User> usersForAccounts = new Map<Id, User>();
   		for (User u : [Select Id, FirstName, LastName, Username, Email, AccountId From User Where AccountId IN :scope]) {
   			usersForAccounts.put(u.AccountId, u);
   		}

   		List<Account> accountsForDeactivate = new List<Account>();
	    Account accountForDeactivate;
	    User userForAccount;
	    
	    for (sObject accountObj : scope) {
	    	accountForDeactivate = (Account)accountObj;
	    	userForAccount = usersForAccounts.get(accountForDeactivate.Id);
	    	if (userForAccount != null) {
	    		accountForDeactivate.All_Email_Preferences__c = false;
                accountForDeactivate.PersonEmail = userForAccount.Email;
                accountForDeactivate.Account_Status__c = 'Expired';
                accountForDeactivate.FirstName = userForAccount.FirstName;
                accountForDeactivate.LastName = userForAccount.LastName;

                accountsForDeactivate.add(accountForDeactivate);
	    	}
	    }
	    update accountsForDeactivate;	
	}
	
	global void finish(Database.BatchableContext BC) {
		
	}
	
}