objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partial</fullName>
                    <default>true</default>
                    <label>Partial</label>
                </value>
                <value>
                    <fullName>Free Trial</fullName>
                </value>
                <value>
                    <fullName>Active Paid</fullName>
                </value>
                <value>
                    <fullName>Active Grace</fullName>
                </value>
                <value>
                    <fullName>Frozen</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Expired Marketing</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Apple</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>All_Email_Preferences__c</fullName>
        <defaultValue>true</defaultValue>
        <label>All Email Preferences</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Free_Trial_End_Date__c</fullName>
        <label>Free Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hard_Offer_date__c</fullName>
        <description>When change the status from frozen to activepaid</description>
        <label>Hard Offer date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Notification_Country_Code__c</fullName>
        <label>Notification Country Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification_Language_Code__c</fullName>
        <label>Notification Language Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pause_From__c</fullName>
        <label>Pause From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Pause_Until__c</fullName>
        <label>Pause Until</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Previous_Status__c</fullName>
        <label>Previous Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_Change_Date__c</fullName>
        <label>Status Change Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sync_Error_Msg__c</fullName>
        <label>Sync Error Msg</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/DAZNConfiguration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is a configurable custom setting for Forgot Password link</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>Field to store configuration value for specific key</description>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>DAZN Configuration</label>
</CustomObject>

objects/Email_Sync_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Account_Currency__c</fullName>
        <label>Account Currency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>JPY</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>CHF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partial</fullName>
                </value>
                <value>
                    <fullName>Free Trial</fullName>
                </value>
                <value>
                    <fullName>Active Paid</fullName>
                </value>
                <value>
                    <fullName>Active Grace</fullName>
                </value>
                <value>
                    <fullName>Frozen</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Expired Marketing</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Apple</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Email Sync Queues</relationshipLabel>
        <relationshipName>Email_Sync_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>All_Email_Preferences__c</fullName>
        <defaultValue>true</defaultValue>
        <label>All Email Preferences</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dispatch_ID__c</fullName>
        <label>Dispatch ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email_Name__c</fullName>
        <label>Email Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Free_Trial_End_Date__c</fullName>
        <label>Free Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gift_Code_Expiry_Date__c</fullName>
        <label>Gift Code Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hard_Offer_Date__c</fullName>
        <label>Hard Offer Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Double_Opt_in__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to identify user is double opt-in for marketing emails.</description>
        <label>Is Double Opt in</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification_Country_Code__c</fullName>
        <label>Notification Country Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification_Language_Code__c</fullName>
        <label>Notification Language Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pause_From__c</fullName>
        <label>Pause From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Pause_Until__c</fullName>
        <label>Pause Until</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Method_Type__c</fullName>
        <label>Payment Method Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_Email__c</fullName>
        <label>Person Email</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Details__c</fullName>
        <label>Plan Details</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rebill_Date__c</fullName>
        <label>Rebill Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Retried</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscription_Amount__c</fullName>
        <label>Subscription Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subscription_End_Date__c</fullName>
        <label>Subscription End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sync_Error_Msg__c</fullName>
        <label>Sync Error Msg</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Term_Setting_Type__c</fullName>
        <label>Term Setting Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of_Email__c</fullName>
        <label>Type of Email</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Data Import</fullName>
                </value>
                <value>
                    <fullName>Triggered Dispatch</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unsubscribe_Language__c</fullName>
        <label>Unsubscribe Language</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Email Sync Queue</label>
    <nameField>
        <displayFormat>ESQ-{0000}</displayFormat>
        <label>Email Sync Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Sync Queues</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Plan_Details__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Plan Details Conversion with respect to the language selected</description>
    <label>Plan Details</label>
</CustomObject>

classes/BatchEmailSyncQueueCommunicator.cls
/**
* @author Cognizant Technology Solutuions
* @date 22/03/2017
* @description Batch Class searches for the Email_Sync_Queue__c records and then send info from these records to Communicator.
*/
global class BatchEmailSyncQueueCommunicator implements Database.Batchable<sObject>, Database.AllowsCallouts, Schedulable {

    private static final String SCHEDULER_NAME = 'BatchEmailSyncQueueCommunicator';
    public String sQuery;

    global Database.QueryLocator start(Database.BatchableContext bc) {
        sQuery = 'SELECT Id, Account__c, Account_Currency__c, Account_Status__c, All_Email_Preferences__c, Dispatch_ID__c, First_Name__c, Free_Trial_End_Date__c, Rebill_Date__c, Email_Name__c, Gift_Code_Expiry_Date__c, ';
        sQuery += 'Hard_Offer_Date__c, Is_Double_Opt_in__c, Last_Name__c, Notification_Country_Code__c, Notification_Language_Code__c, Payment_Method_Type__c, Sync_Error_Msg__c, Term_Setting_Type__c, ';
        sQuery += 'Person_Email__c, Plan_Details__c, Status__c, Subscription_Amount__c, Subscription_End_Date__c, Type_of_Email__c, Unsubscribe_Language__c, Pause_From__c, Pause_Until__c, ';
        sQuery += 'Account__r.Previous_Status__c, Account__r.Status_Change_Date__c ';
        sQuery += 'FROM Email_Sync_Queue__c ';
        sQuery += 'WHERE Status__c = \'Not Started\' OR Status__c = \'Retried\' ';
        sQuery += 'ORDER BY CreatedDate ASC LIMIT ' + getBatchSizeLimit(); // LIMIT 1000 by default. It is configured in 'Batch Size Email Queue' DAZNConfiguration__c
        return Database.getQueryLocator(sQuery);
    }

    global void execute(Database.BatchableContext BC, List<Email_Sync_Queue__c> scope) {
        List<Email_Sync_Queue__c> dataImportEmailQueueList = new List<Email_Sync_Queue__c>();
        List<Email_Sync_Queue__c> triggeredDispatchEmailQueueList = new List<Email_Sync_Queue__c>();
        for (Email_Sync_Queue__c emailSyncQueue : scope) {
            if (emailSyncQueue.Type_of_Email__c == 'Data Import') {
                dataImportEmailQueueList.add(emailSyncQueue);
            } else if (emailSyncQueue.Type_of_Email__c == 'Triggered Dispatch') {
                triggeredDispatchEmailQueueList.add(emailSyncQueue);
            }
        }

        if (!Test.isRunningTest()) {
            CommunicatorIntegrationHelper.handleEmailSyncRecords(dataImportEmailQueueList, triggeredDispatchEmailQueueList);
        }
    }

    global void finish(Database.BatchableContext BC) {
        
    }

    global void execute(SchedulableContext SC) {
        BatchEmailSyncQueueCommunicator emailSyncBatch  = new BatchEmailSyncQueueCommunicator();
        Id batchProcessId = Database.executeBatch(emailSyncBatch, 200);
    }
    
    /**
    * Invoking start method for BatchEmailSyncQueueCommunicator Scheduler in Every 5 Mins
    */
    public static void startJob() {
        Set<String> intervals = new Set<String>{'00', '05', '10', '15', '20', '25', '30', '35', '40', '45', '50', '55'};
        for (String min : intervals) {
            String scheduleExpression = ('0 ' + min + ' * * * ?');
            String postfixForTestContext = (Test.isRunningTest()) ? 'Test' : '';
            System.schedule(SCHEDULER_NAME + postfixForTestContext + ' - ' + min, scheduleExpression, new BatchEmailSyncQueueCommunicator());
        }
    }
    
    /**
    * Methods gets limit size value from 'Batch Size Email Queue' DAZNConfiguration__c
    */
    public static String getBatchSizeLimit() {
        String limitString = '1000'; // by default
        DAZNConfiguration__c configBatchSize = DAZNConfiguration__c.getValues('Batch Size Email Queue');
        String limitBatchSize = configBatchSize != null ? configBatchSize.Value__c : null;
        if (limitBatchSize != null) {
            try {
                Integer numberLimit = Integer.valueOf(limitBatchSize);
                limitString = String.valueOf(numberLimit);
            } catch (Exception e) {
                System.debug('\nERROR: ' + e.getMessage() + '\nSTACK TRACE: ' + e.getStackTraceString());
            }
        }
        return limitString;
    }

}