objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partial</fullName>
                    <default>true</default>
                    <label>Partial</label>
                </value>
                <value>
                    <fullName>Free Trial</fullName>
                </value>
                <value>
                    <fullName>Active Paid</fullName>
                </value>
                <value>
                    <fullName>Active Grace</fullName>
                </value>
                <value>
                    <fullName>Frozen</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Expired Marketing</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Apple</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>All_Email_Preferences__c</fullName>
        <defaultValue>true</defaultValue>
        <label>All Email Preferences</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_immediate_cancel_email__c</fullName>
        <formula>IF( ISPICKVAL( Type , &apos;Apple&apos;) , TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Disable immediate cancel email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_transactional_emails__c</fullName>
        <formula>OR( ISPICKVAL( Type, &apos;Docomo&apos; ), Disable_all_transactional_emails__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Disable transaction emails</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Free_Trial_End_Date__c</fullName>
        <label>Free Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hard_Offer_date__c</fullName>
        <description>When change the status from frozen to activepaid</description>
        <label>Hard Offer date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Is_Double_OptIn__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to identify user is double opt-in for marketing emails.</description>
        <label>Is Double OptIn</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notification_Country_Code__c</fullName>
        <label>Notification Country Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification_Language_Code__c</fullName>
        <label>Notification Language Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Previous_Status__c</fullName>
        <label>Previous Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sync_Error_Msg__c</fullName>
        <label>Sync Error Msg</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/DAZNCommunicatorConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This will hold the Dispatch id based on the email and the language</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>Column to store communicator table, column, dispatch, trigger id etc.</description>
        <label>Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DAZN Communicator Config</label>
</CustomObject>

objects/Email_Sync_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Account_Currency__c</fullName>
        <label>Account Currency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>JPY</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>CHF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partial</fullName>
                </value>
                <value>
                    <fullName>Free Trial</fullName>
                </value>
                <value>
                    <fullName>Active Paid</fullName>
                </value>
                <value>
                    <fullName>Active Grace</fullName>
                </value>
                <value>
                    <fullName>Frozen</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Expired Marketing</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Apple</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Email Sync Queues</relationshipLabel>
        <relationshipName>Email_Sync_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>All_Email_Preferences__c</fullName>
        <defaultValue>true</defaultValue>
        <label>All Email Preferences</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dispatch_ID__c</fullName>
        <label>Dispatch ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email_Name__c</fullName>
        <label>Email Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Free_Trial_End_Date__c</fullName>
        <label>Free Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hard_Offer_Date__c</fullName>
        <label>Hard Offer Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Double_Opt_in__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to identify user is double opt-in for marketing emails.</description>
        <label>Is Double Opt in</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification_Country_Code__c</fullName>
        <label>Notification Country Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification_Language_Code__c</fullName>
        <label>Notification Language Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Method_Type__c</fullName>
        <label>Payment Method Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_Email__c</fullName>
        <label>Person Email</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Retried</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscription_End_Date__c</fullName>
        <label>Subscription End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sync_Error_Msg__c</fullName>
        <label>Sync Error Msg</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type_of_Email__c</fullName>
        <label>Type of Email</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Data Import</fullName>
                </value>
                <value>
                    <fullName>Triggered Dispatch</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unsubscribe_Language__c</fullName>
        <label>Unsubscribe Language</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Email Sync Queue</label>
    <nameField>
        <displayFormat>ESQ-{0000}</displayFormat>
        <label>Email Sync Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Sync Queues</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>All_Email_Preferences__c</fullName>
        <defaultValue>true</defaultValue>
        <label>All Email Preferences</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notification_Language_Code__c</fullName>
        <label>Notification Language Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>R00N40000001kyLcEAI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora__Currency__c</fullName>
        <label>Currency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__PaymentMethod_Type__c</fullName>
        <formula>IF (  ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__Type__c, &quot;ACH&quot;), &quot;ACH&quot;,
   IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__Type__c, &quot;BankTransfer&quot;), &quot;Bank Transfer&quot;, 
       IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__Type__c, &quot;Cash&quot;), &quot;Cash&quot;,     
         IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__Type__c, &quot;Check&quot;), &quot;Check&quot;, 
           IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__Type__c, &quot;CreditCard&quot;), &quot;Credit Card&quot;, 
                IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__Type__c, &quot;CreditCardReferenceTransaction&quot;), &quot;Credit Card  Reference Transaction&quot;, 
                    IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__Type__c, &quot;DebitCard&quot;), &quot;Debit Card&quot;, 
                       IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__Type__c, &quot;Other&quot;), &quot;Other&quot;, 
                                IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__Type__c, &quot;PayPal&quot;), &quot;PayPal&quot;, 
                                   IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__Type__c, &quot;WireTransfer&quot;), &quot;Wire Transfer&quot;,  &quot;&quot;
                                     )
                                )
                         )
                     )
                )
         )
    )
  )
))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Method Type</label>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Free_Trial_End_Date__c</fullName>
        <label>Free Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__CustomerAccount__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This field holds the Zuora object ID, and is used as external ID for data synchronization between Salesforce and Zuora.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CancelEmail.cls
@RestResource(urlMapping='/CancelEmail/*')
global class CancelEmail {

    @HttpPost
    global static String cancelSubscriptionPost() {
        String requestString;
        String statusMessage; // can be "Success" or "Failure" status

        String accountCrmId; // salesforce Id of Account
        String accountId; // salesforce Id of the Zuora__CustomerAccount__c
        Date subscriptionTermEndDate; // the end date after which subscription is cancelled
        Integer accountBillCycleDay; // what day of the month this account gets billed
        String defaultPaymentMethodType;
        String subscriptionName;

        CancellactionJSON inputJSON;

        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        try {
            requestString = req.requestBody.toString();
            System.debug('### request String ###' + requestString);

            inputJSON = parse(requestString);

            accountCrmId = inputJSON.AccountCrmId;
            accountId = inputJSON.AccountId;
            subscriptionTermEndDate = String.isNotBlank(inputJSON.SubscriptionTermEndDate) ? Date.valueOf(inputJSON.SubscriptionTermEndDate) : null;
            accountBillCycleDay = String.isNotBlank(inputJSON.AccountBillCycleDay) ? Integer.valueOf(inputJSON.AccountBillCycleDay) : null;
            defaultPaymentMethodType = inputJSON.DefaultPaymentMethodType;
            subscriptionName = inputJSON.SubscriptionName;

            if (String.isBlank(accountCrmId) || String.isBlank(accountId) || subscriptionTermEndDate == null || accountBillCycleDay == null) {
                res.statusCode = 400;
                return 'Failure';
            }

            List<Zuora__CustomerAccount__c> billingAccount = [
                SELECT Id, Zuora__Account__c
                FROM Zuora__CustomerAccount__c
                WHERE Zuora__External_Id__c = :accountId
                LIMIT 1
            ];
            if (!billingAccount.isEmpty()) {
                sendSubscriptionCancelationEmails(billingAccount[0].Id, billingAccount[0].Zuora__Account__c, subscriptionTermEndDate, accountBillCycleDay, defaultPaymentMethodType, subscriptionName);
                statusMessage = 'Success';
                res.statusCode = 200;
            }
            else {
                statusMessage = 'Failure';
                res.statusCode = 400;
            }
        } catch (Exception e) {
            statusMessage = 'Failure';
            res.statusCode = 500;
        }

        return statusMessage;
    }

    /* 
    Description: Send Cancellation Email to users using communicator.
    */
    public static void sendSubscriptionCancelationEmails(Id billingCanAccountId, Id accountCrmId, Date subscriptionTermEndDate, Integer accountBillCycleDay, String defaultPaymentMethodType, String subscriptionName) {
        if (billingCanAccountId != null && accountCrmId != null) {
            Map<Id, Zuora__CustomerAccount__c> mapCanBillingAccount = new Map<Id, Zuora__CustomerAccount__c>([SELECT id, Zuora__Account__r.Account_Status__c,
                                                                                                              Zuora__Account__c,
                                                                                                              Zuora__Account__r.Notification_Language_Code__c,
                                                                                                              Zuora__Account__r.PersonEmail, 
                                                                                                              Zuora__Account__r.FirstName,
                                                                                                              Zuora__Account__r.LastName,
                                                                                                              Zuora__Account__r.PersonContactId,
                                                                                                              Zuora__Currency__c, Zuora__PaymentMethod_Type__c,
                                                                                                              Zuora__Account__r.Notification_Country_Code__c,
                                                                                                              Zuora__Account__r.Disable_immediate_cancel_email__c,
                                                                                                              Zuora__Account__r.Disable_transactional_emails__c,
                                                                                                              Zuora__Account__r.All_Email_Preferences__c,
                                                                                                              Zuora__Account__r.Hard_Offer_Date__c,
                                                                                                              Zuora__Account__r.Is_Double_OptIn__c,
                                                                                                              Zuora__Account__r.Previous_Status__c
                                                                                                              FROM Zuora__CustomerAccount__c
                                                                                                              WHERE Id = :billingCanAccountId
                                                                                                              LIMIT 1]);

            String cancellationType;
            // If SubscriptionTermEndDate is in the past/present then send an immediate cancel email else send a standard cancel email.
            // if SubscriptionTermEndDate = Today and Today Day = AccountBillCycleDay then send a standard cancel email.
            if (subscriptionTermEndDate <= System.Date.today()) {
                if (subscriptionTermEndDate == System.Date.today() && System.Date.today().day() == accountBillCycleDay) {
                    cancellationType = 'Standard';
                }
                else {
                    cancellationType = 'Immediate';
                }
            }
            else {
                cancellationType = 'Standard';
            }
            
            Date hardOfferDate;
            if (mapCanBillingAccount.get(billingCanAccountId).Zuora__Account__r.Hard_Offer_Date__c != null) {
                DateTime hardOfferDateTmp = mapCanBillingAccount.get(billingCanAccountId).Zuora__Account__r.Hard_Offer_Date__c;
                hardOfferDate = Date.newInstance(hardOfferDateTmp.year(), hardOfferDateTmp.month(), hardOfferDateTmp.day());
            }
            
            Map<Integer, String> dispatchIdNameValueMap = new Map<Integer, String> {
                Integer.valueOf(DAZNCommunicatorConfig__c.getInstance('DispatchID_User_Cancel').Value__c) => 'Subscription Cancel',
                Integer.valueOf(DAZNCommunicatorConfig__c.getInstance('DispatchID_Payment_Failed_User_Frozen').Value__c) => 'Payment Failed - User Frozen Cancel',
                Integer.valueOf(DAZNCommunicatorConfig__c.getInstance('DispatchID_Immediate_Cancellation').Value__c) => 'Immediate cancellation email',
                Integer.valueOf(DAZNCommunicatorConfig__c.getInstance('DispatchID_Paused_Cancellation').Value__c) => 'Pause & Subscription has been cancelled'
            };

            Integer dispatchID = getDispachId(subscriptionTermEndDate, mapCanBillingAccount.get(billingCanAccountId));
            String emailName = dispatchIdNameValueMap.get(dispatchID);
            Decimal subscriptionAmount = getSubscriptionAmount(subscriptionName, accountCrmId);

            Email_Sync_Queue__c triggeredDispatchEmailQueue = newEmailSyncQueue(
                mapCanBillingAccount.get(billingCanAccountId),
                dispatchID,
                subscriptionAmount,
                defaultPaymentMethodType,
                hardOfferDate,
                subscriptionTermEndDate,
                emailName
            );
            
            if (cancellationType == 'Standard') {
                /* Email Sync Queue record for Standard cancellation emails. */
                triggeredDispatchEmailQueue.Account_Status__c = mapCanBillingAccount.get(billingCanAccountId).Zuora__Account__r.Account_Status__c;
            }
            else if (cancellationType == 'Immediate') {
                /* Email Sync Queue record for Immediate cancellation emails. */
                triggeredDispatchEmailQueue.Account_Status__c = 'Frozen';
            }

            Boolean isDisableSend = (
                mapCanBillingAccount.get(billingCanAccountId).Zuora__Account__r.Disable_immediate_cancel_email__c || // for PD-8928
                mapCanBillingAccount.get(billingCanAccountId).Zuora__Account__r.Disable_transactional_emails__c // for PD-11577
            );
            if (!isDisableSend) {
                insert triggeredDispatchEmailQueue;
            }
        }
    }

    public class CancellactionJSON {
        public String AccountCrmId;
        public String AccountId;
        public String SubscriptionTermEndDate;
        public String DefaultPaymentMethodType;
        public String AccountBillCycleDay;
        public String SubscriptionName;
    }

    public static CancellactionJSON parse(String json) {
        return (CancellactionJSON) System.JSON.deserialize(json, CancellactionJSON.class);
    }

    //////////////////////
    private static String ACTIVE_GRACE = 'Active Grace';
    private static String FREE_TRIAL = 'Free Trial';
    private static String ACTIVE_PAID = 'Active Paid';
    private static String PAUSED = 'Paused';
    private static String FROZEN = 'Frozen';

    private static Integer getDispachId(Date subscriptionTermEndDate, Zuora__CustomerAccount__c account) {
        Integer dispatchID;
        String currentStatus = account.Zuora__Account__r.Account_Status__c;
        String previousStatus = account.Zuora__Account__r.Previous_Status__c;
        if (subscriptionTermEndDate > Date.today()) {
            dispatchID = Integer.valueOf(DAZNCommunicatorConfig__c.getInstance('DispatchID_User_Cancel').Value__c);
        } else {
            if (isCancelationType(currentStatus, previousStatus, ACTIVE_GRACE)) {
                dispatchID = Integer.valueOf(DAZNCommunicatorConfig__c.getInstance('DispatchID_Payment_Failed_User_Frozen').Value__c);
            } else if (isCancelationType(currentStatus, previousStatus, FREE_TRIAL)) {
                dispatchID = Integer.valueOf(DAZNCommunicatorConfig__c.getInstance('DispatchID_Immediate_Cancellation').Value__c);
            } else if (isCancelationType(currentStatus, previousStatus, ACTIVE_PAID)) {
                dispatchID = Integer.valueOf(DAZNCommunicatorConfig__c.getInstance('DispatchID_Immediate_Cancellation').Value__c);
            } else if (isCancelationType(currentStatus, previousStatus, PAUSED)) {
                dispatchID = Integer.valueOf(DAZNCommunicatorConfig__c.getInstance('DispatchID_Paused_Cancellation').Value__c);
            } else {
                dispatchID = Integer.valueOf(DAZNCommunicatorConfig__c.getInstance('DispatchID_User_Cancel').Value__c);
            }
        }
        return dispatchID;
    }

    private static Boolean isCancelationType(String newStatus, String oldStatus, String statusType) {
        return (newStatus == statusType || (oldStatus == statusType && newStatus == FROZEN)) ? true : false;
    }

    private static Email_Sync_Queue__c newEmailSyncQueue(Zuora__CustomerAccount__c account,
                                                         Integer dispatchID,
                                                         Decimal subscriptionAmount,
                                                         String defaultPaymentMethodType,
                                                         Date hardOfferDate,
                                                         Date subscriptionTermEndDate,
                                                         String emailName) {
        return new Email_Sync_Queue__c(
            Account__c = account.Zuora__Account__c,
            Account_Currency__c = account.Zuora__Currency__c,
            All_Email_Preferences__c = account.Zuora__Account__r.All_Email_Preferences__c,
            Dispatch_ID__c = dispatchID,
            First_Name__c = account.Zuora__Account__r.FirstName,
            Last_Name__c = account.Zuora__Account__r.LastName,
            Free_Trial_End_Date__c = null,
            Hard_Offer_Date__c = hardOfferDate,
            Is_Double_Opt_in__c = account.Zuora__Account__r.Is_Double_OptIn__c,
            Notification_Country_Code__c = account.Zuora__Account__r.Notification_Country_Code__c,
            Notification_Language_Code__c = account.Zuora__Account__r.Notification_Language_Code__c,
            Payment_Method_Type__c = defaultPaymentMethodType,
            Person_Email__c = account.Zuora__Account__r.PersonEmail,
            Status__c = 'Not Started',
            Subscription_End_Date__c = subscriptionTermEndDate,
            Sync_Error_Msg__c = null,
            Type_of_Email__c = 'Triggered Dispatch',
            Unsubscribe_Language__c = account.Zuora__Account__r.Notification_Language_Code__c,
            Email_Name__c = emailName,
            Subscription_Amount__c = subscriptionAmount
        );
    }

    private static Decimal getSubscriptionAmount(String subscriptionName, Id accountCrmId) {

        System.debug('LOG : method -> getSubscriptionAmount(subscriptionName = '+ subscriptionName + ', accountCrmId = '+ accountCrmId +' )');
        //Added as part of PD-14237
        if(String.isNotBlank(subscriptionName) && accountCrmId != null){

            List<Zuora__Subscription__c> subscriptions = [
                SELECT SubscriptionAmount__c
                FROM Zuora__Subscription__c 
                WHERE Name = : subscriptionName
                AND Zuora__Account__c = : accountCrmId
            ];

            System.debug('LOG : method -> getSubscriptionAmount() -> subscriptions = ' + subscriptions);

            if(!subscriptions.isEmpty()){
                return subscriptions.get(0).SubscriptionAmount__c;
            }else{
                return 0;
            }
        }
        return 0;

        //Commented as part of PD-14237
        
        /*Decimal subscriptionAmount;
        if (subscriptionName != NULL) {
            
            List<Zuora__Subscription__c> subscr = [
                SELECT Zuora__MRR__c, Zuora__TCV__c, Zuora__TermSettingType__c
                FROM Zuora__Subscription__c 
                WHERE Name = : subscriptionName
                    AND Zuora__Account__c = : accountCrmId
            ];

            if (subscr.size() > 0) {
                if (subscr[0].Zuora__TermSettingType__c == 'TERMED') {
                    subscriptionAmount = subscr[0].Zuora__TCV__c;
                } else {
                    subscriptionAmount = subscr[0].Zuora__MRR__c;
                }
            }
        }
        return subscriptionAmount;*/
    }
}