objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partial</fullName>
                    <default>true</default>
                    <label>Partial</label>
                </value>
                <value>
                    <fullName>Free Trial</fullName>
                </value>
                <value>
                    <fullName>Active Paid</fullName>
                </value>
                <value>
                    <fullName>Active Grace</fullName>
                </value>
                <value>
                    <fullName>Frozen</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Expired Marketing</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Apple</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>All_Email_Preferences__c</fullName>
        <defaultValue>true</defaultValue>
        <label>All Email Preferences</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hard_Offer_date__c</fullName>
        <description>When change the status from frozen to activepaid</description>
        <label>Hard Offer date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>IsReadyToSyncInCommunicator__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag to identify record needs to be sync in communicator.</description>
        <label>IsReadyToSyncInCommunicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Double_OptIn__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to identify user is double opt-in for marketing emails.</description>
        <label>Is Double OptIn</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notification_Country_Code__c</fullName>
        <label>Notification Country Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification_Language_Code__c</fullName>
        <label>Notification Language Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_ID__c</fullName>
        <externalId>true</externalId>
        <label>Partner ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Secondary_Email__c</fullName>
        <label>Secondary Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/BatchTriggerDoubleOptin.cls
global class BatchTriggerDoubleOptin implements Database.Batchable<sObject>, Database.AllowsCallouts{
    String sQuery;
    global Database.QueryLocator start(Database.BatchableContext bc){
      /*  sQuery = 'SELECT Id,Secondary_Email__c,PersonEmail,FirstName,LastName,Account_Status__c,Is_Double_OptIn__c,Partner_ID__c,Type,Notification_Language_Code__c,Notification_Country_Code__c,Hard_Offer_date__c,';
        sQuery += 'All_Email_Preferences__c,IsReadyToSyncInCommunicator__c FROM Account ';  
        sQuery += 'WHERE All_Email_Preferences__c=True AND IsReadyToSyncInCommunicator__c = true AND Type != \'Docomo\' AND Notification_Country_Code__c = \'DE\' AND Account_Status__c=\'Partial\'';  
		*/
        return Database.getQueryLocator(sQuery);
    }
    
    global void execute(Database.BatchableContext BC, List<Account> scope){
        /*List<Account> deenAccounts = new List<Account>();
        List<Account> dedeAccounts = new List<Account>();
        Map<String,List<Account>> mapAccounts = new Map<String,List<Account>>();
        
        if(!Test.isRunningTest()){
            for(Account acc : scope){
                if(acc.Notification_Language_Code__c == 'de')
                    dedeAccounts.add(acc);
                else if(acc.Notification_Language_Code__c == 'en_GB')
                    deenAccounts.add(acc);
            }
            
          if(!deenAccounts.isEmpty())  
            mapAccounts.put('DE_en_GB',deenAccounts)  ;
            if(!dedeAccounts.isEmpty())
            mapAccounts.put('DE_de',dedeAccounts)  ;
            
          //CommunicatorIntegrationHelper.sendDoubleOptInEmail(mapAccounts);
        }*/
    }
    
    global void finish(Database.BatchableContext BC){
        
    }
}