objects/Account.object
<CustomObject>
    <fields>
        <fullName>Partner_ID__c</fullName>
        <externalId>true</externalId>
        <label>Partner ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Partner_Id__c</fullName>
        <formula>IF( Account.Partner_ID__c  &lt;&gt;  null, Account.Partner_ID__c, null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Partner Id</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Customer_Service_Profile_Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Profile_Name__c</fullName>
        <label>Profile Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Customer Service Profile Configuration</label>
</CustomObject>

objects/Partner_Account_Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Partner Account Configuration for all users which are partner users like users coming via Docomo or Amazon Pay etc.</description>
    <fields>
        <fullName>Cancel_Subscription_URL_Large__c</fullName>
        <description>URL for cancel subscription button for Large breakpoint, to be used when the Account status = Active Paid</description>
        <label>Cancel Subscription URL Large</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Cancel_Subscription_URL_Medium__c</fullName>
        <description>URL for cancel subscription button for Medium breakpoint, to be used when the Account status = Active Paid</description>
        <label>Cancel Subscription URL Medium</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Cancel_Subscription_URL_Small__c</fullName>
        <description>URL for cancel subscription button for Small breakpoint, to be used when the Account status = Active Paid</description>
        <label>Cancel Subscription URL Small</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Page_Name__c</fullName>
        <description>To indicate which VF page needs to be displayed for a partner type as specified in the field Partner Type</description>
        <label>Page Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Type__c</fullName>
        <description>The name of the Partner Type for which this my account page is for. This will be the same value as populated on the User type field on the Account.</description>
        <label>Partner Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Payment_History_URL__c</fullName>
        <description>The link for Payment history for DfD</description>
        <label>Payment History URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Subscription_Type_Heading_Text__c</fullName>
        <description>The static text to be shown for Subscription Type Heading</description>
        <label>Subscription Type Heading Text</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_Type_Sub_Heading_Text__c</fullName>
        <description>The static text to be shown for Subscription Type sub Heading</description>
        <label>Subscription Type Sub Heading Text</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Partner Account Configuration</label>
</CustomObject>

objects/TriggerSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Trigger Setting to Turn on and Off</description>
    <fields>
        <fullName>Disable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disable</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Setting</label>
</CustomObject>

classes/EmailMessageExtTest.cls
@isTest
private class EmailMessageExtTest {
	
	@isTest 
	static void testEmailMessageExt() {
		Test.setCurrentPage(Page.Case);
        
        TriggerSetting__c setting = new TriggerSetting__c(
        	Name = 'UpdateAccountTrigger',
            Disable__c = true
        );
		insert setting;
        
        TriggerSetting__c settingTr = new TriggerSetting__c(
        	Name = 'UserTrigger',
            Disable__c = true
        );
		insert settingTr;

		Partner_Account_Configuration__c pac = new Partner_Account_Configuration__c(
            Name = 'Docomo',
            Partner_Type__c = 'Docomo',
            Page_Name__c = 'PartnerAccount.page',
            Subscription_Type_Heading_Text__c = 'Docomo',
            Subscription_Type_Sub_Heading_Text__c = 'Your subscription is managed through your d Account and is payable monthly via your contract with Docomo.',
            Payment_History_URL__c = 'https://www.google.com',
            Cancel_Subscription_URL_Small__c = 'https://www.google.com',
            Cancel_Subscription_URL_Medium__c = 'https://www.google.com',
            Cancel_Subscription_URL_Large__c = 'https://www.google.com'
        );
        insert pac;

		Customer_Service_Profile_Configuration__c conf = new Customer_Service_Profile_Configuration__c();
        conf.Name = '1';
        conf.Profile_Name__c = UserInfo.getProfileId();
        insert conf;

        Account oAccount = SetUpTestData.createPersonAccount('TestFirstName', 'TestLastName','pm2testemail@email.com','Free Trial');
        oAccount.Type = 'Docomo';
        oAccount.Partner_ID__c = '123';
        update oAccount;
        SetUpTestData.createCommunityUser(oAccount.Id, 'pm2testemail@email.com', 'pm1testemail@email.com', 'tstals2','Europe/London','ISO-8859-1','en_US','en_US','TestFName','TestLName',true);
        User oUser = [Select ID,CountryCode from User where Email='pm2testemail@email.com' limit 1];
        
        Case cas = new Case(Origin = 'Self Service   Portal', Subject = 'Unit Test', Type = 'Support', Status = 'Closed', AccountId = oAccount.Id, Description = 'test');
    	insert cas;

        Contact testContact= new Contact();
            testContact.Email='someone@somewhere.com';
            testContact.LastName='lastname';
            testContact.Phone='1234567234';
            testContact.Title='hello';
        insert testContact;


    	EmailMessage[] newEmail = new EmailMessage[0];
    	newEmail.add(new EmailMessage(FromAddress = 'someone@somewhere.com', Incoming = True, ToAddress= 'someone@salesforce.com', Subject = 'Test emailTest emailTest emailTest emailTest emailTest emailTest emailTest emailTest emailTest emailTest emailTest emailTest email', TextBody = 'Test', ParentId = cas.Id)); 
        insert newEmail;

        EmailMessageExt controller = new EmailMessageExt(new ApexPages.StandardController(newEmail[0]));
        System.assert(controller != null);
	}
	
}