objects/Account.object
<CustomObject>
    <fields>
        <fullName>IsReadyToSyncInZuora__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to identify record needs to be sync in Zuora</description>
        <label>IsReadyToSyncInZuora</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>R00N40000001kyLcEAI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__Zuora_Id__c</fullName>
        <description>The Zuora Id (external primary key) of this Billing Account.</description>
        <inlineHelpText>The Zuora Id (external primary key) of this Billing Account.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ZAccountsSynchroniser.cls
/**
* @author Cognizant Technology Solutuions
* @date 04/25/2016
* @description Schedule class to update account information in zuora.
*/
global class ZAccountsSynchroniser implements Database.Batchable<sObject>, Database.AllowsCallouts{
    
    global String query ;
    global Map<Id, Account> mapAccounts ;
    global Map<String,Account> mapAccountsforZuora ;
    global List<Zuora__CustomerAccount__c> zBillingAccounts;
    global Database.QueryLocator start(Database.BatchableContext BC){
        query = 'SELECT id,Name,FirstName,LastName,PersonEmail from Account WHERE IsReadyToSyncInZuora__c = True LIMIT 50'; 
        return Database.getQueryLocator(query);
        
    }
    
    /*
        Description: - execute method for the Batch job, extracts Accounts, finds billing accounts and updates them in Zuora
                       mark the flag of sync to true in salesforce 
    */ 
    global void execute(Database.BatchableContext BC, List<Account> scope){
        
        mapAccounts = new Map<Id, Account>();
         mapAccountsforZuora = new Map<String,Account>();
        for ( Account acc : scope ){
            mapAccounts.put( acc.id, acc );
        }
        if(mapAccounts!=null && !mapAccounts.isEmpty()){
            zBillingAccounts =  [SELECT Zuora__Account__c,Zuora__External_Id__c,Zuora__Zuora_Id__c FROM Zuora__CustomerAccount__c where Zuora__Account__c IN :mapAccounts.keySet()];
            if(zBillingAccounts!=null && !zBillingAccounts.isEmpty()){  
                for (Zuora__CustomerAccount__c zuoCustAcct : zBillingAccounts){
                    mapAccountsforZuora.put(string.valueof(zuoCustAcct.Zuora__Zuora_Id__c),mapAccounts.get(string.valueof(zuoCustAcct.Zuora__Account__c)));
                }
               ZuoraTransactionHelper.updateUserDetailsinZuora(zBillingAccounts,mapAccountsforZuora);
            }
        }
    }
    global void finish(Database.BatchableContext BC){
    }
}