objects/Account.object
<CustomObject>
    <fields>
        <fullName>Viewer_ID__c</fullName>
        <description>Populating the viewer id of User on account</description>
        <label>Viewer ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/DAZNConfiguration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is a configurable custom setting for Forgot Password link</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>Field to store configuration value for specific key</description>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>DAZN Configuration</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Viewer_Id__c</fullName>
        <formula>ExternalID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Viewer Id</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/AccountPlaybackHistoryController.cls
public with sharing class AccountPlaybackHistoryController {

    public AccountPlaybackHistoryController(ApexPages.StandardController sc) {}
    
    /* Methos gets the User.Viewer_Id__c for current Account and redirect to Playback History link
     * 'https://pulse.conviva.com/subscribers/?days=1&filter=97628&viewerId={!User.Viewer_Id__c}''
     */
    public pageReference doInit() {
        String accountId = ApexPages.currentpage().getParameters().get('Id');
        DAZNConfiguration__c configPlaybackHistoryUrl = DAZNConfiguration__c.getValues('CustomerPlaybackHistory');
        String playbackHistoryLink = configPlaybackHistoryUrl != null ? configPlaybackHistoryUrl.Value__c : null;

        if (String.isNotBlank(playbackHistoryLink) && String.isNotBlank(accountId)) {
            List<User> linkedUser = [
                SELECT Id, Viewer_Id__c
                FROM User
                WHERE AccountId =: accountId
                LIMIT 1
            ];
            if (!linkedUser.isEmpty()) {
                playbackHistoryLink += linkedUser[0].Viewer_Id__c;
            }
        }
        if (String.isNotBlank(playbackHistoryLink)) {
            PageReference pageRef = new PageReference(playbackHistoryLink);
            pageRef.setRedirect(true);
            return pageRef;
        } else {
            return null;
        }
	}

}