objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partial</fullName>
                    <default>true</default>
                    <label>Partial</label>
                </value>
                <value>
                    <fullName>Free Trial</fullName>
                </value>
                <value>
                    <fullName>Active Paid</fullName>
                </value>
                <value>
                    <fullName>Active Grace</fullName>
                </value>
                <value>
                    <fullName>Frozen</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Expired Marketing</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Apple</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>All_Email_Preferences__c</fullName>
        <defaultValue>true</defaultValue>
        <label>All Email Preferences</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_transactional_emails__c</fullName>
        <formula>OR( ISPICKVAL( Type, &apos;Docomo&apos; ), Disable_all_transactional_emails__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Disable transaction emails</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Free_Trial_End_Date__c</fullName>
        <label>Free Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hard_Offer_date__c</fullName>
        <description>When change the status from frozen to activepaid</description>
        <label>Hard Offer date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Is_Double_OptIn__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to identify user is double opt-in for marketing emails.</description>
        <label>Is Double OptIn</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notification_Country_Code__c</fullName>
        <label>Notification Country Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification_Language_Code__c</fullName>
        <label>Notification Language Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/DAZNCommunicatorConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This will hold the Dispatch id based on the email and the language</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>Column to store communicator table, column, dispatch, trigger id etc.</description>
        <label>Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DAZN Communicator Config</label>
</CustomObject>

objects/Email_Sync_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Account_Currency__c</fullName>
        <label>Account Currency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>JPY</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>CHF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partial</fullName>
                </value>
                <value>
                    <fullName>Free Trial</fullName>
                </value>
                <value>
                    <fullName>Active Paid</fullName>
                </value>
                <value>
                    <fullName>Active Grace</fullName>
                </value>
                <value>
                    <fullName>Frozen</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Expired Marketing</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Apple</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Email Sync Queues</relationshipLabel>
        <relationshipName>Email_Sync_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>All_Email_Preferences__c</fullName>
        <defaultValue>true</defaultValue>
        <label>All Email Preferences</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dispatch_ID__c</fullName>
        <label>Dispatch ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Free_Trial_End_Date__c</fullName>
        <label>Free Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hard_Offer_Date__c</fullName>
        <label>Hard Offer Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Double_Opt_in__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to identify user is double opt-in for marketing emails.</description>
        <label>Is Double Opt in</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification_Country_Code__c</fullName>
        <label>Notification Country Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification_Language_Code__c</fullName>
        <label>Notification Language Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Method_Type__c</fullName>
        <label>Payment Method Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_Email__c</fullName>
        <label>Person Email</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Details__c</fullName>
        <label>Plan Details</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Retried</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Email__c</fullName>
        <label>Type of Email</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Data Import</fullName>
                </value>
                <value>
                    <fullName>Triggered Dispatch</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unsubscribe_Language__c</fullName>
        <label>Unsubscribe Language</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Email Sync Queue</label>
    <nameField>
        <displayFormat>ESQ-{0000}</displayFormat>
        <label>Email Sync Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Sync Queues</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>R00N40000001kyLcEAI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora__Currency__c</fullName>
        <label>Currency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__PaymentMethod_Type__c</fullName>
        <formula>IF (  ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__Type__c, &quot;ACH&quot;), &quot;ACH&quot;,
   IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__Type__c, &quot;BankTransfer&quot;), &quot;Bank Transfer&quot;, 
       IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__Type__c, &quot;Cash&quot;), &quot;Cash&quot;,     
         IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__Type__c, &quot;Check&quot;), &quot;Check&quot;, 
           IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__Type__c, &quot;CreditCard&quot;), &quot;Credit Card&quot;, 
                IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__Type__c, &quot;CreditCardReferenceTransaction&quot;), &quot;Credit Card  Reference Transaction&quot;, 
                    IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__Type__c, &quot;DebitCard&quot;), &quot;Debit Card&quot;, 
                       IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__Type__c, &quot;Other&quot;), &quot;Other&quot;, 
                                IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__Type__c, &quot;PayPal&quot;), &quot;PayPal&quot;, 
                                   IF ( ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__Type__c, &quot;WireTransfer&quot;), &quot;Wire Transfer&quot;,  &quot;&quot;
                                     )
                                )
                         )
                     )
                )
         )
    )
  )
))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Method Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Zuora_Id__c</fullName>
        <description>The Zuora Id (external primary key) of this Billing Account.</description>
        <inlineHelpText>The Zuora Id (external primary key) of this Billing Account.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__Payment__c.object
<CustomObject>
    <description>Zuora Payment object.  A payment is the money that customers send to pay for charges related to their subscriptions. 
The Payment object holds all of the information about an individual payment, including the payment amount and to which invoices the payment is applied.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The CRM Account that this payment is related to.</description>
        <inlineHelpText>The CRM Account that this payment is related to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Free_Trial_End_Date__c</fullName>
        <label>Free Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__CustomerAccount__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Zuora_Id__c</fullName>
        <description>The Zuora Id (external primary key) of this Subscription.</description>
        <inlineHelpText>The Zuora Id (external primary key) of this Subscription.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UpdateAccount.cls
/** 
* @author Zuora and Cognizant Technology Solutuions
* @date 21/10/2015
* @description Class to update Account status on payment failure.
*/
global without sharing class UpdateAccount {

    /*
        Description: Process successful payment.
    */
    public void processSuccessfulPayment(String accountId){
        //Note: Code changed to mark Account Status = "Active Paid" if payment successfully processed in first attempt.
        if (isProcessSuccessPaymentNeeded(accountId)) {
            createPaymentSuccessfulEmailQueueRecords(accountId); // creates 'Successful Payment Retry' Email Sync Queue record only if Account_Status__c = 'Active Grace'/'Paused' and Disable_transactional_emails__c = false
            setSuccessfulPayment(accountId, true);
            setFirstTrial(accountID, false);
        }
    }
    
    /*
        Description: creates Email Sync Queue records with 'DispatchID_Payment_Successful' dispatch Id.
    */
    public void createPaymentSuccessfulEmailQueueRecords(String accountId) {
        List<Zuora__CustomerAccount__c> anAccount = [
            SELECT Id, Name, Zuora__Currency__c, Zuora__PaymentMethod_Type__c, Zuora__Account__c, Zuora__Account__r.Type,
                Zuora__Account__r.Notification_Country_Code__c, Zuora__Account__r.Notification_Language_Code__c, Zuora__Account__r.PersonEmail,
                Zuora__Account__r.All_Email_Preferences__c,	Zuora__Account__r.FirstName, Zuora__Account__r.LastName, Zuora__Account__r.Hard_Offer_Date__c,
                Zuora__Account__r.Is_Double_OptIn__c
            FROM Zuora__CustomerAccount__c
            WHERE Zuora__Zuora_Id__c = :accountId.trim()
                AND Zuora__Account__r.Disable_transactional_emails__c = false
                AND (Zuora__Account__r.Account_Status__c = 'Active Grace' OR Zuora__Account__r.Account_Status__c = 'Paused') LIMIT 1 // check according to PD-13456
        ];
        if (!anAccount.isEmpty()) {
            Date hardOfferDate;
            if (anAccount[0].Zuora__Account__r.Hard_Offer_Date__c != null) {
                DateTime hardOfferDateTmp = anAccount[0].Zuora__Account__r.Hard_Offer_Date__c;
                hardOfferDate = Date.newInstance(hardOfferDateTmp.year(), hardOfferDateTmp.month(), hardOfferDateTmp.day());
            }
            Email_Sync_Queue__c triggeredDispatchEmailQueue = new Email_Sync_Queue__c(
                Account__c = anAccount[0].Zuora__Account__c,
                Account_Currency__c = anAccount[0].Zuora__Currency__c,
                Account_Status__c = 'Active Paid',
                All_Email_Preferences__c = anAccount[0].Zuora__Account__r.All_Email_Preferences__c,
                Dispatch_ID__c = (!Test.isRunningTest()) ? Integer.valueOf(DAZNCommunicatorConfig__c.getInstance('DispatchID_Payment_Successful').Value__c) : 12345,
                First_Name__c = anAccount[0].Zuora__Account__r.FirstName,
                Last_Name__c = anAccount[0].Zuora__Account__r.LastName,
                Free_Trial_End_Date__c = null,
                Hard_Offer_Date__c = hardOfferDate,
                Is_Double_Opt_in__c = anAccount[0].Zuora__Account__r.Is_Double_OptIn__c,
                Notification_Country_Code__c = anAccount[0].Zuora__Account__r.Notification_Country_Code__c,
                Notification_Language_Code__c = anAccount[0].Zuora__Account__r.Notification_Language_Code__c,
                Payment_Method_Type__c = anAccount[0].Zuora__PaymentMethod_Type__c,
                Person_Email__c = anAccount[0].Zuora__Account__r.PersonEmail,
                Plan_Details__c = 'Active Paid',
                Status__c = 'Not Started',
                Type_of_Email__c = 'Triggered Dispatch',
                Unsubscribe_Language__c = anAccount[0].Zuora__Account__r.Notification_Language_Code__c,
                Email_Name__c = 'Successful Payment Retry'
            );
            insert triggeredDispatchEmailQueue;
        }
    }

    /*
        Description: Process first payment failure.
    */
    public void processFirstTrial(String accountId){
        setFirstTrial(accountID.trim(), true);
        setSuccessfulPayment(accountId.trim(), false);
    }

    /*
        Description: Get first payment failure status.
    */
    public Boolean getFirstTrial(String accountId){
        List<Zuora__CustomerAccount__c> selectedAccount = [select name, id,First_Payment_Trial__c from Zuora__CustomerAccount__c where Zuora__Zuora_Id__c =:accountId LIMIT 1];        
        for(Zuora__CustomerAccount__c acc :selectedAccount){
            return acc.First_Payment_Trial__c;
        }
        return false;
    }

    /*
        Description: Get final payment failure status.
    */
    public Boolean isProcessSuccessPaymentNeeded(String accountId) {
        List<Zuora__CustomerAccount__c> selectedAccount = [
            SELECT Id, Name, Zuora__Account__c, Zuora__Account__r.Account_Status__c
            FROM Zuora__CustomerAccount__c
            WHERE Zuora__Zuora_Id__c =:accountId LIMIT 1
        ];
        if (!selectedAccount.isEmpty()) {
            return (selectedAccount[0].Zuora__Account__r.Account_Status__c == 'Paused' ||
                selectedAccount[0].Zuora__Account__r.Account_Status__c == 'Active Grace' || // condition for PD-12615
                selectedAccount[0].Zuora__Account__r.Account_Status__c == 'Free Trial' // condition for PD-13456
            ) ;
        }
        return false;
    }

    /*
        Description: Mark first payment trial in salesforce.
    */
    public void setFirstTrial(String accountId, Boolean state){
        List<Zuora__CustomerAccount__c> selectedAccount = [select name, id,First_Payment_Trial__c, Zuora__Account__r.Id from Zuora__CustomerAccount__c where Zuora__Zuora_Id__c =:accountId LIMIT 1];
        for(Zuora__CustomerAccount__c acc :selectedAccount){  
            acc.First_Payment_Trial__c=state;                                       
        } 
        update(selectedAccount);
        if(state == true && selectedAccount!= NULL && !selectedAccount.isEmpty()){
            shouldIRun.allow = true; //allow account trigger to execute
            updateAccountStatus(selectedAccount[0].Zuora__Account__r.Id, 'Active Grace');
        }
    }

    /*
        Description: Perform an Immediate Cancellation via Zuora Workflows.
    */
    public String performImmediateCancellation(String accountId) {
        String statusMessage;
        List<Zuora__CustomerAccount__c> selectedAccount = [
            SELECT Id, Name, Zuora__Account__c, Zuora__Account__r.Id
            FROM Zuora__CustomerAccount__c
            WHERE Zuora__Zuora_Id__c =:accountId.trim() LIMIT 1
        ];
        if (!selectedAccount.isEmpty()) {
            // Get account and subscription information for zuora account.
            Zuora__Subscription__c oSubscription;
            List<Account> lstAccount = [
                SELECT ID, Account_Status__c,
                    (SELECT Id, Name
                        FROM Zuora__Subscriptions__r 
                        WHERE Zuora__Status__c = 'Active'
                        ORDER By CreatedDate DESC NULLS LAST)
                FROM Account 
                WHERE Id =:selectedAccount[0].Zuora__Account__c
            ];
            if (lstAccount != NULL && !lstAccount.isEmpty()) {
                List<Zuora__Subscription__c> lstSubscription = lstAccount[0].Zuora__Subscriptions__r;
                if (lstSubscription!= NULL && !lstSubscription.isEmpty()) {
                    oSubscription = lstSubscription[0];
                    
                    String paymentId = '';
                    String cancelDate = CommunityHelper.ConvertDateToString(Date.today(), 'ZouraFormat', 'NA');
                    List<Zuora__Payment__c> paymentRecObj = new List<Zuora__Payment__c>();
                    paymentRecObj = [
                        SELECT Id, Name, Zuora__EXT_ID__c, Zuora__SettledOn__c, Zuora__CreatedDate__c, Zuora__Account__c
                        FROM Zuora__Payment__c
                        WHERE Zuora__Account__c = :lstAccount[0].Id ORDER BY Zuora__CreatedDate__c DESC
                    ];
                    if (paymentRecObj.size() > 0) {
                        if (paymentRecObj[0].Zuora__SettledOn__c != null) {
                            paymentId = paymentRecObj[0].Zuora__EXT_ID__c;
                        } else {
                            statusMessage = System.Label.LS_CancelSubscription_Page_Message_No_Settled_On;
                            ExceptionLoggerHelper.createExceptionLog(UserInfo.getUserId(), 'UpdateAccount', 'setFinalTrial', '', '', System.Label.LS_CancelSubscription_Page_Message_No_Settled_On);
                            return statusMessage;
                        }
                    }
                    // Invocation of Zuora Workflows to do Immediate Cancellation
                    Map<String, String> outputResult = PauseCalloutHelper.runImmediateCancelZuoraWorkflow(oSubscription.Name, cancelDate, paymentId);
                    Boolean isResultSuccess = Boolean.valueOf(outputResult.get('success'));
                    if (isResultSuccess) {
                        shouldIRun.allow = true; //allow account trigger to execute
                        updateAccountStatus(selectedAccount[0].Zuora__Account__r.Id, 'Frozen');
                        statusMessage = 'Success';
                    } else {
                        statusMessage = outputResult.get('message');
                        ExceptionLoggerHelper.createExceptionLog(UserInfo.getUserId(), 'UpdateAccount', 'setFinalTrial', '', '', outputResult.get('message'));
                    }
                } else {
                    statusMessage = 'There are no active subscriptions for this Account';
                    ExceptionLoggerHelper.createExceptionLog(UserInfo.getUserId(), 'UpdateAccount', 'setFinalTrial', '', '', 'There are no active subscriptions for this Account');
                }
            }
        } else {
            statusMessage = 'Billing Account with such ID is not found';
            ExceptionLoggerHelper.createExceptionLog(UserInfo.getUserId(), 'UpdateAccount', 'setFinalTrial', '', '', 'Billing Account with such ID is not found');
        }

        return statusMessage;
    }
    
    /*
        Description: Mark payment successful in salesforce.
    */
    public void setSuccessfulPayment(String accountId,Boolean state){
        List<Zuora__CustomerAccount__c> selectedAccount = [select name, id,Payment_Success__c, Zuora__Account__r.Id, Zuora__Account__r.Account_Status__c from Zuora__CustomerAccount__c where Zuora__Zuora_Id__c =:accountId LIMIT 1];
        for(Zuora__CustomerAccount__c acc :selectedAccount){
            acc.Payment_Success__c=state;                  
        } 
        update(selectedAccount);
        if (state == true && selectedAccount!= NULL && !selectedAccount.isEmpty()) {
            shouldIRun.allow = true; //allow account trigger to execute
            updateAccountStatus(selectedAccount[0].Zuora__Account__r.Id, 'Active Paid');
        }
        if (state != null && state == false) {
            updateAccountStatus(selectedAccount[0].Zuora__Account__r.Id, 'Active Grace');
        }
    }

    /*
        Description: Get Zuora Account id from request xml.
    */
    public String getAccountId(String zuoraCalloutString){
        DOM.Document zuoraCalloutAsDOM = new DOM.Document();
        try {
            zuoraCalloutAsDOM.load(zuoraCalloutString);   
            DOM.XMLNode root = zuoraCalloutAsDOM.getRootElement();        
            if (root.getNodeType() == DOM.XMLNodeType.ELEMENT) {
            if('callout'.equals(root.getName())){
            for (Integer i = 0; i< root.getChildElements().size(); i++ ) {
            //loop through all "parameters" sent
            DOM.XMLNode thisChild = root.getChildElements().get(i);
            if ('AccountID'.equals(thisChild.getAttribute('name', null))) {
            return thisChild.getText();
            }}}}
        } catch (System.XMLException e) {  // invalid XML
            System.debug(e.getMessage());
        }
        return null;
    }

    /*Start part of PD-11138*/
    public String getSubscriptionId(String zuoraCalloutString) {
        DOM.Document zuoraCalloutAsDOM = new DOM.Document();
        try {
            zuoraCalloutAsDOM.load(zuoraCalloutString);   
            DOM.XMLNode root = zuoraCalloutAsDOM.getRootElement();        
            if (root.getNodeType() == DOM.XMLNodeType.ELEMENT) {
            if('callout'.equals(root.getName())){
            for (Integer i = 0; i< root.getChildElements().size(); i++ ) {
            //loop through all "parameters" sent
            DOM.XMLNode thisChild = root.getChildElements().get(i);
            if ('SubscriptionID'.equals(thisChild.getAttribute('name', null))) {
            return thisChild.getText();
            }}}}
        } catch (System.XMLException e) {  // invalid XML
            System.debug(e.getMessage());
        }
        return null;
    }
    /*End part of PD-11138*/
    
    /*
        Description: Get values from request XML.
    */
    public Map<String,String> getValuesFromRequestXML(Map<String,String> attribute, String zuoraCalloutString){
        
        DOM.Document zuoraCalloutAsDOM = new DOM.Document();
        try {
            zuoraCalloutAsDOM.load(zuoraCalloutString);   
            
            DOM.XMLNode root = zuoraCalloutAsDOM.getRootElement();   
            
            if (root.getNodeType() == DOM.XMLNodeType.ELEMENT) {
                if('callout'.equals(root.getName())){
                    for (Integer i = 0; i< root.getChildElements().size(); i++ ) {
                    //loop through all "parameters" sent
                        DOM.XMLNode thisChild = root.getChildElements().get(i);
                        if (attribute.containsKey((thisChild.getAttribute('name', null)))) {
                             attribute.put(thisChild.getAttribute('name', null), thisChild.getText());
                        }
                        
                    }
                    
                }
                
            }
        } catch (System.XMLException e) {  // invalid XML
            System.debug(e.getMessage());
        }
        return attribute;
    }
    
    /*
        Description: Method to update Account status based on payment status.
    */
    private void updateAccountStatus(Id sAccountId, string sStatus){
        List<Account> lstAccount = [Select Id, Account_Status__c, PauseScheduled__c, Pause_From__c, Pause_Until__c from Account where ID=:sAccountId LIMIT 1];
        if(lstAccount!= NULL && !lstAccount.isEmpty()){
            Account oAccount = lstAccount[0];
            oAccount.Pause_From__c = null;
            oAccount.Pause_Until__c = null;
            oAccount.Pause_Scheduled_Time__c = null;
            oAccount.Account_Status__c = sStatus;
            update oAccount;
        }
    }

    /*
        Description: Method to update Account status based on payment status. PD-9349
    */
    public void TransitionAccountToFrozen(String accountId)
    {   
        List<Zuora__CustomerAccount__c> selectedAccount = [select name, id,Payment_Success__c, Zuora__Account__r.Id from Zuora__CustomerAccount__c where Zuora__Zuora_Id__c =:accountId LIMIT 1];
        if(selectedAccount!= NULL && !selectedAccount.isEmpty()){
            /*start part of PD-11138*/
            List<Zuora__Subscription__c> subscroptions = [SELECT Zuora__Account__c, Zuora__Status__c 
                                                        FROM Zuora__Subscription__c 
                                                        WHERE Zuora__Account__c = :selectedAccount[0].Zuora__Account__r.Id 
                                                            AND Zuora__Status__c = 'Active'];
            /*end part of PD-11138*/
            if (subscroptions.isEmpty()) {
                shouldIRun.allow = true; //allow account trigger to execute
                updateAccountStatus(selectedAccount[0].Zuora__Account__r.Id, 'Frozen');
            }
            
        }
    }
}