objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partial</fullName>
                    <default>true</default>
                    <label>Partial</label>
                </value>
                <value>
                    <fullName>Free Trial</fullName>
                </value>
                <value>
                    <fullName>Active Paid</fullName>
                </value>
                <value>
                    <fullName>Active Grace</fullName>
                </value>
                <value>
                    <fullName>Frozen</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Expired Marketing</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Apple</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DAZN_Id__c</fullName>
        <externalId>true</externalId>
        <label>DAZN Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Partner_ID__c</fullName>
        <externalId>true</externalId>
        <label>Partner ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Partner_Registration_Status__c</fullName>
        <label>Partner Registration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secondary_Email__c</fullName>
        <label>Secondary Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/DAZN_User_Device_Feed__c.object
<CustomObject>
    <fields>
        <fullName>DAZN_User_feed__c</fullName>
        <label>DAZN User Feed</label>
        <referenceTo>DAZNUserFeed__c</referenceTo>
        <relationshipLabel>DAZN User Devices Feed (DAZN User Feed)</relationshipLabel>
        <relationshipName>DAZN_User_Devices_Feed</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_of_Registration__c</fullName>
        <description>Date of registration of the user device</description>
        <label>Date of Registration</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Device_Id__c</fullName>
        <description>Unique ID identifying the device</description>
        <label>Device Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DAZN User Device Feed</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>DAZN  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DAZN User Devices Feed</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/DAZNUserFeed__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>User_Feed</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Frozen</fullName>
                </value>
                <value>
                    <fullName>Active Paid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Alias__c</fullName>
        <label>Alias</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BillingCountryCode__c</fullName>
        <label>BillingCountryCode</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DAZN_Id__c</fullName>
        <description>Unique Identifier created by Massive to identify the user</description>
        <label>DAZN Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Preferences__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Marketing preferences as entered by user during sign up, for Docomo users this is always set to TRUE.</description>
        <label>Email Preferences</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>The email of the customer. For partner users like Docomo, this email will be &lt;partner Id&gt;@dazn.com.
For default DAZN subscribers, it will be the email they have used to sign up.</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the user if the user has completed sign up to DAZN                                                                                                                                                                                                                                                                                                                                        , empty otherwise.</description>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LanguageLocaleKey__c</fullName>
        <label>LanguageLocaleKey</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ja</fullName>
                </value>
                <value>
                    <fullName>en_GB</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocaleSidKey__c</fullName>
        <label>LocaleSidKey</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ja_JP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Id__c</fullName>
        <externalId>true</externalId>
        <label>Partner Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Registration_status__c</fullName>
        <label>Partner Registration status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secondary_Email__c</fullName>
        <description>Email to be used for notifying the customer about information related to their DAZN account. For default DAZN subscribers, this will be the same as Email field. 
For Docomo users, this will be the email they filled in during sign up to DAZN.</description>
        <label>Secondary Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>TimeZoneSidKey__c</fullName>
        <label>TimeZoneSidKey</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Asia/Tokyo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ViewerId__c</fullName>
        <label>ViewerId</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>DAZN User Feed</label>
    <nameField>
        <displayFormat>DFD-{0000}</displayFormat>
        <label>User feed Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DAZN User Feed</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ViewerId__c</fullName>
        <externalId>true</externalId>
        <label>ViewerId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/DAZNUserDeviceFeedTriggerHandlerTest.cls
/**
* @author Cognizant Technology Solutuions
* @date 11/28/2016
* @description Test class to cover DAZNUserDeviceFeedTriggerHandler functionality.
*/
@istest
public class DAZNUserDeviceFeedTriggerHandlerTest{
    @testSetup /*  calling CreateTestDataforUnitTest */  
    public static void getCommunityUsersTestData(){
        CreateTestDataforUnitTest.triggerSettings();
        CreateZuoraDataforUnitTest.createZuoraDeatils();
        CreateTestDataforUnitTest.createTestcustomsetting();
        CreateTestDataforUnitTest.createTestUserDevices();
    }
    public static testmethod void testCreateAccount(){ 
        Account oAccount = SetUpTestData.createPersonAccount('TestFirstName', 'TestLastName','testemail@email.com','Free Trial');
        DAZNUserFeed__c userdetails=new  DAZNUserFeed__c();
        userdetails.First_Name__c='firsttest';
        userdetails.Last_Name__c='lasttest';
        userdetails.Email__c='test2344@test.com';
        userdetails.BillingCountryCode__c='JP';
        userdetails.LanguageLocaleKey__c='ja';
        userdetails.Email_Preferences__c=true;
        userdetails.Secondary_Email__c='test222@test.com';
        userdetails.Alias__c = 'tt23';
        userdetails.TimeZoneSidKey__c = 'Asia/Tokyo';
        userdetails.LocaleSidKey__c = 'ja_JP';
        userdetails.Account_Status__c='Active Paid';
        userdetails.Partner_Registration_status__c='complete';
        userdetails.Partner_Id__c='asdghh243';
		userdetails.AccountId__c = oAccount.id;
        userdetails.ViewerId__c = '222121223';
        userdetails.DAZN_Id__c = '2323223';
        insert userdetails;
        system.assertNotEquals(null, userdetails);        
    	List<Profile> profile=[select Id,Name from profile where Name='External User' limit 1];
        system.assert(profile.size()>0);
        List<User> oUser = [Select Id, Name, UserName,Alias,Country,profileId,LanguageLocaleKey from User where profileId=:profile[0].id and IsActive=True limit 1];
        system.assertNotEquals(null, oUser);
        System.RunAs(oUser[0]){
            list <DAZN_User_Device_Feed__c> listOfDaznUserDev = new  list <DAZN_User_Device_Feed__c>();        
            for(Integer i=0;i<5;i++) {
                DAZN_User_Device_Feed__c  DazUserDevFeedObj = new DAZN_User_Device_Feed__c ();
                DazUserDevFeedObj.Date_of_Registration__c = system.today();
                DazUserDevFeedObj.Device_Id__c = '12345';
                DazUserDevFeedObj.DAZN_User_feed__c =userdetails.id;
                listOfDaznUserDev.add(DazUserDevFeedObj);
            	}
            insert listOfDaznUserDev;
        }
       
        
    }
  
  
  
  
        }