objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partial</fullName>
                    <default>true</default>
                    <label>Partial</label>
                </value>
                <value>
                    <fullName>Free Trial</fullName>
                </value>
                <value>
                    <fullName>Active Paid</fullName>
                </value>
                <value>
                    <fullName>Active Grace</fullName>
                </value>
                <value>
                    <fullName>Frozen</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Expired Marketing</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Apple</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>All_Email_Preferences__c</fullName>
        <defaultValue>true</defaultValue>
        <label>All Email Preferences</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsReadyToSyncInZuora__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to identify record needs to be sync in Zuora</description>
        <label>IsReadyToSyncInZuora</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Double_OptIn__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to identify user is double opt-in for marketing emails.</description>
        <label>Is Double OptIn</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notification_Country_Code__c</fullName>
        <label>Notification Country Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/DAZNConfiguration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is a configurable custom setting for Forgot Password link</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>Field to store configuration value for specific key</description>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>DAZN Configuration</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>All_Email_Preferences__c</fullName>
        <defaultValue>true</defaultValue>
        <label>All Email Preferences</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/AnonymizerUserTest.cls
@isTest
private class AnonymizerUserTest {

	private static final String EMAIL_PATTERN = '@testEmailPattern.com';
	private static final String STR_ENV_NAME = 'testVal';
	
	@testSetup static void generateTestData() {
		CreateTestDataforUnitTest.triggerSettings();

		DAZNConfiguration__c daznConfig = new DAZNConfiguration__c(
        	Name = 'EnviornmentName',
        	Value__c = STR_ENV_NAME
        );
        insert daznConfig;

        Profile profileForTestUser = [Select Id, Name From Profile Where Name = 'Customer Community User' LIMIT 1];

        List<Account> accountsForTestUsers = new List<Account>();
        accountsForTestUsers.add(
        	new Account(
        		FirstName = 'firstName1',
                LastName = 'lastName1',
                PersonEmail = 'email1' + EMAIL_PATTERN,
                Notification_Country_Code__c = 'DE',
                All_Email_Preferences__c = true,
                Account_Status__c = 'Active Paid',
                Is_Double_OptIn__c = true,
                IsReadyToSyncInZuora__c = true
        	)
        );
        insert accountsForTestUsers;

        String personContactId = [Select Id, PersonContactId From Account].PersonContactId;

        List<User> usersForTest = new List<User>();
        usersForTest.add(
        	new User(
        		FirstName = 'firstName1',
        		LastName = 'lastName1',
        		Email = 'email1' + EMAIL_PATTERN,
        		UserName = 'test@username1.com',
        		Alias = 'LiveSp1',
        		TimeZoneSidKey = 'Europe/London',
        		LocaleSidKey = 'de_DE',
        		EmailEncodingKey = 'ISO-8859-1',
        		ProfileId = profileForTestUser.Id,
        		LanguageLocaleKey = 'en_GB',
        		ContactId = personContactId
        	)
        );
        insert usersForTest;
	}
	
	@isTest static void testBatch() {
		String testUserEmail = 'email1' + EMAIL_PATTERN;
		User testUserBefore = [Select Id, FirstName, LastName, Username, Email, IsActive From User Where Email = :testUserEmail LIMIT 1];

		AnonymizerUser anonymizerUser = new AnonymizerUser(EMAIL_PATTERN);

		Test.startTest();
		Database.executeBatch(anonymizerUser, 1000);
		Test.stopTest();

		User testUserAfter = [Select Id, FirstName, LastName, Username, Email, IsActive From User Where Id = :testUserBefore.Id LIMIT 1];
		
		String testUserAfterFirstName = 'anonymous[' + STR_ENV_NAME + ']' + testUserAfter.Id;
		String testUserAfterLastName = 'anonymous[' + STR_ENV_NAME + ']' + testUserAfter.Id;
		String testUserAfterUsername = ('anonymous[' + STR_ENV_NAME + ']' + testUserAfter.Id + '@livesport.com').toLowerCase();
		String testUserAfterEmail = ('anonymous' + STR_ENV_NAME + testUserAfter.Id + '@livesport.com').toLowerCase();

		System.assertEquals(testUserAfterFirstName, testUserAfter.FirstName);
		System.assertEquals(testUserAfterLastName, testUserAfter.LastName);
		System.assertEquals(testUserAfterUsername, testUserAfter.Username);
		System.assertEquals(testUserAfterEmail, testUserAfter.Email);
		System.assertEquals(false, testUserAfter.IsActive);
	}
	
}