objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partial</fullName>
                    <default>true</default>
                    <label>Partial</label>
                </value>
                <value>
                    <fullName>Free Trial</fullName>
                </value>
                <value>
                    <fullName>Active Paid</fullName>
                </value>
                <value>
                    <fullName>Active Grace</fullName>
                </value>
                <value>
                    <fullName>Frozen</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Expired Marketing</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Apple</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PauseScheduled__c</fullName>
        <formula>IF( 
ISNULL( Pause_From__c ), 
false, 
IF( 
Pause_From__c &gt; TODAY(), 
true, 
false 
) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PauseScheduled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pause_Until__c</fullName>
        <label>Pause Until</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/NextChargeDateSectionController.cls
public class NextChargeDateSectionController {
    
    public String nextChargeDateString { get; set; }
    
    public NextChargeDateSectionController(ApexPages.StandardController controller) {
        Account acc = [Select Id, Pause_Until__c, Account_Status__c, PauseScheduled__c From Account Where Id = :controller.getRecord().Id];
        DateTime nextChargeDate = ZuoraTransactionHelper.getRatePlanChargeChargedThroughDateByAccountId(acc.Id);
        if (acc.Account_Status__c.equalsIgnoreCase('Paused') || acc.PauseScheduled__c) {
        	nextChargeDate = acc.Pause_Until__c;
        }
        nextChargeDateString = (nextChargeDate != null) ? nextChargeDate.format('dd/MM/yyyy') : null;
    }
    
}