objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partial</fullName>
                    <default>true</default>
                    <label>Partial</label>
                </value>
                <value>
                    <fullName>Free Trial</fullName>
                </value>
                <value>
                    <fullName>Active Paid</fullName>
                </value>
                <value>
                    <fullName>Active Grace</fullName>
                </value>
                <value>
                    <fullName>Frozen</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Expired Marketing</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Apple</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>All_Email_Preferences__c</fullName>
        <defaultValue>true</defaultValue>
        <label>All Email Preferences</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Double_OptIn__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to identify user is double opt-in for marketing emails.</description>
        <label>Is Double OptIn</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>All_Email_Preferences__c</fullName>
        <defaultValue>true</defaultValue>
        <label>All Email Preferences</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>R00N40000001kyLcEAI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RefundProcessor.cls
@RestResource(urlMapping='/ProcessRefund/*')
global class RefundProcessor {
    /*
Main method - to handle the chargeback callout from Zuora.
*/
    @HttpPost  
    global static String handleRefund() {
        String accountID;
        String requestString;
        String reasonCode;
        String paymentId;
        String lastInvoiceDate ;
        UpdateAccount updateAccount;
        final String CHARGEBACK = 'Chargeback';
        
        
        Map<String,String> mapAttributes = new Map<String,String> { 'AccountId' => '', 'RefundReasonCode' => '', 'PaymentID' => '', 'AccountLastInvoiceDate' => ''};
            updateAccount = new UpdateAccount();
        RestRequest req = RestContext.request;
        requestString = req.requestBody.toString();
        mapAttributes = updateAccount.getValuesFromRequestXML(mapAttributes,requestString);
        
        accountID = mapAttributes.get('AccountId');
        reasonCode = mapAttributes.get('RefundReasonCode');
        paymentId = mapAttributes.get('PaymentID');
        lastInvoiceDate = mapAttributes.get('AccountLastInvoiceDate');
        
        String[] invoiceDate = lastInvoiceDate.split('-',3);
        
        if(reasonCode == CHARGEBACK){
            
            if(!Test.isRunningTest()){
                ZuoraTransactionHelper.handleChargeBacks (paymentId , Date.parse(invoiceDate[2]+'/'+invoiceDate[1]+'/'+invoiceDate[0]));
            }
            updateAccount(accountID);
            
        }
        
        return accountID;
    }
    
    /*Update the account status to Blocked, since the User has been cancelled in zuora*/
    private static void updateAccount(String billingAccountId){
        List<Zuora__CustomerAccount__c> lstAccount = [Select Zuora__Account__c from Zuora__CustomerAccount__c where Zuora__External_Id__c = :billingAccountId];
        if(lstAccount != null &&  !lstAccount.isEmpty()){
            Account account = new Account (Id = lstAccount[0].Zuora__Account__c, Account_Status__c = 'Blocked', All_Email_Preferences__c = false, Is_Double_OptIn__c = false);
            update account;
        }
    }
    
    
}