objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partial</fullName>
                    <default>true</default>
                    <label>Partial</label>
                </value>
                <value>
                    <fullName>Free Trial</fullName>
                </value>
                <value>
                    <fullName>Active Paid</fullName>
                </value>
                <value>
                    <fullName>Active Grace</fullName>
                </value>
                <value>
                    <fullName>Frozen</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Expired Marketing</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Apple</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LastInvoiceDate__c</fullName>
        <label>LastInvoiceDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Notification_Country_Code__c</fullName>
        <label>Notification Country Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification_Language_Code__c</fullName>
        <label>Notification Language Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Type_Last_Digits_and_Expiry_Date__c</fullName>
        <label>Payment Type,Last Digits and Expiry Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retrieve_Email__c</fullName>
        <externalId>true</externalId>
        <label>Retrieve Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/DAZN_Help_Redirect__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>DAZN Help Redirect settings use to redirect the respective page</description>
    <fields>
        <fullName>CountryISOCode__c</fullName>
        <label>CountryISOCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsDefaultCountry__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefaultCountry</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>DAZN Help Redirect</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Notification_Language_Code__c</fullName>
        <label>Notification Language Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Retrive_Email__c</fullName>
        <formula>LOWER(Zuora__Account__r.FirstName) &amp;&quot;-&quot;&amp; LOWER(Zuora__Account__r.LastName) &amp; &quot;-&quot; &amp; IF( OR( Zuora__Default_Payment_Method__r.Zuora__BankTransferType__c == &quot;SEPA&quot;,Zuora__Default_Payment_Method__r.Zuora__BankTransferType__c == &quot;IBAN&quot;), RIGHT( Zuora__Default_Payment_Method__r.Zuora__BankTransferAccountNumber__c , 4), RIGHT(Zuora__CreditCard_Number__c, 4))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Retrive Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__LastInvoiceDate__c</fullName>
        <label>Last Invoiced</label>
        <type>Date</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BillingAccountTriggerTest.cls
/* This test class will cover the code coverage for BillingAccountTriggerHandler*/
@isTest(seeAllData = false)
public class BillingAccountTriggerTest{

    @testSetup
    public static void setUpTestData() {
        List<DAZN_Help_Redirect__c> dhr = new List<DAZN_Help_Redirect__c>();
        dhr.add(new DAZN_Help_Redirect__c(
            Name = 'Japan',
            Country__c = 'Japan',
            CountryISOCode__c = 'JP',
            IsDefaultCountry__c = false,
            Language__c = 'ja'
        ));
        dhr.add(new DAZN_Help_Redirect__c(
            Name = 'Japan en',
            Country__c = 'Japan',
            CountryISOCode__c = 'JP',
            IsDefaultCountry__c = false,
            Language__c = 'en'
        ));
        dhr.add(new DAZN_Help_Redirect__c(
            Name = 'Germany',
            Country__c = 'Germany',
            CountryISOCode__c = 'DE',
            IsDefaultCountry__c = false,
            Language__c = 'en'
        ));
        dhr.add(new DAZN_Help_Redirect__c(
            Name = 'Germany_default',
            Country__c = 'Germany',
            CountryISOCode__c = 'DE',
            IsDefaultCountry__c = true,
            Language__c = 'de'
        ));
        insert dhr;

        Account oAccount = new Account();
        oAccount.FirstName = 'strFirstName';
        oAccount.LastName = 'strLastName';
        oAccount.PersonEmail = 'test@test.com';
        oAccount.Account_Status__c = 'Free Trial';
        oAccount.Notification_Country_Code__c = 'ja_JP';
        oAccount.Notification_Language_Code__c = 'ja';
        insert oAccount;SetUpTestData.triggerSettings();
    }
    
    @isTest 
    static void testUpdate() {
        
        //Account oAccount = [SELECT Id, FirstName, LastName, Notification_Country_Code__c, Notification_Language_Code__c, Payment_Type_Last_Digits_and_Expiry_Date__c FROM Account];1
        Account oAccount = new Account();
        oAccount.FirstName = 'strFirstName';
        oAccount.LastName = 'strLastName';
        oAccount.PersonEmail = 'test123@test.com';
        oAccount.Account_Status__c = 'Free Trial';
        oAccount.Notification_Country_Code__c = 'JP';
        oAccount.Notification_Language_Code__c = 'ja';
        insert oAccount;
        User oCSUser = SetUpTestData.createCustomerServiceTeamManagementUser(null, 'testcsagent@email.com', 'testcsagent@email.com', 'tstals','Europe/London','ISO-8859-1','en_US','en_US','TestFNameCS','TestLNameCS',true);
        User oUser = SetUpTestData.createCommunityUser(oAccount.Id, 'testemail@email.com', 'testusername1@email.com', 'tstals','Europe/London','ISO-8859-1','en_US','en_US','TestFName','TestLName',true); 
        Zuora__CustomerAccount__c bAccount;
        System.runAs(oCSUser) {
            Test.startTest();
                bAccount = SetUpTestData.createBillingAccount(oAccount.Id,'test billing account', 'Active', 'A00000073', 'testbill Name', 'Germany', 'test bill name', 'Credit Card', 'batch2', 'USD','1st of the month');
            Test.stopTest();

        }
        
        Account oAccountAfter = [SELECT Id, Notification_Country_Code__c, LastInvoiceDate__c FROM Account WHERE Id =: oAccount.Id];
        Zuora__CustomerAccount__c testBillingAccount = [Select Id, Zuora__LastInvoiceDate__c From Zuora__CustomerAccount__c Where Id = :bAccount.Id];
        System.assertEquals('DE', oAccountAfter.Notification_Country_Code__c);
        System.assertEquals(testBillingAccount.Zuora__LastInvoiceDate__c, oAccountAfter.LastInvoiceDate__c);
    }

    @isTest
    static void testUpdateAccountRetrieveEmail() {
        Account oAccount = [SELECT Id FROM Account];
        Test.startTest();
            Zuora__CustomerAccount__c bAccount = SetUpTestData.createBillingAccount(oAccount.Id,'test billing account', 'Active', 'A00000073', 'testbill Name', 'Germany', 'test bill name', 'Credit Card', 'batch2', 'USD','1st of the month');
        Test.stopTest();
        Account oAccountAfter = [SELECT Id, Retrieve_Email__c, Notification_Country_Code__c FROM Account WHERE Id =: oAccount.Id];
        Zuora__CustomerAccount__c billingAccountAfter = [SELECT Id, Retrive_Email__c FROM Zuora__CustomerAccount__c WHERE Id =: bAccount.Id];
        System.assertEquals(billingAccountAfter.Retrive_Email__c, oAccountAfter.Retrieve_Email__c);
    }

    @isTest
    static void testAccountRetrieveEmailNotUpdated() {
        Account oAccount = [SELECT Id, FirstName FROM Account];
        
        Test.startTest();
        Zuora__CustomerAccount__c bAccount = SetUpTestData.createBillingAccount(oAccount.Id, 'test billing account', 'Active', 'A00000073', 'testbill Name', 'Germany', 'test bill name', 'Credit Card', 'batch2', 'USD','1st of the month');
        
        Account oAccountAfterInsert = [SELECT Id, FirstName, Retrieve_Email__c, Notification_Country_Code__c FROM Account WHERE Id =: oAccount.Id];
        Zuora__CustomerAccount__c billingAccountAfterInsert = [SELECT Id, Name, Retrive_Email__c FROM Zuora__CustomerAccount__c WHERE Id =: bAccount.Id];
        
        oAccount.FirstName = 'strFirstNameUpdated';
        update oAccount;
        bAccount.Name = 'test billing account updated';
        update bAccount;

        Account oAccountAfterUpdate = [SELECT Id, FirstName, Retrieve_Email__c, Notification_Country_Code__c FROM Account WHERE Id =: oAccount.Id];
        Zuora__CustomerAccount__c billingAccountAfterUpdate = [SELECT Id, Name, Retrive_Email__c FROM Zuora__CustomerAccount__c WHERE Id =: bAccount.Id];
        Test.stopTest();

        System.assertEquals(billingAccountAfterInsert.Retrive_Email__c, oAccountAfterInsert.Retrieve_Email__c);
        //System.assertNotEquals(billingAccountAfterUpdate.Retrive_Email__c, oAccountAfterUpdate.Retrieve_Email__c);
    }

}