objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partial</fullName>
                    <default>true</default>
                    <label>Partial</label>
                </value>
                <value>
                    <fullName>Free Trial</fullName>
                </value>
                <value>
                    <fullName>Active Paid</fullName>
                </value>
                <value>
                    <fullName>Active Grace</fullName>
                </value>
                <value>
                    <fullName>Frozen</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Expired Marketing</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Apple</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AuthKey__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>This field is updated when the user choose to sign out of all the devices.</description>
        <label>AuthKey</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Cancelled_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelled Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Partner_ID__c</fullName>
        <externalId>true</externalId>
        <label>Partner ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Submitted_for_cancellation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Submitted for cancellation</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Partner_Id__c</fullName>
        <formula>IF( Account.Partner_ID__c  &lt;&gt;  null, Account.Partner_ID__c, null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Partner Id</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Zuora__Payment__c.object
<CustomObject>
    <description>Zuora Payment object.  A payment is the money that customers send to pay for charges related to their subscriptions. 
The Payment object holds all of the information about an individual payment, including the payment amount and to which invoices the payment is applied.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The CRM Account that this payment is related to.</description>
        <inlineHelpText>The CRM Account that this payment is related to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__CreatedDate__c</fullName>
        <description>The date when the payment was created in Zuora system.</description>
        <inlineHelpText>The date when the payment was created in Zuora system.</inlineHelpText>
        <label>Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Zuora__EXT_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>External Id For Payment object,   Represents a Zuora Payment object Id</description>
        <externalId>true</externalId>
        <label>Unique External Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <description>The payment ID in Zuora system.</description>
        <externalId>true</externalId>
        <label>External ID(Deprecated)</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__SettledOn__c</fullName>
        <description>The date when the payment was settled in the payment processor.</description>
        <inlineHelpText>The date when the payment was settled in the payment processor.</inlineHelpText>
        <label>Settled On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <description>The status of the payment in the Zuora system. The value depends on the type of payment.</description>
        <inlineHelpText>The status of the payment in the Zuora system. The value depends on the type of payment.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Posted</fullName>
                </value>
                <value>
                    <fullName>Voided</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This field holds the Zuora object ID, and is used as external ID for data synchronization between Salesforce and Zuora.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__NextChargeDate__c</fullName>
        <label>Next Charge Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__NextRenewalDate__c</fullName>
        <label>Next Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__SubscriptionEndDate__c</fullName>
        <description>This is when the subscription ends. This is always equal to term end date, unless the subscription has been cancelled. If the subscription has been cancelled, this is set to the cancellation date.</description>
        <label>Subscription End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__SubscriptionStartDate__c</fullName>
        <description>The date when the subscription term starts. This is equal to the term start date if the subscription is on its initial term. Otherwise, it is the original term start date if the subscription has renewed.</description>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BlockUserController.cls
/**
* @author Cognizant Technology Solutuions
* @date 20/04/2016
* @description Block User  class
*/

global with sharing class BlockUserController {

    public String refundstatus { get; set; }
    public Account acc { get; set; }
    public String sAccountId { get; set; }
    public String Comment { get; set; }
    public User logInUser;
    public String sEffectiveDate = null;
    public boolean bShowPanel { get; set; }
    public boolean navigateError { get; set; }
    public String typeOfAccount { get; set; }
    
    /*Constructor*/
    public BlockUserController() {
        navigateError = false;
        if (ApexPages.CurrentPage() != null) {
            sAccountId = ApexPages.CurrentPage().getparameters().get('aId');
            //Validation on Account Id, if in case invalid Account id setting navigate Error flag to true *PD-7932*. 
            if (sAccountId != null  && sAccountId != '' && String.escapeSingleQuotes(sAccountId).isAlphanumeric()) {
                if (Schema.sObjectType.User.fields.AccountID.isAccessible()) {
                    List<User> userResults = [
                        SELECT Name, FirstName,LastName,Email,UserName,AccountID, CountryCode, Country, contactId, LanguageLocaleKey
                        FROM User
                        WHERE AccountID=:sAccountId
                    ]; 
                    if (userResults != null && userResults.size() > 0) {
                        logInUser = userResults[0];
                    } else {
                        reportErrorWithoutReturn(System.Label.LS_BlockUser_MissingInfo);
                    }
                }
                
                List<Account>  accList = [
                    SELECT Id, Firstname, LastName, Account_Status__c, Cancelled_Account__c, OwnerId, Type, Partner_ID__c,
                       (SELECT Name, Zuora__Status__c, Zuora__NextRenewalDate__c, Zuora__External_Id__c,Zuora__NextChargeDate__c, Zuora__SubscriptionEndDate__c 
                        FROM Zuora__Subscriptions__r
                        WHERE Zuora__Status__c = 'Active'
                        ORDER BY Zuora__SubscriptionStartDate__c DESC NULLS LAST)
                    FROM Account WHERE id = :sAccountId
                ];
                if (accList.size() > 0) {
                    acc = accList[0];
                    bShowPanel = true;
                } else {
                    reportErrorWithoutReturn(System.Label.LS_BlockUser_MissingInfo);
                }
            } else {
                reportErrorWithoutReturn(System.Label.LS_BlockUser_MissingInfo);
            }
        }
        
    }
    
    webservice static String saveWeb(Id accId) {
        BlockUserController ctrl = new BlockUserController();
        String result;
        ctrl.typeOfAccount = 'Apple';
        List<Account>  accList = [select id ,Firstname,LastName,Account_Status__c,Cancelled_Account__c,OwnerId,Type, Partner_ID__c, (SELECT Name, Zuora__Status__c, Zuora__NextRenewalDate__c,Zuora__External_Id__c,Zuora__NextChargeDate__c, Zuora__SubscriptionEndDate__c 
                                                                                                                                     FROM Zuora__Subscriptions__r Where Zuora__Status__c='Active'
                                                                                                                                     Order By Zuora__SubscriptionStartDate__c
                                                                                                                                     DESC NULLS LAST) from Account where id =: accId];
        
        List<User> userResults = [select Name, FirstName,LastName,Email,UserName,AccountID, CountryCode, Country, 
                                  contactId ,LanguageLocaleKey from User  where AccountID=:accId]; 
        ctrl.sAccountId = accId;

        if (userResults != null && userResults.size() > 0) {
            ctrl.logInUser = userResults[0];
            
        }
        
        if(accList.size() > 0) {
            ctrl.acc = accList[0];
        }
        
        result = JSON.serialize(String.valueOf(ctrl.save())) ;
        return result;
    }
    
    /*
      Method to do the Cancellation, User blocking
    */
    public PageReference save() {
        String cancellationType;
        Zuora__Subscription__c oSubscription;
        if (acc != null && !navigateError) {
            if (acc.Zuora__Subscriptions__r != null && acc.Zuora__Subscriptions__r.size() > 0) {
                oSubscription = acc.Zuora__Subscriptions__r[0];
            }
            
            if (refundstatus == System.Label.LS_Block_User_Without_Refund) {
                if (acc.Account_Status__c == 'Free trial') {
                    cancellationType = 'Standard';
                } else if (acc.Account_Status__c == 'Active Paid' || acc.Account_Status__c == 'Active Grace') {
                    cancellationType = 'Immediate';
                }
            } else {
                cancellationType = 'Immediate';
            }
            
            Map<String, String> outputResult = new Map<String, String>();
            
            if (cancellationType == 'Standard') {
                if (acc.Zuora__Subscriptions__r != null && acc.Zuora__Subscriptions__r.size() > 0) {
                    /*Check Account has at least one subscription and the subscription is active*/
                    if (oSubscription.Zuora__Status__c == 'Active') {
                        //added as part of PD-13271
                        Date ratePlanChargeChargedThroughDate = ZuoraTransactionHelper.getRatePlanChargeChargedThroughDateByAccountId(sAccountID);
                        if (ratePlanChargeChargedThroughDate != null) {
                            sEffectiveDate = CommunityHelper.ConvertDateToString(ratePlanChargeChargedThroughDate, 'ZouraFormat', 'NA');
                        } else {
                            return reportError(System.Label.LS_CancelSubscription_ErrMsg_NoRatePlanCharge);
                        }
                        outputResult = PauseCalloutHelper.runStandardCancelZuoraWorkflow(oSubscription.Name, sEffectiveDate);
                    }
                }
            } else if (cancellationType == 'Immediate') {
                /*Check Account has atleast one subscription and the subscription is active*/
                if (acc.Zuora__Subscriptions__r.size() > 0  && oSubscription.Zuora__Status__c == 'Active') {
                    String paymentId = '';
                    sEffectiveDate = CommunityHelper.ConvertDateToString(Date.today(), 'ZouraFormat', 'NA');
                    List<Zuora__Payment__c> paymentRecObj = new List<Zuora__Payment__c>();
                    paymentRecObj = [
                        SELECT Id, Name, Zuora__EXT_ID__c, Zuora__SettledOn__c, Zuora__CreatedDate__c, Zuora__Account__c
                        FROM Zuora__Payment__c
                        WHERE Zuora__Account__c = :acc.Id ORDER BY Zuora__CreatedDate__c DESC
                    ];
                    if (paymentRecObj.size() > 0) {
                        if (paymentRecObj[0].Zuora__SettledOn__c != null) {
                            paymentId = paymentRecObj[0].Zuora__EXT_ID__c;
                        } else {
                            return reportError(System.Label.LS_CancelSubscription_Page_Message_No_Settled_On);
                        }
                    }
                    outputResult = PauseCalloutHelper.runImmediateCancelZuoraWorkflow(oSubscription.Name, sEffectiveDate, paymentId);
                }
            }
            
            if (outputResult.get('success') != null && !Boolean.valueOf(outputResult.get('success'))) {
                if (outputResult.get('success') != null) {
                    return reportError(outputResult.get('message'));
                } else {
                    return reportError(System.Label.LS_BlockUser_FailedtoCancel);
                }
            }
            /* Updating the Account status */
            if (acc.Account_Status__c != System.Label.LS_Account_Status_Blocked) {
                if (acc.Account_Status__c == 'Free Trial') {
                    acc.Submitted_for_cancellation__c = true;
                    acc.Cancelled_Account__c = true;
                }
                acc.Account_Status__c = System.Label.LS_Account_Status_Blocked;
                acc.Cancelled_Account__c = true;
                acc.AuthKey__c = System.now(); //PD-9738 Reset the Auth Key when the user is blocked in salesforce
            } else if (acc.Account_Status__c == System.Label.LS_Account_Status_Blocked) {
                /*Added as a part of PD-10582*/
                if ((acc.Type == 'Docomo' && acc.Partner_ID__c != null) || acc.Type == 'Apple') {
                    acc.Account_Status__c = 'Active Paid';
                    acc.Cancelled_Account__c = false;
                } else { //End of PD-10582
                    acc.Account_Status__c = System.Label.LS_Account_Status_Forzen;
                }
            }
            
            /*Creating Task  */
            Task newTask = New Task();
            newTask.WhatID = acc.Id;
            newTask.Ownerid = UserInfo.getUserId();
            if (acc.Account_Status__c == System.Label.LS_Account_Status_Blocked) {
                newTask.Subject = acc.Firstname + '' + acc.LastName + ' ' + System.Label.LS_Block_User_Is_Blocked;
            } else {
                newTask.Subject = acc.Firstname + '' + acc.LastName + ' ' + System.Label.LS_UnblockUser_Comment;
            }
            newTask.description = Comment ;
            newTask.ActivityDate = Date.today();
            newTask.Status = 'Completed';
            newTask.Priority = 'Normal';
            insert newTask ;
            
            update acc;
            bShowPanel = false;
        }
        return new PageReference('/'+sAccountId);
    }
    
    public PageReference reportError (String message){
        if (typeOfAccount != null && typeOfAccount == 'Apple') {
            //returnErrorForApple(message);
            return new PageReference('/'+message);
        }
        apexpages.addmessage(new apexpages.message(ApexPages.severity.INFO, message));
        navigateError = true;
       
        return null;
    }
    
    public void reportErrorWithoutReturn (String message){
        
        apexpages.addmessage(new apexpages.message(ApexPages.severity.INFO, message));
        navigateError = true;
        return ;
    }

}