objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partial</fullName>
                    <default>true</default>
                    <label>Partial</label>
                </value>
                <value>
                    <fullName>Free Trial</fullName>
                </value>
                <value>
                    <fullName>Active Paid</fullName>
                </value>
                <value>
                    <fullName>Active Grace</fullName>
                </value>
                <value>
                    <fullName>Frozen</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Expired Marketing</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Apple</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>All_Email_Preferences__c</fullName>
        <defaultValue>true</defaultValue>
        <label>All Email Preferences</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Campaign_Id__c</fullName>
        <label>Gift Code Campaign Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Disable_transactional_emails__c</fullName>
        <formula>OR( ISPICKVAL( Type, &apos;Docomo&apos; ), Disable_all_transactional_emails__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Disable transaction emails</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Free_Trial_End_Date__c</fullName>
        <label>Free Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gift_Code_End_Date__c</fullName>
        <label>Gift Code End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gift_Code_Start_Date__c</fullName>
        <label>Gift Code Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Double_OptIn__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to identify user is double opt-in for marketing emails.</description>
        <label>Is Double OptIn</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notification_Country_Code__c</fullName>
        <label>Notification Country Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification_Language_Code__c</fullName>
        <label>Notification Language Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/DAZNCommunicatorConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This will hold the Dispatch id based on the email and the language</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>Column to store communicator table, column, dispatch, trigger id etc.</description>
        <label>Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DAZN Communicator Config</label>
</CustomObject>

objects/Email_Sync_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partial</fullName>
                </value>
                <value>
                    <fullName>Free Trial</fullName>
                </value>
                <value>
                    <fullName>Active Paid</fullName>
                </value>
                <value>
                    <fullName>Active Grace</fullName>
                </value>
                <value>
                    <fullName>Frozen</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Expired Marketing</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Apple</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Email Sync Queues</relationshipLabel>
        <relationshipName>Email_Sync_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>All_Email_Preferences__c</fullName>
        <defaultValue>true</defaultValue>
        <label>All Email Preferences</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dispatch_ID__c</fullName>
        <label>Dispatch ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email_Name__c</fullName>
        <label>Email Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Free_Trial_End_Date__c</fullName>
        <label>Free Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Double_Opt_in__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to identify user is double opt-in for marketing emails.</description>
        <label>Is Double Opt in</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification_Country_Code__c</fullName>
        <label>Notification Country Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification_Language_Code__c</fullName>
        <label>Notification Language Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_Email__c</fullName>
        <label>Person Email</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Details__c</fullName>
        <label>Plan Details</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Retried</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Email__c</fullName>
        <label>Type of Email</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Data Import</fullName>
                </value>
                <value>
                    <fullName>Triggered Dispatch</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unsubscribe_Language__c</fullName>
        <label>Unsubscribe Language</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Email Sync Queue</label>
    <nameField>
        <displayFormat>ESQ-{0000}</displayFormat>
        <label>Email Sync Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Sync Queues</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Gift_Code_History__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Gift Code History</relationshipLabel>
        <relationshipName>Gift_Code_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Applied_On__c</fullName>
        <label>Applied On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Campaign_Id__c</fullName>
        <label>Campaign Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gift_Code_End_Date__c</fullName>
        <label>Gift Code End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gift_Code_Start_Date__c</fullName>
        <label>Gift Code Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_Of_Periods__c</fullName>
        <label>Number Of Periods</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Gift Code History</label>
    <nameField>
        <label>Gift Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gift Code History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>All_Email_Preferences__c</fullName>
        <defaultValue>true</defaultValue>
        <label>All Email Preferences</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notification_Language_Code__c</fullName>
        <label>Notification Language Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>R00N40000001kyLcEAI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora__Currency__c</fullName>
        <label>Currency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Campaign_Id__c</fullName>
        <label>Gift Code Campaign Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Free_Trial_End_Date__c</fullName>
        <label>Free Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gift_Code_End_Date__c</fullName>
        <label>Gift Code End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gift_Code_Start_Date__c</fullName>
        <formula>IF( 
ISBLANK(Giftcode__c), 
null, 
NULLVALUE( 
Free_Trial_End_Date__c, 
IF( 
OR( ISNULL ( Campaign_Id__c ), ISBLANK ( Campaign_Id__c ) ), 
null, 
Zuora__SubscriptionStartDate__c 
) 
) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gift Code Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SubscriptionAmount__c</fullName>
        <formula>IF(ISPICKVAL(Zuora__TermSettingType__c , &apos;TERMED&apos;), (Zuora__MRR__c * 12), Zuora__MRR__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subscription Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__CustomerAccount__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__NextChargeDate__c</fullName>
        <label>Next Charge Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__TermSettingType__c</fullName>
        <description>Case sensitive. Denotes if a subscription is evergreen (has no end date or term length) or has a term.</description>
        <label>Term Setting Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TERMED</fullName>
                </value>
                <value>
                    <fullName>EVERGREEN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GiftCodeProvider.cls
/**
 * @Author Cognizant Technology Solutuions
 * @Date 09-Oct-2017
 * @Description : This class is used to process callouts from Zuora after user applied a new gift code
*/
@RestResource(urlMapping='/GiftCodeProvider/*')
global without sharing class GiftCodeProvider {

    /**
     * @Author Cognizant Technology Solutuions
     * @Date 09-Oct-2017
     * @Description : This method is used to process a POST requests from Zuora when a new gift code is applied
    */
    @HttpPost
    global static String createGiftCodeHistory() {
        RestRequest req = RestContext.request;
        String requestBodyJSONString = req.requestBody.toString();

        GiftCodeProvider.CallbackJSONBody callbackJSONBody = (GiftCodeProvider.CallbackJSONBody)JSON.deserialize(req.requestBody.toString(), GiftCodeProvider.CallbackJSONBody.class);
        
        List<Zuora__Subscription__c> subscription = [
            SELECT Id, Zuora__NextChargeDate__c, SubscriptionAmount__c, Zuora__Account__c, Zuora__TermSettingType__c,
                Zuora__CustomerAccount__r.Zuora__Currency__c, Zuora__Account__r.Account_Status__c, Zuora__Account__r.All_Email_Preferences__c,
                Zuora__Account__r.FirstName, Zuora__Account__r.LastName, Zuora__Account__r.Is_Double_OptIn__c, Free_Trial_End_Date__c,
                Zuora__Account__r.Notification_Country_Code__c, Zuora__Account__r.Notification_Language_Code__c,
                Zuora__Account__r.PersonEmail, Zuora__Account__r.Disable_transactional_emails__c
            FROM Zuora__Subscription__c
            WHERE Name = :callbackJSONBody.Workflow.SubscriptionName
        ];
        if (subscription == null || subscription.isEmpty()) {
            RestContext.response.statusCode = 400;
            return 'Error';
        }

        Gift_Code_History__c gch = new Gift_Code_History__c(
            Name = callbackJSONBody.Workflow.GiftCode,
            Account__c = subscription[0].Zuora__Account__c,
            Applied_On__c = callbackJSONBody.Workflow.ExecutionDate,
            Campaign_Id__c = callbackJSONBody.Workflow.CampaignName,
            Gift_Code_Start_Date__c = callbackJSONBody.Workflow.VoucherCodeEffectiveDate,
            Gift_Code_End_Date__c = callbackJSONBody.Workflow.VoucherCodeEffectiveDate.addMonths(callbackJSONBody.Workflow.UpToPeriods),
            Number_Of_Periods__c = callbackJSONBody.Workflow.UpToPeriods
        );
        insert gch;
        
        if (!subscription[0].Zuora__Account__r.Disable_transactional_emails__c) {
            Email_Sync_Queue__c triggeredDispatchEmailQueue = new Email_Sync_Queue__c(
                Account__c = subscription[0].Zuora__Account__c,
                Account_Status__c = subscription[0].Zuora__Account__r.Account_Status__c,
                All_Email_Preferences__c = subscription[0].Zuora__Account__r.All_Email_Preferences__c,
                First_Name__c = subscription[0].Zuora__Account__r.FirstName,
                Last_Name__c = subscription[0].Zuora__Account__r.LastName,
                Is_Double_Opt_in__c = subscription[0].Zuora__Account__r.Is_Double_OptIn__c,
                Notification_Country_Code__c =  subscription[0].Zuora__Account__r.Notification_Country_Code__c,
                Notification_Language_Code__c =  subscription[0].Zuora__Account__r.Notification_Language_Code__c,
                Person_Email__c =  subscription[0].Zuora__Account__r.PersonEmail,
                Plan_Details__c = subscription[0].Zuora__Account__r.Account_Status__c,
                Status__c = 'Not Started',
                Type_of_Email__c = 'Triggered Dispatch',
                Unsubscribe_Language__c = subscription[0].Zuora__Account__r.Notification_Language_Code__c,
                Email_Name__c = 'Gift Code Success',
                Dispatch_ID__c = (!Test.isRunningTest()) ? Integer.valueOf(DAZNCommunicatorConfig__c.getInstance('DispatchID_Gift_Code_Success').Value__c) : 12340,
                Free_Trial_End_Date__c = subscription[0].Free_Trial_End_Date__c,
                Rebill_Date__c = subscription[0].Zuora__NextChargeDate__c,
                Account_Currency__c = subscription[0].Zuora__CustomerAccount__r.Zuora__Currency__c,
                Subscription_Amount__c = subscription[0].SubscriptionAmount__c,
                Term_Setting_Type__c = (subscription[0].Zuora__TermSettingType__c == 'TERMED') ? 'TERMED' : 'EVERGREEN',
                Gift_Code_Expiry_Date__c = gch.Gift_Code_End_Date__c
            );
            insert triggeredDispatchEmailQueue;
        }

        APILogger.CreateAPILogs(
            subscription[0].Zuora__Account__c,
            '/GiftCodeProvider',
            'Inbound',
            callbackJSONBody.Workflow.ProcessId,
            requestBodyJSONString,
            null,
            null,
            null
        );

        return 'Success';
    }



    private class CallbackJSONBody {
        private CallbackJSONBodyWorkflow Workflow;
    }

    private class CallbackJSONBodyWorkflow {
        private Date ExecutionDate;
        private String GiftCode;
        private String CampaignName;
        private String ProcessId;
        private Integer UpToPeriods;
        private String SubscriptionName;
        private String ProductRatePlanChargeId;
        private String CallbackUrl;
        private String RegionOrigin;
        private String ProductRatePlanId;
        private Date VoucherCodeEffectiveDate;
    }

}