objects/Account.object
<CustomObject>
    <fields>
        <fullName>DAZN_Id__c</fullName>
        <externalId>true</externalId>
        <label>DAZN Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Partner_ID__c</fullName>
        <externalId>true</externalId>
        <label>Partner ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Secondary_Email__c</fullName>
        <label>Secondary Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ExternalID__c</fullName>
        <displayFormat>Ext-{00000000}</displayFormat>
        <label>ExternalID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>ViewerId__c</fullName>
        <externalId>true</externalId>
        <label>ViewerId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ResetD4DAccount.cls
global with sharing class ResetD4DAccount {
	
	webservice static String resetAccount(Id accId) {
        String result = 'unsuccess';
        List<Account>  accList = [select id ,Firstname,LastName, DAZN_Id__c,Type, Partner_ID__c, PersonEmail, Secondary_Email__c from Account where id =: accId];
        if (!accList.isEmpty()) {
        	for (Account item :accList) {
        		item.Partner_ID__c = accList[0].Id;
	        	item.Secondary_Email__c = 'resetD4DAccount@test.test';
	        	item.PersonEmail = 'resetD4DAccount' +accList[0].Id+ '@test.test';
	        	item.Firstname = 'resetAccount';
	        	item.LastName = 'resetAccount';
	        	item.DAZN_Id__c = accList[0].Id;
        	}
        	
        	update accList;
        	resetViewerIdUser(accId);
        	result = 'success';
        }      
        
        return result;
    }

    public static void resetViewerIdUser(String accId) {
    	List<User> us = [SELECT ViewerId__c, ExternalID__c FROM User WHERE AccountId = :accId LIMIT 1];
    	if (!us.isEmpty()) {
    		for (User item :us) {
    			item.ViewerId__c = null;
    		}
    		update us;
    	} 
    }
}