objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partial</fullName>
                    <default>true</default>
                    <label>Partial</label>
                </value>
                <value>
                    <fullName>Free Trial</fullName>
                </value>
                <value>
                    <fullName>Active Paid</fullName>
                </value>
                <value>
                    <fullName>Active Grace</fullName>
                </value>
                <value>
                    <fullName>Frozen</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Expired Marketing</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Apple</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CampaignID__c</fullName>
        <label>Gift Code Campaign ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cancelled_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelled Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Free_Trial_End_Date__c</fullName>
        <label>Free Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gift_Code_End_Date__c</fullName>
        <label>Gift Code End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gift_Code_Start_Date__c</fullName>
        <label>Gift Code Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gift_Code_Status__c</fullName>
        <formula>IF(
    Gift_Code_Start_Date__c &gt; TODAY(),
    &apos;Applied&apos;,
    IF(
        AND( Gift_Code_Start_Date__c &lt;= TODAY(), Gift_Code_End_Date__c &gt; TODAY() ),
        &apos;In Use&apos;,
        IF(
            Gift_Code_End_Date__c &lt;= TODAY(),
            &apos;Expired&apos;,
            &apos;&apos;
        )
    )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gift Code Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Giftcode__c</fullName>
        <label>Gift Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification_Country_Code__c</fullName>
        <label>Notification Country Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NumGiftPeriods__c</fullName>
        <label>NumGiftPeriods</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PauseScheduled__c</fullName>
        <formula>IF( 
ISNULL( Pause_From__c ), 
false, 
IF( 
Pause_From__c &gt; TODAY(), 
true, 
false 
) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PauseScheduled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Submitted_for_cancellation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Submitted for cancellation</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CountryListForGiftCode__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is created to check the countries for which Gift code is Enabled</description>
    <fields>
        <fullName>IsGiftCodeAvailable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is Boolean to check whether the Gift code is available for this country or not</description>
        <label>IsGiftCodeAvailable</label>
        <type>Checkbox</type>
    </fields>
    <label>CountryListForGiftCode</label>
</CustomObject>

objects/DAZNConfiguration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is a configurable custom setting for Forgot Password link</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>Field to store configuration value for specific key</description>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>DAZN Configuration</label>
</CustomObject>

objects/Gift_Code_History__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Gift Code History</relationshipLabel>
        <relationshipName>Gift_Code_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gift_Code_End_Date__c</fullName>
        <label>Gift Code End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gift_Code_Start_Date__c</fullName>
        <label>Gift Code Start Date</label>
        <type>Date</type>
    </fields>
    <label>Gift Code History</label>
    <nameField>
        <label>Gift Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gift Code History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>R00N40000001kyLcEAI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora__AutoPay__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto Pay</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zuora__Default_Payment_Method__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Default Payment Method</label>
        <referenceTo>Zuora__PaymentMethod__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>CampaignID__c</fullName>
        <description>Changed the API Name on 14 Jun 2017 as per request from Zoura (David) during Cog 1.8 release</description>
        <label>Gift Code Campaign ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Free_Trial_End_Date__c</fullName>
        <label>Free Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gift_Code_End_Date__c</fullName>
        <label>Gift Code End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gift_Code_Start_Date__c</fullName>
        <formula>IF( 
ISBLANK(Giftcode__c), 
null, 
NULLVALUE( 
Free_Trial_End_Date__c, 
IF( 
OR( ISNULL ( Campaign_Id__c ), ISBLANK ( Campaign_Id__c ) ), 
null, 
Zuora__SubscriptionStartDate__c 
) 
) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gift Code Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gift_Code_Status__c</fullName>
        <formula>IF(
    Gift_Code_Start_Date__c &gt; TODAY(),
    &apos;Applied&apos;,
    IF(
        AND( Gift_Code_Start_Date__c &lt;= TODAY(), Gift_Code_End_Date__c &gt; TODAY() ),
        &apos;In Use&apos;,
        IF(
            Gift_Code_End_Date__c &lt;= TODAY(),
            &apos;Expired&apos;,
            &apos;&apos;
        )
    )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gift Code Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Giftcode__c</fullName>
        <label>Gift Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NumFreeTrialPeriods__c</fullName>
        <label>NumFreeTrialPeriods</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NumGiftPeriods__c</fullName>
        <label>NumGiftPeriods</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__CustomerAccount__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__SubscriptionEndDate__c</fullName>
        <description>This is when the subscription ends. This is always equal to term end date, unless the subscription has been cancelled. If the subscription has been cancelled, this is set to the cancellation date.</description>
        <label>Subscription End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__SubscriptionStartDate__c</fullName>
        <description>The date when the subscription term starts. This is equal to the term start date if the subscription is on its initial term. Otherwise, it is the original term start date if the subscription has renewed.</description>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GiftCodeHelper.cls
/**
 * @Author Cognizant Technology Solutuions
 * @Date 10-Oct-2017
 * @Description : This class contains the Global method related to Gift Code Functionality 
*/
public class GiftCodeHelper {
    
    public static User user ;
    public static Boolean showRedeemLinkFlag ;
    public static Boolean showAddPaymentFlag;
    public static PageReference ref;
    public static Boolean isGiftCodeAvailable;
    public static String sCountry ;

    public Static List<Zuora__CustomerAccount__c> lstCustomerAccount;
    
    
    /**
     * @Author Cognizant Technology Solutuions
     * @Date 10-Oct-2017
     * @Description : This method is used to check if user country is available for Gift code
     * @Parameter1 : user 
    */
    public Static Boolean checkGiftCodeAvailable( User usr ){
    sCountry  = usr.CountryCode;
  
    
    Map<String, CountryListForGiftCode__c> showGiftCodeMap= CountryListForGiftCode__c.getAll();        
   
    if (showGiftCodeMap.containsKey(sCountry) ) {
            
       isGiftCodeAvailable = CountryListForGiftCode__c.getValues(sCountry).IsGiftCodeAvailable__c;
  
    }
     return isGiftCodeAvailable ;
  }  
 
    
    /**
     * @Author Cognizant Technology Solutuions
     * @Date 10-Oct-2017
     * @Description : This method is used to check the if Add Payment link should be visible or not 
     * @Parameter1 :  Subscription and Billing Account Object 
    */
    public Static Boolean checkPaymentMethod( Zuora__Subscription__c zsubs , Zuora__CustomerAccount__c billAcc) {
        showAddPaymentFlag = false;
        User user = CommunityHelper.getCurrentUser(); 
        if ( zsubs != null  && billAcc!= null &&  !CommunityHelper.IsDfDUser() && !CommunityHelper.isAppleUser() ){
            if ( String.isBlank(billAcc.Zuora__Default_Payment_Method__c) && billAcc.Zuora__Default_Payment_Method__c == null && !billAcc.Zuora__AutoPay__c && String.isNotBlank(zsubs.NumGiftPeriods__c) && Integer.valueOf(zsubs.NumGiftPeriods__c) > 0){
                showAddPaymentFlag = true;
            }
        }  
        return showAddPaymentFlag ;
    }
    
    
   
    /**
     * @Author Cognizant Technology Solutuions
     * @Date 10-Oct-2017
     * @Description : This method is used to check the if Add Gift code link should be visible or not 
     * @Parameter1 : accountId 
    */
    public Static Boolean checkRedeemLinkCriteria(Account acc , User user ) {
       Boolean showRedeemLinkFlag = false; 
      isGiftCodeAvailable =checkGiftCodeAvailable(user);
       
      if (isGiftCodeAvailable  != null ){
        if (  isGiftCodeAvailable  && acc!= null && !acc.Submitted_for_cancellation__c  && !acc.PauseScheduled__c && !acc.Cancelled_Account__c&&  (acc.Account_Status__c == 'Active Paid' || acc.Account_Status__c == 'Active Grace' || acc.Account_Status__c == 'Free Trial') ){
            showRedeemLinkFlag = true;
        }
        }
        else {
            showRedeemLinkFlag = false;
        }
        return showRedeemLinkFlag ;
    }
    
    /**
     * @Author Cognizant Technology Solutuions
     * @Date 10-Oct-2017
     * @Description : This method is used to Navigate to Redeem URL page
     * @Parameter1 :
    */
    public static PageReference redeemGiftCode() {
        
        String redeemUrl = (DAZNConfiguration__c.getValues('RedeemGiftCode') != null) ? DAZNConfiguration__c.getValues('RedeemGiftCode').Value__c : null;
        if (String.isNotBlank(redeemUrl)) {
            ref = new PageReference(redeemUrl);
            ref.setRedirect(true); 
        }
        return ref;
    }
    
        public Static Boolean checkRedeemLinkCriteria(User user ) {
        Boolean showRedeemLinkFlag = false;
        List<Account> lstAcc = [Select Id, Account_Status__c, Cancelled_Account__c , Notification_Country_Code__c, Submitted_for_cancellation__c , PauseScheduled__c FROM Account WHERE ID =:user.AccountId limit 1];
        
         isGiftCodeAvailable =checkGiftCodeAvailable(user);
        
        if (isGiftCodeAvailable  != null ){
        if (isGiftCodeAvailable  && lstAcc != null && !lstAcc.isEmpty()  && !lstAcc[0].Submitted_for_cancellation__c  && !lstAcc[0].PauseScheduled__c && !lstAcc[0].Cancelled_Account__c&&  (lstAcc[0].Account_Status__c == 'Active Paid' || lstAcc[0].Account_Status__c == 'Active Grace' || lstAcc[0].Account_Status__c == 'Free Trial') ){
            showRedeemLinkFlag = true;
        }
        }
        else {
            showRedeemLinkFlag = false;
        }
        return showRedeemLinkFlag ;
    }


    /**
     * @Author Cognizant Technology Solutuions
     * @Date 10-Oct-2017
     * @Description : This method is used to get the actual gift code end date
     * @Parameter1 : accountId : Id of person account for which gift code will be searched
    */
    public static Date getLatesGiftCodeEndDate(String accountId) {

        isGiftCodeAvailable = checkGiftCodeAvailable(CommunityHelper.getCurrentUser());
        if (isGiftCodeAvailable == null || !isGiftCodeAvailable) {
            return null;
        }
        
        List<Zuora__Subscription__c> sub = [Select Id, Gift_Code_End_Date__c
            From Zuora__Subscription__c
            Where Zuora__Account__c = :accountId
                AND (Zuora__Status__c = 'Active'OR (Zuora__Status__c = 'Cancelled' AND Zuora__SubscriptionEndDate__c > TODAY))
                AND Gift_Code_End_Date__c != null Order By Gift_Code_End_Date__c DESC LIMIT 1];

        List<Gift_Code_History__c> gch = [Select Id, Gift_Code_End_Date__c
            From Gift_Code_History__c
            Where Account__c = :accountId AND Gift_Code_End_Date__c != null Order By Gift_Code_End_Date__c DESC LIMIT 1];

        Date latesGiftCodeEndDate;

        if ((sub != null && !sub.isEmpty()) && (gch != null && !gch.isEmpty())) {
            latesGiftCodeEndDate = (sub[0].Gift_Code_End_Date__c > gch[0].Gift_Code_End_Date__c) ? sub[0].Gift_Code_End_Date__c : gch[0].Gift_Code_End_Date__c;
        } else if (sub != null && !sub.isEmpty()) {
            latesGiftCodeEndDate = sub[0].Gift_Code_End_Date__c;
        }  else if (gch != null && !gch.isEmpty()) {
            latesGiftCodeEndDate = gch[0].Gift_Code_End_Date__c;
        }

        return latesGiftCodeEndDate;
    }

    /**
     * @Author Cognizant Technology Solutuions
     * @Date 10-Oct-2017
     * @Description : This method is used to determine if gift code will expire soon or not
     * @Parameter1 : accountId : Id of person account for which gift code will be searched
    */
    public static Boolean isGiftCodeEndDateExpire(String accountId) {
        Date giftCodeEndDate = getLatesGiftCodeEndDate(accountId);
        return (giftCodeEndDate != null) && (giftCodeEndDate <= (Date.today() + 14));
    }
    
    /**
     * @Author Cognizant Technology Solutuions
     * @Date 11-Oct-2017
     * @Description : This method is used to pull information related to Gif Codes
     * @Parameter1 : accountId : Id of person account for which gift code will be searched
    */
    public Static Zuora__Subscription__c getSubscriptionWithGigtInfo(String accountId) {
         Zuora__Subscription__c subscriptionWithGiftInfo;
         List<Zuora__Subscription__c> subscriptions = [
            SELECT Id,
                CampaignID__c,
                Free_Trial_End_Date__c,
                Gift_Code_End_Date__c,
                Gift_Code_Start_Date__c,
                Giftcode__c,
                Gift_Code_Status__c,
                NumFreeTrialPeriods__c,
                NumGiftPeriods__c
            FROM Zuora__Subscription__c
            WHERE Zuora__Account__c =: accountId
                AND (Zuora__Status__c = 'Active' OR (Zuora__Status__c = 'Cancelled' AND Zuora__SubscriptionEndDate__c > TODAY ))
            ORDER BY Zuora__SubscriptionStartDate__c DESC NULLS LAST LIMIT 1
        ];
        if (!subscriptions.isEmpty()) {
            subscriptionWithGiftInfo = subscriptions[0];
        }
        return subscriptionWithGiftInfo;
    }
    
}