objects/Account.object
<CustomObject>
    <fields>
        <fullName>Notification_Country_Code__c</fullName>
        <label>Notification Country Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification_Language_Code__c</fullName>
        <label>Notification Language Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_ID__c</fullName>
        <externalId>true</externalId>
        <label>Partner ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Secondary_Email__c</fullName>
        <label>Secondary Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Notification_Country_Code__c</fullName>
        <label>Notification Country Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification_Language_Code__c</fullName>
        <label>Notification Language Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Id__c</fullName>
        <formula>IF( Account.Partner_ID__c  &lt;&gt;  null, Account.Partner_ID__c, null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Partner Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Previous_Customer_Comments__c</fullName>
        <label>Previous Customer Comments</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SamplePageCon.cls
public with sharing class SamplePageCon {
public string caseID;
public case cases{get;set;}

public samplePageCon(){
   // try{
     caseID = ApexPages.currentPage().getParameters().get('parent_id');
      if(caseID != null){
       cases =[select id, casenumber,subject,description,status,recordtype.name,recordtype.id,Notification_Country_Code__c,
                        Notification_Language_Code__c,Account.Notification_Country_Code__c,ContactEmail,Previous_Customer_Comments__c,Account.Notification_Language_Code__c,Accountid,Account.name,Account.Secondary_Email__c,SuppliedEmail,Account.Partner_ID__c, Account.Type,account.firstname,
                        account.lastname from case where id =:caseID ];
      
                        
      
      }
     
     
   /*}catch(exception ex){
   system.debug('Constructor------>'+ex.getMessage()+' line No :'+ex.getStackTraceString());
    ExceptionLoggerHelper.createExceptionLog(userinfo.getuserid(), 'CaseCommentExtCon', 'CaseCommentExtCon', ex.getMessage(), ex.getTypeName(), ex.getStackTraceString());
   apexpages.addmessage(new apexpages.message(ApexPages.severity.ERROR, System.Label.Please_Contact_Your_Admi));
                        
   
   }*/


}

    
  
    

}