objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partial</fullName>
                    <default>true</default>
                    <label>Partial</label>
                </value>
                <value>
                    <fullName>Free Trial</fullName>
                </value>
                <value>
                    <fullName>Active Paid</fullName>
                </value>
                <value>
                    <fullName>Active Grace</fullName>
                </value>
                <value>
                    <fullName>Frozen</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Expired Marketing</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Apple</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Zuora__Payment__c.object
<CustomObject>
    <description>Zuora Payment object.  A payment is the money that customers send to pay for charges related to their subscriptions. 
The Payment object holds all of the information about an individual payment, including the payment amount and to which invoices the payment is applied.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The CRM Account that this payment is related to.</description>
        <inlineHelpText>The CRM Account that this payment is related to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Amount__c</fullName>
        <description>The amount of the payment.</description>
        <inlineHelpText>The amount of the payment.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Zuora__CreatedDate__c</fullName>
        <description>The date when the payment was created in Zuora system.</description>
        <inlineHelpText>The date when the payment was created in Zuora system.</inlineHelpText>
        <label>Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Zuora__EXT_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>External Id For Payment object,   Represents a Zuora Payment object Id</description>
        <externalId>true</externalId>
        <label>Unique External Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__EffectiveDate__c</fullName>
        <description>The date when the payment takes effect.</description>
        <inlineHelpText>The date when the payment takes effect.</inlineHelpText>
        <label>Effective Date (Deprecated)</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <description>The payment ID in Zuora system.</description>
        <externalId>true</externalId>
        <label>External ID(Deprecated)</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The invoice that the payment is applied to.</description>
        <label>Invoice</label>
        <referenceTo>Zuora__ZInvoice__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__PaymentMethod__c</fullName>
        <description>The display name of the payment method used for the payment.</description>
        <inlineHelpText>The display name of the payment method used for the payment.</inlineHelpText>
        <label>Payment Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__SettledOn__c</fullName>
        <description>The date when the payment was settled in the payment processor.</description>
        <inlineHelpText>The date when the payment was settled in the payment processor.</inlineHelpText>
        <label>Settled On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <description>The status of the payment in the Zuora system. The value depends on the type of payment.</description>
        <inlineHelpText>The status of the payment in the Zuora system. The value depends on the type of payment.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Posted</fullName>
                </value>
                <value>
                    <fullName>Voided</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__PaymentMethod__c.object
<CustomObject>
    <description>PaymentMethod contains information on how the contact pays for the account. In order to activate an account, you need to create a payment method.</description>
    <fields>
        <fullName>Zuora__CreatedDate__c</fullName>
        <description>Zuora system automatically generates this date when the payment method is created.</description>
        <inlineHelpText>Zuora system automatically generates this date when the payment method is created.</inlineHelpText>
        <label>Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Payment Method</label>
    <nameField>
        <label>Payment Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__Refund__c.object
<CustomObject>
    <description>The Refund object is used to create and query refunds. 

Note that refunds imply that money has been returned to customers. You should use adjustments (credit memos) if you are issuing credit to customers, but are not returning funds to a customer.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The CRM Account that this payment is related to.</description>
        <inlineHelpText>The CRM Account that this payment is related to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Amount__c</fullName>
        <description>The amount the refund. Cannot exceed the amount of the payment the refund is applied to.</description>
        <inlineHelpText>The amount the refund. Cannot exceed the amount of the payment the refund is applied to.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Zuora__CreatedDate__c</fullName>
        <description>The Zuora system automatically generates this value, which records when the object was created.</description>
        <inlineHelpText>The Zuora system automatically generates this value, which records when the object was created.</inlineHelpText>
        <label>Created On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External_Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__PaymentMethod__c</fullName>
        <description>A valid PaymentMethod ID indicating the method being used to make the payment.</description>
        <inlineHelpText>A valid PaymentMethod ID indicating the method being used to make the payment.</inlineHelpText>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACH,</fullName>
                </value>
                <value>
                    <fullName>PayPal,</fullName>
                </value>
                <value>
                    <fullName>CreditCard,</fullName>
                </value>
                <value>
                    <fullName>DebitCard,</fullName>
                </value>
                <value>
                    <fullName>CreditCardReferenceTransaction,</fullName>
                </value>
                <value>
                    <fullName>BankTransfer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zuora__Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference of a previous payment to which a refund is applied.</description>
        <inlineHelpText>The reference of a previous payment to which a refund is applied.</inlineHelpText>
        <label>Payment</label>
        <referenceTo>Zuora__Payment__c</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <description>The status of the refund. These statuses are determined by the system.</description>
        <inlineHelpText>The status of the refund. These statuses are determined by the system.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Voided</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Refund</label>
    <nameField>
        <label>Refund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__ZInvoice__c.object
<CustomObject>
    <description>Zuora Invoice object. Invoices are bills that you send to customers.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The CRM account that the invoice is associated to.</description>
        <inlineHelpText>The CRM account that the invoice is associated to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This field holds the Zuora object ID, and is used as external ID for data synchronization between Salesforce and Zuora.</description>
        <externalId>true</externalId>
        <inlineHelpText>This field holds the Zuora object ID, and is used as external ID for data synchronization between Salesforce and Zuora.</inlineHelpText>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <description>The status of the invoice in the system. This status is not the status of the payment of the invoice, just the status of the invoice itself.</description>
        <inlineHelpText>The status of the invoice in the system. This status is not the status of the payment of the invoice, just the status of the invoice itself.</inlineHelpText>
        <label>Status</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Zuora_Id__c</fullName>
        <description>The Zuora ID of the invoice.</description>
        <inlineHelpText>The Zuora ID of the invoice.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/paymentRelListController.cls
/**
* @author Cognizant Technology Solutuions
* @date 24/04/2017
* @description paymentRelListController is the  class to get the payment id and do the respect procees on request (Edit.delete and refund)
*/



public class paymentRelListController {
    public List<Zuora__Payment__c> payRelList {get; set;}
    public String accIdofpayment {get; set;}
    public String PayDelId {get; set;}
    public String PayEditId {get; set;}
    public String PayRecId {get; set;}
    public Boolean ProfileDisplaySet{get; set;}

    public List<PaymentWrp> paymentWrp  { get; set; }

    public String choosePaymentId {get;set;}
    public Boolean isShowTable {get;set;}
    
    public paymentRelListController(ApexPages.StandardController controller) {    
        accIdofpayment = controller.getRecord().id;
        paymentWrp = new List<PaymentWrp>();
        isShowTable = true;
        if (userinfo.getProfileId() != null) {
            Profile pfDisp = [Select id, Name from profile where id =: userinfo.getProfileId()];
            String strPrf = pfDisp.Name;
            String CustLab =System.label.LS_RefundEnable_Profiles; 
            if (System.label.LS_RefundEnable_Profiles.contains(pfDisp.Name)) {
              ProfileDisplaySet = TRUE;
            } else {
              ProfileDisplaySet = False;                
            }
        }
        paymentWrp = getPayments();
    }

    public List<PaymentWrp> getPayments() {
        List<PaymentWrp> payments = new List<PaymentWrp>();
        List<PaymentWrp> paymentsFinal = new List<PaymentWrp>();
        if (!String.isBlank(accIdofpayment)) {    
            payRelList  = [Select id,Name,Zuora__Amount__c,Zuora__EffectiveDate__c,Zuora__PaymentMethod__c,Zuora__Status__c,
                            Zuora__CreatedDate__c, Zuora__Account__r.Account_Status__c, Zuora__SettledOn__c from Zuora__Payment__c where Zuora__Account__c =:accIdofpayment ];   
        }    

        if (!payRelList.isEmpty()) {
            Map<Id,Zuora__Payment__c> finalPaymentsById;
            /*Checking User access to REfund functionality*/
            if (RefundTransactionController.isAccessToRefund() || Test.isRunningTest()) {
                finalPaymentsById = RefundTransactionController.checkPaymentList(payRelList);
            }

            for (Zuora__Payment__c item :payRelList) {
                payments.add(new PaymentWrp(item, finalPaymentsById));
            }
            payments.sort();
            // sort list in decending order.
            for (Integer iCount = payments.size()-1; iCount >=0; iCount--) {
                paymentsFinal.add(payments.get(iCount));
            }
        }
        return paymentsFinal;
    }

    public PageReference refreshPage() {
        paymentWrp = getPayments();
        isShowTable = true;
        return null;
    }

    public PageReference refundProcess() {
        Boolean isRefundSuccess = true;
        Boolean isInvoiceAdjustmentSuccess = true;

        List<Zuora.zApi.SaveResult> lstSaveResult;
        List<Zuora.zApi.SaveResult> invoicesAdjustmentResult;

        List<Zuora__Payment__c> payments = [SELECT ID, Zuora__EXT_ID__c, Zuora__Invoice__r.Zuora__Zuora_Id__c, Zuora__Invoice__r.Zuora__External_Id__c
                                                FROM Zuora__Payment__c 
                                                WHERE Id = :choosePaymentId];  

        if (!payments.isEmpty()) {
          List<Zuora__Refund__c> refunds = [SELECT Zuora__Payment__c FROM Zuora__Refund__c WHERE Zuora__Payment__c = :choosePaymentId];
            if (!refunds.isEmpty()) {
                apexpages.addmessage(new apexpages.message(ApexPages.severity.WARNING, Label.LS_Refund_Refund_not_possible));
                isShowTable = false;
                return null;
            }
        }                                      
        String errorMessage;                           
        if (payments!=null && !payments.isEmpty()) {
            if (!Test.isRunningTest()) {
                lstSaveResult = ZuoraTransactionHelper.RefundAmount(payments[0].Zuora__EXT_ID__c,  payments[0].Zuora__Invoice__r.Zuora__Zuora_Id__c, 'Immediate Cancellation');
            }
            
            if (lstSaveResult == null || lstSaveResult.isEmpty() || lstSaveResult[0].Success != true || lstSaveResult[0].Errors != null) {
                if (!Test.isRunningTest()) {
                    isRefundSuccess = false;
                }
                errorMessage = lstSaveResult != null ? String.valueOf(lstSaveResult[0].Errors) : 'Error';
            } 

            if (isRefundSuccess) {
                if (!Test.isRunningTest()) {
                    invoicesAdjustmentResult = ZuoraTransactionHelper.createInvoiceLineItemAdjusment(payments[0].Zuora__Invoice__r.Zuora__External_Id__c,'Chargeback','Credit'); 
                }                
                if (invoicesAdjustmentResult == null || invoicesAdjustmentResult.isEmpty() || invoicesAdjustmentResult[0].Success != true ||  invoicesAdjustmentResult[0].Errors != null) {
                    if (!Test.isRunningTest()) {
                        isInvoiceAdjustmentSuccess = false;
                    }                    
                    errorMessage = invoicesAdjustmentResult != null ? String.valueOf(invoicesAdjustmentResult[0].Errors) : 'Error';
                }
            }             
        }  
        if (isRefundSuccess && isInvoiceAdjustmentSuccess) {
            apexpages.addmessage(new apexpages.message(ApexPages.severity.CONFIRM, Label.LS_Refund_processed));
        } else {
            apexpages.addmessage(new apexpages.message(ApexPages.severity.ERROR, errorMessage));
        }
        isShowTable = false;
        return null;
    }

    public class PaymentWrp implements Comparable {
        public String id {get;set;}
        public String name {get;set;}
        public String linkRefund {get;set;}
        public Boolean isRefund {get;set;}
        public Decimal amount {get;set;}
        public Datetime effectiveDate {get;set;}
        public String paymentMethod {get;set;}
        public String status {get;set;}
        public Datetime creaeDate {get;set;}

        public PaymentWrp (Zuora__Payment__c item, Map<Id, Zuora__Payment__c> finalPaymentsById) {
            id = item.Id;
            name = item.Name;
            linkRefund = item.Id;
            isRefund = makeIsRefund(item, finalPaymentsById);
            amount = item.Zuora__Amount__c;
            effectiveDate = item.Zuora__EffectiveDate__c;
            paymentMethod = item.Zuora__PaymentMethod__c;
            status = item.Zuora__Status__c;
            creaeDate = item.Zuora__CreatedDate__c;
        }

        public Boolean makeIsRefund(Zuora__Payment__c item, Map<Id, Zuora__Payment__c> finalPaymentsById) {
            Boolean isResult = false;
            if (finalPaymentsById != null && !finalPaymentsById.isEmpty()) {
                if (finalPaymentsById.containsKey(item.Id) && item.Zuora__SettledOn__c != null) {
                    isResult = true;
                }
            }
            return isResult;
        }

        public Integer compareTo(Object compareTo) {
            PaymentWrp compareToPH = (PaymentWrp)compareTo;
            if(creaeDate == compareToPH.creaeDate) return 0;
            if(creaeDate > compareToPH.creaeDate) return 1;
            return -1;
        }

    }

    /*    
    Description: This method is used to Delete the payment Records.
    */
    public void editdelProcess() {
        try{
            if(!string.isEmpty(PayDelId)){
                Zuora__Payment__c del = new Zuora__Payment__c(ID=PayDelId);
                delete del; 
            }  
        }
        catch(Exception ex){
            ExceptionLoggerHelper.createExceptionLog(UserInfo.getUserId(), 'paymentRelListController', 'editdelProcess', ex.getMessage(), ex.getTypeName(), ex.getStackTraceString());
        }  
    }
  
}