objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partial</fullName>
                    <default>true</default>
                    <label>Partial</label>
                </value>
                <value>
                    <fullName>Free Trial</fullName>
                </value>
                <value>
                    <fullName>Active Paid</fullName>
                </value>
                <value>
                    <fullName>Active Grace</fullName>
                </value>
                <value>
                    <fullName>Frozen</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Expired Marketing</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Apple</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>All_Email_Preferences__c</fullName>
        <defaultValue>true</defaultValue>
        <label>All Email Preferences</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>All_Email_Preferences__c</fullName>
        <defaultValue>true</defaultValue>
        <label>All Email Preferences</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EmailPreferencesControllerTest.cls
/**
* @author Cognizant Technology Solutuions
* @date 05/02/2015
* @description This class test emailpreferences functionality
*/
@isTest
public class EmailPreferencesControllerTest {
    @testSetup 
    public static void getCommunityUsersTestData(){
        CreateTestDataforUnitTest.triggerSettings();
        CreateTestDataforUnitTest.createTestAccounts();
        CreateTestDataforUnitTest.createTestCommunityUsers();
        CreateTestDataforUnitTest.createTestcustomsetting();
        }

    /* Test email preference update*/
    static testMethod void testEmailPreferencesUpdate() {
        List<Account> accList = [Select Id, Name, PersonEmail,PersonContactId from Account where Account_Status__c = 'Free Trial'];
        List<Id> contactIdList = new List<Id>();
        for(Account acc : accList){
            contactIdList.add(acc.PersonContactId);
        }
        List<User> oUser = [Select Id, Name, UserName,Alias,Country,LanguageLocaleKey from User where ContactId In : contactIdList];
        
            PageReference oPageReference = Page.EmailPreferences; 
            Test.setCurrentPage(oPageReference); 
            ApexPages.currentPage().getParameters().put('UserId','UID'+accList[0].id);
            
            // Initiate email preference class
            EmailPreferencesController oEmailPreference = new EmailPreferencesController();
            
            // Unsubscribe and verify changes.
            oEmailPreference.Unsubscribe();
            oEmailPreference.navigateError = true;
            oEmailPreference.navigateToErrorPage();
                
            
            List<Account> lstAccount = [Select id, All_Email_Preferences__c from Account where Id=:accList[0].id];
            system.assertEquals(false, lstAccount[0].All_Email_Preferences__c);
            
    }
    
    /* Test email preference update*/
    static testMethod void testEmailPreferencesUpdation() {
        List<Account> accList = [Select Id, Name, PersonEmail,PersonContactId from Account where Account_Status__c = 'Free Trial'];
        List<Id> contactIdList = new List<Id>();
        for(Account acc : accList){
            contactIdList.add(acc.PersonContactId);
        }
        List<User> oUser = [Select Id, Name, UserName,Alias,Country,LanguageLocaleKey from User where ContactId In : contactIdList];
        
        System.RunAs(oUser[0]){
            Test.StartTest();
            PageReference oPageReference = Page.EmailPreferences; 
            Test.setCurrentPage(oPageReference); 
            ApexPages.currentPage().getParameters().put('UserId','UID'+accList[0].id);
            
            // Initiate email preference class
            EmailPreferencesController oEmailPreference = new EmailPreferencesController();
            
            // Unsubscribe and verify changes.
            oEmailPreference.Unsubscribe();
            oEmailPreference.navigateError = true;
            oEmailPreference.navigateToErrorPage();
                
            
            List<Account> lstAccount = [Select id, All_Email_Preferences__c from Account where Id=:accList[0].id];
            
            Test.StopTest();
        }
    }
}