objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partial</fullName>
                    <default>true</default>
                    <label>Partial</label>
                </value>
                <value>
                    <fullName>Free Trial</fullName>
                </value>
                <value>
                    <fullName>Active Paid</fullName>
                </value>
                <value>
                    <fullName>Active Grace</fullName>
                </value>
                <value>
                    <fullName>Frozen</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Expired Marketing</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Apple</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Viewer_ID__c</fullName>
        <description>Populating the viewer id of User on account</description>
        <label>Viewer ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Viewer_Id__c</fullName>
        <formula>ExternalID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Viewer Id</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/GTMHeaderTest.cls
@isTest
public class GTMHeaderTest {

    public static testMethod void MyaccountGTMHeader() {
        CreateTestDataforUnitTest.triggerSettings();
        CreateTestDataforUnitTest.createTestAccounts();
        CreateTestDataforUnitTest.createTestCommunityUsers();
        CreateTestDataforUnitTest.CreateGuestUser();
        List<Account> accList = [Select Id, Name, PersonEmail, PersonContactId From Account Where Account_Status__c = 'Free Trial' LIMIT 1];
        List<User> oUser = [Select Id, FirstName, LastName, UserName, Alias, Country, CountryCode, LanguageLocaleKey, Viewer_Id__c From User Where ContactId = :accList[0].PersonContactId LIMIT 1];
        System.runAs(oUser[0]) {
            GTMHeaderController gtmObj = new GTMHeaderController();
            gtmObj.pageName = 'myaccount';
            GTMHeaderController.errorMsgDsply = 'test';
            GTMHeaderController.errorMsgDsply1 = 'test';

            GTMHeaderController.errorDespFromAccountController('test');
            
            System.assertEquals(gtmObj.language, oUser[0].LanguageLocaleKey);
            System.assertEquals(gtmObj.territory, oUser[0].CountryCode);
            System.assertEquals(gtmObj.customerId, oUser[0].Viewer_Id__c);
        }
    }

}