objects/API_Log__c.object
<CustomObject>
    <description>It will capture API logs while call out to external environments</description>
    <label>API Log</label>
    <nameField>
        <displayFormat>API-{000000}</displayFormat>
        <label>API Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Gift_Code_History__c.object
<CustomObject>
    <label>Gift Code History</label>
    <nameField>
        <label>Gift Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gift Code History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__CustomerAccount__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GiftCodeProviderTest.cls
@isTest
private class GiftCodeProviderTest {
	
	@isTest static void testCreateGiftCodeHistory() {
		SetUpTestData.triggerSettings();
		Account oAccount = SetUpTestData.createPersonAccount('TestFirstName', 'TestLastName', 'te@test.com', 'Free Trial');
		Zuora__CustomerAccount__c bAccount = SetUpTestData.createBillingAccount(oAccount.Id, 'test billing account', 'Active', 'A00000073', 'testbill Name', 'United Kingdom', 'test bill name', 'Credit Card', 'batch2', 'USD', '1st of the month');
        Zuora__Subscription__c zSubsp = SetUpTestData.createZuoraSubscription(oAccount.Id, bAccount.Id, 'Test Zuora', 'Active', System.today(), System.today() + 30);

		RestRequest req = new RestRequest();
		req.requestURI = '/GiftCodeProvider';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(
        	'{ '+
            '    "Workflow": { '+
            '        "ExecutionDate": "2017-09-23", '+
            '        "GiftCode": "GiftCodedkadjsfladj", '+
            '        "CampaignName": "string", '+
            '        "ProcessId": "ProcessIDdfasdfads", '+
            '        "UpToPeriods": 2, '+
            '        "SubscriptionName": "' + zSubsp.Name + '", '+
            '        "ProductRatePlanChargeId": "2c92c0f9587b0ad001588c6a447257ca", '+
            '        "CallbackUrl": "CallbackURL", '+
            '        "RegionOrigin": "EU", '+
            '        "ProductRatePlanId": "2c92c0f85bf61f6b015bfc3ebcd6179a", '+
            '        "VoucherCodeEffectiveDate":"2017-09-20" '+
            '    } '+
            '}'
        );
        RestContext.request = req;

		Test.startTest();
		String res = GiftCodeProvider.createGiftCodeHistory();
		System.assertEquals('Success', res);
		Test.stopTest();

		System.assertEquals(1, [Select Id From Gift_Code_History__c].size());
		System.assertEquals(1, [Select Id From API_Log__c].size());
	}
	
}