objects/API_Log__c.object
<CustomObject>
    <description>It will capture API logs while call out to external environments</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>API Logs</relationshipLabel>
        <relationshipName>API_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Call_out_end_point__c</fullName>
        <label>Call out end point</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Call_out_type__c</fullName>
        <description>Determines whether its a inbound out bound call out.</description>
        <label>Call out type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Inbound</fullName>
                </value>
                <value>
                    <fullName>Outbound</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Process_ID__c</fullName>
        <description>It will be used to capture work flow ID while Zuora call out</description>
        <label>Process ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <description>It will capture API request</description>
        <label>Request</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Code__c</fullName>
        <inlineHelpText>Response code received from external app</inlineHelpText>
        <label>Response Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Response</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed with time out</fullName>
                </value>
                <value>
                    <fullName>Failed with errors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>API Log</label>
    <nameField>
        <displayFormat>API-{000000}</displayFormat>
        <label>API Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/APILogger.cls
/**
 * @Author : Cognizant Technology Solution
 * @Date : 01-Sept-2017
 * @Description: This class will be used to create API logs which will be used to track API call outs
 * @Parameter1 : accountId : It captures Id of person account for API call out
 * @Parameter2 : callOutEndPointURLStr : It captures end point of API call out
 * @Parameter3 : callOutTypeStr : Its a restricted picklist and its values will be Inbound/Outbound depending on call out. 
 * @Parameter4 : processIDStr : It captures Workflow ID/Process Id of API call out
 * @Parameter5 : requestStr : It captures request of API call out
 * @Parameter6 : responseCodeStr : It captures response of API call out
 * @Parameter7 : statusStr : It captures status of API call out
**/
global class APILogger{
    public static void CreateAPILogs(Id accountId,String callOutEndPointURLStr,String callOutTypeStr,String processIDStr,
									String requestStr,String responseStr,String responseCodeStr,String statusStr){
    	API_Log__c apiLogRec = new API_Log__c();
        if(accountId <> null)
        	apiLogRec.Account__c = accountId; 
        if(callOutEndPointURLStr <> null)
            apiLogRec.Call_out_end_point__c = callOutEndPointURLStr; 
        apiLogRec.Call_out_type__c = callOutTypeStr;
        apiLogRec.Process_ID__c = processIDStr;
        //Update API Request                                 
        if(requestStr <> '' && requestStr <> null){            
            System.debug(requestStr.length());
            if(requestStr.length() > 131071){                
            	apiLogRec.Request__c = requestStr.substring(0,131071);
            }
            else
                apiLogRec.Request__c = requestStr;
        }
        //Update API Response 
        if(responseStr <> '' && responseStr <> null){
            if(responseStr.length() > 131071){
                apiLogRec.Response__c = responseStr.substring(0,131071);
            }
            else
                apiLogRec.Response__c = responseStr;
        }
		apiLogRec.Response_Code__c = responseCodeStr;                                    
		apiLogRec.Status__c = statusStr;
        try{
        	insert apiLogRec;//Create API Log record   
        }catch(Exception ex){
            ExceptionLoggerHelper.createExceptionLog(userInfo.getUserId(), 'APILogger', 'CreateAPILogs', ex.getMessage(), ex.getTypeName(), ex.getStackTraceString());
        }                     
    }
}