objects/Case.object
<CustomObject>
    <fields>
        <fullName>Notification_Language_Code__c</fullName>
        <label>Notification Language Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Mass_Email_Request__c.object
<CustomObject>
    <label>Mass Email Request</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Mass Email Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mass Email Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Mass_Email_Request_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Mass Email Requests detail</relationshipLabel>
        <relationshipName>Mass_Email_Requests_detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Mass Email Requests detail</relationshipLabel>
        <relationshipName>Mass_Email_Requests_detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mass_Email_Request__c</fullName>
        <label>Mass Email Request</label>
        <referenceTo>Mass_Email_Request__c</referenceTo>
        <relationshipLabel>Mass Email Requests detail</relationshipLabel>
        <relationshipName>Mass_Email_Requests_detail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Mass Email Request Detail</label>
    <nameField>
        <displayFormat>MD-{0000}</displayFormat>
        <label>Mass Email Request Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mass Email Requests detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ConnectionWithRequest.cls
global class ConnectionWithRequest implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id, Notification_Language_Code__c, SuppliedEmail, AccountId FROM Case LIMIT 10000';

		return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Case> scope) {
        List<Mass_Email_Request_Detail__c> massEmailDetails = new List<Mass_Email_Request_Detail__c>();
        for (Case item: scope) {
            Mass_Email_Request_Detail__c massEmailDetail = new Mass_Email_Request_Detail__c();
			if (!String.isBlank(item.AccountId) || !String.isBlank(item.SuppliedEmail)) {
				massEmailDetail.Account__c = item.AccountId;
				massEmailDetail.Case__c = item.Id;
				massEmailDetail.Email__c =  item.SuppliedEmail;
				if (String.isBlank(item.Notification_Language_Code__c) || item.Notification_Language_Code__c == 'Unknown') {
					massEmailDetail.Language__c = 'en';
				} else {
					massEmailDetail.Language__c = item.Notification_Language_Code__c.toLowerCase();
				}
				massEmailDetail.Mass_Email_Request__c = 'a229E0000001ujv';
				massEmailDetails.add(massEmailDetail);
			}
        }
        insert massEmailDetails;
    }
    
    global void finish(Database.BatchableContext BC) {
        
    }
}