objects/Case.object
<CustomObject>
    <fields>
        <fullName>Contact_us_email__c</fullName>
        <label>Contact us email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>IsGuestUser__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checks if the user is a guest user or a logged in user.</description>
        <label>IsGuestUser</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notification_Country_Code__c</fullName>
        <label>Notification Country Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification_Language_Code__c</fullName>
        <label>Notification Language Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Type__c</fullName>
        <label>Provider Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DAZN</fullName>
                </value>
                <value>
                    <fullName>Docomo</fullName>
                </value>
                <value>
                    <fullName>Non-member</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <description>Case sub-types, this field is dependent on case type field.</description>
        <label>Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Cancellation</fullName>
                </value>
                <value>
                    <fullName>Device Specific Log in Issue</fullName>
                </value>
                <value>
                    <fullName>Error Message</fullName>
                </value>
                <value>
                    <fullName>Feedback</fullName>
                </value>
                <value>
                    <fullName>Forgotten Password</fullName>
                </value>
                <value>
                    <fullName>Forgotten Username</fullName>
                </value>
                <value>
                    <fullName>Geoblocking Query</fullName>
                </value>
                <value>
                    <fullName>Live Event</fullName>
                </value>
                <value>
                    <fullName>Not Available on Site</fullName>
                </value>
                <value>
                    <fullName>Not loading</fullName>
                </value>
                <value>
                    <fullName>Platform Compatibility Query</fullName>
                </value>
                <value>
                    <fullName>Quality Issue</fullName>
                </value>
                <value>
                    <fullName>Rebill Issue</fullName>
                </value>
                <value>
                    <fullName>Refund Request</fullName>
                </value>
                <value>
                    <fullName>Spinning Circle</fullName>
                </value>
                <value>
                    <fullName>Unable to Sign In</fullName>
                </value>
                <value>
                    <fullName>Unable to Subscribe</fullName>
                </value>
                <value>
                    <fullName>Update Account Settings</fullName>
                </value>
                <value>
                    <fullName>Update Personal Information</fullName>
                </value>
                <value>
                    <fullName>Video not working</fullName>
                </value>
                <value>
                    <fullName>VOD</fullName>
                </value>
                <value>
                    <fullName>Other General Enquiry</fullName>
                </value>
                <value>
                    <fullName>Schedule/Content General Enquiry</fullName>
                </value>
                <value>
                    <fullName>Account, Payments &amp; Billing General Enquiry</fullName>
                </value>
                <value>
                    <fullName>Catch Up General enquiry</fullName>
                </value>
                <value>
                    <fullName>Live Stream General enquiry</fullName>
                </value>
                <value>
                    <fullName>Login General equiry</fullName>
                </value>
                <value>
                    <fullName>PS Beta Feedback</fullName>
                </value>
                <value>
                    <fullName>About DAZN</fullName>
                </value>
                <value>
                    <fullName>Supported country</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Custom_Provider__c.object
<CustomObject>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>en</fullName>
                </value>
                <value>
                    <fullName>de</fullName>
                </value>
                <value>
                    <fullName>ja</fullName>
                </value>
                <value>
                    <fullName>fr</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider_Type__c</fullName>
        <label>Provider Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DAZN</fullName>
                </value>
                <value>
                    <fullName>Docomo</fullName>
                </value>
                <value>
                    <fullName>Non-member</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Custom Provider</label>
    <nameField>
        <label>Custom Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DAZNConfiguration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is a configurable custom setting for Forgot Password link</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>Field to store configuration value for specific key</description>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>DAZN Configuration</label>
</CustomObject>

objects/Email_Help_Option__c.object
<CustomObject>
    <fields>
        <fullName>Case_Resolution_Owner__c</fullName>
        <label>Case Resolution Owner</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DAZN</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Resolution_Text__c</fullName>
        <description>Static text that will be displayed back to the customer, if the Case Resolution Owner is External</description>
        <label>Case Resolution Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>AT</fullName>
                </value>
                <value>
                    <fullName>CH</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Display_Sequence__c</fullName>
        <label>Display Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>en</fullName>
                </value>
                <value>
                    <fullName>de</fullName>
                </value>
                <value>
                    <fullName>ja</fullName>
                </value>
                <value>
                    <fullName>fr</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider_Type__c</fullName>
        <description>Can be either DAZN, Docomo or non-member</description>
        <label>Provider Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DAZN</fullName>
                </value>
                <value>
                    <fullName>Docomo</fullName>
                </value>
                <value>
                    <fullName>Non-member</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sign_in_Needed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>TRUE/FALSE value depending on whether the user needs to sign in for this case type</description>
        <label>Sign in Needed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <label>Email Help Option</label>
    <nameField>
        <label>Type Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Email Help Option</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Notification_Language_Code__c</fullName>
        <label>Notification Language Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ContactUsController.cls
/**************************************************************************************************************************************
Class  Name : ContactUsController.
Class  Description : ContactUs Controller for ContactUs VF Page.
History of Changes:                 
-----------------------------------------------------------------------------------------------------------------------------------
        Date                              Developer                                                            Comments
----------------------------------------------------------------------------------------------------------------------------------
      04-Oct-2016                         Srikanth                                                      PD-8637 Changed class sharing model form without to with.

**************************************************************************************************************************************/

/*Changed the class to with sharing as per PD-7930
PD-8637 -Changed class sharing model form without to with */
global with sharing class ContactUsController {
    public Boolean isEmailEdit { get; set; }  
    public User oUser { get; set; }
    public String strNewEmail { get; set; }
    public String caseDescription { get; set; } 
    public String sCaseSubject { get; set; }
    public String sCaseType { get; set; }
    public String sCaseLanguage { get; set; }
    public String sCaseCountry { get; set; }
    public String sUniqueCaseType { get; set; }
    public String sCaseSubType { get; set; }
    public Boolean bIsGuestUser { get; set; }
    public String sTrakingParams { get; set; }
    public Boolean isDfDUser { get; set; }
    public String selectedProvider { get; set; }
    public List<Email_Help_Option__c> subjects { get; set; }

    public String strCountry {
        get {
            Cookie country = ApexPages.currentpage().getCookies().get('Country');
            String sCountry = (country != null) ? country.getValue() : ApexPages.currentpage().getParameters().get('Country');
            return (String.isNotBlank(sCountry)) ? sCountry : strCountry;
        }
        set;
    }

    public String strLanguage {
        get {
            Cookie lang = ApexPages.currentpage().getCookies().get('lang');
            String sLanguage = (lang != null) ? lang.getValue() : ApexPages.currentpage().getParameters().get('lang');
            sLanguage = (String.isNotBlank(sLanguage)) ? sLanguage.split('_')[0] : sLanguage;
            return (String.isNotBlank(sLanguage)) ? sLanguage : strLanguage;
        }
        set;
    }
    
    public String selectedSubject {
        get {
            String selectedEmailHelpOption;
            if (String.isNotBlank(sCaseType)) {
                for (Email_Help_Option__c eho : typeOfCase) {
                    if (eho.Name == sCaseType) {
                        selectedEmailHelpOption = eho.Type__c;
                        break;
                    }
                }
            }
            return selectedEmailHelpOption;
        }
        set;
    }
    
    public List<Custom_Provider__c> userTypes {
        get {
            String sLanguage = (String.isNotBlank(strLanguage)) ? strLanguage.split('_')[0] : strLanguage;
            String sCountry = strCountry;
            if (String.isNotBlank(sCountry) && String.isNotBlank(sLanguage)) {
                return [SELECT Name, Provider_Type__c FROM Custom_Provider__c 
                        WHERE Language__c = :sLanguage AND Country_Code__c = :sCountry
                        ORDER BY NAME LIMIT :(Limits.getLimitQUeryRows() - Limits.getQueryRows())];
            } else {
                return null;
            }
        }
        set;
    }

    public List<Email_Help_Option__c> typeOfCase {
        get {
            String sLanguage = (String.isNotBlank(strLanguage)) ? strLanguage.split('_')[0] : strLanguage;
            String sCountry = strCountry;
            List<Email_Help_Option__c> emailHelpOptions = new List<Email_Help_Option__c>();
            if (String.isNotBlank(sCountry) && String.isNotBlank(sLanguage)) {
                for (Email_Help_Option__c caseType : subjects) {
                    Boolean isAppropriateCaseType = String.isNotBlank(caseType.Language__c) && caseType.Language__c == sLanguage
                        && String.isNotBlank(caseType.Country__c) && caseType.Country__c == sCountry
                        && String.isNotBlank(caseType.Provider_Type__c) && caseType.Provider_Type__c == selectedProvider;
                    
                    if (isAppropriateCaseType) {
                        emailHelpOptions.add(caseType);
                    }
                }
            }
            return emailHelpOptions;
        }
        set;
    }

    /*
    Description: ContactUs Constructor PD-8875
    */
    public ContactUsController() {
        sCaseType = ApexPages.currentpage().getParameters().get('type');
        if (String.isNotBlank(sCaseType) && String.escapeSingleQuotes(sCaseType.deleteWhitespace()).isAlpha()) {
            sCaseType = sCaseType;
        }
        
        sTrakingParams = ApexPages.currentpage().getParameters().get('TrakingParams');

        subjects = [SELECT Name, Type__c, Country__c, Language__c, Case_Resolution_Owner__c, Case_Resolution_Text__c, Sign_in_Needed__c, Provider_Type__c, Display_Sequence__c
                    FROM EMAIL_HELP_OPTION__c
                    ORDER BY Display_Sequence__c ASC NULLS LAST LIMIT :(Limits.getLimitQUeryRows() - Limits.getQueryRows())];
        
        // check for User
        if (userInfo.getUserType().Equals('Guest')) {
            isEmailEdit = true;
            bIsGuestUser = true;
            isDfDUser = false;
        } else {
            oUser = CommunityHelper.getCurrentUser();
            isEmailEdit = false;
            bIsGuestUser = false;
            strNewEmail = oUser.Email;
            isDfDUser = CommunityHelper.IsDfDUser();

            if (isDfDUser) {
                selectedProvider = 'Docomo';
            } else {
                selectedProvider = 'DAZN';
            }
        }
    }
    
    /*
    Description: Event to edit email
    */
    public void edit() {
        String field = apexpages.currentpage().getParameters().get('field');  
        isEmailEdit = true;      
        if (String.isNotBlank(field) && field.equals('Email')) {
            strNewEmail = oUser.Email;
        }
    }
    
    /*
    Description: Method to create case for email inquiry. 
    */
    public PageReference createCase() {
        try {
            if (String.isEmpty(sCaseSubject)) {
                sCaseSubject = DAZNConfiguration__c.getValues('DefaultCaseSubject').Value__c;
                sCaseType = DAZNConfiguration__c.getValues('DefaultCaseType').Value__c;
            }
            Database.DMLOptions oDMLOptiono = new Database.DMLOptions();
            oDMLOptiono.assignmentRuleHeader.useDefaultRule= true;
            Case oCase = new Case();
            oCase.Origin = 'Email';
            oCase.Type = sCaseType;
            oCase.Status= 'Open';
            oCase.Subject = sCaseSubject;
            oCase.Description= caseDescription;
            oCase.SuppliedEmail = strNewEmail;
            oCase.Contact_us_email__c = strNewEmail;
            oCase.setOptions(oDMLOptiono);
            //added as part of PD-15017 ticket
            oCase.Notification_Language_Code__c = (String.isNotBlank(sCaseLanguage) && sCaseLanguage.startsWithIgnoreCase('en')) ? sCaseLanguage.split('_')[0] : sCaseLanguage;
            oCase.Notification_Country_Code__c = (String.isNotBlank(sCaseCountry)) ? sCaseCountry.toUpperCase() : '';
            oCase.IsGuestUser__c = bIsGuestUser;
            oCase.Sub_Type__c = !String.isBlank(sCaseSubType) ? sCaseSubType : oCase.Sub_Type__c;

            /*PD-9519*/
            oCase.Provider_Type__c = selectedProvider;

            /* PD-11053: Replaced guestDAZNUserBehaviour() method from CaseTriggerHandler to CaseAssociationHelper class */
            if (bIsGuestUser) {
                CaseAssociationHelper.guestDAZNUserBehaviour(new List<Case> {oCase});
            } else {
                insert oCase;
            }

            Pagereference oPageref = new Pagereference('/Thanks');
            oPageref.setredirect(true);
            return oPageref;
        } catch (Exception ex) {
            ExceptionLoggerHelper.createExceptionLog(userInfo.getUserId(), 'ContactUsController', 'createCase', ex.getMessage(), ex.getTypeName(), ex.getStackTraceString());
            //Changes as per PD-7852 --- Start
            //throw ex;
            //return null;
            return CommunityHelper.redirectToErrorPage(ex.getMessage());
            //PD-7852 Changes End
        }
    }

    /*PD-8875*/
    public Pagereference daznSignIn() {
        PageReference daznLogin = null;
        daznLogin = new PageReference('/mylogin');
        if (String.isNotBlank(selectedSubject)) {
            daznLogin.getParameters().put('type', selectedSubject);
        }
        daznLogin.getParameters().put('loginType', 'DAZN');
        daznLogin.setRedirect(true);
        return daznLogin;
    }
    
    /*PD-9104*/
    public PageReference redirectToDocomoSignInPage() {
        String subjectParam = 'contactus' + ';' + selectedSubject;
        return CommunityHelper.docomoAuthentication(subjectParam);
    }
}