objects/DAZNConfiguration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is a configurable custom setting for Forgot Password link</description>
    <label>DAZN Configuration</label>
</CustomObject>

objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__CustomerAccount__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SelectOptionControllerTest.cls
//This test class will cover the code coverage for SelectOptionController.
@IsTest
public class SelectOptionControllerTest{
    static testmethod void testSelectOption()
    {
        SetUpTestData.triggerSettings();
        SetUpTestData.emailCustsett();
        Account oAccount = SetUpTestData.createPersonAccount('TestFirstName', 'TestLastName','testemail@email.com','Frozen');
        
        User oUser = SetUpTestData.createCommunityUser(oAccount.Id, 'testemail@email.com', 'testusername@email.com', 'tstals','Europe/London','ISO-8859-1','en_US','en_US','TestFName','TestLName',true); 
        Zuora__CustomerAccount__c bAccount = SetUpTestData.createBillingAccount(oAccount.Id,'test billing account', 'Active', 'A00000073', 'testbill Name', 'United Kingdom', 'test bill name', 'Credit Card', 'batch2', 'USD','1st of the month');
        Zuora__Subscription__c zSubsp = SetUpTestData.createZuoraSubscription(oAccount.Id ,bAccount.Id, 'Test Zuora', 'Active', System.today(), system.today()+30);
       PageReference oPageReference = Page.Discount; 
        oPageReference.getParameters().put('id',oAccount.id); 
        Test.setCurrentPage(oPageReference); 
    
        Test.startTest();
        SelectOptionController oCancelSubscriptionBatch = new SelectOptionController();
        oCancelSubscriptionBatch.submit();
        System.assertEquals(true, oCancelSubscriptionBatch.flagForRecord);
        System.assertEquals(oAccount.Id, oCancelSubscriptionBatch.accountId);
        Test.stopTest();
    }
    
    static testmethod void testForCheckRole()
    {
        SetUpTestData.triggerSettings();
        SetUpTestData.emailCustsett();
        Account oAccount = SetUpTestData.createPersonAccount('Test Rajesh', 'Test Reddy','WCTestNew1@test.com','Free Trial');
        User oUser = SetUpTestData.createCustomerServicesShiftLeaderUser(oAccount.Id, 'WCTestNew1@test.com', 'WCTestNew1@test.com', 'wctstr1','Europe/London','ISO-8859-1','en_US','en_US','Test Rajesh','Test Reddy',true);
        Account oPersonAccountInfo =[SELECT  Owner.Name, owner.UserRoleId From Account Where Id=:oAccount.Id];
        System.assertEquals(oAccount.Id, oPersonAccountInfo.Id);
        
        DAZNConfiguration__c dznConfigHelpSectionURL = SetUpTestData.testCreateDAZNConfiguration('CS_ShiftLeads_Roles', 'Customer Services Team Leader DACH');    
        UserRole oUserRole = [Select id,name from UserRole where Name = 'Customer Services Team Leader DACH'];
        oPersonAccountInfo.owner.UserRoleId = oUserRole.Id;
        update oPersonAccountInfo;     
        System.assertEquals(oUserRole.Id, oPersonAccountInfo.owner.UserRoleId);
        
        Test.StartTest();
        system.runAs(oUser){
            Boolean result = SelectOptionController.checkRoleForCSLeads(oPersonAccountInfo.owner.UserRoleId);
            system.assertEquals(result,true);
        }
        Test.stopTest();
    }
}