objects/DAZNConfiguration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is a configurable custom setting for Forgot Password link</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>Field to store configuration value for specific key</description>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>DAZN Configuration</label>
</CustomObject>

classes/CommunitiesLoginControllerTest.cls
/**
* An apex page controller that exposes the site login functionality
*/
/*Added Assert statements as per PD-7938*/

@IsTest global with sharing class CommunitiesLoginControllerTest {
    @IsTest(SeeAllData=true) 
    global static void testCommunitiesLoginController () {
        CommunitiesLoginController oCommunitiesLoginController = new CommunitiesLoginController();
        Test.startTest();
        oCommunitiesLoginController.forwardToAuthPage();
        System.assertEquals(DAZNConfiguration__c.getValues('LoginPageURL').Value__c, oCommunitiesLoginController.forwardToAuthPage().getURL());
        Test.stopTest();
    }    
}