objects/DAZNCommunicatorConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This will hold the Dispatch id based on the email and the language</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>Column to store communicator table, column, dispatch, trigger id etc.</description>
        <label>Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DAZN Communicator Config</label>
</CustomObject>

objects/DAZNConfiguration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is a configurable custom setting for Forgot Password link</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>Field to store configuration value for specific key</description>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>DAZN Configuration</label>
</CustomObject>

objects/Exception_Log__c.object
<CustomObject>
    <description>This objects log all exception occurred from different classes.</description>
    <fields>
        <fullName>Method_Name__c</fullName>
        <description>Method name on which exception occured</description>
        <label>Method Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>ELI-{0000000}</displayFormat>
        <label>Exception Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Zuora__DefaultPaymentMethod__c</fullName>
        <label>Default Payment Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__Payment__c.object
<CustomObject>
    <description>Zuora Payment object.  A payment is the money that customers send to pay for charges related to their subscriptions. 
The Payment object holds all of the information about an individual payment, including the payment amount and to which invoices the payment is applied.</description>
    <fields>
        <fullName>Zuora__PaymentMethod__c</fullName>
        <description>The display name of the payment method used for the payment.</description>
        <inlineHelpText>The display name of the payment method used for the payment.</inlineHelpText>
        <label>Payment Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__PaymentMethod__c.object
<CustomObject>
    <description>PaymentMethod contains information on how the contact pays for the account. In order to activate an account, you need to create a payment method.</description>
    <fields>
        <fullName>Zuora__DefaultPaymentMethod__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Default payment method or not</description>
        <inlineHelpText>Default payment method or not</inlineHelpText>
        <label>Default Payment Method</label>
        <type>Checkbox</type>
    </fields>
    <label>Payment Method</label>
    <nameField>
        <label>Payment Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__CustomerAccount__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Zuora__ZInvoice__c.object
<CustomObject>
    <description>Zuora Invoice object. Invoices are bills that you send to customers.</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchSendPaymentExpiryNotificationTest.cls
@isTest
public class BatchSendPaymentExpiryNotificationTest{
    public static String CRON_EXP = '0 1 * * * ?';
    
    /*
        Description: Setup required data.
    */
    @testSetup
    public static void setData(){
        SetUpTestData.triggerSettings();
        SetUpTestData.emailCustsett();
        Account oAccount = SetUpTestData.createPersonAccount('TestFirstName', 'TestLastName','test@test.com','Active Paid');
        system.AssertnotEquals(oAccount ,null);
        User oUser = SetUpTestData.createCommunityUser(oAccount.Id, 'testemail@email.com', 'testusername@email.com', 'tstals','Europe/London','ISO-8859-1','en_GB','en_GB','TestFName','TestLName',true);
        system.AssertnotEquals(oAccount.Id,null);
        Zuora__CustomerAccount__c bAccount = SetUpTestData.createBillingAccount(oAccount.Id,'test billing account', 'Active', 'A00000073', 'testbill Name', 'United Kingdom', 'test bill name', 'Credit Card', 'batch2', 'USD','1st of the month');
        system.AssertnotEquals(oAccount.Id,null);
        Zuora__Subscription__c zSubsp = SetUpTestData.createZuoraSubscription(oAccount.Id ,bAccount.Id, 'Test Zuora', 'Active', System.today(), system.today()+30);
        system.AssertnotEquals(bAccount.Id,null);
        Zuora__ZInvoice__c  zInv = SetUpTestData.createZuoraInvoice(oAccount.Id, bAccount.Id, 0.00 );
        system.AssertnotEquals(bAccount.Id,null);
        Zuora__Payment__c zPay = SetUpTestData.createZuoraPayment(oAccount.Id,bAccount.Id,zInv.Id, 0.00);
        system.AssertnotEquals(zInv.Id,null);
        Zuora__PaymentMethod__c zPaymentMethod = SetupTestData.createZuoraPaymentMethod(bAccount.Id, 'Active', 'CreditCard', '4111111111111111', 'Visa', 'Test Test', String.valueOf(System.Today().month()), String.valueOf(System.Today().year()), '123', 'Success');
        system.AssertnotEquals(bAccount.Id,null);
        zPaymentMethod.Zuora__DefaultPaymentMethod__c = true;
        update zPaymentMethod;
        
        //create custom setting data        
        List<DAZNCommunicatorConfig__c> lstCustomSetting = new List<DAZNCommunicatorConfig__c>();
        List<DAZNConfiguration__c> lstConfig = new List<DAZNConfiguration__c>();
        
        lstConfig.add(new DAZNConfiguration__c(name='LoginPageURL', Value__c='test.salesforce.com'));
        lstConfig.add(new DAZNConfiguration__c(name='CommunicatorAPIUserName', Value__c='test'));
        lstConfig.add(new DAZNConfiguration__c(name='CommunicatorAPIUserPwd', Value__c='test'));
        insert lstConfig;
                
        lstCustomSetting.add(new DAZNCommunicatorConfig__c(name='DispatchID_Payment_Expiry_en_GB',Value__c=12345));
        insert lstCustomSetting;    
    }
    
    @isTest
    public static void testExpiryNotification(){
     Test.startTest();

        // Schedule the test job
        String jobId = System.schedule('scheduleExpiryNotification', CRON_EXP, new scheduleExpiryNotification());
         
        // Get the information from the CronTrigger API object
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];

        // Verify the expressions are the same
        System.assertEquals(CRON_EXP, ct.CronExpression);

        // Verify the job has not run
        System.assertEquals(0, ct.TimesTriggered);

        Test.stopTest();   
        
        List<Exception_Log__c> lstException = new List<Exception_Log__c>();
        lstException = [Select id from Exception_Log__c where Method_Name__c='sendPaymentExpiryNotification' ];
        system.assert(lstException.isEmpty());  
    }
}