objects/DAZN_Help_Redirect__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>DAZN Help Redirect settings use to redirect the respective page</description>
    <fields>
        <fullName>CountryISOCode__c</fullName>
        <label>CountryISOCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsDefaultCountry__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefaultCountry</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>DAZN Help Redirect</label>
</CustomObject>

objects/DAZNLanguageSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Use this custom setting to configure languages on myaccount</description>
    <fields>
        <fullName>LanguageToDisplay__c</fullName>
        <label>LanguageToDisplay</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DAZNLanguageSetting</label>
</CustomObject>

objects/Partner_Account_Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Partner Account Configuration for all users which are partner users like users coming via Docomo or Amazon Pay etc.</description>
    <fields>
        <fullName>Cancel_Subscription_URL_Large__c</fullName>
        <description>URL for cancel subscription button for Large breakpoint, to be used when the Account status = Active Paid</description>
        <label>Cancel Subscription URL Large</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Cancel_Subscription_URL_Medium__c</fullName>
        <description>URL for cancel subscription button for Medium breakpoint, to be used when the Account status = Active Paid</description>
        <label>Cancel Subscription URL Medium</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Cancel_Subscription_URL_Small__c</fullName>
        <description>URL for cancel subscription button for Small breakpoint, to be used when the Account status = Active Paid</description>
        <label>Cancel Subscription URL Small</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Page_Name__c</fullName>
        <description>To indicate which VF page needs to be displayed for a partner type as specified in the field Partner Type</description>
        <label>Page Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Type__c</fullName>
        <description>The name of the Partner Type for which this my account page is for. This will be the same value as populated on the User type field on the Account.</description>
        <label>Partner Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Payment_History_URL__c</fullName>
        <description>The link for Payment history for DfD</description>
        <label>Payment History URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Subscription_Type_Heading_Text__c</fullName>
        <description>The static text to be shown for Subscription Type Heading</description>
        <label>Subscription Type Heading Text</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_Type_Sub_Heading_Text__c</fullName>
        <description>The static text to be shown for Subscription Type sub Heading</description>
        <label>Subscription Type Sub Heading Text</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Partner Account Configuration</label>
</CustomObject>

classes/CheckingAccountTypeControllerTest.cls
@isTest
private class CheckingAccountTypeControllerTest {
	
	@testSetup
	public static void getCommunityUsersTestData() {
		CreateTestDataforUnitTest.triggerSettings();
        CreateTestDataforUnitTest.createTestAccountsDocomo();
        CreateTestDataforUnitTest.createTestCommunityUsers();
        CreateTestDataforUnitTest.createTestcustomsetting();

        CreateTestDataforUnitTest.createTestUserDevices();
        CreateTestDataforUnitTest.createTestUserDevices();
        CreateTestDataforUnitTest.createTestUserDevices();
        CreateTestDataforUnitTest.createTestUserDevices();

        List<DAZNLanguageSetting__c> ls = new List<DAZNLanguageSetting__c>();
		ls.add(new DAZNLanguageSetting__c(
			Name = 'Austria',
			LanguageToDisplay__c = 'en_GB,DE'
		));
		ls.add(new DAZNLanguageSetting__c(
			Name = 'Germany',
			LanguageToDisplay__c = 'en_GB,DE'
		));
		ls.add(new DAZNLanguageSetting__c(
			Name = 'Japan',
			LanguageToDisplay__c = 'en_GB,ja'
		));
		ls.add(new DAZNLanguageSetting__c(
			Name = 'Switzerland',
			LanguageToDisplay__c = 'en_GB,DE'
		));
		ls.add(new DAZNLanguageSetting__c(
			Name = 'United Kingdom',
			LanguageToDisplay__c = 'en_GB'
		));
		ls.add(new DAZNLanguageSetting__c(
			Name = 'United States',
			LanguageToDisplay__c = 'en_GB'
		));
		insert ls;

        List<Partner_Account_Configuration__c> partnerConfiguration = new List<Partner_Account_Configuration__c>();
        Partner_Account_Configuration__c pac = new Partner_Account_Configuration__c(
        	Name = 'Docomo',
        	Partner_Type__c = 'Docomo',
        	Page_Name__c = 'PartnerAccount.page',
        	Subscription_Type_Heading_Text__c = 'Docomo',
        	Subscription_Type_Sub_Heading_Text__c = 'Your subscription is managed through your d Account and is payable monthly via your contract with Docomo.',
        	Payment_History_URL__c = 'https://www.google.com',
        	Cancel_Subscription_URL_Small__c = 'https://www.google.com',
        	Cancel_Subscription_URL_Medium__c = 'https://www.google.com',
        	Cancel_Subscription_URL_Large__c = 'https://www.google.com'
        );
        partnerConfiguration.add(pac);
        Partner_Account_Configuration__c pacApple = new Partner_Account_Configuration__c(
        	Name = 'Apple',
        	Partner_Type__c = 'Apple',
        	Page_Name__c = 'ApplepayAccount.page',
        	Subscription_Type_Heading_Text__c = 'LS_MyAccount_Subscription_Sub_Type_Heading_Text_Apple',
        	Subscription_Type_Sub_Heading_Text__c = 'LS_MyAccount_Subscription_Type_Heading_Text_Apple',
        	Payment_History_URL__c = 'https://www.google.com',
        	Cancel_Subscription_URL_Small__c = 'https://www.google.com',
        	Cancel_Subscription_URL_Medium__c = 'https://www.google.com',
        	Cancel_Subscription_URL_Large__c = 'https://www.google.com'
        );
        partnerConfiguration.add(pacApple);
        insert partnerConfiguration;

        DAZN_Help_Redirect__c dhr = new DAZN_Help_Redirect__c(
        	Name = 'Japan',
        	Country__c = 'Japan',
        	CountryISOCode__c = 'JP',
        	IsDefaultCountry__c = true,
        	Language__c = 'ja'
        );
        insert dhr;
	}

	@isTest 
	static void testApple() {
		Account oAccount = SetUpTestData.createDfDAccount('TestFName', 'TestLName','test@test.com','Active Paid', '12345567890', 'Apple');
  		User cUser = SetUpTestData.createCommunityUser(oAccount.Id, 'testemailAppleUser@email.com', 'testusernameAppleUser@email.com', 'tstals','Europe/London','ISO-8859-1','en_US','en_US','TestFName','TestLName',true); 
  		System.runAs(cUser) {
  			Test.startTest();
  				CheckingAccountTypeController ctrl = new CheckingAccountTypeController();
  			Test.stopTest();
  			System.assertEquals(ctrl.docomoPartnerPage,'PartnerAccount');
  			System.assertEquals(ctrl.isAppleUser,true);
  		}

	}
	
	@isTest 
	static void testDocomo() {
		Account oAccount = SetUpTestData.createDfDAccount('TestFName', 'TestLName','test@test.com','Active Paid', '12345567890', 'Docomo');
  		User cUser = SetUpTestData.createCommunityUser(oAccount.Id, 'testemailAppleUser@email.com', 'testusernameAppleUser@email.com', 'tstals','Europe/London','ISO-8859-1','en_US','en_US','TestFName','TestLName',true); 
  		System.runAs(cUser) {
  			Test.startTest();
  				CheckingAccountTypeController ctrl = new CheckingAccountTypeController();
  			Test.stopTest();
  			System.assertEquals(ctrl.docomoPartnerPage,'PartnerAccount');
  			System.assertEquals(ctrl.isDocomoUser,true);
  		}

	}
}