objects/DAZNConfiguration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is a configurable custom setting for Forgot Password link</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>Field to store configuration value for specific key</description>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>DAZN Configuration</label>
</CustomObject>

objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>R00N40000001kyLcEAI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora__Zuora_Id__c</fullName>
        <description>The Zuora Id (external primary key) of this Billing Account.</description>
        <inlineHelpText>The Zuora Id (external primary key) of this Billing Account.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/InvoicePDFCalloutHelper.cls
public with sharing class InvoicePDFCalloutHelper {
    
    public class SuccessResponceInvoice {
        public List<Invoices> invoices;
    }

    public class Invoices {
        public String id;
        public String accountId;
        public String accountNumber;
        public String invoiceNumber;
        public List<InvoiceItems> invoiceItems;
        public List<InvoiceFiles> invoiceFiles;
    }

    public class InvoiceItems {
        public String id;
        public String subscriptionName;
    }

    public class InvoiceFiles {
        public String pdfFileUrl;
    }
    /*Description: Method using for getting endpoint for download PDF file from Zuora and getting information about Invoice*/
    public static SuccessResponceInvoice initInvoiceCallout(User oUser) {
        String endpointUrl = (DAZNConfiguration__c.getValues('ZuoraEndPointInvoiceURL') != null) ? DAZNConfiguration__c.getValues('ZuoraEndPointInvoiceURL').Value__c : null;
        String username = (DAZNConfiguration__c.getValues('ZuoraAPIUserId') != null) ? DAZNConfiguration__c.getValues('ZuoraAPIUserId').Value__c : null;
        String password = (DAZNConfiguration__c.getValues('ZuoraAPIUserPassword') != null) ? DAZNConfiguration__c.getValues('ZuoraAPIUserPassword').Value__c : null;

        List<Zuora__CustomerAccount__c> billAccount = [SELECT id,  Zuora__Zuora_Id__c FROM Zuora__CustomerAccount__c WHERE Zuora__Account__c = :oUser.AccountID limit 1];
        if (endpointUrl.length() > 1 && username.length() > 1 && password.length() > 1 && !billAccount.isEmpty()) {

            Blob authorizationBlob = Blob.valueOf(username + ':' + password);
            String authorization = EncodingUtil.base64Encode(authorizationBlob);

            HttpRequest request = new HttpRequest();
            request.setEndpoint(endpointUrl + billAccount[0].Zuora__Zuora_Id__c);
            request.setMethod('GET');
            request.setTimeout(Integer.valueOf(DAZNConfiguration__c.getValues('InvoicePDFGettingTimeout').Value__c));
            request.setHeader('content-type','application/json');
            request.setHeader('Authorization', 'Basic ' + authorization);
            Http http = new Http();
            try {
                HttpResponse response = http.send(request);
                if (response.getStatusCode() == 200) {
                    SuccessResponceInvoice setPauseSuccessResponse = (SuccessResponceInvoice)JSON.deserialize(response.getBody(), SuccessResponceInvoice.class);
                    return setPauseSuccessResponse;
                }
            }
            catch (Exception ex) {
                ExceptionLoggerHelper.createExceptionLog(UserInfo.getUserID(), 'InvoicePDFCalloutHelper', 'initInvoiceCallout', ex.getMessage(), ex.getTypeName(), ex.getStackTraceString());
            }
        }
        return null;
    }
}