objects/Exception_Log__c.object
<CustomObject>
    <description>This objects log all exception occurred from different classes.</description>
    <fields>
        <fullName>Class_Name__c</fullName>
        <description>Class name on which exception occured</description>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_Message__c</fullName>
        <description>Exception Message</description>
        <label>Exception Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_Type__c</fullName>
        <description>Types of Exception</description>
        <label>Exception Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Method_Name__c</fullName>
        <description>Method name on which exception occured</description>
        <label>Method Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Running_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User who execute the code while exception occurred.</description>
        <label>Running User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Exception_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StackTrace_Message__c</fullName>
        <description>Message from Stack Tracke</description>
        <label>StackTrace Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>ELI-{0000000}</displayFormat>
        <label>Exception Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ExceptionLoggerHelper.cls
/**
* @author Cognizant Technology Solutuions
* @date 06/11/2015
* @description Exception Logger Utility
*/
public class ExceptionLoggerHelper{
    
    /*
Description: Method log exception in Exception log object.
*/
    public static void createExceptionLog(String sRunninguserId, String sClassName, String sMethodName, String sExMsg, String sTypeName, String sStackTrace)
    {
        //Checking the user has a access to the fields below before inserting in exceptionlog custom object(PD-7903)
        if(schema.SObjectType.Exception_Log__c.fields.Class_Name__c.isAccessible() && 
           schema.SObjectType.Exception_Log__c.fields.Exception_Type__c.isAccessible() && 
           schema.SObjectType.Exception_Log__c.fields.Method_Name__c.isAccessible() && 
           schema.SObjectType.Exception_Log__c.fields.StackTrace_Message__c.isAccessible()&& 
           schema.SObjectType.Exception_Log__c.fields.Exception_Message__c.isAccessible()){
               //checking the Exception Message length if it is greater than 255 truncating to 255 characters part of PD-9722
               	
               if(sExMsg.length() > 255){
                   sExMsg=sExMsg.substring(0, 254);
               }
               Exception_Log__c oExceptionLog = new Exception_Log__c();
               oExceptionLog.Running_User__c = sRunninguserId;
               oExceptionLog.Class_Name__c = sClassName;
               oExceptionLog.Method_Name__c = sMethodName;
               oExceptionLog.Exception_Message__c=sExMsg; 
               oExceptionLog.Exception_Type__c= sTypeName;
               oExceptionLog.StackTrace_Message__c = sStackTrace;
               insert oExceptionLog;
           }
        else
        { //user doesn't have permission to create a task then notify the same to system admin
            String strError = 'Unauthorized user trying to insert an Exception log :'+' User Id :'+UserInfo.getUserID();
            SendEmailWithErrorsToAdmins.sendEmail(strError);   
        }
    }   
}