objects/Partner_Account_Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Partner Account Configuration for all users which are partner users like users coming via Docomo or Amazon Pay etc.</description>
    <fields>
        <fullName>Cancel_Subscription_URL_Large__c</fullName>
        <description>URL for cancel subscription button for Large breakpoint, to be used when the Account status = Active Paid</description>
        <label>Cancel Subscription URL Large</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Cancel_Subscription_URL_Medium__c</fullName>
        <description>URL for cancel subscription button for Medium breakpoint, to be used when the Account status = Active Paid</description>
        <label>Cancel Subscription URL Medium</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Cancel_Subscription_URL_Small__c</fullName>
        <description>URL for cancel subscription button for Small breakpoint, to be used when the Account status = Active Paid</description>
        <label>Cancel Subscription URL Small</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Page_Name__c</fullName>
        <description>To indicate which VF page needs to be displayed for a partner type as specified in the field Partner Type</description>
        <label>Page Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Type__c</fullName>
        <description>The name of the Partner Type for which this my account page is for. This will be the same value as populated on the User type field on the Account.</description>
        <label>Partner Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Payment_History_URL__c</fullName>
        <description>The link for Payment history for DfD</description>
        <label>Payment History URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Subscription_Type_Heading_Text__c</fullName>
        <description>The static text to be shown for Subscription Type Heading</description>
        <label>Subscription Type Heading Text</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_Type_Sub_Heading_Text__c</fullName>
        <description>The static text to be shown for Subscription Type sub Heading</description>
        <label>Subscription Type Sub Heading Text</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Partner Account Configuration</label>
</CustomObject>

objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Zuora__Zuora_Id__c</fullName>
        <description>The Zuora Id (external primary key) of this Billing Account.</description>
        <inlineHelpText>The Zuora Id (external primary key) of this Billing Account.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__Payment__c.object
<CustomObject>
    <description>Zuora Payment object.  A payment is the money that customers send to pay for charges related to their subscriptions. 
The Payment object holds all of the information about an individual payment, including the payment amount and to which invoices the payment is applied.</description>
    <label>Payment</label>
    <nameField>
        <label>Payment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__ZInvoice__c.object
<CustomObject>
    <description>Zuora Invoice object. Invoices are bills that you send to customers.</description>
    <fields>
        <fullName>Zuora__Zuora_Id__c</fullName>
        <description>The Zuora ID of the invoice.</description>
        <inlineHelpText>The Zuora ID of the invoice.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RefundProcessorTest.cls
@isTest
public class RefundProcessorTest{
    static testMethod void testHandleRefund() {
        SetUpTestData.triggerSettings();
        Account oAccount = SetUpTestData.createPersonAccount('TestFirstName', 'TestLastName','testemail@email.com','Free Trial');
        User oUser = SetUpTestData.createCommunityUser(oAccount.Id, 'testemail@email.com', 'testusername@email.com', 'tstals','Europe/London','ISO-8859-1','en_US','en_US','TestFName','TestLName',true);
        Zuora__CustomerAccount__c bAccount = SetUpTestData.createBillingAccount(oAccount.Id,'test billing account', 'Active', 'A00000073', 'testbill Name', 'United Kingdom', 'test bill name', 'Credit Card', 'batch2', 'USD','1st of the month');    
        Zuora__ZInvoice__c  zInv = SetUpTestData.createZuoraInvoice(oAccount.Id, bAccount.Id, 10.00 );
        Zuora__Payment__c zPay = SetUpTestData.createZuoraPayment(oAccount.Id,bAccount.Id,zInv.Id, 10.00);
        
        bAccount.Zuora__Zuora_Id__c = 'TestFF123';
        update bAccount;
        Partner_Account_Configuration__c pac = new Partner_Account_Configuration__c(
            Name = 'Docomo',
            Partner_Type__c = 'Docomo',
            Page_Name__c = 'PartnerAccount.page',
            Subscription_Type_Heading_Text__c = 'Docomo',
            Subscription_Type_Sub_Heading_Text__c = 'Your subscription is managed through your d Account and is payable monthly via your contract with Docomo.',
            Payment_History_URL__c = 'https://www.google.com',
            Cancel_Subscription_URL_Small__c = 'https://www.google.com',
            Cancel_Subscription_URL_Medium__c = 'https://www.google.com',
            Cancel_Subscription_URL_Large__c = 'https://www.google.com'
        );
        insert pac;
        Test.StartTest();
        RestRequest req = new RestRequest(); 
        req.requestURI = '/services/apexrest/ProcessRefund';
        req.requestBody = Blob.valueof('<?xml version="1.0" encoding="UTF-8"?><callout><parameter name="AccountID">'+ bAccount.Zuora__Zuora_Id__c +'</parameter><parameter name="RefundReasonCode">'+ 'Chargeback' +'</parameter><parameter name="PaymentID">'+ zPay.Id +'</parameter><parameter name="AccountLastInvoiceDate">'+ '2017-02-28' +'</parameter></callout>');
        req.httpMethod = 'POST';
        RestContext.request = req;
        RefundProcessor.handleRefund();
        Test.StopTest();
    }
}