objects/Partner_Account_Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Partner Account Configuration for all users which are partner users like users coming via Docomo or Amazon Pay etc.</description>
    <fields>
        <fullName>Page_Name__c</fullName>
        <description>To indicate which VF page needs to be displayed for a partner type as specified in the field Partner Type</description>
        <label>Page Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Partner Account Configuration</label>
</CustomObject>

classes/CheckingAccountTypeController.cls
public with sharing class CheckingAccountTypeController {
	public Boolean isDocomoUser;
	public Boolean isAppleUser;
	public String docomoPartnerPage {get;set;}
	public CheckingAccountTypeController() {

		if (!userInfo.getUserType().Equals('Guest') || Test.isRunningTest()) {
			this.isAppleUser = false;
			this.isDocomoUser = false;
			if (CommunityHelper.isAppleUser()) {
				this.isAppleUser = true;
			}
			if (CommunityHelper.IsDfDUser()) {
				this.isDocomoUser = true;
			}
		}

		if (this.isAppleUser || this.isDocomoUser) {
			redirectToPage();
		}
	}

	public void redirectToPage() {
		Boolean isDaznUser = true;
		PageReference redirectPage;
		Partner_Account_Configuration__c pac = Partner_Account_Configuration__c.getInstance('Docomo');

		if (this.isAppleUser) {
			isDaznUser = false;
			this.docomoPartnerPage = (String.isNotBlank(pac.Page_Name__c) && pac.Page_Name__c.contains('.')) ? pac.Page_Name__c.substring(0, pac.Page_Name__c.indexOf('.')) : pac.Page_Name__c;
		}
		if (this.isDocomoUser) {
			isDaznUser = false;
			this.docomoPartnerPage = (String.isNotBlank(pac.Page_Name__c) && pac.Page_Name__c.contains('.')) ? pac.Page_Name__c.substring(0, pac.Page_Name__c.indexOf('.')) : pac.Page_Name__c;
		}
	}

}