objects/TriggerSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Trigger Setting to Turn on and Off</description>
    <fields>
        <fullName>Disable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disable</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Setting</label>
</CustomObject>

objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__Refund__c.object
<CustomObject>
    <description>The Refund object is used to create and query refunds. 

Note that refunds imply that money has been returned to customers. You should use adjustments (credit memos) if you are issuing credit to customers, but are not returning funds to a customer.</description>
    <fields>
        <fullName>Zuora__Type__c</fullName>
        <description>Specifies if the refund is electronic or external.</description>
        <inlineHelpText>Specifies if the refund is electronic or external.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Electronic</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Refund</label>
    <nameField>
        <label>Refund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__CustomerAccount__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RefundTriggerHandlerTest.cls
/**
* @author Cognizant Technology Solutuions
* @date 14/04/2016
* @description Test class to cover Refund trigger and handler functionality
*/
@isTest
public class RefundTriggerHandlerTest{    
    /*
Description: Test method to test the Refund trigger and handler .
*/
    public static testMethod void testrefundReleatedAccountUpdate(){
        SetUpTestData.triggerSettings();
        SetUpTestData.emailCustsett();
        Account oAccount = SetUpTestData.createPersonAccount('TestFirstName', 'TestLastName ','TestNew1@test.com','Free Trial');
        System.assertNotEquals(null, oAccount.Id);
        User oUser = SetUpTestData.createCommunityUser(oAccount.Id, 'TestNew1@test.com', 'TestNew1@test.com', 'tsnewtr1','Europe/London','ISO-8859-1','en_GB','en_GB','TestFirstName','TestLastName',true);
        Zuora__CustomerAccount__c oCustAccount = SetUpTestData.createBillingAccount(oAccount.Id,'test billing account', 'Active', 'A00000073', 'testbill Name', 'United Kingdom', 'test bill name', 'PayPal', 'batch2', 'USD','1st of the month');
        Zuora__Subscription__c oSubscription = SetupTestData.createZuoraSubscription(oAccount.Id, oCustAccount.Id, 'test billing account', 'Active', Date.Today(), Date.today().addMonths(2) );
        Zuora__Refund__c zurObj1 = SetupTestData.createZuoraRefund(oAccount.Id, oCustAccount.Id, 'External','Payment Reversal',10.00);
        list<Zuora__Refund__c> zurRefundList = new list<Zuora__Refund__c> ();
        zurRefundList.add(zurObj1);
        Zuora__Refund__c zurObj2 = SetupTestData.createZuoraRefund(oAccount.Id, oCustAccount.Id, 'Electronic','Payment Reversal',10.00);
        zurRefundList.add(zurObj2);
        update zurRefundList;
        System.assert(zurRefundList.size()>0);
        zurObj2.Zuora__Type__c = 'External';
        update zurObj2;      
        test.startTest();
        refundTriggerHandler.updateRelatedAccount(zurRefundList);
        test.stopTest();
    }
    /* Method when  trigger is disabled*/
    public static testMethod void testrefund(){
        SetUpTestData.triggerSettings();
        SetUpTestData.emailCustsett();
        TriggerSetting__c trigSet= TriggerSetting__c.getInstance('ZuoraRefundTrigger');
        trigSet.Disable__c=true;
        Update trigSet;
        Account oAccount = SetUpTestData.createPersonAccount('TestFirstName', 'TestLastName ','TestNew1@test.com','Free Trial');
        System.assertNotEquals(null, oAccount.Id);
        User oUser = SetUpTestData.createCommunityUser(oAccount.Id, 'TestNew1@test.com', 'TestNew1@test.com', 'tsnewtr1','Europe/London','ISO-8859-1','en_GB','en_GB','TestFirstName','TestLastName',true);
        Zuora__CustomerAccount__c oCustAccount = SetUpTestData.createBillingAccount(oAccount.Id,'test billing account', 'Active', 'A00000073', 'testbill Name', 'United Kingdom', 'test bill name', 'PayPal', 'batch2', 'USD','1st of the month');
        Zuora__Subscription__c oSubscription = SetupTestData.createZuoraSubscription(oAccount.Id, oCustAccount.Id, 'test billing account', 'Active', Date.Today(), Date.today().addMonths(2) );
        Zuora__Refund__c zurObj1 = SetupTestData.createZuoraRefund(oAccount.Id, oCustAccount.Id, 'External','Payment Reversal',10.00);
        list<Zuora__Refund__c> zurRefundList = new list<Zuora__Refund__c> ();
        zurRefundList.add(zurObj1);
        Zuora__Refund__c zurObj2 = SetupTestData.createZuoraRefund(oAccount.Id, oCustAccount.Id, 'Electronic','Payment Reversal',10.00);
        zurRefundList.add(zurObj2);
        update zurRefundList;
        System.assert(zurRefundList.size()>0);
        zurObj2.Zuora__Type__c = 'External';
        update zurObj2;      
        test.startTest();
        refundTriggerHandler.updateRelatedAccount(zurRefundList);
        test.stopTest();
    }
}