objects/User_Devices__c.object
<CustomObject>
    <description>This object is used to store user devices used to sign-in in application.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>User Account and Device Relationship field</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>User Devices</relationshipLabel>
        <relationshipName>User_Devices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Of_Registration__c</fullName>
        <description>Device Registration Date</description>
        <label>Date Of Registration</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Device Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>InActive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Device Type</description>
        <label>Device Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Console</fullName>
                </value>
                <value>
                    <fullName>Desktop</fullName>
                </value>
                <value>
                    <fullName>Laptop</fullName>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                </value>
                <value>
                    <fullName>Tablet</fullName>
                </value>
                <value>
                    <fullName>TV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Devices</label>
    <nameField>
        <displayFormat>DN-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Devices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UserDevicesController.cls
public with sharing class UserDevicesController {
    
    public List<User_Devices__c> lstUserDevices {get;set;}
    
    public UserDevicesController() {
        lstUserDevices= new List<User_Devices__c>();
        
        lstUserDevices= [SELECT name,
                          Account__c,
                          Date_Of_Registration__c,
                          Type__c,
                          Status__c
                       FROM User_Devices__c LIMIT 5];
    }

}