objects/User.object
<CustomObject>
    <fields>
        <fullName>ExternalID__c</fullName>
        <displayFormat>Ext-{00000000}</displayFormat>
        <label>ExternalID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>ViewerId__c</fullName>
        <externalId>true</externalId>
        <label>ViewerId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/User_Devices__c.object
<CustomObject>
    <description>This object is used to store user devices used to sign-in in application.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>User Account and Device Relationship field</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>User Devices</relationshipLabel>
        <relationshipName>User_Devices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Device_Id__c</fullName>
        <label>Device Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Device Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>InActive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Device Type</description>
        <label>Device Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Console</fullName>
                </value>
                <value>
                    <fullName>Desktop</fullName>
                </value>
                <value>
                    <fullName>Laptop</fullName>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                </value>
                <value>
                    <fullName>Tablet</fullName>
                </value>
                <value>
                    <fullName>TV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Devices</label>
    <nameField>
        <displayFormat>DN-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Devices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/signOutSingleDevicesController.cls
/*
    This Class is used to Delete the Devices of the Particular Account based on the ExternalId and DeviceId.If Device Type is Desktop,
    it also deletes the AuthSession Ids(User need to be logout from Desktop and other Devices we just delete them) 
*/
@RestResource(urlMapping='/signOutSingleDevices/*')
global with sharing class signOutSingleDevicesController {

/*
  This method is used to delete the Devices and giving the Responses based on the External Id and Device Id.
*/
    @HttpPost
    global static Response signOutSingleDevicesPost(String strExternalID, String DeviceId) {
        Response oResponse = null;
        try {
            oResponse = new Response();
            List<User_Devices__c> lstUserDevices = new List<User_Devices__c>();
            List<User> lstUser = new List<User>();
            if (!String.isBlank(strExternalID)) {
                lstUser= [SELECT Id, AccountId, Email, ExternalID__c, ViewerId__c FROM User WHERE (ExternalID__c =: strExternalID) OR (ViewerId__c =: strExternalID)];
            }
            // Get user information using external id.
            if (lstUser == null || lstUser.isEmpty()) {
                 oResponse.ExtId = System.Label.LS_Logout_Not_Valid_ExternalId;
                 oResponse.strStatus =System.label.LS_SignOutAll_Fail_Msg;
                 oResponse.StatusCode = System.label.LS_SignOutAll_Fail_Code;
            } else {
                // Get User Devices using device ID and Nulll
                if (DeviceId == null || DeviceId =='') {
                    lstUserDevices = [SELECT id, Account__c, Status__c, Type__c, Device_Id__c FROM User_Devices__c WHERE Status__c = 'Active' AND Account__c =: lstUser[0].AccountId];
                } else {
                    lstUserDevices = [SELECT id, Account__c, Status__c, Type__c, Device_Id__c FROM User_Devices__c WHERE Status__c = 'Active' AND Account__c =: lstUser[0].AccountId AND Device_Id__c =: DeviceId];
                }
                if (lstUserDevices == null || lstUserDevices.isEmpty()) {
                     oResponse.DeviceId = System.Label.LS_Logout_Not_Valid_DeviceId;
                     oResponse.strStatus = System.label.LS_SignOutAll_Fail_Msg;
                     oResponse.StatusCode = System.label.LS_SignOutAll_Fail_Code;
                } else {
                    MyAccountController.signOutOfSingleDevicesUpdated(lstUserDevices, lstUser, DeviceId);
                    oResponse.strStatus = System.label.LS_SignOutAll_SUCCESS;
                    oResponse.StatusCode = System.label.LS_SignOutAll_SUCCESS_Code;
                }
            }
        } catch (Exception ex) {
            updateFailedResponse(oResponse, ex.getMessage(), ex.getLineNumber());
        }
        return oResponse;
    }
    
    @TestVisible
    private static void updateFailedResponse(Response oResponse, String errorMessage, Integer errorLineNumber) {
        oResponse.strStatus = 'Failure==>' + errorMessage + '=LineNumber=>' + errorLineNumber;
        oResponse.StatusCode = System.label.LS_SignOutAll_Fail_Code;
    }
    
    /*
        This child class is used to give the Success and Failure Responses.If StatusCode equals to 200 ,then it is Success,If 
        StatusCode equals to 500,then it is Failure.
    */
    global class Response {
        global String strStatus;
        global String ExtId;
        global String DeviceId;
        global String StatusCode;
    }
    
}