objects/User_Devices__c.object
<CustomObject>
    <description>This object is used to store user devices used to sign-in in application.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>User Account and Device Relationship field</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>User Devices</relationshipLabel>
        <relationshipName>User_Devices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Of_Registration__c</fullName>
        <description>Device Registration Date</description>
        <label>Date Of Registration</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Device_Id__c</fullName>
        <label>Device Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Device Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>InActive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Device Type</description>
        <label>Device Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Console</fullName>
                </value>
                <value>
                    <fullName>Desktop</fullName>
                </value>
                <value>
                    <fullName>Laptop</fullName>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                </value>
                <value>
                    <fullName>Tablet</fullName>
                </value>
                <value>
                    <fullName>TV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Devices</label>
    <nameField>
        <displayFormat>DN-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Devices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/signOutSingleDevicesControllerTest.cls
@isTest 
public class signOutSingleDevicesControllerTest {
    
    static testMethod void  signOutSingleDevicesControllerMethod() {
        SetUpTestData.triggerSettings();
        String strExternalId = '';
        String DeviceId = 'Test001';
        Account oAccount = SetUpTestData.createPersonAccount('TestFirstName', 'TestLastName', 'testemail@email.com', 'Frozen');
        User oUser = SetUpTestData.createCommunityUser(strExternalId, 'en_GB', 'DE', oAccount.Id, 'testemail@email.com', 'testusername@email.com', 'tstals', 'Europe/London', 'ISO-8859-1', 'en_US', 'en_US', 'TestFName', 'TestLName', true);
        User_Devices__c objUserDevice = new User_Devices__c();
        objUserDevice.Account__c = oAccount.id;
        objUserDevice.Device_Id__c = 'Test001';
        objUserDevice.Date_Of_Registration__c = system.today();
        objUserDevice.Type__c = 'DESKTOP';
        insert objUserDevice;
        
        List<User> oUserList = new List<User>();
        oUserList.add(oUser);
        System.assertEquals(1, oUserList.size());
        List<User> oUserListnull = new List<User>();
        List<User_Devices__c> objUserDeviceList = new List<User_Devices__c>();
        objUserDeviceList.add(objUserDevice);
        System.assertEquals(1, objUserDeviceList.size());
        signOutSingleDevicesController.signOutSingleDevicesPost(strExternalId, DeviceId);
        signOutSingleDevicesController.response resposne = new signOutSingleDevicesController.response();
        resposne.strStatus = 'SUCCESS';
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/signOutSingleDevices'; //Request URL
        req.httpMethod = 'POST';//HTTP Request Type
        RestContext.request = req;
        RestContext.response = res;
    }
    static testMethod void  signOutSingleDevicesControllerMethod2() {
        SetUpTestData.triggerSettings();
        String strExternalId = 'Ext-00005952';
        String DeviceId = '';
        
        Account oAccount = SetUpTestData.createPersonAccount('TestFirstName', 'TestLastName','testemail@email.com','Frozen');
        User oUser = SetUpTestData.createCommunityUser(strExternalId, 'en_GB', 'DE', oAccount.Id, 'testemail@email.com', 'testusername@email.com', 'tstals','Europe/London','ISO-8859-1','en_US','en_US','TestFName','TestLName', true);
        User_Devices__c objUserDevice = new User_Devices__c();
        objUserDevice.Account__c = oAccount.id;
        objUserDevice.Device_Id__c = 'Test001';
        objUserDevice.Date_Of_Registration__c = system.today();
        objUserDevice.Type__c = 'Desktop';
        insert objUserDevice; 
        
        List<User> oUserList = new List<User>();
        oUserList.add(oUser);
        System.assertEquals(1, oUserList.size());
        List<User_Devices__c> objUserDeviceList = new List<User_Devices__c>();
        objUserDeviceList.add(objUserDevice);
        System.assertEquals(1, objUserDeviceList.size());
        
        signOutSingleDevicesController.signOutSingleDevicesPost(strExternalId, DeviceId);
        signOutSingleDevicesController.response resposne = new signOutSingleDevicesController.response();
        resposne.strStatus = 'SUCCESS';
        MyAccountController.signOutOfSingleDevicesUpdated(objUserDeviceList, oUserList, DeviceId);
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/signOutSingleDevices'; //Request URL
        req.httpMethod = 'POST';//HTTP Request Type   
        RestContext.request = req;
        RestContext.response = res;
    }
    static testMethod void  signOutSingleDevicesControllerMethod3() {
        SetUpTestData.triggerSettings();
        String strExternalId = 'Ext-00005952';
        String DeviceId = 'Test0011';
        
        Account oAccount = SetUpTestData.createPersonAccount('TestFirstName', 'TestLastName','testemail@email.com','Frozen');
        User oUser = SetUpTestData.createCommunityUser(strExternalId, 'en_GB', 'DE', oAccount.Id, 'testemail@email.com', 'testusername@email.com', 'tstals','Europe/London','ISO-8859-1','en_US','en_US','TestFName','TestLName', true);
        User_Devices__c objUserDevice = new User_Devices__c();
        objUserDevice.Account__c = oAccount.id;
        objUserDevice.Device_Id__c = 'Test0011';
        objUserDevice.Date_Of_Registration__c = system.today();
        objUserDevice.Type__c = 'Desktop';
        insert objUserDevice; 
        
        List<User> oUserList = new List<User>();
        oUserList.add(oUser);
        System.assertEquals(1, oUserList.size());
        List<User_Devices__c> objUserDeviceList = new List<User_Devices__c>();
        objUserDeviceList.add(objUserDevice);
        System.assertEquals(1, objUserDeviceList.size());
        
        signOutSingleDevicesController.signOutSingleDevicesPost(strExternalId, DeviceId);
        signOutSingleDevicesController.response resposne = new signOutSingleDevicesController.response();
        resposne.strStatus = 'SUCCESS';
        MyAccountController.signOutOfSingleDevicesUpdated(objUserDeviceList, oUserList, DeviceId);
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/signOutSingleDevices'; //Request URL
        req.httpMethod = 'POST';//HTTP Request Type
        RestContext.request = req;
        RestContext.response = res;
    }
    static testMethod void  signOutSingleDevicesControllerMethod4() {
        SetUpTestData.triggerSettings();
        String strExternalId = 'Ext-00414648';
        String DeviceId = 'Test0011';
        
        Account oAccount = SetUpTestData.createPersonAccount('TestFirstName', 'TestLastName','testemail@email.com','Frozen');
        User oUser = SetUpTestData.createCommunityUser(strExternalId, 'en_GB', 'DE', oAccount.Id, 'testemail@email.com', 'testusername@email.com', 'tstals','Europe/London','ISO-8859-1','en_US','en_US','TestFName','TestLName', true);
        User_Devices__c objUserDevice = new User_Devices__c();
        objUserDevice.Account__c = oAccount.Id;
        objUserDevice.Device_Id__c = 'Test0011';
        objUserDevice.Date_Of_Registration__c = system.today();
        objUserDevice.Type__c = 'Desktop';
        objUserDevice.Status__c = 'Active';
        insert objUserDevice; 
        
        List<User> oUserList = new List<User>();
        oUserList.add(oUser);
        System.assertEquals(1, oUserList.size());
        
        List<User_Devices__c> objUserDeviceList = new List<User_Devices__c>();
        objUserDeviceList.add(objUserDevice);
        System.assertEquals(1, objUserDeviceList.size());
        
        signOutSingleDevicesController.signOutSingleDevicesPost(strExternalId, '');
        signOutSingleDevicesController.response resposne = new signOutSingleDevicesController.response();
        resposne.strStatus = 'SUCCESS';
        MyAccountController.signOutOfSingleDevicesUpdated(objUserDeviceList, oUserList,DeviceId);
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/signOutSingleDevices'; //Request URL
        req.httpMethod = 'POST';//HTTP Request Type
        RestContext.request = req;
        RestContext.response = res;
    }
    static testMethod void  signOutSingleDevicesControllerMethod5() {
        SetUpTestData.triggerSettings();
        String strExternalId = 'Ext-00005952';
        String DeviceId = 'Test0011';
        Account oAccount = SetUpTestData.createPersonAccount('TestFirstName', 'TestLastName','testemail@email.com','Frozen');
        User oUser = SetUpTestData.createCommunityUser(strExternalId, 'en_GB', 'DE', oAccount.Id, 'testemail@email.com', 'testusername@email.com', 'tstals','Europe/London','ISO-8859-1','en_US','en_US','TestFName','TestLName', true);
        
        List<User> oUserList = new List<User>();
        oUserList.add(oUser);
        System.assertEquals(1, oUserList.size());
        
        List<User_Devices__c> objUserDeviceList = new List<User_Devices__c>();
        Test.startTest();
        signOutSingleDevicesController.signOutSingleDevicesPost(strExternalId , DeviceId);
        signOutSingleDevicesController.response resposne = new signOutSingleDevicesController.response();
        signOutSingleDevicesController.updateFailedResponse(resposne, 'Error happens', 100);
        resposne.strStatus = 'SUCCESS';
        MyAccountController.signOutOfSingleDevicesUpdated(objUserDeviceList, oUserList, DeviceId);
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/signOutSingleDevices'; //Request URL
        req.httpMethod = 'POST';//HTTP Request Type
        RestContext.request = req;
        RestContext.response = res;
        Test.stopTest();
    }
    
}