objects/Zuora__Payment__c.object
<CustomObject>
    <description>Zuora Payment object.  A payment is the money that customers send to pay for charges related to their subscriptions. 
The Payment object holds all of the information about an individual payment, including the payment amount and to which invoices the payment is applied.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The CRM Account that this payment is related to.</description>
        <inlineHelpText>The CRM Account that this payment is related to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <description>The payment ID in Zuora system.</description>
        <externalId>true</externalId>
        <label>External ID(Deprecated)</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <description>The status of the payment in the Zuora system. The value depends on the type of payment.</description>
        <inlineHelpText>The status of the payment in the Zuora system. The value depends on the type of payment.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Posted</fullName>
                </value>
                <value>
                    <fullName>Voided</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This field holds the Zuora object ID, and is used as external ID for data synchronization between Salesforce and Zuora.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__NextChargeDate__c</fullName>
        <label>Next Charge Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__NextRenewalDate__c</fullName>
        <label>Next Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__SubscriptionEndDate__c</fullName>
        <description>This is when the subscription ends. This is always equal to term end date, unless the subscription has been cancelled. If the subscription has been cancelled, this is set to the cancellation date.</description>
        <label>Subscription End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__SubscriptionStartDate__c</fullName>
        <description>The date when the subscription term starts. This is equal to the term start date if the subscription is on its initial term. Otherwise, it is the original term start date if the subscription has renewed.</description>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UserSubscriptionHelper.cls
/**
* @author Cognizant Technology Solutuions
* @date 04/11/2015
* @description User Subscrition information helper
*/
public without sharing class UserSubscriptionHelper {

    public User oUser {get;set;}
    public String subscriptionType {get;set;}
    public Boolean showCancelSubscription {get;set;}
    public Boolean showResubscribe {get; set;}
    public Zuora__Subscription__c subscription {get; set;} 
    public Boolean bFreeTrialMember{get;set;}
    
    /*
        Method to get the user subscription information.
    */
    public void getUserSubscription()
    {
        if(oUser == null){
            oUser = CommunityHelper.getCurrentUser();
        }
        
        bFreeTrialMember = false;
        
        string accountId = oUser.AccountId;/*Changes made for PD-7931*/
        
        if(accountId  != null && accountId  != '')
        {
            accountId = String.escapeSingleQuotes(accountId);/*Changes made for PD-7931*/
            List<Account> lstAccount=[select ID, (Select Zuora__Status__c,Zuora__NextRenewalDate__c,Zuora__SubscriptionEndDate__c,
                                                         Id,Zuora__External_Id__c, Zuora__NextChargeDate__c 
                                                  From Zuora__Subscriptions__r 
                                                  Order By Zuora__SubscriptionStartDate__c DESC NULLS LAST),
                                                  (Select ID,Name,Zuora__Status__c From Zuora__Payments__r)
                                      FROM Account 
                                      Where ID=:accountId];/*Changes made for PD-7931*/
                                      
            if(lstAccount != NULL && !lstAccount.isEmpty()){
                                      
                List<Zuora__Subscription__c> lstSubscription=lstAccount[0].Zuora__Subscriptions__r;
                List<Zuora__Payment__c> lstPayment=lstAccount[0].Zuora__Payments__r;
                   
                if(lstPayment==NULL || lstPayment.size()==0)
                {
                    if(lstSubscription!=null&& !lstSubscription.isEmpty()){
                        subscription=lstSubscription[0];            
                        if(lstSubscription[0].Zuora__Status__c.equalsIgnoreCase('Active')){
                            subscriptionType=Label.LS_MyAccount_InfoMsg_SubscriptionFreeSubscribed;                
                            showCancelSubscription=true;
                        }
                        else if(lstSubscription[0].Zuora__Status__c.equalsIgnoreCase('Cancelled')){
                            subscriptionType= Label.LS_MyAccount_InfoMsg_SubscriptionFreeUnsubscribed;
                        }
                        bFreeTrialMember=true;
                    }
                }
                else if(lstPayment!=NULL || lstPayment.size()>0)
                {
                    if(lstSubscription!=null && !lstSubscription.isEmpty()){
                        subscription=lstSubscription[0];
                        if(lstSubscription[0].Zuora__Status__c.equalsIgnoreCase('Active')){                
                            Date today=Date.today();
                            Date renewalDate=lstSubscription[0].Zuora__NextChargeDate__c;
                            
                            if(renewalDate != null && today>renewalDate && today<=renewalDate.addDays(2)){
                                if(!(lstPayment[0].Zuora__Status__c.Equals('Processed'))){
                                    subscriptionType=Label.LS_MyAccount_InfoMsg_SubscriptionGrace;                   
                                    showResubscribe=true;
                                }
                            }else{   
                                subscriptionType=Label.LS_MyAccount_InfoMsg_SubscriptionPaidSubscribed;                                  
                                showCancelSubscription=true;
                            }
                        }else if(lstSubscription[0].Zuora__Status__c.equalsIgnoreCase('Cancelled')){
                            subscriptionType=Label.LS_MyAccount_InfoMsg_SubscriptionPaidCancelled;                
                        }
                    }
                }
            }
        }
    }
}