objects/Zuora__Payment__c.object
<CustomObject>
    <description>Zuora Payment object.  A payment is the money that customers send to pay for charges related to their subscriptions. 
The Payment object holds all of the information about an individual payment, including the payment amount and to which invoices the payment is applied.</description>
    <fields>
        <fullName>Zuora__EXT_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>External Id For Payment object,   Represents a Zuora Payment object Id</description>
        <externalId>true</externalId>
        <label>Unique External Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <description>The payment ID in Zuora system.</description>
        <externalId>true</externalId>
        <label>External ID(Deprecated)</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The invoice that the payment is applied to.</description>
        <label>Invoice</label>
        <referenceTo>Zuora__ZInvoice__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__SettledOn__c</fullName>
        <description>The date when the payment was settled in the payment processor.</description>
        <inlineHelpText>The date when the payment was settled in the payment processor.</inlineHelpText>
        <label>Settled On</label>
        <type>DateTime</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__PaymentInvoice__c.object
<CustomObject>
    <description>Zuora Invoice Payment object.  An Invoice Payment is a mechanism to tie a payment to an invoice and indicate how much of the payment to apply to the invoice.  PaymentInvoice has Master-Detail relationship to Payment object and Lookup relationship to Invoice.</description>
    <fields>
        <fullName>Zuora__EXT_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>External Id For Invoice Payment object,   Represents a Zuora Invoice Payment object Id</description>
        <externalId>true</externalId>
        <label>Unique External Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <description>The Invoice Payment ID in Zuora system.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Invoice Payment ID in Zuora system.</inlineHelpText>
        <label>External ID(Deprecated)</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The invoice associated with this Invoice Payment object.</description>
        <inlineHelpText>The invoice associated with this Invoice Payment object.</inlineHelpText>
        <label>Invoice</label>
        <referenceTo>Zuora__ZInvoice__c</referenceTo>
        <relationshipLabel>Invoice Payments</relationshipLabel>
        <relationshipName>PaymentInvoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Payment__c</fullName>
        <description>The payment associated with this Invoice Payment object.</description>
        <inlineHelpText>The payment associated with this Invoice Payment object.</inlineHelpText>
        <label>Payment</label>
        <referenceTo>Zuora__Payment__c</referenceTo>
        <relationshipLabel>Invoice Payments</relationshipLabel>
        <relationshipName>PaymentInvoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice Payment</label>
    <nameField>
        <displayFormat>IP{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__Refund__c.object
<CustomObject>
    <description>The Refund object is used to create and query refunds. 

Note that refunds imply that money has been returned to customers. You should use adjustments (credit memos) if you are issuing credit to customers, but are not returning funds to a customer.</description>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External_Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference of a previous payment to which a refund is applied.</description>
        <inlineHelpText>The reference of a previous payment to which a refund is applied.</inlineHelpText>
        <label>Payment</label>
        <referenceTo>Zuora__Payment__c</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Refund</label>
    <nameField>
        <label>Refund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__ZInvoice__c.object
<CustomObject>
    <description>Zuora Invoice object. Invoices are bills that you send to customers.</description>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This field holds the Zuora object ID, and is used as external ID for data synchronization between Salesforce and Zuora.</description>
        <externalId>true</externalId>
        <inlineHelpText>This field holds the Zuora object ID, and is used as external ID for data synchronization between Salesforce and Zuora.</inlineHelpText>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__ZuoraId__c</fullName>
        <description>The Invoice ID in the Zuora system.</description>
        <inlineHelpText>The Invoice ID in the Zuora system.</inlineHelpText>
        <label>Invoice ID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RefundProcessController.cls
/**
* @author Cognizant Technology Solutuions
* @date 24/04/2017
* @description RefundProcessController is the  class to create the Refund and Invoice line adjustment for the Payments by CS agents
*/

public without sharing class RefundProcessController {
	String payRecID {get; set;}
	public RefundProcessController (){
		list <Zuora__Refund__c> refObj = new list <Zuora__Refund__c>();
		list<Zuora__Payment__c>  paymentRecObj = new list<Zuora__Payment__c>  ();
		list<Zuora__PaymentInvoice__c> payInvObj  = new list<Zuora__PaymentInvoice__c>();
		List<Zuora.zApi.SaveResult> lstInvoiceAdjustmentsaveResult1;
        List<Zuora.zApi.SaveResult> checkrefund = new List<Zuora.zApi.SaveResult>();
		 payRecID= ApexPages.currentPage().getParameters().get('param1');
		paymentRecObj = [Select id,Name,Zuora__SettledOn__c,Zuora__EXT_ID__c,Zuora__External_Id__c from Zuora__Payment__c where id =:payRecID];
		payInvObj = [SELECT id,Name,Zuora__Payment__c,Zuora__Invoice__c,Zuora__Invoice__r.Zuora__External_Id__c,Zuora__Invoice__r.Zuora__ZuoraId__c 
							from Zuora__PaymentInvoice__c where Zuora__Payment__c =:payRecID ];
		refObj = [SELECT id,name,Zuora__Payment__c from  Zuora__Refund__c where  Zuora__Payment__c =:  payRecID];
		if((refObj.size()>0 && !refObj.isEmpty() && refObj != null)  ){		
			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, System.label.LS_Refund_Error));
			}
		else{
			if((paymentRecObj[0].Zuora__SettledOn__c  != null  && payInvObj.size()>0) ){
				String InvoiceId = payInvObj[0].Zuora__Invoice__c;
                    checkrefund = ZuoraTransactionHelper.RefundAmount( paymentRecObj[0].Zuora__External_Id__c , payInvObj[0].Zuora__Invoice__r.Zuora__External_Id__c, 'Customer Satisfaction');
				if((checkrefund !=null && !checkrefund.isEmpty() && checkrefund[0].Success == true && checkrefund[0].Errors == null) || (test.isRunningTest())){ 
                        lstInvoiceAdjustmentsaveResult1 = ZuoraTransactionHelper.createInvoiceLineItemAdjusment(payInvObj[0].Zuora__Invoice__r.Zuora__External_Id__c,'Customer Satisfaction','Credit');                 					              
					if((lstInvoiceAdjustmentsaveResult1 != null && !lstInvoiceAdjustmentsaveResult1.isEmpty() && lstInvoiceAdjustmentsaveResult1[0].Success == true && 	lstInvoiceAdjustmentsaveResult1[0].Errors == null))
						{  
						apexpages.addmessage(new apexpages.message(ApexPages.severity.CONFIRM, System.Label.LS_Invoice_Success));
						}
                    else{
                        	apexpages.addmessage(new apexpages.message(ApexPages.severity.CONFIRM, System.Label.LS_Invoice_Error));
                    	}
					}  
				}
			else{
				ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,System.Label.LS_Payment_Setteled));
				}
			}
		}
}