objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__Payment__c.object
<CustomObject>
    <description>Zuora Payment object.  A payment is the money that customers send to pay for charges related to their subscriptions. 
The Payment object holds all of the information about an individual payment, including the payment amount and to which invoices the payment is applied.</description>
    <label>Payment</label>
    <nameField>
        <label>Payment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__Refund__c.object
<CustomObject>
    <description>The Refund object is used to create and query refunds. 

Note that refunds imply that money has been returned to customers. You should use adjustments (credit memos) if you are issuing credit to customers, but are not returning funds to a customer.</description>
    <fields>
        <fullName>Zuora__Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reference of a previous payment to which a refund is applied.</description>
        <inlineHelpText>The reference of a previous payment to which a refund is applied.</inlineHelpText>
        <label>Payment</label>
        <referenceTo>Zuora__Payment__c</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__RefundDate__c</fullName>
        <description>The date of the refund. The date of the refund cannot be before the Payment date.</description>
        <inlineHelpText>The date of the refund. The date of the refund cannot be before the Payment date.</inlineHelpText>
        <label>Refund Date (Deprecated)</label>
        <type>DateTime</type>
    </fields>
    <label>Refund</label>
    <nameField>
        <label>Refund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__ZInvoice__c.object
<CustomObject>
    <description>Zuora Invoice object. Invoices are bills that you send to customers.</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/paymentRelListControllerTest.cls
/**
* @author Cognizant Technology Solutuions
* @date 24/04/2017
* @description Test class to cover paymentRelListController functionality.
*/

@isTest 
public class paymentRelListControllerTest{
    static testMethod void testHandleDelProcess() {
        SetUpTestData.triggerSettings();
        
        Account oAccount = SetUpTestData.createPersonAccount('TestFirstName', 'TestLastName','testemail@email.com','Free Trial');
        User oUser = SetUpTestData.createCommunityUser(oAccount.Id, 'testemail@email.com', 'testusername@email.com', 'tstals','Europe/London','ISO-8859-1','en_US','en_US','TestFName','TestLName',true);
        Zuora__CustomerAccount__c bAccount = SetUpTestData.createBillingAccount(oAccount.Id,'test billing account', 'Active', 'A00000073', 'testbill Name', 'United Kingdom', 'test bill name', 'Credit Card', 'batch2', 'USD','1st of the month');    
        Zuora__ZInvoice__c  zInv = SetUpTestData.createZuoraInvoice(oAccount.Id, bAccount.Id, 10.00 );
        Zuora__Payment__c zPay = SetUpTestData.createZuoraPayment(oAccount.Id,bAccount.Id,zInv.Id, 10.00);
        // Query your permission set name from Organization that your want to test.
        User us = [SELECT Id FROM User WHERE AccountId = :oAccount.Id LIMIT 1];
        System.runAs(us) {

            ApexPages.StandardController sc = new ApexPages.StandardController(oAccount);
            paymentRelListController testAccPlan = new paymentRelListController(sc);  
            Test.setCurrentPageReference(new PageReference('Page.PaymentRelList')); 
            System.currentPageReference().getParameters().put('id', oAccount.id); 
            testAccPlan.PayDelId = zPay.id;
            testAccPlan.PayEditId = zPay.id;
            testAccPlan.refundProcess();
            testAccPlan.editdelProcess();
            List<Zuora__Payment__c> paymentAfterDel = [SELECT Id FROM Zuora__Payment__c ];
            System.assert(!paymentAfterDel.isEmpty());
              
        }
        
    }

    static testMethod void testHandleRefundProcess() {
        SetUpTestData.triggerSettings();
        Account oAccount = SetUpTestData.createPersonAccount('TestFirstName', 'TestLastName','testemail@email.com','Free Trial');
        User oUser = SetUpTestData.createCommunityUser(oAccount.Id, 'testemail@email.com', 'testusername@email.com', 'tstals','Europe/London','ISO-8859-1','en_US','en_US','TestFName','TestLName',true);
        Zuora__CustomerAccount__c bAccount = SetUpTestData.createBillingAccount(oAccount.Id,'test billing account', 'Active', 'A00000073', 'testbill Name', 'United Kingdom', 'test bill name', 'Credit Card', 'batch2', 'USD','1st of the month');    
        Zuora__ZInvoice__c  zInv = SetUpTestData.createZuoraInvoice(oAccount.Id, bAccount.Id, 10.00 );
        Zuora__Payment__c zPay = SetUpTestData.createZuoraPayment(oAccount.Id,bAccount.Id,zInv.Id, 10.00);
        
        System.runAs(oUser){
            Test.startTest();
            ApexPages.StandardController sc = new ApexPages.StandardController(oAccount);
            paymentRelListController testAccPlan = new paymentRelListController(sc);  
            Test.setCurrentPageReference(new PageReference('Page.PaymentRelList')); 
            List<Zuora__Refund__c> refundBefore = [SELECT ID FROM Zuora__Refund__c];
            System.currentPageReference().getParameters().put('id', oAccount.id); 
            testAccPlan.PayRecId =zPay.id;
            testAccPlan.choosePaymentId = zPay.Id;

            testAccPlan.refundProcess();     
            List<ApexPages.Message> msgList = ApexPages.getMessages();

            for(ApexPages.Message msg :  ApexPages.getMessages()) {
                System.assertEquals(Label.LS_Refund_processed, msg.getSummary());
            }
            Test.stopTest();        
        }
        
    }
    
    static testMethod void testHandleRefundProcessWithFalse() {
        SetUpTestData.triggerSettings();
        Account oAccount = SetUpTestData.createPersonAccount('TestFirstName', 'TestLastName','testemail@email.com','Free Trial');
        User oUser = SetUpTestData.createCommunityUser(oAccount.Id, 'testemail@email.com', 'testusername@email.com', 'tstals','Europe/London','ISO-8859-1','en_US','en_US','TestFName','TestLName',true);
        User  cSTeamMember  =SetUpTestData.createCustomerServicesShiftLeaderUser(oAccount.Id, 'pm3testemail@emailOne.com', 'pm3testemailOne@email.com', 'tstals3','Europe/London','ISO-8859-1','en_US','en_US','TestFName','TestLName',true); 
        Zuora__CustomerAccount__c bAccount = SetUpTestData.createBillingAccount(oAccount.Id,'test billing account', 'Active', 'A00000073', 'testbill Name', 'United Kingdom', 'test bill name', 'Credit Card', 'batch2', 'USD','1st of the month');    

        SetUpTestData.createZuoraInvoicesAndPayments(oAccount.Id, bAccount.Id, 10.00, 10.00);
        Zuora__Payment__c zPay = [SELECT Id FROM Zuora__Payment__c LIMIT 1];

        System.runAs(cSTeamMember){
            ApexPages.StandardController sc = new ApexPages.StandardController(oAccount);
            paymentRelListController testAccPlan = new paymentRelListController(sc);  
            Test.setCurrentPageReference(new PageReference('Page.PaymentRelList')); 
            System.currentPageReference().getParameters().put('id', oAccount.id); 
            testAccPlan.PayRecId =zPay.id;
            testAccPlan.refundProcess();
            for(ApexPages.Message msg :  ApexPages.getMessages()) {
                System.assertEquals(Label.LS_Refund_processed, msg.getSummary());
            }              
        }
        
    }

    static testMethod void testHandleRefundProcessWithRefund() {
        SetUpTestData.triggerSettings();
        Account oAccount = SetUpTestData.createPersonAccount('TestFirstName', 'TestLastName','testemail@email.com','Free Trial');
        User oUser = SetUpTestData.createCommunityUser(oAccount.Id, 'testemail@email.com', 'testusername@email.com', 'tstals','Europe/London','ISO-8859-1','en_US','en_US','TestFName','TestLName',true);
        Zuora__CustomerAccount__c bAccount = SetUpTestData.createBillingAccount(oAccount.Id,'test billing account', 'Active', 'A00000073', 'testbill Name', 'United Kingdom', 'test bill name', 'Credit Card', 'batch2', 'USD','1st of the month');    
        Zuora__ZInvoice__c  zInv = SetUpTestData.createZuoraInvoice(oAccount.Id, bAccount.Id, 10.00 );
        Zuora__Payment__c zPay = SetUpTestData.createZuoraPayment(oAccount.Id,bAccount.Id,zInv.Id, 10.00);

        Zuora__Refund__c oZuoraRefund = SetUpTestData.createZuoraRefund(oAccount.Id,bAccount.Id,'External','Payment Reversal',1000.00);
            oZuoraRefund.Zuora__Payment__c = zPay.Id;  
            oZuoraRefund.Zuora__RefundDate__c = Date.today().addDays(-5);
        update oZuoraRefund;
        
        System.runAs(oUser){
            Test.startTest();
            ApexPages.StandardController sc = new ApexPages.StandardController(oAccount);
            paymentRelListController testAccPlan = new paymentRelListController(sc);  
            Test.setCurrentPageReference(new PageReference('Page.PaymentRelList')); 
            List<Zuora__Refund__c> refundBefore = [SELECT ID FROM Zuora__Refund__c];
            System.currentPageReference().getParameters().put('id', oAccount.id); 
            testAccPlan.PayRecId =zPay.id;
            testAccPlan.choosePaymentId = zPay.Id;

            testAccPlan.refundProcess();     
            List<ApexPages.Message> msgList = ApexPages.getMessages();

            for(ApexPages.Message msg :  ApexPages.getMessages()) {
                System.assertEquals(Label.LS_Refund_Refund_not_possible, msg.getSummary());
            }
            Test.stopTest();        
        }
    }

    static testMethod void testRefreshPage() {
        SetUpTestData.triggerSettings();
        Account oAccount = SetUpTestData.createPersonAccount('TestFirstName', 'TestLastName','testemail@email.com','Free Trial');
        User oUser = SetUpTestData.createCommunityUser(oAccount.Id, 'testemail@email.com', 'testusername@email.com', 'tstals','Europe/London','ISO-8859-1','en_US','en_US','TestFName','TestLName',true);
        Zuora__CustomerAccount__c bAccount = SetUpTestData.createBillingAccount(oAccount.Id,'test billing account', 'Active', 'A00000073', 'testbill Name', 'United Kingdom', 'test bill name', 'Credit Card', 'batch2', 'USD','1st of the month');    
        Zuora__ZInvoice__c  zInv = SetUpTestData.createZuoraInvoice(oAccount.Id, bAccount.Id, 10.00 );
        Zuora__Payment__c zPay = SetUpTestData.createZuoraPayment(oAccount.Id,bAccount.Id,zInv.Id, 10.00);

        System.runAs(oUser){
            Test.startTest();
                ApexPages.StandardController sc = new ApexPages.StandardController(oAccount);
                paymentRelListController testAccPlan = new paymentRelListController(sc);  
                Test.setCurrentPageReference(new PageReference('Page.PaymentRelList')); 
                testAccPlan.refreshPage();
                System.assert(testAccPlan.isShowTable == true);
            Test.stopTest();        
        }
    }
}