objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Zuora__AccountNumber__c</fullName>
        <label>Account Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>R00N40000001kyLcEAI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora__Batch__c</fullName>
        <label>Batch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__BillCycleDay__c</fullName>
        <label>Bill Cycle Day</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__BillToCountry__c</fullName>
        <label>Bill To Address Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__BillToName__c</fullName>
        <label>Bill To Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__CreditCardType__c</fullName>
        <formula>IF(  ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__CreditCardType__c, &quot;AmericanExpress&quot;),  &quot;AmericanExpress&quot;,
IF(  ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__CreditCardType__c, &quot;Discover&quot;), &quot; Discover&quot;, 
IF(  ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__CreditCardType__c, &quot;MasterCard&quot;), &quot;MasterCard&quot;,
IF(  ISPICKVAL(Zuora__Default_Payment_Method__r.Zuora__CreditCardType__c, &quot;Visa&quot;), &quot;Visa&quot;,  &quot;&quot;))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Credit Card Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Currency__c</fullName>
        <label>Currency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__DefaultPaymentMethod__c</fullName>
        <label>Default Payment Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__SoldToName__c</fullName>
        <label>Sold To Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Zuora_Id__c</fullName>
        <description>The Zuora Id (external primary key) of this Billing Account.</description>
        <inlineHelpText>The Zuora Id (external primary key) of this Billing Account.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__PaymentMethod__c.object
<CustomObject>
    <description>PaymentMethod contains information on how the contact pays for the account. In order to activate an account, you need to create a payment method.</description>
    <fields>
        <fullName>Zuora__BankIdentificationNumber__c</fullName>
        <description>This is the first six digits of the PaymentMethod, such as the credit card number or account number.</description>
        <inlineHelpText>This is the first six digits of the PaymentMethod, such as the credit card number or account number.</inlineHelpText>
        <label>Bank Identification Number</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__BankTransferAccountNumber__c</fullName>
        <description>The account number for of the customer&apos;s bank account.</description>
        <inlineHelpText>The account number for of the customer&apos;s bank account.</inlineHelpText>
        <label>Bank Transfer Account Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__BillingAccount__c</fullName>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Payment Methods</relationshipLabel>
        <relationshipName>Payment_Methods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora__CreditCardExpirationMonth__c</fullName>
        <label>Credit Card Expiration Month</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zuora__CreditCardExpirationYear__c</fullName>
        <description>The expiration year of the credit or debit card.</description>
        <inlineHelpText>The expiration year of the credit or debit card.</inlineHelpText>
        <label>Credit Card Expiration Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__CreditCardMaskNumber__c</fullName>
        <description>A masked version of the credit or debit card number.</description>
        <inlineHelpText>A masked version of the credit or debit card number.</inlineHelpText>
        <label>Credit Card Mask Number</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__CreditCardType__c</fullName>
        <description>The type of credit or debit card that is being billed.</description>
        <inlineHelpText>The type of credit or debit card that is being billed.</inlineHelpText>
        <label>Credit Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AmericanExpress</fullName>
                </value>
                <value>
                    <fullName>Discover</fullName>
                </value>
                <value>
                    <fullName>MasterCard</fullName>
                </value>
                <value>
                    <fullName>Visa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zuora__DefaultPaymentMethod__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Default payment method or not</description>
        <inlineHelpText>Default payment method or not</inlineHelpText>
        <label>Default Payment Method</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zuora__LastTransactionStatus__c</fullName>
        <description>The status of the most recent transaction.</description>
        <inlineHelpText>The status of the most recent transaction.</inlineHelpText>
        <label>Last Transaction Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__PaymentMethodStatus__c</fullName>
        <description>Specify the status of the payment method, either Active or Closed.</description>
        <inlineHelpText>Specify the status of the payment method, either Active or Closed.</inlineHelpText>
        <label>Payment Method Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zuora__PaypalEmail__c</fullName>
        <description>The email address associated with the account holder&apos;s PayPal account</description>
        <inlineHelpText>The email address associated with the account holder&apos;s PayPal account</inlineHelpText>
        <label>Paypal Email</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACH</fullName>
                </value>
                <value>
                    <fullName>BankTransfer</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>CreditCard</fullName>
                </value>
                <value>
                    <fullName>CreditCardReferenceTransaction</fullName>
                </value>
                <value>
                    <fullName>DebitCard</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PayPal</fullName>
                </value>
                <value>
                    <fullName>WireTransfer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment Method</label>
    <nameField>
        <label>Payment Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__CustomerAccount__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__NextChargeDate__c</fullName>
        <label>Next Charge Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__SubscriptionStartDate__c</fullName>
        <description>The date when the subscription term starts. This is equal to the term start date if the subscription is on its initial term. Otherwise, it is the original term start date if the subscription has renewed.</description>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__TermStartDate__c</fullName>
        <label>Term Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__Zuora_Id__c</fullName>
        <description>The Zuora Id (external primary key) of this Subscription.</description>
        <inlineHelpText>The Zuora Id (external primary key) of this Subscription.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Zuora__ZInvoice__c.object
<CustomObject>
    <description>Zuora Invoice object. Invoices are bills that you send to customers.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The CRM account that the invoice is associated to.</description>
        <inlineHelpText>The CRM account that the invoice is associated to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__BillingAccount__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>The Zuora billing account that the invoice is for.</description>
        <inlineHelpText>The Zuora billing account that the invoice is for.</inlineHelpText>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>ZInvoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <description>The status of the invoice in the system. This status is not the status of the payment of the invoice, just the status of the invoice itself.</description>
        <inlineHelpText>The status of the invoice in the system. This status is not the status of the payment of the invoice, just the status of the invoice itself.</inlineHelpText>
        <label>Status</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Zuora_Id__c</fullName>
        <description>The Zuora ID of the invoice.</description>
        <inlineHelpText>The Zuora ID of the invoice.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CreateZuoraDataforUnitTest.cls
@IsTest
public class CreateZuoraDataforUnitTest {
    //This method is used to create ZuoraDeatils recode.
    @testSetup
    public static void createZuoraDeatils(){
        //Calling CreateTest Account and Users to setup data
        CreateTestDataforUnitTest.createTestAccounts();
        CreateTestDataforUnitTest.CreateTestCommunityUsers();        
        List<Account> accList = [Select Id,Name,PersonContactId from Account];
        List<Zuora__CustomerAccount__c> bAccount = new List<Zuora__CustomerAccount__c>();
        List<Zuora__Subscription__c> lstSubscription =new list<Zuora__Subscription__c>();
        List<Zuora__PaymentMethod__c> oZuoraPayMethList = new List<Zuora__PaymentMethod__c>();
        Integer  bcount=100;
        for(Account accOb: accList){
            // add Zuora bAccount
            Zuora__CustomerAccount__c zCustomerAcct = new Zuora__CustomerAccount__c();
            zCustomerAcct.Zuora__Account__c = accOb.id;
            zCustomerAcct.Name = accOb.Name;
            zCustomerAcct.Zuora__Status__c = 'Active';
            zCustomerAcct.Zuora__AccountNumber__c = 'A'+bcount;
            //zCustomerAcct.Zuora__Zuora_Id__c = 'A'+bcount+'z';
            zCustomerAcct.Zuora__BillToName__c = 'billing account'+accOb.Name;
            zCustomerAcct.Zuora__BillToCountry__c = 'Japan';
            zCustomerAcct.Zuora__SoldToName__c = 'billing account'+accOb.Name;
            zCustomerAcct.Zuora__DefaultPaymentMethod__c= 'CreditCard';
            zCustomerAcct.Zuora__Batch__c= 'Batch1';
            zCustomerAcct.Zuora__Currency__c= 'JPY';
            zCustomerAcct.Zuora__BillCycleDay__c= '5th of the month';
            bAccount.add(zCustomerAcct);
            bcount++;
        }
        Database.insert(bAccount,true);
        //add Zuora PaymentMethod
        for(Zuora__CustomerAccount__c obill: bAccount){
            Zuora__PaymentMethod__c oPaymethMethod = new Zuora__PaymentMethod__c();
            oPaymethMethod.Zuora__PaymentMethodStatus__c = 'Active';
            oPaymethMethod.Zuora__Type__c = 'CreditCard';
            oPaymethMethod.Zuora__CreditCardMaskNumber__c = '************1111';
            oPaymethMethod.Zuora__CreditCardType__c = 'Visa';
            oPaymethMethod.Zuora__DefaultPaymentMethod__c = true;
            oPaymethMethod.Zuora__CreditCardExpirationMonth__c = '8';
            oPaymethMethod.Zuora__CreditCardExpirationYear__c = '2018';
            oPaymethMethod.Zuora__BankIdentificationNumber__c = '411111';
            oPaymethMethod.Zuora__LastTransactionStatus__c = 'Approved';
            oPaymethMethod.Zuora__BankTransferAccountNumber__c = '4111111111111111';
            oPaymethMethod.Zuora__BillingAccount__c = obill.id;
            oPaymethMethod.Zuora__PaypalEmail__c = 'test@test.test';
            oZuoraPayMethList.add(oPaymethMethod);
        }
        Database.insert(oZuoraPayMethList,true);
        System.debug('oZuoraPayMethList'+oZuoraPayMethList);
        /*Add Zuora Subscription*/
        for(Zuora__CustomerAccount__c obillAcc: bAccount){
            Zuora__Subscription__c oSubscription = new Zuora__Subscription__c();
            oSubscription.Name = 'test billing account';
            oSubscription.Zuora__Status__c = 'Active';
            oSubscription.Zuora__SubscriptionStartDate__c = Date.Today();
            oSubscription.Zuora__NextChargeDate__c = Date.today().addMonths(2);
            oSubscription.Zuora__Account__c = obillAcc.Zuora__Account__c;
            oSubscription.Zuora__CustomerAccount__c = obillAcc.Id;
            oSubscription.Zuora__TermStartDate__c = Date.Today();
            lstSubscription.add(oSubscription);
          
        }
          Database.insert(lstSubscription,true);
            System.debug('lstSubscription'+lstSubscription);
    }
    @testSetup
    public static void createInvoice()
    {
        List<Zuora__ZInvoice__c> oZuoraInvoice = new List<Zuora__ZInvoice__c>();
        List<Zuora__CustomerAccount__c> baccList = [Select Id,Zuora__Account__c from Zuora__CustomerAccount__c];
        for(Zuora__CustomerAccount__c baccOb: baccList){
            Zuora__ZInvoice__c oZInvoice = new Zuora__ZInvoice__c();
            oZInvoice.Zuora__Account__c = baccOb.Zuora__Account__c;
            oZInvoice.Zuora__BillingAccount__c = baccOb.id;
            oZInvoice.Zuora__PaymentAmount__c = 0.00;
            oZInvoice.Zuora__InvoiceDate__c =  (Date.today()).addMonths(1);
            oZInvoice.Zuora__TotalAmount__c = 180.00;
            oZInvoice.Name ='test Invoice account';
            oZuoraInvoice.add(oZInvoice);
        }
        System.debug('***oZuoraInvoice'+oZuoraInvoice);
        Database.insert(oZuoraInvoice,true);
    } 
    
}