objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>CampaignID__c</fullName>
        <description>Changed the API Name on 14 Jun 2017 as per request from Zoura (David) during Cog 1.8 release</description>
        <label>Gift Code Campaign ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Free_Trial_End_Date__c</fullName>
        <label>Free Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gift_Code_End_Date__c</fullName>
        <label>Gift Code End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gift_Code_Start_Date__c</fullName>
        <formula>IF( 
ISBLANK(Giftcode__c), 
null, 
NULLVALUE( 
Free_Trial_End_Date__c, 
IF( 
OR( ISNULL ( Campaign_Id__c ), ISBLANK ( Campaign_Id__c ) ), 
null, 
Zuora__SubscriptionStartDate__c 
) 
) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gift Code Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gift_Code_Status__c</fullName>
        <formula>IF(
    Gift_Code_Start_Date__c &gt; TODAY(),
    &apos;Applied&apos;,
    IF(
        AND( Gift_Code_Start_Date__c &lt;= TODAY(), Gift_Code_End_Date__c &gt; TODAY() ),
        &apos;In Use&apos;,
        IF(
            Gift_Code_End_Date__c &lt;= TODAY(),
            &apos;Expired&apos;,
            &apos;&apos;
        )
    )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gift Code Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Giftcode__c</fullName>
        <label>Gift Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NumFreeTrialPeriods__c</fullName>
        <label>NumFreeTrialPeriods</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NumGiftPeriods__c</fullName>
        <label>NumGiftPeriods</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GiftInfoSectionController.cls
public class GiftInfoSectionController {
    
    public GiftInfo giftInfo { get; set; }
    
    public GiftInfoSectionController(ApexPages.StandardController controller) {
        Zuora__Subscription__c subscription = GiftCodeHelper.getSubscriptionWithGigtInfo(controller.getRecord().id);
        if (subscription != null) {
            giftInfo = new GiftInfo(
                subscription.Giftcode__c,
                subscription.Gift_Code_Start_Date__c,
                subscription.CampaignID__c,
                subscription.Gift_Code_End_Date__c,
                subscription.Gift_Code_Status__c,
                subscription.Free_Trial_End_Date__c,
                subscription.NumGiftPeriods__c,
                subscription.NumFreeTrialPeriods__c
            );
        }
    }
    
    public class GiftInfo {
        public String giftCode { get; set; }
        public String giftCodeStartDate { get; set; }
        public String giftCodeCampaignID { get; set; }
        public String giftCodeEndDate { get; set; }
        public String giftCodeStatus { get; set; }
        public String freeTrialEndDate { get; set; }
        public String numGiftPeriods { get; set; }
        public String numFreeTrials { get; set; }
        
        public GiftInfo(String giftCode,
                        Date giftCodeStartDate,
                        String giftCodeCampaignID,
                        Date giftCodeEndDate,
                        String giftCodeStatus,
                        Date freeTrialEndDate,
                        String numGiftPeriods,
                        String numFreeTrials) {
            this.giftCode = giftCode;
            this.giftCodeStartDate = giftCodeStartDate != null ? giftCodeStartDate.format() : null;
            this.giftCodeCampaignID = giftCodeCampaignID;
            this.giftCodeEndDate = giftCodeEndDate != null ? giftCodeEndDate.format() : null;
            this.giftCodeStatus = giftCodeStatus;
            this.freeTrialEndDate = freeTrialEndDate != null ? freeTrialEndDate.format() : null;
            this.numGiftPeriods = numGiftPeriods;
            this.numFreeTrials = numFreeTrials;
        }
    }
    
}